[4 - 6단계 방탈출 사용자 예약] 에버(손채영) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #113
Opened 2024-05-10 16:16 UTC by helenason

수달 안녕하세요! 🦦

지난 단계에서는 리팩터링 후 빠르게 리뷰 요청을 하지 못해 수달과 많은 이야기를 나누지 못한 것이 아쉬웠어요.
따라서 이번 단계 리뷰 반영 과정에선 속도를 우선순위로 리팩터링 해볼까 합니다!
학습하고 싶은 부분이 많아 구현 속도가 빠른 편은 아니지만 최대한 속도를 올려 진행해보겠습니다 🥹

현재 코드에서도 여전히 리팩터링 하고 싶은 부분이 있지만,
리뷰를 받은 후 추가적으로 보완하고 싶어 아직 미흡한 코드임에도 리뷰를 요청 드립니다.

남은 기간 동안 잘 부탁드립니다! : )

감사합니다.

2024-05-12 03:00 UTC, her0807 requested changes
안녕하세요 에버~

빠른 리뷰 요청 주셔서 감사해요. 

인증이 생기면서 어려워졌죠 ㅠㅠ
궁금한 점들을 질문으로 남겨주시면 더 원활한 리뷰가 될 것 같아요!
빠르게 저도 리뷰남기고, 에버 생각을 들어보고 추가 리뷰 남기려고 
간단한 내용 먼저 남겨두었어요. 

이번 리뷰도 재밌게 해봐요 🌞 파이팅입니다!!

2024-05-12 03:00 UTC, her0807 commented on README.md
> +
꼼꼼한 요구사항 도출 👍🏻

2024-05-12 03:00 UTC, her0807 commented on build.gradle
> +    implementation "io.jsonwebtoken:jjwt:0.12.5"
jjwt 도 여러 버전이 있는데요 0.12.5 버전을 선택하신 이유가 있으신가용? ㅎㅎ
없으시다면 한번 찾아보셔도 좋을 것 같아요. 

또한 jjwt github 에서는 3가지를 선언하도록 명시되어 있는데 다른 것들은 불필요하다고 판단하여 ㅕ
선언하지 않으셨는지도 궁금해요!

참고 
- https://github.com/jwtk/jjwt?tab=readme-ov-file#dependencies:~:text=%ED%95%A9%EB%8B%88%EB%8B%A4%20Provider.-,%EC%A2%85%EC%86%8D%EC%84%B1,-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%20%EC%A2%85%EC%86%8D%EC%84%B1%EC%9D%84%20%EC%B6%94%EA%B0%80%ED%95%A9%EB%8B%88%EB%8B%A4

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/AdminPageController.java
> +    public String getReservation() {
적절한 네이밍으로 리팩터링 👍🏻

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/AuthController.java
> +    }
1. 쿠키에 토큰을 넣게 되면 탈취 문제가 발생할 수 있는데요~ 이를 어떤 식으로 해결해볼 수 있을까요? (max age 에 대한 고민)

쿠키 생성을 메서드로 따로 추출해주셨는데요  `ResponseCookie` 을 사용하면 체이닝 방식으로 편하게 
관련 설정들을 추가할 수 있어요. ㅎㅎ

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/MemberController.java
> +    }
ShowMembers 라는 네이밍이 약간 뷰 친화적인 이름인 것 같아요.
서버 관점에서는 단순히 사용자 목록은 반환하는건데 이걸 어디서 보여줄지, 또 어떤 계산에 쓸지는
나타내지 않아도 된다고 생각합니다. 너무 자세한 행위를 명시하면 재사용성이 떨어지는 것 같아요.

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.ok(response);
예약이 생성되었을 때는 201 created status 를 내려주면 어떨까요?

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @GetMapping("/filter") // TODO: 각 조건이 없는 경우?
todo 가 남아있네용

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
response 생성 로직 때문에 중요한 로직들이 가려지는 것 같아요. 

조합하는 과정을 다른 객체에게 책임을 위임하거나 메서드 순서를 조정하는 등 가독성을 향상시키기 위한
전반적인 리팩터링을 해보면 어떨까요?

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +                                                                        @RequestParam(name = "to") LocalDate to) {
아래와 같이 단축시킬 수 있습니다.

```suggestion
  @GetMapping(params = {"themeId", "memberId", "from", "to"})
    public ResponseEntity<List<ReservationResponse>> searchReservations() {
```

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +                                                                        @RequestParam(name = "to") LocalDate to) {
에버는 어떤 기준으로 params vs request body 로 데이터를 받는 방식을 나누시나요?

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/config/CheckAdminInterceptor.java
> +        }
메세지를 던져 Admin 인지 확인하셨군요!! ㅎㅎ 아주 잘하셨습니다.

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/config/LoginMemberArgumentResolver.java
> +        return new LoginMember(loginMember.getId(), loginMember.getName(), loginMember.getEmail());
resolveArgument 에서 토큰을 파싱해서 로그인 된 유저의 정보를  
반환하고 있는데요~ Id 는 식별자이기 때문에 꼭 필수요소라고 생각하지만 이름과 이메일은 필수는 아닌 것 같은데 함께 넘겨주는 
이유가 있을까요? 

해당 정보 같은 경우는 유저가 이름이나 이메일을 변경할 수도 있는데요~ 토큰이 발급된 시점에 변경이 된다면
변경되지 않은 정보로 어플리케이션 내에서 핸들링될 위험이 있을 것 같아요!

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/config/WebMvcConfiguration.java
> +    private final CheckAdminInterceptor checkAdminInterceptor;
ArgumentResolver 와 Interceptor  모두 사용자 request 가 controller 에 매핑되기 전에 
전처리를 할 수 있는데요~ 어떤 차이가 있을까요? 🙂

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/request/AdminReservationRequest.java
> +    private final long memberId;
@NotNull, @NotEmpty, @NotBlank 키워드를 활용해서 검증해보아도 좋을 것 같아요.

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/response/MemberReservationTimeResponse.java
> +    public static MemberReservationTimeResponse from(ReservationTimeDto time, boolean isBooked) {
정적 팩터리 메서드 `from` 과 `of` 는 각각 어떨때 쓰면 좋을까요?

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/controller/response/ReservationResponse.java
> +                new MemberResponse(member.getId(), member.getName(), member.getEmail()));
각각의 response 에게 변환 책임을 위임해주면 어떨까요?

지금은 예약에 회원, 테마 등등이 의존되어 있어 조회 될 때 한꺼번에 조회되지만


각 response 에 변환 책임을 위임해두면 테마 목록만 반환되거나 회원 목록만 반환될 때 재사용할 수 있게 될 것 같아요.

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(exception.getMessage(), HttpStatus.UNAUTHORIZED);
적절한 예외에 대한 핸들링도 잊지 않고 챙겨주셨군요 💯

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/model/Member.java
> +    private final String password;
도메인 내에 속성들이 충분히 검증이 되었나요?

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    }
1. 하나의 쿼리로 전부 가져오기  vs 단건으로 조회해서 합쳐주기 


각각 어떤 장단점이 있을까요?


합치게 된다면 join 을 사용해서 데이터를 가져올 수 있을 것 같아요~

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/service/AuthService.java
> +    }
jwt 의 구조에 대해서 알고 계시나요?

위에서 남긴 피드백과 같이 변경될 여지가 있는 데이터를 payload 에 담게되면
데이터가 유효하지 않은데 핸들링을 하게 될 여지가 있어요. 

어떤 데이터를 어디에 담으면 좋을지 같이 고민해볼까요?

참고 

https://jwt.io/introduction

2024-05-12 03:00 UTC, her0807 commented on src/main/java/roomescape/service/AuthService.java
> +public class AuthService {
사용자 로그인을 유지시키는 여러 방법 중 

토큰 vs 쿠키 vs 세션 각각 어떤 차이가 있을까요? 🙂

2024-05-12 08:02 UTC, helenason commented on src/main/java/roomescape/controller/AuthController.java
> +    }
`ResponseCookie`라는 클래스가 존재했었네요! 체이닝 방식을 사용하니 더욱 가독성이 높아진 것 같아요.

쿠키 탈취 문제는 쿠키의 만료 기한을 짧게 설정함으로써 어느정도 방지할 수 있을 것 같아요. 저는 30분으로 설정해주겠습니다!

2024-05-12 08:07 UTC, helenason commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.ok(response);
해당 컨트롤러 (showReservationTimesInformation)는 예약 생성이 아닌 예약 가능 여부 정보를 담은 시간들을 반환하는 컨트롤러이기 때문에 200 상태 코드를 내려주었습니다!

2024-05-12 08:45 UTC, helenason commented on src/main/java/roomescape/controller/ReservationController.java
> +    }
네 수달의 의견에 동의합니다! ReservationTimeInfoResponse(구 MemberReservationTimeResponse) 클래스가 해당 역할을 수행하도록 하여 컨트롤러의 가독성을 높였습니다.

2024-05-12 09:12 UTC, helenason commented on src/main/java/roomescape/controller/ReservationController.java
> +                                                                        @RequestParam(name = "to") LocalDate to) {
네! 가독성이 훨씬 좋아졌네요. 추천 감사합니다! 😃

2024-05-12 09:21 UTC, helenason commented on src/main/java/roomescape/controller/ReservationController.java
> +                                                                        @RequestParam(name = "to") LocalDate to) {
RequestBody가 아닌 RequestParam을 사용했던 이유는 해당 API의 경우에도 저번에 말씀드린 [경우](https://github.com/woowacourse/spring-roomescape-member/pull/35#discussion_r1587819813)와 동일하구요! 어떤 기준으로 데이터 받는 방식을 나누는가에 대해 고민해보자면, 요청 받은 데이터를 통해 서버 내의 데이터들을 분류하거나 정렬하여 반환하는 경우 param을 사용하고, 요청 받은 데이터가 서버 내에 저장이 되는 경우에는 body를 사용하고 있습니다!

2024-05-12 09:25 UTC, helenason commented on src/main/java/roomescape/controller/config/CheckAdminInterceptor.java
> +        }
감사합니다! ㅎㅎ 🥹😍

2024-05-12 11:23 UTC, helenason commented on src/main/java/roomescape/controller/request/AdminReservationRequest.java
> +    private final long memberId;
네! 점차 검증 로직이 많아져, 모든 요청 데이터에 대해 validation 라이브러리를 사용하여 검증하도록 하였습니다!

2024-05-12 11:40 UTC, helenason commented on src/main/java/roomescape/controller/response/MemberReservationTimeResponse.java
> +    public static MemberReservationTimeResponse from(ReservationTimeDto time, boolean isBooked) {
정적 팩터리 메서드에서 from은 하나의 파라미터를 받아 타입을 전환할 때, of는 여러개의 파라미터를 받아 해당 파라미터를 포함하는 타입으로 변환할 때 관용적으로 사용한다고 알고 있습니다. 하지만 위의 경우는 해당 컨벤션을 따르지 못했네요. of 로 수정하겠습니다!

2024-05-12 11:59 UTC, helenason commented on src/main/java/roomescape/controller/response/ReservationResponse.java
> +                new MemberResponse(member.getId(), member.getName(), member.getEmail()));
앗 그러네요!! Response 변환 메서드를 생성해두었는데, 해당 코드에서 재사용하지 못했어요. 다음부턴 이런 상황이 발생하지 않도록 사용하지 않는 생성자에 대해 private으로 접근을 막아두었습니다!

2024-05-12 15:00 UTC, helenason commented on src/main/java/roomescape/model/Member.java
> +    private final String password;
4~6단계 구현 과정에선 검증 부분이 부족했던 것 같네요 🥹
검증 로직을 추가하는 과정에서, 관련 로직이 많아져 이후 확장성을 생각하였을 때 이메일 중복 검증, 비밀번호 구조 검증 등 다양한 검증이 생길 것이 분명하기 때문에 각 필드를 새로운 클래스로 감싸도록 하였습니다!

2024-05-12 16:35 UTC, helenason commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    }
장점이 곧 반대 의견의 단점이라고 생각하기 때문에 장점을 위주로 적어보겠습니다!

### 하나의 쿼리로 전부 가져오기

  - 한 번의 데이터베이스 접근으로 원하는 데이터를 조회할 수 있어 데이터베이스 리소스 낭비가 적습니다.
  - 원하는 데이터로 조합하는 과정(repository 내)에서 사용되는 불필요한 메모리가 적습니다.

### 단건으로 조회하여 합쳐주기

  - 하나의 DAO가 하나의 테이블에만 접근하여, 하나의 DAO는 하나의 책임만을 갖습니다.
  - DAO의 재사용 관점에서 더욱 용이합니다. (join으로 묶인 쿼리는 재사용하기 어렵다고 생각합니다.)
  - (저의 경우) 이를 위해 DAO와 repository 계층을 나누었기 때문에, 서비스 계층이 무거워지는 현상을 방지합니다. 대신 repository가 해당 역할을 담당합니다. DAO가 여러 데이터베이스에 접근했다면 repository 계층을 나누기 어려웠을 것이라 생각합니다.
  - 서비스 계층과의 의존성 분리가 가능합니다. DAO가 최대한 CRUD 관련 로직만 구현하게 함으로써 서비스가 어떤 데이터를 원하는지 최대한 모르도록 하였습니다.

이 중 제가 가장 중요하다고 생각했던 장점은, 하나의 DAO가 하나의 테이블에만 접근할 수 있다는 점이었습니다. 1~3단계 구현 초반에는 전자의 방식을 선택하였지만, 리팩터링 과정에서 테이블 간의 의존성을 분리하기 위해 큰 공사를 거쳐 후자의 방식으로 수정하였습니다. 덕분에 이후의 구현 과정에서 SQL 쿼리가 장황해지지 않고 깔끔하여 수정된 방향에 대해 만족하고 있습니다. 하지만 제가 생각한 장점에 분명 오류가 있을 수 있다고 생각합니다. 따라서 이에 대한 수달의 의견도 궁금해요! 😃

추가로, 단건으로 조회함으로써 복잡해진 repository 계층의 코드 가독성을 높이기 위해 (특히, ReservationRepository의 경우) 중복 로직을 추출하여 메서드화하였습니다!

2024-05-12 16:56 UTC, helenason commented on build.gradle
> +    implementation "io.jsonwebtoken:jjwt:0.12.5"
> jjwt 도 여러 버전이 있는데요 0.12.5 버전을 선택하신 이유가 있으신가용? ㅎㅎ
없으시다면 한번 찾아보셔도 좋을 것 같아요.

단순히 가장 최근 버전의 라이브러리를 사용하기 위함이었습니다...ㅎ 최근 버전이면 이전 버전들의 취약한 부분들을 보완했을 것이라고 생각했거든요! 그런데 사실 돌아가게 하는 것에 급급하여 어떤 버전을 선택할지 깊게 생각해보진 않았어요!

> 또한 jjwt github 에서는 3가지를 선언하도록 명시되어 있는데 다른 것들은 불필요하다고 판단하여
선언하지 않으셨는지도 궁금해요!

혹시 수달이 말씀하신 3가지가
```
implementation group: 'io.jsonwebtoken', name: 'jjwt', version: '0.12.5'
```
일까요? 아니면 문서에서 제공된 
```
api('io.jsonwebtoken:jjwt-api:0.12.5')
runtimeOnly('io.jsonwebtoken:jjwt-impl:0.12.5')
runtimeOnly('io.jsonwebtoken:jjwt-orgjson:0.12.5') {
    exclude(group: 'org.json', module: 'json') //provided by Android natively
}
```
를 말씀하시는 것인가요?

저는 https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt/0.12.5 에서 코드를 가져왔고, 저의 `build.gradle` 코드와의 통일성을 위해 한 줄로 줄였습니다. 큰 이유는 없었습니다 ㅎㅎ

2024-05-12 17:19 UTC, helenason commented on src/main/java/roomescape/controller/MemberController.java
> +    }
그렇겠네요. 'show'라는 단어 자체가 뷰 친화적인 이름이네요! 목록을 반환한다는 의미의 이름으로, return, find, get 정도 생각해보았는데 get으로 변경하겠습니다! 혹시 더 좋은 의견이 있다면 언급해주시면 감사하겠습니다 ☺️

2024-05-13 05:42 UTC, helenason commented on src/main/java/roomescape/controller/config/LoginMemberArgumentResolver.java
> +        return new LoginMember(loginMember.getId(), loginMember.getName(), loginMember.getEmail());
언젠간 필요하겠지라는 안일한 생각해 해당 정보들을 포함시킨 것 같아요. 식별자인 id만 포함하도록 수정하겠습니다!

2024-05-13 07:55 UTC, helenason commented on src/main/java/roomescape/controller/config/WebMvcConfiguration.java
> +    private final CheckAdminInterceptor checkAdminInterceptor;
ArgumentResolver는 특정 조건의 파라미터를 컨트롤러 메서드 호출 전 전처리 과정을 통해 바인딩합니다. 즉, 일련의 과정을 거쳐 어떠한 값을 컨트롤러에 넘겨주어야 할 때 사용되는 전처리 기법입니다. 이와 달리 Inteceptor는 컨트롤러 메서드 호출 전, 컨트롤러 메서드 호출 후이자 뷰 호출 전, 뷰 호출 후, 이 세 가지 시점에 특정 로직을 수행할 수 있게 합니다.

두 기법의 차이라면, 전자는 파라미터를 바인딩하여 전달하는 것이 목적인 반면 후자는 특정 시점에 특정 동작을 수행하기 위한 목적이라고 생각했습니다. 또한 전자는 데이터를 컨트롤러에 전달할 수 있고, 후자는 그러한 동작이 불가능합니다. 이 정도의 차이점을 생각해보았는데 혹시 추가될 수 있는 점이 있으면 언급 부탁드려요!

더불어 여기서 수달에게 궁금한 점이 있습니다. ArgumentResolver는 어떤 시점에 호출이 되나요? 저의 코드의 경우 ReservationController 클래스에서 addReservation, showReservationTimesInformation, searchReservations 메서드의 각 파라미터에 대해서만 한 번씩 호출됩니다. 왜 다른 클래스에서는 호출되지 않는지, 왜 같은 클래스 다른 메서드에서도 호출되지 않는지 궁금합니다. 검색을 해보아도, 어떤 기준으로 리졸버가 호출되는지 잘 모르겠습니다. 혼자 해결해보려 하였으나 쉽지 않아 이렇게 도움 요청 드려봅니다 🥹

2024-05-13 08:29 UTC, helenason commented on src/main/java/roomescape/service/AuthService.java
> +    }
이전에는 JWT에 식별자 id만 담아 이름, 이메일, 역할 정보는 데이터베이스에서 조회하여 사용하였습니다. 하지만 해당 방법을 사용할 경우 토큰에서 사용자 정보를 추출(checkToken 메서드)할 때마다 데이터베이스에 접근해야만 했습니다. CheckToken 메서드는 로그인된 사용자가 수행하는 모든 동작에 대해 한 번씩 호출됩니다. 한 명의 사용자라면 큰 문제가 없으나 사용자의 수가 많아질 경우 데이터베이스에 과부하가 올 수 있다고 생각하였습니다. 따라서 토큰의 claim에 정보를 담았고 이로써 데이터베이스 접근 로직을 제거할 수 있었습니다.

만약, 발급된 토큰을 사용하고 있는 유저가 이름, 이메일 등의 정보를 변경할 경우, claim을 업데이트하여 토큰을 새로 발급함으로써 유효하지 않은 데이터를 핸들링할 여지를 남기지 않을 수 있을 것 같아요!

2024-05-13 08:49 UTC, helenason commented on src/main/java/roomescape/service/AuthService.java
> +public class AuthService {
먼저, 세 방식 모두 HTTP의 stateless한 특징을 stateful하도록 하기 위한 방식입니다.

세션과 쿠키는 모두 서버와 클라이언트 간의 매개체 역할을 합니다. 쿠키는 클라이언트 쪽에 정보를 저장하고, 세션은 서버 쪽에 정보를 저장한다고 합니다. 토큰은 사용자의 정보를 바탕으로 인코딩하여 각 사용자마다 토큰을 발급합니다. 토큰은 요청이나 응답 시에 헤더 또는 쿠키에 담아 반환할 수 있습니다.

여기서 궁금한 점은, 쿠키는 클라이언트 쪽에 정보를 저장한다고 하였는데, 저희 미션의 클라이언트 코드에서는 쿠키 관련 코드를 찾을 수 없었습니다. 서버에서 쿠키를 응답에 담아 반환하면 만료되기 전까지는 영구적으로 헤더에 담겨있는 것처럼 보이는데, 현재 저희 미션에서 클라이언트는 어떻게 쿠키를 저장하고 있는 것인가요?

2024-05-13 08:52 UTC, helenason commented
수달 안녕하세요!

리뷰 반영하여 다시 요청 드립니다. 학습하면서 궁금했던 점 추가로 코멘트 남겨두었어요!

이번 리뷰도 잘 부탁드립니다 😁

2024-05-13 13:30 UTC, her0807 commented on build.gradle
> +    implementation "io.jsonwebtoken:jjwt:0.12.5"
현업에서는 한번 의존성을 주입하게 되면 쉽게 제거하지 못하겠더라고요.
제가 설정해둔 것은 제거할 수 있는데 다른 분들이 적용한 것은 뜻이 있겠지(?)
라는 생각에.. ㅎㅎ

그래서 최대한 사용되는 것들로만 의존성을 맺는 연습을 통해 의도치 않은 장애를 막을 수 있고
혼란스러움도 줄일 수 있을 것 같아 남긴 피드백이었습니다!

저는 주로 이전 버전 3개에 대한 변경사항을 확인하고, 해당 라이브러리가 지속적인 유지보수가 되는지
업데이트 이력을 살펴보고 설정을 적용하는 것 같습니다.

저도 과거에 대부분 플젝하다보면 큰 이유가 없이 사용법을 구글링해서 바로 적용했던 것 같아요
그런데 현업은 서비스에 타격이 직결되다보니 이런 것들을 확인하는 습관이 있으면 좋더라구요. 
이런 관점도 알려드리고 싶어서 남겨두었습니다 ㅎㅎ

2024-05-13 13:36 UTC, her0807 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    }
단건으로 조회하여 합쳐주기에서 꼭 고려해야하는 점은
이렇게 조회된 데이터의 성질인데요~
여러 번의 쿼리를 날리는 도중 데이터 변경이 생길 경우 데이터 `일관성을 유지하기 어렵습니다.`

그래서 일관된 데이터가 필요할 경우 한꺼번에 조인을 통해서 가져오는 것이 더 적절한 상황이 있을수도 있을 것 같아요 

예를 들면 방탈출 예약서비스 일 때 조회가능한 시간을 먼저 조회하고, 테마를 조회하고~.. 또 다른 걸 조회하고 있을 때 
누군가가 예약을 해버려서 조회가능한 시간이 줄어들었다면,,?

2024-05-13 13:39 UTC, her0807 commented on src/main/java/roomescape/service/AuthService.java
> +public class AuthService {
다른 크루가 답변한 내용이 있어 첨부해두겠습니다 ㅎㅎ

<img width="700" alt="스크린샷 2024-05-13 오후 10 38 45" src="https://github.com/woowacourse/spring-roomescape-member/assets/26570275/438c290b-7bc3-4935-a2d9-a90d60cb9b90">

2024-05-13 13:40 UTC, her0807 commented on src/main/java/roomescape/controller/MemberController.java
> +    }
get과 find 도 데이터를 조회할 때 데이터가 없으면 예외를 반환하는지 안하는지 여부로 나뉘는 것 같아요. 

참고 : https://creampuffy.tistory.com/162

2024-05-13 13:57 UTC, her0807 commented on src/main/java/roomescape/controller/config/WebMvcConfiguration.java
> +    private final CheckAdminInterceptor checkAdminInterceptor;
ArgumentResolver 는 저희가 사용하는 @RequestBody , @RequestParam 등등에서도 동작하는데요.
에버가 만든 커스텀 ArgumentResolver 는 아래 조건을 통해서 바인딩 됩니다. 
자세한 내용은 블로그 포스팅 걸어둘게요
<img width="678" alt="스크린샷 2024-05-13 오후 10 57 20" src="https://github.com/woowacourse/spring-roomescape-member/assets/26570275/ea28a4d4-4ce9-4630-ab89-1bb14f2bb4bc">


ArgumentResolver  동작원리  : https://kookiencream.tistory.com/120

2024-05-13 14:06 UTC, her0807 approved these changes
안녕하세요 에버

미션을 진행하면서 늘 깊게 고민하고 적용하는 모습이 아주 멋집니다.
질문 남겨주신 내용에 대해서 코멘트 남겨두었어요. 

간단한 내용이고, 요구사항은 모두 만족된 것 같아 이만 머지 하겠습니다 🙇🏻‍♀️
미션 고생 많으셨어요~!

2024-05-13 14:06 UTC, merged