[4 - 6단계 방탈출 사용자 예약] 폭포(이성주) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #116
Opened 2024-05-10 19:28 UTC by BurningFalls

안녕하세요, 썬! 폭포입니다.

Spring이 처음인데다가 인증, 인가에 대한 CS지식도 깊지 않다보니, 익숙하지 않은 프레임워크로 익숙하지 않은 개념들을 구현하는데 꽤 많은 어려움을 겪었습니다.

나름대로 개념들을 공부해보고는 있으나 생각보다 하나하나 깨우치는데 오래 걸려서, 일단 빠르게 구현을 먼저 하고 공부를 아직 못한 부분들은 코드 피드백을 받으면서 동시에 분석해보려고 합니다.

리뷰 부탁드립니다. 감사합니다. 😃

2024-05-11 11:50 UTC, syoun602 requested changes
안녕하세요 폭포!

2단계도 잘 구현해주셨네요 👍
몇가지 코멘트 남겨봤으니 확인 후 재요청 주세요!

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/auth/controller/LoginMemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {
리턴값을 Member로 제한해볼까요?

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/auth/controller/LoginMemberArgumentResolver.java
> +    private String extractTokenFromCookie(NativeWebRequest webRequest) {
메서드가 중복되고 있는데, 하나의 포인트에서 관리해볼 수 있지 않을까요? 😊

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/auth/controller/LogoutController.java
> +    @PostMapping("/logout")
logout 기능도 만들어두셨네요 👍 (확인은 못해봤지만 🥲)
따로 컨트롤러를 분리하신 의도가 궁금해요

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +    private long validityInMilliseconds;
yml 활용 👍

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/member/repository/MemberRepository.java
> +        return jdbcTemplate.queryForObject(sql, ROW_MAPPER, email);
결과가 없으면 어떻게 되나요?

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/reservation/provider/WhereQueryProvider.java
> +public class WhereQueryProvider {
오,, 동적 쿼리 활용 👍👍

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        return reservationRepository.readByReservationId(reservationId);
보통 persistence 레이어에서는 `findBy`를 사용하는 것 같아요

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/theme/repository/ThemeRepository.java
> +    public Long create(Theme theme) {
create로 변경하신 의도가 궁금합니다~

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/auth/controller/CheckMemberInterceptor.java
> +        if (role.isBlank() || role.equals("USER")) {
role을 enum으로 관리해봐도 좋을 것 같아요

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/auth/controller/LoginController.java
> +    }
user도 admin처럼 user interaction용 페이지 컨트롤러를 만들어볼 수 있겠네요

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +                .claim("role", member.getRole())
Jwt에 id만 넣고 DB에서 조회하기 vs 지금처럼 몇가지 속성을 토큰에 넣기 중 후자를 선택하신 이유가 궁금합니다~

2024-05-11 11:50 UTC, syoun602 commented on src/main/java/roomescape/auth/controller/LoginController.java
> +    public ResponseEntity<MemberResponse> checkLogin(Member member) {
다른 곳은 dto를 사용하셨는데, 이 곳에서는 그대로 member를 사용하시는걸까요?

2024-05-11 11:50 UTC, syoun602 commented on src/test/java/roomescape/auth/controller/LoginControllerTest.java
> +                .all()
```
.given().log().all()
.when().log().all()
.get...
```
과 같이 인덴트를 구분하는게 더 읽기 쉬울 것 같아요

2024-05-12 01:34 UTC, BurningFalls commented on build.gradle
> +    implementation 'javax.xml.bind:jaxb-api:2.3.1'
### `io.jsonwebtoken:jjwt:0.9.1`

* https://github.com/jwtk/jjwt?tab=readme-ov-file#what-is-a-json-web-token
* https://github.com/jwtk/jjwt?tab=readme-ov-file#gradle

정보를 안전하고 간결하게 전송하기 위한 일반적인 용도의 텍스트 기반 메시징 포맷인 `JWT`를 생성하고 검증하는 기능을 제공하는 dependency로 보여집니다.

LMS에서 학습한 바에 의하면 토큰 인증은 다음과 같습니다. 토큰 인증은 클라이언트에서 토큰을 저장하고 있어 request에 토큰을 포함시켜 자신을 인증하는 방식이며, 세션 인증과는 다르게 서버에서 사용자의 세션 상태를 유지할 필요가 없어 서버의 관리와 확장성에 유리합니다. 이는 별도의 세션 정보를 저장하지 않는다는 것이며, 토큰의 진위를 검증하는 데 사용되는 key는 서버에서 관리합니다.

* https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt/0.9.1
* https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api
* https://github.com/jwtk/jjwt?tab=readme-ov-file#understanding-jjwt-dependencies
* https://github.com/jwtk/jjwt/blob/master/CHANGELOG.md

`io.jsonwebtoken`의 artifact가 `jjwt-api`로 이동했다는 문구를 볼 수 있었는데, 0.10 버전으로 넘어가면서 `jjwt`가 `jjwt-api`, `jjwt-impl` 등등으로 분리된 것으로 보여집니다. 이는 경고 없이 변경될 수 있는 다른 모든 내부 구현 세부 사항을 런타임 전용 종속성으로 지정하도록 설계해서, 안정적인 jjwt 사용과 업그레이드를 보장하려고 바뀌게 된 것 같습니다.

###

2024-05-12 05:05 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/CheckMemberInterceptor.java
> +        return Arrays.stream(cookies)
.

2024-05-12 05:13 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/CheckMemberInterceptor.java
> +    }
.

2024-05-12 05:14 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/CheckMemberInterceptor.java
> +        return cookies.stream()
> request가 아닌 쿠키를 받아서 처리하는건 어떨까요?

쿠키를 받아서 토큰으로 바꿔주는 메서드이고 `HttpServletRequest`의 쿠키에 대한 값만 필요하기 때문에, 처음부터 인자로 쿠키를 받는 것이 더 직관적이고 좋네요! 수정완료했습니다. https://github.com/woowacourse/spring-roomescape-member/pull/116#discussion_r1597552357

> NPE에 대한 처리도 필요해보입니다!

2024-05-12 05:42 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/CheckMemberInterceptor.java
> +public class CheckMemberInterceptor implements HandlerInterceptor {
> 어드민 인가와 관련된 인터셉터라면 Member보다는 Admin이 맞지 않을까요~?

Admin인지를 Check하는 어드민 인가와 관련된 인터셉터이므로 `CheckAdminInterceptor`가 적절하겠네요! 수정완료했습니다.

2024-05-12 05:58 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/CheckMemberInterceptor.java
> +        return cookies.stream()
> NPE에 대한 처리도 필요해보입니다!

토큰, 쿠키, 권한에 대해서 값이 없는 경우를 제대로 고려하지 못했었네요. 수정완료했습니다. https://github.com/woowacourse/spring-roomescape-member/pull/116#discussion_r1597553123

2024-05-12 06:13 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/CheckMemberInterceptor.java
> +public class CheckMemberInterceptor implements HandlerInterceptor {
> 또한, argumentResolver와 interceptor은 어떤차이가 있나요?

Interceptor는 컨트롤러 실행의 전(`preHandle)`과 후(`postHandle`) 및 request 완료 후(`afterCompletion`)에 특정 로직을 수행할 수 있게 해줍니다. 반면에 ArgumentResolver는 컨트롤러 메서드 호출 전에 특정 조건에 따라 파라미터 값을 준비하고 제공할 수 있게 해줍니다.

2024-05-12 06:43 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/LoginMemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer, NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception {
그대로 메서드를 오버라이드 해와서 리턴 타입에 신경쓰지 못했네요. Member로 수정했습니다.

2024-05-12 07:21 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/LoginMemberArgumentResolver.java
> +    private String extractTokenFromCookie(NativeWebRequest webRequest) {
ArgumentResolver와 Interceptor에서 쿠키에서 토큰을 추출하는 로직이 공통되어 이를 `JwtTokenProvider` 책임으로 넘길 수 있네요! 수정했습니다. de09c7da81407a1ee556584bec85e3416bce42d4

2024-05-12 07:27 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/LogoutController.java
> +    @PostMapping("/logout")
`LoginController`를 먼저 만들었는데, 여기에 `/login`과 `/login/check` api가 있어 `@RequestMapping("/login")`으로 묶어놓았기 때문에, 해당 컨트롤러에는 `/login`으로 시작하는 api만 놔두고 싶어서 `LogoutController`를 따로 만들게 되었습니다. 다른 곳에도 api의 url 첫 부분을 기준으로 컨트롤러들을 나누었기 때문에 통일성을 갖추고자 한 것도 있습니다.

다 만들고 나서 하나의 `AuthController`로 합칠 수도 있겠다는 생각이 들었지만, 위와 같은 이유들로 수행하지 않았습니다. 하지만, 로그아웃 같은 경우`/logout` 하나의 api만 존재하고 더이상 api가 추가될 일이 없다고 봐도 무방하므로, 하나로 합치는 것도 좋다고 생각합니다.

2024-05-12 08:53 UTC, BurningFalls commented on src/main/java/roomescape/member/repository/MemberRepository.java
>      }
.

2024-05-12 09:04 UTC, BurningFalls commented on src/main/java/roomescape/member/repository/MemberRepository.java
> +        return jdbcTemplate.queryForObject(sql, ROW_MAPPER, email);
결과가 없는 경우에 대해, 바로 에러를 던지는 것 대신 어떤 추가 작업을 해야할 수도 있겠네요. `Optional`을 사용하여 안전하게 null을 처리할 수 있게 수정했습니다. https://github.com/woowacourse/spring-roomescape-member/pull/116#discussion_r1597585314

2024-05-12 10:19 UTC, BurningFalls commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        return reservationRepository.readByReservationId(reservationId);
* create -> `save`
* read -> `find`
* update -> `update`
* delete -> `delete`

* Repository -> `find` / `findAll`
* Service -> `findObject` / `findObjectList`
* Controller -> `findObject` / `findObjectList`

다음과 같은 컨벤션으로 전체 CRUD 메서드들의 네이밍을 수정했습니다. 85aab71367b66c24c8872aa1f85006c5d626241d

2024-05-12 11:51 UTC, BurningFalls commented on src/main/java/roomescape/theme/repository/ThemeRepository.java
> +    public Long create(Theme theme) {
위와 동일합니다. https://github.com/woowacourse/spring-roomescape-member/pull/116#discussion_r1597605799

2024-05-12 13:04 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/CheckMemberInterceptor.java
> +        if (role.isBlank() || role.equals("USER")) {
Enum Role로 관리하면 좀 더 명확하고 내부 메서드로 동등성 판별이 가능해지네요! 수정했습니다.

2024-05-12 13:08 UTC, BurningFalls commented on .gitignore
> +/src/main/resources/application.yml
다시 추가했습니다.

2024-05-12 13:21 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/LoginController.java
> +    }
관리자는 로그인할 필요가 없고 멤버만 로그인 기능이 필요하기 때문에, 해당 API를 `MemberPageController`에서 관리할 수 있겠네요! 

분리하고 나니 `LoginController`에 view가 아닌 객체를 반환하는 메서드들만 남아서 `@RestController`를 붙일 수 있게 되어 더 깔끔해질 수 있었습니다.

2024-05-12 15:32 UTC, BurningFalls commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +                .claim("role", member.getRole())
추가적인 db 조회 없이 토큰에서 바로 정보를 추출할 수 있어, 토큰에 멤버 정보를 담는 방법을 선택했습니다. 대신, 토큰이 탈취당할 경우를 대비해서 password와 같은 민감한 정보는 담지 않도록 했습니다.

말씀해주신 내용을 바탕으로 추가로 분석 및 조사를 해보았습니다.

---

## 토큰에 사용자 정보를 포함하는 경우
### 장점
* 추가적인 db 조회 없이 토큰에서 바로 정보 추출이 가능해서 **처리 속도가 빠르다**.
* db 조회할 필요가 없어 **서버나 db에 부가적인 부하를 주지 않는다**.
### 단점
* 사용자 정보를 포함하여 토큰의 크기가 커지면, 네트워크 대역폭을 더 많이 사용하여 클라이언트와 서버 간의 **통신 속도에 영향을 준다**.
* 토큰이 탈취되면 사용자의 **모든 정보가 노출될 수 있다**.
* **사용자 정보가 변경될 경우, 토큰을 새로 발급해야 한다**.

## 토큰에 id만 포함하는 경우
### 장점
* 토큰이 탈취되어도 **사용자의 중요 정보가 노출되지 않는다**.
* 사용자 정보가 변경되더라도 db에서 새로 조회하기 때문에 **항상 최신의 정보를 사용할 수 있다**.
* 토큰의 크기가 작아져 **네트워크 통신의 효율이 증가한다**.
### 단점
* 모든 요청마다 db를 조회해야 해서 **처리 속도가 느리다**.
* 자주 사용자 정보를 조회해야 해서 **데이터베이스 부하가 증가한다**.

---

db 조회로 인한 처리 속도에 대해서는 예상했지만, 사용자 정보 변경으로 인한 토큰 갱신은 생각해보지 못한 문제였습니다. 

보안이 중요한 애플리케이션 또는 사용자 정보가 자주 변경되는 애플리케이션이라면 **토큰에 id만 포함하는 방식**을, 성능이 중요하고 사용자 정보가 자주 변경되지 않는 애플리케이션이라면 **토큰에 사용자 정보를 포함하는 방법**을 선택하게 될 것 같습니다.

2024-05-12 17:04 UTC, BurningFalls commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +                .claim("role", member.getRole())
지금의 서비스는 db 조회 속도 및 데이터베이스 부하를 신경 쓸만큼 데이터가 많지 않으므로, 사용자의 중요 정보를 숨기고 항상 최신의 정보를 사용할 수 있도록 토큰에 id만 포함하는 방식으로 코드를 수정해보았습니다.

id만 포함하는 방식으로 수정하다가 의도치않게 많은 양의 코드가 개선되었고, 아래와 같은 측면으로 훨씬 더 깔끔해졌습니다.

< 계층화 >
* `CheckAdminInterceptor`, `LoginMemberArgumentResolver` -> Controller
* `AuthService` -> Service
* `MemberRepository`, `JwtTokenProvider` -> Repository

< 코드 변화 >
* `Interceptor`와 `ArgumentResolver`가 `JwtTokenProvider`에 대한 의존성을 갖지 않고, `AuthService`만을 의존함.
* `JwtTokenProvider`의 작업은 전부 `AuthService`에서 수행
* 기존에 `Interceptor` 또는 `ArgumentResolver`에서 수행하는 cookie에서 token을 찾고 token에서 member를 추출하는 로직을 `AuthService`에서 `findMemberByCookie`의 하나의 로직으로 관리

2024-05-12 18:03 UTC, BurningFalls commented on src/test/java/roomescape/auth/controller/LoginControllerTest.java
> +                .all()
`.log().all()`은 테스트 메서드의 로그를 보기 위한 메서드이므로, 전부 통과하는 것을 확인해서 필요없다고 생각해서 삭제했습니다.

다음에 테스트 로그를 확인할 필요성이 생겼을 때, 알려주신 방법으로 붙여서 가독성을 늘리겠습니다. `given()` 뒤에 하나를 붙여서 request 이전 데이터를 확인하고, `then()` 뒤에 하나를 붙여서 API request를 확인해볼 예정입니다.

2024-05-12 18:58 UTC, BurningFalls commented on src/main/java/roomescape/auth/controller/LoginController.java
> +    public ResponseEntity<MemberResponse> checkLogin(Member member) {
* `ArgumentResolver`가 이미 request에서 특정 데이터를 추출해서 사용자 정의 객체로 변환하는 작업을 해주고 넘겨주었기 때문에 충분하다고 생각했습니다.
* `ArgumentResolver`가 넘겨주는 객체를 여러 곳에서 사용하고, 사용하는 곳마다 필요한 정보들의 형태가 다를 것으로 예상됩니다. 그래서 dto를 사용하려면 사용하는 곳마다 별개의 dto가 있어야 할 것 같은데, 그러면 특정 객체로 매핑시켜주는 `ArgumentResolver`의 의미가 퇴색되는 같습니다.

위의 두 가지 이유로 `ArgumentResolver`가 넘겨주는 객체는 도메인 클래스 그대로의 객체를 사용했습니다. 아직 `ArgumentResolver`에 대한 학습이 부족해서 잘못 이해한 것일수도 있다고 생각하고 있으므로, 제 의견에 틀린 부분이 있으면 지적 및 피드백 부탁드립니다.

2024-05-12 19:16 UTC, BurningFalls commented
빠르고 상세한 리뷰 감사합니다, 썬! 🙇 

우테코 들어와서 이번 미션이 가장 힘들었고, 힘든 만큼 배워가는 것도 엄청 많다는 생각이 듭니다. 그렇게 여유를 부린 것이 아니었음에도 불구하고 기한 내에 만족할만한 코드를 완성하고 내용을 정리하려고 노력하면서 지금까지와는 다른 차원의 어려움을 느끼고 있습니다.

spring을 처음 배웠기 때문인지, cs 지식이 부족해서 공부를 많이 해야 했기 때문인지, LMS의 설명만으로는 부족해서 수많은 시행착오를 거쳐야 했기 때문인지, 배워야 하는 양이 많았기 때문인지, 힘들다는 것을 느낀 이유가 무엇일지를 고민해보면 그냥 전부 다인 것 같습니다.

미션을 구현할때는 제가 무엇에 포커스를 맞추고 공부를 해야 하는가에 대한 제대로 된 감도 오지 않았지만, 썬의 RC 덕분에 제가 무엇을 모르고 있는지와 이번 미션에서 어떤 것들을 알아가면 좋은지에 대해 알 수 있어서 매우 좋았습니다.

원래 각 미션에서 리뷰어와 피드백을 주고받으며 새로 알게 된 깊게 공부한 내용들을 블로그에 정리해서 적어왔는데, 이번 미션은 공부해서 적어야할 주제 리스트도 산더미인 데다가 바로 화요일에 다음 미션을 시작해버리니 정리할 시간이 없다는 것이 아쉬울 따름입니다.

2024-05-12 19:27 UTC, BurningFalls commented
빠르고 상세한 리뷰 감사합니다, 썬! 🙇 

우테코 들어와서 이번 미션이 가장 힘들었고, 힘든 만큼 배워가는 것도 엄청 많다는 생각이 듭니다. 그렇게 여유를 부린 것이 아니었음에도 불구하고 기한 내에 만족할만한 코드를 완성하고 내용을 정리하려고 노력하면서 지금까지와는 다른 차원의 어려움을 느끼고 있습니다.

spring을 처음 배웠기 때문인지, cs 지식이 부족해서 공부를 많이 해야 했기 때문인지, LMS의 설명만으로는 부족해서 수많은 시행착오를 거쳐야 했기 때문인지, 배워야 하는 양이 많았기 때문인지, 힘들다는 것을 느낀 이유가 무엇일지를 고민해보면 그냥 전부 다인 것 같습니다.

미션을 구현할때는 제가 무엇에 포커스를 맞추고 공부를 해야 하는가에 대한 제대로 된 감도 오지 않았지만, 썬의 RC 덕분에 제가 무엇을 모르고 있는지와 이번 미션에서 어떤 것들을 알아가면 좋은지에 대해 알 수 있어서 매우 좋았습니다.

원래 각 미션에서 리뷰어와 피드백을 주고받으며 새로 알게 된 깊게 공부한 내용들을 블로그에 정리해서 적어왔는데, 이번 미션은 공부해서 적어야할 주제 리스트도 산더미인 데다가 바로 화요일에 다음 미션을 시작해버리니 정리할 시간이 없다는 것이 아쉬울 따름입니다. 

공부하고 고쳤지만 미흡한 부분이 있을 수 있고, 아직 의문이 남아있는 부분들은 Reply에 기입해 놓았습니다. 마지막까지 최선을 다하겠습니다. 통찰력 깊은 피드백 다시 한번 감사드립니다. 😄

2024-05-13 08:29 UTC, BurningFalls commented on src/main/java/roomescape/member/repository/MemberRepository.java
>      }
`Optional`을 사용하는 것의 장점에 대해서 추가로 알아보았습니다.

* **명확한 의도 표현**: `Optional`을 반환함으로써, **해당 메서드가 null을 반환할 수 있음을 명시적으로 나타낸다**. 이는 메서드의 시그니처만 보고도 반환 값이 없을 수 있다는 것을 쉽게 인지할 수 있게 해준다. 반면, null 반환은 메서드의 문서화를 자세히 읽거나 코드를 직접 확인하지 않는 한 이를 알아차리기 어려울 수 있다.

* **NullPointerException 방지**: `Optional`은 **null 관련 버그를 예방하는 데 도움을 준다**. `Optional` 객체를 사용하면, null 체크를 강제하기 때문에 `NullPointerException`을 방지할 수 있다. `Optional`의 메서드들은 값의 존재 여부를 체크하는 안전한 방법을 제공하며, `get()` 메서드를 호출하기 전에 `isPresent()`나 `ifPresent()`를 사용하여 값이 있는지 확인할 수 있다.

* **함수형 프로그래밍 지원**: `Optional`은 함수형 프로그래밍 스타일을 지원하는 메서드들(map, flatMap, filter 등)을 제공한다. 이러한 메서드들을 사용하면, 조건적 로직을 체인으로 연결하여 **더 간결하고 읽기 쉬운 코드를 작성할 수 있다**.

2024-05-13 15:27 UTC, syoun602 approved these changes
안녕하세요 폭포!

리뷰 잘 반영하신 것 확인했습니다 👍 코멘트마다 커밋 내역과 링크를 달아주셔서 리뷰하는 입장에서 변경점을 찾기 훨씬 수월했던 것 같아요 🙇‍♂️ 스프링이 워낙 방대하기 때문에 너무 조급해하기보다는 지금처럼 차근차근 꾸준히 학습하시면 충분히 잘 성장하실 것 같습니다!
이번 미션은 이만 머지할게요 고생 많으셨습니다 💪

2024-05-13 15:27 UTC, syoun602 commented on src/main/java/roomescape/auth/controller/CheckAdminInterceptor.java
> +        validateCookie(cookies);
추후에는 해당 interceptor안에서 쿠키를 관리하기보다는 쿠키를 관리하는 전용 클래스를 분리해봐도 좋을 것 같습니다!

2024-05-13 15:27 UTC, syoun602 commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +        return Long.valueOf(id);
파싱에 실패하면 어떻게 될까요?!

2024-05-13 15:27 UTC, merged