[4 - 6단계 방탈출 사용자 예약] 커찬(이충안) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #122
Opened 2024-05-11 05:59 UTC by leegwichan

안녕하세요 오리! 커찬입니다.

한 패키지에 파일이 많아지다보니, 패키지를 전반적으로 변경하게 되었습니다 (보시기는 힘드실 것 같아요 ㅠ_ㅠ)
그리고 저번 단계에 주셨던 피드백에는 코멘트 달아 놓았으니 참고 부탁드립니다!
리뷰 부탁드리겠습니다!

2024-05-11 06:28 UTC, leegwichan reviewed
아래는 저번 리뷰에 따른 코멘트입니다!

2024-05-11 06:28 UTC, leegwichan commented on src/test/java/roomescape/reservation/dao/ReservationDaoTest.java
> +class ReservationDaoTest {
> 어플리케이션의 크기가 1, 2레벨때는 크지 않기 때문에 현재의 구조로도 충분하다고 생각하는데 데이터 set이 많아지면 많아질수록 코드량 또한 많아지기 때문에 테스트 가독성이 떨어져요. truncate.sql은 되지만 data.sql은 종속되니까 안된다라는건 어색한 의견일 것 같아요.
1레벨때 15line을 넘지말라라는 요구사항이 있었을때 이는 테스트 메소드에도 적용되는 부분인데요. 이를 해결하기 위해서 해당 given 구절을 메소드로 분리한다면 이건 sql로 분리한 것과 depth는 결국 똑같아지게 될 것 같아요. (현재 구조에서 무조건 변경되어야한다고 남기는 코멘트는 아닙니다.)

"데이터 set이 많아지면 많아질수록 코드량 또한 많아진다는 것"을 이번 기회에 느꼈습니다. Reservation에 Member가 추가되면서 수정해야 될 포인트가 늘어났고, 위와 같이 관리하는 구조가 변경에 유연하지 못하다는 것을 깨달았습니다.

그리고 필요한 데이터들이 많아지면서 가독성이 점점 떨어진다는 것에 공감했습니다. 그래서 `init-test.sql`을 이용해 테스트에서 사용하는 데이터를 분리해 주었습니다.

2024-05-11 06:28 UTC, leegwichan commented on src/main/java/roomescape/reservation/controller/AdminReservationController.java
> +    }
> 커찬이 이야기한 내용도 혼동이 올 수 있는 부분이라 생각해요. 그래서 이미 @RestController가 달린 곳에 통일만을 위해서 ResponseEntity를 모두 쓰는 것이 아닌 status를 필요한 곳에만 사용하도록 하는 것을 말씀드린 것이었구요.
코드를 작성할 때 주의해야하는 것은 일관성을 지키는 것이 맞지만 프레임워크를 사용할 때 주의해야하는 것은 이 프레임워크의 의도대로 잘 쓰고 있느냐에요. 이미 200 json으로 반환하는데 ResponseEntity를 반환하는 것은 Spring이 의도한 사항은 아니기 때문에 초기부터 남겨드렸던 코멘트였어요.

저번에 뵙을 때도 이야기 해주셨던 내용인데요. 다음 RC에서 수정해보도록 하겠습니다!

2024-05-11 06:28 UTC, leegwichan commented on src/test/java/roomescape/advice/GlobalExceptionHandlerTest.java
> +    private final GlobalExceptionHandler globalExceptionHandler = new GlobalExceptionHandler();
> api를 구현해서 테스트해야할까요? mock으로 행위를 의도한 테스트를 만들어도 되지 않을까요?
혹은 단위테스트로 원하는 status가 반환되는지만 테스트해도 되지 않나요?

해당 메서드들이 정확한 값을 반환하는지 확인하는 테스트로 수정했습니다!

2024-05-11 11:17 UTC, leegwichan commented on src/main/java/roomescape/advice/GlobalExceptionHandler.java
> `RuntimeException` 대신 `Exception`으로 잡아주지 않아도 되나요?

당연히 기능 상 문제가 없다고 생각합니다! 오리는 `Exception`으로 명시하는 것이 더 명확하다고 생각하시나요?

2024-05-11 16:00 UTC, jinyoungchoi95 requested changes
안녕하세요 커찬 😄

몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-12 13:57 UTC, leegwichan reviewed
안녕하세요 오리! 커찬입니다.

달아주신 리뷰에 대해 코멘트 남겼습니다! 그리고 주신 리뷰는 최대한 반영해보았습니다.
리뷰 부탁드리겠습니다!

2024-05-12 13:57 UTC, leegwichan commented on src/main/java/roomescape/config/handler/AuthenticationArgumentResolver.java
> +        throw new MemberAuthenticationException();
해당 쿠키를 가져오는 과정을 `AccessTokenCookie`로 이동해서 처리하도록 변경했습니다!

2024-05-12 13:57 UTC, leegwichan commented on src/main/java/roomescape/config/handler/AdminAuthenticationInterceptor.java
일단 테스트 전용 컨트롤러를 만들어서 테스트를 진행했습니다. 이것이 좋은 방법인지는 고민이 되네요.
오리가 생각하는 Interceptor, ArgumentResoler의 테스트 방법이 있을까요?

2024-05-12 16:34 UTC, jinyoungchoi95 commented on src/main/java/roomescape/member/service/AuthService.java
> +    }
```java
    public AuthService(MemberDao memberDao, @Value("${jwt.secret-key}") String secretKey) {
        this.memberDao = memberDao;
        this.secretKey = secretKey;
    }
```
를 말한것이었습니다. `@Autowired`가 오히려 더 불필요한 생성자가 아닐까싶네요.

아래에 있는 생성자가 문제가 아닌 위에 있는 생성자가 문제인 것으로 `@Value`를 통해서 저렇게 nullable하게 표현하진 않습니다. 오히려 `secretKey`가 final이 아니기 때문에 더 객체지향에서 멀어지는것 아닌가요?

2024-05-12 16:38 UTC, jinyoungchoi95 commented on src/main/java/roomescape/member/service/AuthService.java
> +        }
에러메시지와는 별개로 jwt가 만료 혹은 잘못되는 이유는 발생하는 exception의 종류마다 다르기때문에 뭉뚱거려서 표현한다면 어떤 문제때문에 예외가 발생했는지 로직에서 확인하기 힘들기 때문입니다. 메시지가 동일하더라도 예외는 달라야겠죠.

2024-05-12 16:40 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/handler/AdminAuthenticationInterceptor.java
굳이 요청이 필요할까싶어요. "스프링"의 의존성이 필요한 경우에만 `@SpringBootTest`가 필요하지 현재의 경우에는 단위테스트로 실행해도 충분히 로직에 대한 테스트가 완수되는 것 아닐까요?

2024-05-12 17:00 UTC, jinyoungchoi95 requested changes
안녕하세요 커찬 😄

몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-12 17:00 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/handler/AuthenticationArgumentResolver.java
> +        return authService.findLoggedInMember(cookies);
여기도 사실 그냥 `Cookie`에서 특정 값을 가져오고 `AuthService`에는 단순히 추출된 id만 넘겨도 된다고 생각하는데요. 클래스 분리를 과하게 하지는 않았는지, 적절한 계층에 나뉘게끔 그 분리가 명확한지 고민해보시면 좋을 것 같아요.

2024-05-13 07:39 UTC, leegwichan reviewed
안녕하세요 오리! 커찬입니다. (자주 인사드리게 되네요)
주신 리뷰 중 일부 내용 반영해 보았습니다. 아래는 공통적인 코멘트에 대해 정리해 보았습니다. 리뷰 부탁드립니다!

### 인증, 인가 과정 리팩터링
Cookie, Token, memberId, Member 정보를 주고 받는 과정에서 역할이 잘 나뉘어지지 않았다고 생각이 들었습니다.

인증/인가가 필요한 곳에서 모두 쿠키를 만들어주거나, 쿠키의 내부 값이 들어오는 과정이 공통으로 들어 있었습니다. 그래서 이를 AuthService 내부로 넣으려고 하다 보니 이전과 같은 구조가 나왔던 것 같습니다. 'Web 계층의 정보는 컨트롤러에서 관리'하기 위해서 다음과 같이 구조를 바꾸었습니다.

<img src="https://github.com/woowacourse/spring-roomescape-member/assets/44027393/80d35c40-4228-4c68-990c-bd002a4ba59f" width="70%">

각 계층의 역할을 명확하게 분리하여, 조금 더 쉽게 알아볼 수 있도록 되었습니다.

2024-05-13 07:39 UTC, leegwichan commented on src/main/java/roomescape/auth/dto/RequestCookies.java
> +    }
일급 컬렉션에서 지금과 같은 상황은 이상해보이네요;; 다른 코드의 통일성을 고려했을 때는 `NullPointerException`이 적절해 보입니다!

전반적인 구조를 잘못 가져간 것 같습니다. 변경된 AuthService의 전반적인 구조는 전체 코멘트에 첨부했습니다!

2024-05-13 07:39 UTC, leegwichan commented on src/main/java/roomescape/auth/service/AuthService.java
> +    private String secretKey;
앗... 이렇게 쓸 때마다 더 좋은 방법이 없을까 고민 만하고 찾아보지는 않았네요. 조금 제 자신을 돌아보며 반성하게 되네요.

오리의 의견 반영해서 생성자에 `@Value`를 사용하도록 하겠습니다!

2024-05-13 09:51 UTC, jinyoungchoi95 approved these changes
안녕하세요 커찬 😄

현재 미션에서의 학습과 구현이 충분하게 진행된 것 같아 머지하겠습니다. 미션 수고하셨습니다 :)

감사합니다 🙇‍♂️

2024-05-13 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/auth/controller/TokenCookieManager.java
> +public class TokenCookieManager {
`@Component`일 이유가 따로 없어보이는데 `@Component`로 사용한 이유가 있을까요?

2024-05-13 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/auth/service/TokenProvider.java
테스트가 필요해보이네요.

2024-05-13 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    private final ThemeDao themeDao;
`Reservation`을 담당하는 서비스가 너무 많은 도메인들의 쿼리 의존성을 가지고 있는것 같아보이네요.

2024-05-13 09:51 UTC, jinyoungchoi95 commented on src/test/java/roomescape/config/handler/controller/HandlerTestController.java
> +    }
사용되지 않고 있는 것 같아보여요.

2024-05-13 09:51 UTC, jinyoungchoi95 commented on build.gradle
> +    implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'
개인적으로 major version이 0인 라이브러리는 신뢰되지 않아 사용하지 않습니다.

2024-05-13 09:51 UTC, jinyoungchoi95 commented on src/main/java/roomescape/config/handler/AdminAuthorizationInterceptor.java
`config`는 말그대로 설정만 있어야합니다. interceptor와 resolver는 특정한 기능을 담당하기 때문에 설정보다는 별도의 `interceptor`등과 같은 패키지가 더 어울리겠네요.

2024-05-13 09:51 UTC, merged