[4 - 6단계 방탈출 사용자 예약] 트레(이충렬) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #123
Opened 2024-05-11 06:57 UTC by takoyakimchi

안녕하세요 수달!
토큰, 쿠키, 인터셉터, ArgumentResolver 등의 개념이 아직 생소해서 구현에 꽤나 오랜 시간이 걸렸던 것 같아요.

요구사항은 모두 만족하였고, 리팩토링해야할 부분이 아직 조금 남아 있는데
제출이 너무 늦어지면 다음 미션에 지장이 가기도 하고, 리뷰를 많이 주고받지 못할 것 같아
TODO를 몇 가지 남긴 채 PR 보내는 점 양해 부탁드립니다 😭

패키지 구조나 토큰, 쿠키, 인터셉터, ArgumentResolver를 중점적으로 어색한 부분 피드백 주시면 감사드리겠습니다!

# 과제 진행 방향성
- 사용자(관리자)가 로그인하면, 브라우저에 사용자 정보에 대한 토큰이 쿠키로 남게 됩니다.
- 토큰에는 id, name, email, role(관리자 or 사용자) 정보가 들어 있습니다. 이 정보를 효율적으로 관리하기 위해서 `LoginMember` 도메인을 추가하였습니다.
- 기존의 `ReservationController`를 관리자, 사용자의 권한에 맞도록 각각 `AdminReservationController`, `UserReservationController`로 분리하였습니다.

# 앞으로의 리팩토링 방향성
- 일반 사용자는 ReservationTime을 추가, 삭제할 수 없도록 변경해 보겠습니다.
- 응답 DTO에서 과도한 정보를 전달하는 부분을 개선해 보겠습니다.
  - 예) `CreateReservationResponse`에서 `LoginMember`, `ReservationTime`, `Theme`의 모든 정보를 응답하고 있음
- 사용자가 로그아웃을 하더라도 토큰이 만료되지 않고 그대로 사용할 수 있는 문제를 개선해 보겠습니다.

2024-05-11 07:24 UTC, takoyakimchi commented on src/main/java/roomescape/global/auth/CheckRoleInterceptor.java
> +}
로그인이 되어 있지 않은 경우 cookies가 null로 들어와서 부득이하게 검증 로직이 많아진 것 같아요. 어떻게 개선할 수 있을까요...?

2024-05-11 07:24 UTC, takoyakimchi commented on src/test/java/roomescape/TokenTestFixture.java
> +}
`JwtTokenProvider`를 직접 의존해서 그때그때 토큰을 생성해주면 제일 좋겠지만, static으로 하기가 쉽지 않더라구요.

토큰을 사용하는 모든 테스트 클래스에서 토큰을 생성하는 방법도 생각해 보았지만, 미리 생성하고 하드코딩으로 넣는 방식이 더 편하다고 생각하였고, 2060-01-01에 만료되는 임의의 토큰을 만들었습니다.

토큰을 사용하는 테스트를 이렇게 작성하는 것이 과연 바람직할까요...?!

2024-05-11 07:24 UTC, takoyakimchi commented on src/main/java/roomescape/controller/api/LogoutController.java
> +}
로그아웃해도 기존의 토큰을 복사해서 나중에 그대로 사용할 수 있더라구요.
그래서 토큰을 강제로 만료시키는 로직이 필요할 것 같은데,
다른 크루에게 물어보니 로그아웃 시 해당 토큰을 블랙리스트에 추가하는 방식을 사용했다는 답변을 받았습니다!

그런데 그렇게 하자니, 로그아웃 횟수에 따라 데이터가 너무 방대하게 쌓일 것 같아서, Map을 쓴다고 하더라도 꽤나 비효율적일 것 같다는 생각이 드네요...

어떤 방식으로 하는 것이 좋을까요...?
현업에서는(~~마법의 키워드~~) 어떻게 하시는지 알려주시면 감사하겠습니다! 🙇

2024-05-11 07:24 UTC, takoyakimchi commented on src/main/resources/schema.sql
> +);
비밀번호를 포함한 모든 회원 정보가 하나의 테이블에 있는 것이 마음에 걸리는데요,
member_id, email, password를 따로 분리하여 테이블을 만드는 것이 더 좋을까요?

2024-05-12 06:27 UTC, her0807 commented on src/main/java/roomescape/global/auth/CheckRoleInterceptor.java
> +}
1. 인터셉터에서 쿠키나 토큰을 직접 검증하지 않아도 될 것 같아요. 
jwtTokenProvider 에 해당 책임을 위임해보면 어떨까요?

2. 잘못된 접근입니다 외에 구체적인 메세지가 있었으면 좋겠어요. 

3. `member.role() != ADMIN `은 메세지를 던져서 처리할 수 있을 것 같아요.

2024-05-12 06:30 UTC, her0807 commented on src/test/java/roomescape/TokenTestFixture.java
> +}
토큰을 고정해두고 테스트를 진행하는건 바람직하지 않을 것 같아요. 
이 토큰으로는 통과하지만, 비지니스 로직에서는 통과하지 않는 예외가 있을 수도 있을 것 같아요. 

또한 토큰의 만료기한을 통해서 검증해야하는 부분도 있는데 그런 부분에 대한 처리가 어렵기도 하고요. 
그래서 조금 불편하더라도 토큰을 생성해주는 방식을 하거나 토큰 검증 로직을 모킹해서 인수테스트를 진행하곤 하는 것 같습니다.

2024-05-12 06:37 UTC, her0807 commented on src/main/java/roomescape/controller/api/LogoutController.java
> +}
1. 우선 토큰을 블랙리스트에 넣는건 비추에요. 
세션이 아닌 토큰을 사용하는 이유는 확장성이 좋고, 세션을 관리하기 위한 특정 디비에 종속적인 행위를 하지 않아도 되어서인데요.
이렇게 되면 블랙리스트 토큰을 관리하는 또 다른 DB 와의 의존관계를 맺게 됩니다. 그러면 토큰의 이점을 제대로 활용할수 없게되어요.


그래서 현업에서는 어떤 서비스냐에 따라 다르지만, 
토큰 탈취시 위험이 큰 도메인이라면 세션을 쓰기도 하고(직접 만료시킬 수 있으니) 
토큰을 쓸 경우는 만료기간을 3분 내외로 잡아서 유효성 검사를 자주 하게 하는 것 같아요. 

그리고 리프레시 토큰을 통해서 사용자가 만료시간으로 인해 직접 갱신을 하지 않고 갱신 시켜주는 작업을 하곤 하는데요. 


- 토큰 유효, 유효한 리프레시 토큰 있음 -> 바로 로그인
- 토큰 만료, 유효한 리프레시 토큰 있음 -> DB 에서 리프레시 토큰 유무 확인 후 검증된 유저이면 새로운 토큰 발급해서 쿠키 세팅

이러면 이것도 블랙리스트 토큰 저장이나 세션과 비슷하게 DB 에 종속적이게 되는거 아닌가? 라는 의문이 들수 있습니다.
그러나 DB 를 찌르는 횟수가 현저히 적어집니다. 위 두개의 방법은 요청 100개면 100번 확인해야하는데 
리프레시 토큰은 100번 요청이면 만료된 시점만 확인하면 되니까요. 1번~ 2번이 될 수도 있겠죠???

2024-05-12 06:40 UTC, her0807 commented on src/main/resources/schema.sql
> +);
정규화를 진행할 때는 `이행적함수종속성`에 위배되거나, 중복이 있거나 여러 이유가 있을 것 같은데요 .어떤 점에서 마음에 걸리시나요?
테이블이 분리된다는 것은 관련된 정보가 분리되어서 매번 조회 될 때 조인과 같은 추가 비용이 드는 것을 의미하는데요.
그렇기 때문에 라이프 사이클이 같다면 같이 관리하는 것을 추천드립니다. ㅎㅎ

2024-05-12 06:41 UTC, her0807 commented on src/main/resources/schema.sql
> +);
그러나 때로는 반정규화를 하기도 해요. 예를 들면 어떤 게시물의 게시물 수나 조회수 같은 경우
조회 될 때마다 모든 데이터를 전부 스캔하게되니 그 비용보다 조회수를 매번 갱신하는 것이 더 비용이 적게 든다고 생각하는거죠

2024-05-12 07:16 UTC, her0807 requested changes
안녕하세요 트레!

오오 ~ 이번 미션 엄청 재밌게 구현하셨군요. 
질문 남겨주신 내용에 대한 제 생각 남겨두었습니다. 
내용 확인하시고 빠르게 다시 리뷰 요청 주세요.

테스트 코드도 엄청 꼼꼼히 작성해주시고 테스트 유저도 신경써서 남겨주어서 고마워요. 🙏

2024-05-12 07:16 UTC, her0807 commented on src/main/java/roomescape/global/argumentresolver/AuthenticationPrincipalArgumentResolver.java
> +}
`ArgumentResolver`  는 어떤 역할을 할까요?

조건에 만족하면 토큰에서 회원정보를 controller 시그니처에 전달해주는 것이 조금더 사용성에 좋을 것 같은데요. 
이렇게 되면 

1. 로그인 된 유저에 한해서 특정 행위를 하게끔 보장된다. 
2. 불필요한 defaultMember 검증을 하지 않아도 된다. 

개선이 될 것 같습니다.

2024-05-12 07:16 UTC, her0807 commented on src/main/java/roomescape/global/auth/JwtTokenProvider.java
> +            .claim(CLAIM_NAME, member.getName())
인터셉터에 있던 검증 부분이 파서 로직에 추가되면 빈약한 도메인이 보충될 것 같아요!!

2024-05-12 07:16 UTC, her0807 commented on src/main/java/roomescape/global/auth/JwtTokenProvider.java
> +        return Jwts.builder()
JWT 토큰 내 구조는 어떻게 생겼을까요?

payload 내에도 여러개의 정보를 담을 수 있는데요. 

payload 가 무거워지면 그만큼 긴 토큰을 네트워크 통신을 할 때 주고 받게 되고, 

특히 이름과 이메일, 롤과 같은 부분은 변경이 가능한데, 토큰이 만료되지 않은 상태에서 핸들링이 된다면 
잘못된 데이터로 비지니스 로직을 수행할 수 있게 되어요 🥹

그래서 최대한 불변하면서, 사용자를 식별가능한 무언가를 넣어주면 좋습니다.

2024-05-12 07:16 UTC, her0807 commented on src/main/java/roomescape/global/auth/JwtTokenProvider.java
> +
오오 환경 변수를 사용해서 설정 값을 가려주었군요 👍🏻

2024-05-12 07:16 UTC, her0807 commented on src/test/java/roomescape/controller/api/AdminReservationControllerTest.java
> +class AdminReservationControllerTest {
### 테스트에 대하여

트레!이번 테스트를 보니 인수 테스트를 모든 케이스로 진행해준 것 같아요,

그런데 인수테스트는 실제 스프링 빈이 주입되고 관련 데이터가 세팅되어야하고, 네트워크 비용도 드는 
엄청 비싼 테스트랍니다. 

그래서 최대한 단위테스트를 많이 작성하고, 필요한 로직에 한해서 인수테스트를 작성하는 것을 권장드리는데요.

트레는 어떨 때 단위/통합/인수 테스트를 작성하시나요?
해피케이스/베드 케이스 모두 인수테스트가 존재해야한다고 생각하나요?

2024-05-13 05:58 UTC, takoyakimchi commented on src/main/java/roomescape/controller/api/MemberController.java
> +@Controller
이 부분 놓쳤네요.
반영하였습니다!

2024-05-13 06:22 UTC, takoyakimchi commented on src/main/java/roomescape/domain/member/Email.java
> +public class Email {
검증 로직도 분리되고 견고해지는 것 같아요!

2024-05-13 06:24 UTC, takoyakimchi commented on src/main/java/roomescape/global/argumentresolver/AuthenticationPrincipalArgumentResolver.java
> +}
검증 로직을 `JwtTokenProvider`한테 맡기고 역할에 집중하도록 수정하였습니다!
생각보다 중복 코드가 좀 많더라구요 ... 😅

2024-05-13 06:33 UTC, takoyakimchi commented on src/main/java/roomescape/global/auth/JwtTokenProvider.java
> +        return Jwts.builder()
JWT 토큰 내 구조를 알아보았습니다!

> Header, Payload, Signature가 `.`으로 구분되어 나타난다.
> **Header**: typ(토큰 타입), alg(서명 알고리즘 방식)
> **Payload**: 클레임(토큰에서 사용할 정보의 조각)이 담겨 있음
> **Signature**: 토큰을 인코딩하거나 유효성 검증을 할 때 사용하는 고유한 암호화 코드

토큰에 어떠한 정보가 담겨야 할지는 아직 감이 잘 안 오네요.
현재는 role을 토큰에 담는 방식으로 구현했는데요.

이름, 이메일, role이 변경되면 그 때 토큰을 만료시키고 변경시키면 되지 않을까? 하는 생각이 있었는데,
그렇게는 구현하지 않는 편인가요?

2024-05-13 06:38 UTC, takoyakimchi commented on src/main/java/roomescape/global/auth/CheckRoleInterceptor.java
> +}
감사합니다!!

수달의 리뷰를 보고 코드를 수정하면서 ArgumentResolver, 인터셉터 등등
각각의 역할에 대해서 감이 조금 잡힌 것 같아요!

2024-05-13 06:41 UTC, takoyakimchi commented on src/main/resources/schema.sql
> +);
SELECT문을 잘못 작성한 경우 비밀번호가 노출되는 경우도 있고
email, role 등은 가져올 일이 많은데 비밀번호처럼 민감정보가 동일한 테이블에 같이 있는 것이
마음에 걸렸던 것 같아요!

추후 미션 진행하면서 차근차근 알아보도록 하겠습니다!

2024-05-13 06:42 UTC, takoyakimchi commented on build.gradle
이번 리뷰는 잘못 남겨주신 걸까요?!
이와 별개로 21, 22번 라인의 의존성은 필요가 없다는 걸 알게 되었어요.
(트러블슈팅 과정에서 스택 오버플로우에서 그대로 복붙해왔습니다... 😅)

현재는 아래와 같이 수정했습니다!

```
    implementation 'io.jsonwebtoken:jjwt:0.9.1'
    implementation 'javax.xml.bind:jaxb-api:2.3.1'
```

2024-05-13 06:46 UTC, takoyakimchi commented on src/main/java/roomescape/controller/api/AdminReservationController.java
> +
path variable: 고유 리소스 식별
query parameter: 정렬, 필터링, 조회 등등 / GET에서 사용
request body: 파일 업로드, 데이터 추가 등등 / POST에서 사용

이렇게 알고 있습니다!

2024-05-13 06:46 UTC, takoyakimchi commented on src/main/java/roomescape/controller/api/AdminReservationController.java
> +            )).toList();
적용해 보겠습니다 !!

2024-05-13 06:47 UTC, takoyakimchi commented on src/main/java/roomescape/controller/api/LoginController.java
> +
30분으로 설정해보겠습니다
!

2024-05-13 06:47 UTC, takoyakimchi commented on src/main/java/roomescape/controller/api/UserReservationController.java
> +            member.id(), request.date(), request.timeId(), request.themeId()));
이건 그냥 parameter로 직접 넣어주는 게 좋을 것 같네요!

2024-05-13 07:11 UTC, takoyakimchi commented on src/test/java/roomescape/controller/api/AdminReservationControllerTest.java
> +class AdminReservationControllerTest {
인수 테스트가 많으면 좋은 줄 알았는데 그런 것도 아니었군요.
다음 미션부터는 유념해서 작성해 보도록 하겠습니다!

단위 테스트 -> 도메인, 서비스 계층에서 비즈니스 로직 테스트
통합 테스트 -> DB 등 외부 시스템과 연동이 잘 되는지 테스트
인수 테스트 -> 클라이언트의 시나리오에 따라 잘 작동되는지를 해피 케이스만 작성하되, 치명적 보안 이슈가 있을 수 있는 경우에는 배드 케이스까지 작성

이렇게 일단 생각해 보았는데, 아직은 잘 모르겠네요 ... ㅠㅠ

2024-05-13 07:25 UTC, her0807 commented on src/main/java/roomescape/global/auth/JwtTokenProvider.java
> +        return Jwts.builder()
@takoyakimchi  토큰을 만료시킬  수 있나요??

2024-05-13 08:42 UTC, takoyakimchi commented on src/main/java/roomescape/global/auth/JwtTokenProvider.java
> +        return Jwts.builder()
@her0807 토큰에 이미 만료날짜가 포함된 상태로 발급되기 때문에 그렇게는 안 될 것 같네요...!
member ID를 넣어 놓고 그때그때 admin인지 DB에 물어봐야 할까요?

2024-05-13 13:10 UTC, her0807 commented on src/main/java/roomescape/controller/api/LogoutController.java
> +    }
아하 그렇군요!! 그런데 불필요하게 분리된 컨트롤러는 관리 포인트가 늘어나는 페인 포인트가 되기도 하는 것 같아요 🥲

그래서 현업에서는 주로 도메인 별로 / 사용 영역 별로(internal, external ) 나누곤 하는 것 같습니다.
여러가지 기준으로 경험해보는 것은 아주 좋은 것 같아요.

2024-05-13 13:10 UTC, her0807 commented on build.gradle
아 네네 위에 부분은 잘못 남긴 것 같아요 😅

현업에서는 한번 의존성을 주입하게 되면 쉽게 제거하지 못하겠더라고요.
제가 설정해둔 것은 제거할 수 있는데 다른 분들이 적용한 것은 뜻이 있겠지(?)
라는 생각에.. ㅎㅎ 

그래서 최대한 사용되는 것들로만 의존성을 맺는 연습을 통해 의도치 않은 장애를 막을 수 있고
혼란스러움도 줄일 수 있을 것 같아 남긴 피드백이었습니다!

2024-05-13 13:12 UTC, her0807 commented on src/main/java/roomescape/controller/api/UserReservationController.java
> +            member.id(), request.date(), request.timeId(), request.themeId()));
어떤 이유로 그렇게 생각하셨는지도 함께 남겨주시면 이해하는데 도움이 많이 될 것 같아요. 

제가 볼 때는 불필요하게 SaveReservationDto 내부가 노출되는 것 같이 느껴지고 예약을 저장하는 행위가 
가려지는 느낌이 들어서 제안드렸던 것이었거든요.

2024-05-13 13:14 UTC, her0807 commented on src/main/java/roomescape/global/auth/JwtTokenProvider.java
> +        return Jwts.builder()
이럴 경우 리프레시 토큰을 통해서 더이상 토큰을 갱신하지 못하게 할 수는 있을 것 같아요. 

> member ID를 넣어 놓고 그때그때 admin인지 DB에 물어봐야 할까요?

이렇게 되면 매번 DB 와 통신을 해야하기 때문에 토큰을 쓰는 장점을 활용하지 못하게 됩니다 ㅠㅠ
`토큰, 세션, 쿠키, 리프레시 토큰` 한번더 찾아보시면 좋을 것 같습니다.

2024-05-13 13:15 UTC, her0807 commented on src/test/java/roomescape/controller/api/AdminReservationControllerTest.java
> +class AdminReservationControllerTest {
여러가지 경험을 통해서 나만의 생각을 정립하는 과정이기 때문에
이렇게 고민해보고 정리해보는 경험들이 쌓여서 점점 선명해질거예요.

정답은 없기 때문에 다음 미션에 생각해보신대로 구현해보고 또한번 테스트에 대한 기준을 정리해보고
그러면 좋을 것 같습니다.

2024-05-13 13:24 UTC, her0807 approved these changes
안녕하세요 트레!

인증/ 인가 들어가면서 정말 어려워졌죠 😞
미션 처음 시작할 때는 항상 할만한 것 같은데 
갑자기 러닝 커브가 급격히 올라간 느낌이 들기도 할 것 같아요. 

이럴 때일 수록 지금 상태에서 흡수할 수 있는 지식들만 취사 선택해서 얻어가고,
이번에 가져가지 못한 키워드는 언젠가 볼 수 있게 키워드로 남겨두면 좋을 것 같아요. 

크게 수정할 곳은 없어보여서 이만 머지할게요!
미션 하느라 고생 많으셨어요~!

2024-05-13 13:25 UTC, merged