[4 - 6단계 방탈출 사용자 예약] 아톰(이하늘) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #125
Opened 2024-05-11 07:10 UTC by le2sky

2024-05-11 08:52 UTC, kimhodol requested changes
안녕하세요 아톰 :)

요구사항 잘 구현해주셨네요.

코멘트 확인 부탁드릴게요!

2024-05-11 08:52 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +                .claim("isAdmin", member.isAdmin())
의견) 중복되는 문자열들은 상수화해도 좋을 것 같아요.

2024-05-11 08:52 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +                .orElseThrow(() -> new IllegalArgumentException(AUTHENTICATION_FAIL_MESSAGE));
의견) 메세지가 중복되는 것 같은데, IllegalArgumentException을 상속받는 AuthenticationException 커스텀 클래스를 만들어보는 것은 어떨까요? 아니면 지금 사용하고 있는 UnauthorizedException를 써도 될것 같아요.

2024-05-11 08:52 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/persistence/dynamic/ReservationQueryConditions.java
> +public class ReservationQueryConditions {
검색 조건을 잘 추상화하신것 같네요! 굿굿

2024-05-11 08:52 UTC, kimhodol commented on src/main/java/roomescape/domain/Member.java
> +    private final String password;
의견) email이나 password도 name처럼 값 객체로 만들어주는 것은 어떨까요?

2024-05-11 08:52 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +    private static final String SECRET_KEY_VALUE = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
의견) 사소하긴한데, 키 값을 application property로 관리해보는 것은 어떨까요? expiry도 같이 설정하면 좋을 것 같네요.

2024-05-11 08:52 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/persistence/MemberRepository.java
> +    }
의견) 하나의 row만 가져온다는 의미에서 LIMIT 1을 붙여주면 어떨까요?

2024-05-11 08:52 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/persistence/dynamic/ReservationQueryConditions.java
> +        }
의견) 인덴트는 1 이하로 만들어주세요.

2024-05-11 08:52 UTC, kimhodol commented on src/main/java/roomescape/web/controller/AuthController.java
> +    public ResponseEntity<AuthenticatedMemberProfile> check(HttpServletRequest request) {
질문) 만들어놓은 ArgumentResolver를 사용하지 않은 이유가 있나요?

2024-05-11 08:52 UTC, kimhodol commented on src/test/java/roomescape/infrastructure/persistence/ReservationRepositoryTest.java
> +                .themeId(1L)
의견) 1L, 2L같이 테스트 시드 데이터의 값들을 상수화해서 IntegrationTestSupport에 넣어두고 사용하는 것은 어떨까요?

2024-05-12 06:21 UTC, le2sky commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +                .claim("isAdmin", member.isAdmin())
현재 상수화 처리했습니다! 감사합니다. 😀

2024-05-12 07:04 UTC, le2sky commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +                .orElseThrow(() -> new IllegalArgumentException(AUTHENTICATION_FAIL_MESSAGE));
단순히, 해당 클래스에서만 사용되는 메시지이기 때문에 상수로 추출했었는데요.
현재는 AuthenticationFailException 커스텀 클래스를 구현하도록 변경했습니다! 

**[질문]** 이전 코드는 인프라 영역에서 상위 계층의 예외 메시지를 결정하는데요. 이것도 문제가 될 수 있을까요?
예를 들어 `AuthService` 구현체가 바뀐다면 해당 메시지가 주어질지 예측하기 어렵습니다. 
상위 계층에서 테스트가 잘 작성되어 있으면 좋겠지만 그렇지 않을 수도 있어요.

이 경우에는 상위 맥락(응용 계층)의 커스텀 예외(AuthenticationFailException)를 사용해서 메시지를 강제할 수 있어요.
하지만, 결국에는 `AuthService`의 구현체를 개발하는 다른 개발자가 해당 커스텀 예외를 던지지 않으면, 메시지를 강제하지 못하게 됩니다.  

**[질문]** 이런 경우에는 다른 개발자를 위해서 아래와 같이 인터페이스에 `throws` 키워드를 명시하는 편이 좋을까요?

/service/auth/AuthService.java
```java
public interface AuthService {

    String authenticate(AuthenticationRequest request) throws AuthenticationFailException;

    AuthenticatedMemberProfile authorize(String token) throws UnauthorizedException;
}
```

**[질문]** 혹은 지금 구조 자체가 불필요하게 복잡할까요!? 호돌의 의견은 어떠신가요?

2024-05-12 07:06 UTC, le2sky commented on src/main/java/roomescape/domain/Member.java
> +    private final String password;
현재 email, password 값 객체로 변경해봤습니다! 하는 김에.. 테마 name,  description, thumbnail도 값 객체로 변경해봤는데요. 어색한 부분이 있다면, 추가 피드백 부탁드립니다!

2024-05-12 07:32 UTC, le2sky commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +    private static final String SECRET_KEY_VALUE = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
현재 프로퍼티로 관리하고, 만료일도 지정했습니다! 어색한 부분이 있다면, 추가 피드백 부탁드립니다. 감사합니다.🙇🏻‍♂️
(구현하면서 `spring-boot-configuration-processor` 의존성을 추가했습니다!)

그리고 개발하면서 사소한 궁금증이 생겼는데요. 

**[질문]** 인증과 인가는 중요한 기능으로 알고 있어요. 프로젝트 개발 초기에 필요한 기능일까요?

예를 들어, 엑세스 토큰과 리프레시 토큰을 이용해서 인증과 인가를 한다고 가정했을 때,
테스트 코드 작성 시점에는 인증과 인가를 담당하는 부분 대신에 테스트 대역을 사용해 볼 수 있을 것 같아요.
혹은 지금처럼 테스트 계정을 사용해볼 수도 있겠습니다.

하지만, 프론트엔드 개발자가 클라이언트 코드를 만들때, 번거로운 상황이 생길 수도 있을 것 같아요. 
예를 들어, API를 연동해서 개발해야하는데.. 토큰이 만료되는 상황이 있을 수도 있을 것 같습니다.
호돌의 의견은 어떠신가요?

2024-05-12 07:37 UTC, le2sky commented on src/main/java/roomescape/infrastructure/persistence/MemberRepository.java
> +    }
의견 주셔서 감사합니다! 현재 `LIMIT 1`을 추가하도록 변경했습니다.
성능상 큰 이점은 없지만, 하나의 로우를 가져온다는 의도를 담기 위한 것으로 해석했는데요.
호돌의 피드백을 올바르게 이해하고 적용했을까요? 놓치고 있는 것이 있다면, 추가 피드백 부탁드립니다! 😀

2024-05-12 07:38 UTC, le2sky commented on src/main/java/roomescape/infrastructure/persistence/dynamic/ReservationQueryConditions.java
> +        }
헉.. 현재 인덱트를 1로 변경했습니다. 감사합니다! 🙇🏻‍♂️

2024-05-12 07:40 UTC, le2sky commented on src/main/java/roomescape/web/controller/AuthController.java
> +    public ResponseEntity<AuthenticatedMemberProfile> check(HttpServletRequest request) {
ArgumentResolver가 `Long Id`를 만들도록  만들어놔서, 단순히 여기서는 못쓰겠다 생각하고 넘긴 것 같아요..!
현재는 ArgumentResolver가 AuthenticatedMemberProfile를 만들도록 변경했습니다!

2024-05-12 07:46 UTC, le2sky commented on src/test/java/roomescape/infrastructure/persistence/ReservationRepositoryTest.java
> +                .themeId(1L)
비용이 큰 작업이라고 생각이 들어서, 호돌의 의견을 정확히 이해하고 반영해보고 싶습니다!
혹시 아래와 같은 느낌을 의도하신게 맞을까요?!

```java
    @Test
    @DisplayName("특정 시간 id를 사용하고 있는 예약 데이터가 존재하는지 검증한다.")
    void hasByTimeId() {
        ReservationQueryConditions conditions = ReservationQueryConditions.builder()
                .timeId(예약에서_사용되고_있는_시간_ID)
                .build();

        boolean result = target.hasBy(conditions);

        assertThat(result).isTrue();
}
```

2024-05-13 08:18 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +                .orElseThrow(() -> new IllegalArgumentException(AUTHENTICATION_FAIL_MESSAGE));
> 이전 코드는 인프라 영역에서 상위 계층의 예외 메시지를 결정하는데요. 이것도 문제가 될 수 있을까요?

질문이 잘 이해가 안 가긴했는데, 이해한대로 답변드리겠습니다. 하위 계층에서 상위 계층의 예외 메시지를 결정해두고, 만일 상위 계층에서 메세지 변경이 필요하다면 try-catch를 상위 계층에서 다시 하는 것이 자연스럽지 않을까요?

> 이런 경우에는 다른 개발자를 위해서 아래와 같이 인터페이스에 throws 키워드를 명시하는 편이 좋을까요? 

`throws`를 사용하면 외부에서 무조건 try-catch를 해줘야하지 않나요? 저는 fast fail 방식을 선호해서, 에러가 난 곳에서 예외를 던지는 편입니다.

> 혹은 지금 구조 자체가 불필요하게 복잡할까요!? 호돌의 의견은 어떠신가요?

구조야 뭐 정답이 없는 문제지만, 지금 복잡하다는 생각은 들지 않습니다! 좋은 고민을 하고 계신 것 같아요 👍

2024-05-13 08:21 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +    private static final String SECRET_KEY_VALUE = "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E=";
> 인증과 인가는 중요한 기능으로 알고 있어요. 하지만, 프로젝트 개발 초기에 필요한 기능일까요?

요구사항 따라 다르겠죠? 어떤 프로젝트들은 인증과 인가가 아예 필요 없는 경우도 있습니다. 하지만 인증 인가가 필수적으로 요구되는 서비스라면 먼저 탄탄하게 개발해두는 것이 오히려 나중에 side effect를 줄일 수 있지 않을까요? 클라이언트에서 토큰이 만료되는 경우같은 불편함은 클라이언트 개발자가 알아서 하도록 냅두는게 좋습니다 ㅎㅎ 그 쪽에서도 토큰이 만료되면 재인증을 걸치거나 하는 로직들은 저희가 인증/인가 만들듯이 일반적인 로직인 것 같아요.

2024-05-13 08:30 UTC, kimhodol requested changes
안녕하세요 아톰 :)

거의 다 온 것 같네요.

코멘트 확인 부탁드립니다!

2024-05-13 08:30 UTC, kimhodol commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +        return System.currentTimeMillis() + (ONE_MILLI_SECOND * jwtProperties.tokenExpirationSecond());
질문) 1ms는 왜 추가되나요?

2024-05-13 08:30 UTC, kimhodol commented on src/main/java/roomescape/web/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler()
의견) 불필요한 괄호인것 같아요.

2024-05-13 08:30 UTC, kimhodol commented on src/test/java/roomescape/domain/EmailTest.java
> +    }
질문) 요구사항에는 없지만, 이메일도 이메일 형식을 따르게 해보는 것은 어떨까요?

2024-05-13 08:30 UTC, kimhodol commented on src/test/java/roomescape/infrastructure/persistence/ReservationRepositoryTest.java
> +                .themeId(1L)
네네, 예약시간1_ID 이런것을 생각했습니다!

2024-05-13 11:38 UTC, le2sky commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +                .orElseThrow(() -> new IllegalArgumentException(AUTHENTICATION_FAIL_MESSAGE));
답변 감사합니다! 성장에 많은 도움이 됐습니다. 😀

2024-05-13 11:42 UTC, le2sky commented on src/test/java/roomescape/infrastructure/persistence/ReservationRepositoryTest.java
> +                .themeId(1L)
현재 데이터 값들을 상수화하도록 변경해봤는데요. 어색한 부분이 있다면, 추가 피드백 부탁드립니다! 감사합니다. 🙇🏻‍♂️

2024-05-13 11:45 UTC, le2sky commented on src/main/java/roomescape/infrastructure/authentication/JwtAuthService.java
> +        return System.currentTimeMillis() + (ONE_MILLI_SECOND * jwtProperties.tokenExpirationSecond());
ONE_SECOND(1000ms)를 상수화 해놓은다음에, 토큰 만료 시간 설정 값에서는 초 단위로 명시해주고 싶었어요. 
상수 이름을 잘못 설정해서.. 현재는 `ONE_SECOND`로 변경했습니다! 어색한 부분이 있다면, 추가 피드백 부탁드립니다. 😀

2024-05-13 11:46 UTC, le2sky commented on src/main/java/roomescape/web/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler()
현재 불필요한 괄호를 제거했습니다! 감사합니다.

2024-05-13 12:00 UTC, le2sky commented on src/test/java/roomescape/domain/EmailTest.java
> +    }
이메일 형식 검사에 대한 책임은 프레젠테이션이 가져가는 것이 적당하다고 생각했어요.(현재는 프레젠테이션 계층과 응용 계층의 DTO를 분리하는 것이 복잡도를 높인다고 생각해서, 응용 계층 DTO에 `@Email` 어노테이션이 있기는 하지만요..)

따라서, 프레젠테이션 레이어에서 `@Email`을 이용해서, `@`가 있는지 확인하고, 도메인 레이어 내부에 이메일과 관련된 어떠한 책임을 준다고 한다면, 유효한 도메인(`naver.com`, `woowacourse.com`)인지 검사하는 것을 구현하려고 했어요. 

제가 놓치고 있는 부분이 있을 수도 있어요. 호돌의 의견은 어떠신가요?

2024-05-15 00:44 UTC, kimhodol commented on src/test/java/roomescape/domain/EmailTest.java
> +    }
프레젠테이션에서 Email 검증을 하고 있군요? 그렇다면 이슈 없습니다!

2024-05-15 00:49 UTC, kimhodol approved these changes
안녕하세요 아톰 :)

이번 미션은 여기서 마무리해도 될 것 같네요.

다음 미션도 화이팅입니다!

2024-05-15 00:49 UTC, merged