[4 - 6단계 방탈출 사용자 예약] 프린(남기범) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #134
Opened 2024-05-11 14:00 UTC by GIVEN53

2024-05-11 17:00 UTC, jinyoungchoi95 requested changes
안녕하세요 프린 😄

몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-12 16:40 UTC, GIVEN53 reviewed
안녕하세요 오리 🐥

리뷰 반영과 함께 코멘트 남겼습니다
감사합니다!

2024-05-12 16:40 UTC, GIVEN53 commented on src/main/java/roomescape/global/config/WebMvcConfig.java
> +    }
두 구현체는 다른 빈에 주입되지 않고 위처럼 추가하지 않으면 사용하지 못하기 때문에 IoC 컨테이너의 불필요한 빈 관리를 피하기 위해 생성자를 사용했어요
무지성 `@Component`는 지양하려는 편인데, 제가 놓친 두 구현체에 `@Component`를 사용했을 때 얻을 수 있는 다른 이점이 있을까요??

2024-05-12 16:40 UTC, GIVEN53 commented on src/test/java/roomescape/auth/AuthenticationInfoExtractorTest.java
> +@SpringBootTest(webEnvironment = WebEnvironment.NONE)
클래스를 삭제하면서 해당 테스트도 삭제되었습니다!

2024-05-12 16:40 UTC, GIVEN53 commented on src/test/java/roomescape/auth/CheckAdminAccessInterceptorTest.java
> +@WithoutWebSpringBootTest
혼란의 여지가 있군요
적당한 네이밍이 떠오르지 않아서 ServiceTest로 변경했어요 Service가 아니면 사용하면 안될 것 같은 느낌인데 역시 네이밍은 어렵네요,,

2024-05-12 16:40 UTC, GIVEN53 commented on src/test/resources/application.yml
> +      data-locations:
프로덕션의 data.sql이 테스트에서 실행되는 것을 막기 위해 설정했습니다
명확하게 하기 위해 null을 명시했습니다

2024-05-12 17:05 UTC, jinyoungchoi95 commented on src/main/java/roomescape/global/config/WebMvcConfig.java
> +    }
저는 차라리 무지성 `@Component`가 낫다라는 생각입니다. `@Controller`, `@Service`는 사용하면서 `@Component`로 빈등록을 하지 않는다는 것은 빈등록에 대한 일관성을 떨어뜨리고, 이건 어디에서 빈등록되었는지 알아보기 힘들기 때문이에요. 어짜피
```java
    private final AuthService authService;
    private final AuthenticationPrincipalArgumentResolver authenticationPrincipalArgumentResolver;

    public WebMvcConfig(AuthService authService, AuthenticationPrincipalArgumentResolver authenticationPrincipalArgumentResolver) {
        this.authService = authService;
        this.authenticationPrincipalArgumentResolver = authenticationPrincipalArgumentResolver;
    }

    @Override
    public void addArgumentResolvers(List<HandlerMethodArgumentResolver> resolvers) {
        resolvers.add(authenticationPrincipalArgumentResolver);
    }
```
로 사용되나 생성하나 IoC에서 관리되는 동작은 똑같으니까요.

오히려 `@Configuration`에서 주입하는 경우가 특이케이스이고 보통은 바로 빈등록이 되지 않아야하는 클래스인 경우이거나 Config에서 특정 로직을 통해서 빈등록이 되어야하는 경우에 그렇게 구현하는 것 같네요.

2024-05-12 17:07 UTC, jinyoungchoi95 commented on src/test/resources/application.yml
> +      data-locations:
혼동을 주기 때문에 차라리 옵션을 제거하고, `data.sql`과 같은 default 네이밍이 아닌 필요한 네이밍으로 파일을 변경하고 필요에 따라 yml에 설정하는 것이 더 좋아보여요.

2024-05-12 17:07 UTC, jinyoungchoi95 commented on src/main/java/roomescape/application/MemberService.java
> +    }
괜찮다고 생각합니다 :)

2024-05-12 17:20 UTC, jinyoungchoi95 requested changes
안녕하세요 프린 😄

현재 미션에서의 학습과 구현이 충분하게 진행된 것 같아 머지하려는데 추가 남긴 코멘트에 궁금하신점이 있을까하여 request change 드려요.

감사합니다 🙇‍♂️

2024-05-12 17:20 UTC, jinyoungchoi95 commented on src/main/java/roomescape/global/advice/GlobalExceptionHandler.java
> +        e.printStackTrace();
stackTrace는 print하지 않습니다.

2024-05-12 17:20 UTC, jinyoungchoi95 commented on src/main/java/roomescape/ui/support/AuthenticationExtractInterceptor.java
> +        request.setAttribute(PRINCIPAL_KEY_NAME, principal);
현재 어플리케이션 규모에서 `ThreadLocal` 혹은 `@RequestScope`를 사용하지 않아도 된다는 것에는 동의하는데 `HttpServletRequest`를 컨트롤하는 것은 지양하는 편이 좋아요.

`HttpServletRequest`는 실제 request에서 들어오는 값들이 담긴 것으로, 여기서 뭔가 값을 추가하게되면 실제 http request에서 더 추가가 되는 것이기 때문에 이걸 만약에 쓸 수도 있는 다른 객체에서 request를 오인할 수 있어요. 그리고 `HttpServletRequest`와 같은 클래스들을 커스텀하다 에러 트러블슈팅할 일이 생기게 될 수 있는데 그때보면 `HttpServletRequest`에서 값을 읽거나 쓰는 동작이 왜 지양되는지 확인할 수 있을 것 같아요.

그래서 반영하지 않아도된다라는 뜻은 저 두가지가 아닌이상 사실 반복 로직을 타는게 낫다라는 생각입니다.

2024-05-12 17:20 UTC, jinyoungchoi95 commented on src/main/java/roomescape/ui/support/CheckAdminAccessInterceptor.java
> +        Principal principal = (Principal) request.getAttribute(AuthenticationExtractInterceptor.PRINCIPAL_KEY_NAME);
여기도 결국 타입캐스팅을 해야하는 문제가 발생하는거구요.

2024-05-12 17:20 UTC, jinyoungchoi95 commented on src/main/java/roomescape/auth/TokenProvider.java
jjwt 라이브러리도 외부 라이브러리이기 때문에 외부 라이브러리를 사용한 구현체에 대한 추상화 처리가 필요해보이네요.

2024-05-12 17:20 UTC, jinyoungchoi95 commented on src/main/java/roomescape/ui/support/AuthenticationExtractInterceptor.java
따지고보면 `Interceptor`는 지원하는 support의 역할이 아닌 하나의 웹요청에 대한 계층에 해당하기 때문에 `interceptor` 패키지로 두는 것이 맞는 것 같아요.

2024-05-12 17:20 UTC, jinyoungchoi95 commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
개인적으로 major version이 0인 라이브러리는 신뢰되지 않아 사용하지 않습니다.

2024-05-12 17:20 UTC, jinyoungchoi95 commented on src/test/java/roomescape/infrastructure/JdbcMemberRepositoryTest.java
> +@JdbcTest
`@JdbcTest`를 사용한 것과 `@ExtendWith(TableTruncateExtension.class)`를 사용하여 테스트를 롤백한 것들이 중복되어있는데 두 방식의 테스트 롤백구조가 어떻게 다르고 어떤걸 사용하여야하는가 고민해보시면 좋을 것 같아요.

2024-05-13 11:05 UTC, GIVEN53 reviewed
안녕하세요 오리!
바쁘신 상황에도 불구하고 정성 리뷰 달아주셔서 정말 감사해요🙃
약간의 코멘트 남겼습니다!

2024-05-13 14:35 UTC, jinyoungchoi95 commented on build.gradle
> +    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
> As JJWT isn't yet at version 1.0, only the latest minor and point revisions are supported for security fixes.
We ask that all users or security researchers upgrade to the latest stable release version and use that for testing before issuing a security report.

이게 몇년째 major 버전을 안올리고 있는데 라이브러리에서 major 버전이라는 것은 꽤나 중요한 의미를 가져다주어요. 다른 라이브러리도 있어서 대안이 없는 것은 아닌 것 같아요.

2024-05-13 14:37 UTC, jinyoungchoi95 commented on src/test/java/roomescape/infrastructure/JdbcMemberRepositoryTest.java
> +@JdbcTest
https://jojoldu.tistory.com/761

라는 이야기가 있으니 재미삼아 읽어보셔요.

2024-05-13 14:38 UTC, jinyoungchoi95 approved these changes
안녕하세요 프린 😄

현재 미션에서의 학습과 구현이 충분하게 진행된 것 같아 머지하겠습니다. 미션 수고하셨습니다 :)

감사합니다 🙇‍♂️

2024-05-13 14:38 UTC, merged