[4 - 6단계 방탈출 사용자 예약] 호기(조호연) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #139
Opened 2024-05-11 16:53 UTC by hoyeonyy

안녕하세요 스티치!! 호기입니다👋

인증, 리졸버, 인터셉터 전부 처음 접해보는 개념이라 리뷰요청까지 시간이 많이걸렸네요..😭
중간에 너무 엉켜 처음부터 다시 구현을 했습니다,,!
제가 고민했던 내용을 공유해드릴께요!

----

### 슬라이싱 테스트에서 통합테스트로..?

사실 컨트롤러를 테스트할 때에는 굳이 스프링 부트가 필요하지 않다고 생각했습니다!
테스트의 시간이 길어지기도 하고 불필요한 빈등록이 필요 없다는 점 때문에 스프링부트를 띄우지 않고 테스트했습니다.
하지만 이번 미션을 진행하며 인증, 리졸버, 인터셉터 등등이 컨트롤러와 엮이며 부트를 띄우지 않는다면 설정해줘야 할 값들이 너무 많았습니다.
테스트 코드를 작성하면서도 이게 맞나..? 라는 생각을 여러번 했던 것 같아요..!

뿐만 아니라 테스트에서 오류가 나면 어디 문제인지 한참을 찾아야 했습니다,, 메서드의 주입 값들은 Mock으로 사용하다보니 어디서 주입이 잘못되었는지 찾아야 할곳이 너무 많더라구요.
심지어 테스트 하나는 아직도 어디인지 못찾아서 우선 주석처리 해두었습니다..!
앞으로 서비스의 기능들을 더 추가해 나가면서 컨트롤러와 엮이는 애들이 더 많아질 것 같은데 이러한 점을 고려하면 부트를 띄워 테스트를 해야하는지 고민이 되었습니다. 이에대한 스티치의 생각이 궁금해요!

처음 접하는 내용을 부랴부랴 구현하느랴 완성도도 많이 떨어지는 것 같고 급하게 찾아 쓴 느낌이 강한것 같아요😭
항상 친절하게 리뷰 남겨주셔서 감사합니다!

2024-05-12 14:43 UTC, lxxjn0 requested changes
호기, 미션 구현하시느라 수고하셨습니다 :)

먼저 프로덕션 코드 위주로 리뷰 남겨봤습니다. 호기가 남겨주신 테스트 관련 질문도 다음 리뷰 때 테스트 코드 쪽을 리뷰하면서 함께 남기도록 할게요! 인증과 인가 부분이 어색할 수 있는데 코드로 잘 구현해주신 것 같아요! 인증 부분에서 실제 DB를 통한 확인이 아닌 단순 토큰만으로 인증하는 부분 쪽을 위주로 한번 피드백 확인해주시면 좋을 것 같아요.

추가로 패키지 구조를 레이어드 아키텍쳐의 구조와는 조금 다르게 도메인 위주로 패키지를 구분하였는데 특별히 의도하신 부분이 있으실까요?

2024-05-12 14:43 UTC, lxxjn0 commented on src/main/java/roomescape/auth/CookieUtils.java
> +public class CookieUtils {
개인적인 의견이지만 실제로 객체가 가지는 역할에 비해 이름이 보편적?인 것 같아요. 쿠키 중 토큰에 해당하는 값을 다루는 객체인 만큼 그에 맞게 구체적인 이름으로 설정해보는 것은 어떨까요?

2024-05-12 14:43 UTC, lxxjn0 commented on src/main/java/roomescape/auth/Role.java
> +public enum Role {
해당 클래스는 Member 도메인에 포함되는 값으로 보이는데 domain이 아닌 auth 패키지로 관리한 이유가 있을까요?

2024-05-12 14:43 UTC, lxxjn0 commented on src/main/java/roomescape/auth/TokenProvider.java
> +    ) {
`@Value`를 통해서 값을 관리하셨네요 👍🏼 추가로 `@ConfigurationProperties`를 한번 찾아보고 공부해보시면 도움이 될 것 같아요.

2024-05-12 14:43 UTC, lxxjn0 commented on src/main/java/roomescape/auth/TokenProvider.java
> +                .claim(JwtClaimKey.MEMBER_ID.getKey(), member.getId().toString())
id까지 토큰 값에 넣어주신 이유가 있을까요? 실제 토큰에 넣기엔 너무 직접적인 값이 아닐까 싶은 생각이 들어 여쭤봅니다.

2024-05-12 14:43 UTC, lxxjn0 commented on src/main/java/roomescape/auth/CookieUtils.java
> +    public static String extractTokenFrom(Cookie[] cookies) {
전달받는 파라미터가 null일 수 있는 케이스도 있을 것 같아요! 방어 로직을 작성해두셔도 좋을 것 같아요.

2024-05-12 14:43 UTC, lxxjn0 commented on src/main/java/roomescape/config/LoginArgumentResolver.java
> +        }
해당 로직을 보면 실제 member가 존재하는지 여부를 판단하기 보다는 처음 토큰이 생성되는 시점의 정보만을 기준으로 판별하는 것 같아요. 실제 조회 당시의 회원 정보를 통해서 인증을 하는 것이 적절하지 않을까요?

2024-05-12 14:43 UTC, lxxjn0 commented on src/main/java/roomescape/member/service/MemberService.java
> +        if (memberRepository.existEmail(member)) {
중요한 부분은 아니지만 파라미터로 email을 전달해주는 것이 더 자연스러울 것 같아요

2024-05-12 14:43 UTC, lxxjn0 commented on src/main/java/roomescape/reservation/dto/TimeResponse.java
> +        @JsonFormat(pattern = "HH:mm") LocalTime startAt
`@DateTimeFormat` 어노테이션도 한번 찾아보시면 좋을 것 같아요

2024-05-13 03:52 UTC, hoyeonyy commented on src/main/java/roomescape/auth/CookieUtils.java
> +public class CookieUtils {
저도 이 `CookieUtils`에 대한 네이밍 고민을 많이 했는데 어떤 쪽에 포커스를 맞추어 네이밍을 진행해야할지 감이 안잡혔습니다!

스티치 말씀대로 쿠키 중 토큰에 내용에 대해 다루는 만큼 `HandleCookieInToken`으로 수정했습니다!

2024-05-13 03:53 UTC, hoyeonyy commented on src/main/java/roomescape/auth/Role.java
> +public enum Role {
Role 이라는 것이 인가에 사용이 될 것이다! 라는 생각 만으로 auth 패키지에 넣었던 것 같습니다,,!

하지만 실제로는 Member 도메인의 필드로 가지고 있기 때문에 Member 패키지에 들어가는게 맞는 것 같습니다!

2024-05-13 05:40 UTC, hoyeonyy commented on src/main/java/roomescape/auth/TokenProvider.java
> +    ) {
`@ConfigurationProperties` 에 대해 공부해 봤습니다!
```java
@ConfigurationProperties(prefix = "security.jwt")
public class TokenProvider {

    private final String secretKey;
    private final long expirationTime;

    public TokenProvider(String secretKey, long expirationTime) {
        this.secretKey = secretKey;
        this.expirationTime = expirationTime;
    }
```

이런식으로 TokenProvider를 바꾸고
```java
@SpringBootApplication
@EnableConfigurationProperties(TokenProvider.class)
public class RoomescapeApplication {

    public static void main(String[] args) {
        SpringApplication.run(RoomescapeApplication.class, args);
    }
}
```

이렇게 어플리케이션에 지정을 해주었는데요!
우선 필드 값에 직접 지정해주지 않고 클래스 레벨에 달아줌으로써 수고를 덜 수 있는 것 같아요!
반면 만약 yml 파일을 읽어가는 클래스가 많다면 `@EnableConfigurationProperties(TokenProvider.class)` 여기에 많은 클래스가 추가되는 게 아쉽긴 합니다!
클래스 단위에 자동 스캔을 할 수 있는 방법이 없나 찾아봤는데 아직 이렇다할 방법을 찾지 못한것 같아요,,!
혹시 방법이 있을까요?!

2024-05-13 06:22 UTC, hoyeonyy commented on src/main/java/roomescape/auth/TokenProvider.java
> +    ) {
이렇게 수정을 하면서 테스트가 전부 깨지게 되었습니다,,😭
컨트롤러 테스트를 Mock 을 사용해 슬라이싱 테스트를 하다보니 여러가지 빈 충돌이 일어나더라구요,,
다시 한번 통합테스트의 필요성을 느끼게 되는 것 같아요..!

2024-05-16 06:33 UTC, hoyeonyy commented on src/main/java/roomescape/auth/TokenProvider.java
> +                .claim(JwtClaimKey.MEMBER_ID.getKey(), member.getId().toString())
JWT 복호화가 이렇게 쉽게 되는지 몰랐던 것 같아요..!
토큰에 id값을 제거했씁니다!

2024-05-16 06:39 UTC, hoyeonyy commented on src/main/java/roomescape/config/LoginArgumentResolver.java
> +        }
스티치 말씀처럼 저 `LoginMemberInToken`이 null 이기 때문에 존재하지 않는 사용자라는 말은 모순이 있는 것 같습니다!

실제 사용자를 조회하는 Service에게 책임을 위임했습니다.

2024-05-17 07:07 UTC, lxxjn0 commented on src/main/java/roomescape/auth/TokenProvider.java
> +    ) {
아마 `ConfigurationPropertiesScan`이 `ConfigurationProperties`를 빈으로 등록해주는 역할을 하는 것으로 알고는 있어요. 해당 어노테이션도 한번 찾아보시면 좋을 것 같습니다 (아닐 수도 있어요.. ㅎㅎㅎ)

2024-05-17 07:09 UTC, lxxjn0 commented on src/main/java/roomescape/auth/TokenProvider.java
> +                .claim(JwtClaimKey.MEMBER_ID.getKey(), member.getId().toString())
이 부분은 사실 애매하긴 한 것 같아요. 저도 다시 생각해보니 id를 넣나 email을 넣나 사실 같은 행위인 것 같긴 해서 어떤게 나은지는 잘 모르겠습니다.. ㅠㅠ 둘 중 어떤 방법을 택해도 나쁘지 않을 것 같아요 :)

2024-05-17 07:12 UTC, lxxjn0 approved these changes
피드백 반영하시느라 수고하셨습니다. 일정이 지나서 바로 머지하게 되었는데 코드가 그래도 전체적으로 잘 정리된 것 같아서 미션 마무리해도 괜찮을 것 같아요!! 다음 미션도 화이팅입니다 👍🏼

2024-05-17 07:12 UTC, merged