[4 - 6단계 방탈출 사용자 예약] 이상(이건상) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #140
Opened 2024-05-11 18:38 UTC by kunsanglee

안녕하세요 수달..
저번 리뷰 때 수달이 말씀해주신 테스트의 해피 케이스, 배드 케이스 테스트를 모두 작성해야 할까 고민해보라고 하셨던 것을 
이번 단계를 진행하면서 뼈저리게 느꼈습니다.

현재 리뷰 요청한 코드가 너무 엉망인 상태이고, 추가된 기능에 대한 테스트가 작성되어있지 않은 상태이지만
리뷰 자체를 받지 못할 수 있겠다는 생각이 들어 기능 구현과 기존 테스트 통과만 시킨 상태로 리뷰 요청 드립니다.

너무 엉망인 상태로 리뷰 요청을 하게 되어서 마음이 너무 안좋네요😢
솔직히 지금 좀 버거운 상태인 것 같습니다. 테스트쪽이 특히 그렇네요..
다시 한 번 죄송하다는 말씀 드립니다.

2024-05-12 07:42 UTC, her0807 requested changes
안녕하세요 이상! 

인증이 들어가며 어려운 부분이 상당 있었을텐데 잘 구현해주셨어요.
관련해서 코멘트 남겨두었는데 빠르게 여러번 리뷰요청 주시면서
점진적으로 개선해보면 좋을것 같아 간단한 코멘트 남겨두었어요. 
이번에도 재밌게 리뷰 나눠요 🙇🏻‍♀️

2024-05-12 07:42 UTC, her0807 commented on build.gradle
jjwt 버전 같은 경우 최신 버전이` 0.12.5 `로 알고 있는데요 ㅎㅎ
특별한 이유가 아니라면 최신 버전을 설정하시는 것을 권장드립니다!


참고

https://github.com/jwtk/jjwt?tab=readme-ov-file#dependencies:~:text=%ED%95%A9%EB%8B%88%EB%8B%A4%20Provider.-,%EC%A2%85%EC%86%8D%EC%84%B1,-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%20%EC%A2%85%EC%86%8D%EC%84%B1%EC%9D%84%20%EC%B6%94%EA%B0%80%ED%95%A9%EB%8B%88%EB%8B%A4

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/application/dto/TokenRequest.java
> +}
email 과 password 가 null 이나  빈 값일 수도 있네용?!

검증이 추가되면 좋을 것 같아요. ㅎㅎ

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/application/AuthService.java
> +        String email = tokenRequest.email();
이메일이 email 과 password 가 null 이나 빈 값일 수도 있네용?!
검증이 추가되면 좋을 것 같아요. ㅎㅎ

여기서 해도 되고, request 객체 내에서 어노테이션 기반으로 간단히 할 수도 있을 것 같습니다.

어디서 하면 좋을지는 이상이 고민해서 추가해주세요!

참고
https://mangkyu.tistory.com/174

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/application/AuthService.java
> +                        String.format("존재하지 않는 회원입니다. 입력한 회원 email:%s", email)));
로직을 추출해볼까요?

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/application/AuthService.java
> +                        String.format("존재하지 않는 회원입니다. 입력한 회원 email:%s", payload))));
회원 찾는 로직이 위에서도 쓰이는 것 같은데 재사용해도 좋을 것 같네요~ 🙂

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/application/MemberService.java
> +    }
정답은 없지만,,


서비스에서 반환값 시그니처를 response 로 하기 vs 도메인으로 하기 
두개 중 하나를 선택한다면 저는 response 로 하고, 정적 팩터리 메서드를 사용해서 controller 에서 바로 response 객체로 반환하는 것을 선호합니다. 그이유는 해당 서비스를 여러 controller 에서 쓸 수 있도록 재사용성이 올라가면서
controller 에서 도메인을 사용하는 것을 바로 response 로 변환하면서 막을 수 있어서 두가지 이점을 모두 누릴 수있다고 느껴서요!
이상도 이 부분도 한번 고민해보시면 재밌을 것 같아요!

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/config/WebMvcConfig.java
> +
ArgumentResolver vs Interceptor 는 둘 다 request 가 controller 로 매핑되기 전에 
전처리를 할 수 있는데요~ 각각 어떨 때 쓰면 좋을까요?

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/domain/Member.java
> +        }
필수값에 대한 검증을 아주 잘해주셨군요 👍🏻 그러나 블랭크 뿐만 아니라 
실제 유효한 형태에 데이터인지 검증도 필요할 것 같아요. 
이메일 형식인지, 비밀번호는 대소문자, 특수문자 포함 몇 자여야하는지 등등요  이렇게 되면 여기 회원을 담당하는 곳에서 
불필요한 검증 로직이 많아 질 것 같아요. 
원시값 포장을 해볼까요?

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/infrastructure/auth/CheckLoginInterceptor.java
> +    }
포비든 예외 처리 굿굿 👍🏻

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/infrastructure/auth/JwtTokenManager.java
> +        cookie.setMaxAge(MINUTE * 30);
만료 시간을 설정한 기준이 어떻게 되나요?

토큰은 탈취되면 만료시킬수 없다는 단점이 있어요. 

그래서 여유있게 토큰을 설정하지 않고, 서비스의 특징에 맞게 적절한 시간에 대한 고민이 필요하고 
만료되었을 때 어떤 방법으로 갱신시켜줄지에 대한고민도 함께 필요합니다. 

고민 후 공유 부탁드려요 🙂

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/infrastructure/auth/JwtTokenProvider.java
> +    }
jwt 토큰에 대해 조금 구체적으로 알고 계시는군요?

jwt 구조는 어떻게 생겼고 어떤 데이터를 저장하면 좋을까요? ㅎㅎㅎ

위에서 쭉 살펴보니 payload 핸들링이 email 로 이뤄지고 있는 것 같아요. 
그런데 회원에 이메일은 완벽한 식별자라고 하긴 힘든것 같아요.
사용자의 id 는 변하지 않지만, 회원의 이메일은 변할 수 있으니까요.

어떤 값을 사용자 식별자로 사용할지 조금 더 고민해주시면 좋을 것 같습니다. ㅎㅎ

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/infrastructure/persistence/JdbcReservationQueryRepository.java
> +            on r.member_id = m.id
left join 을 하신 이유가 있을까요??

이렇게 되면 조건에 맞지 않을 경우 null 값으로 들어올 것 같은데,,

2024-05-12 07:42 UTC, her0807 commented on src/main/java/roomescape/infrastructure/persistence/JdbcReservationQueryRepository.java
> +                """;
데이터 조회시 join 으로 한꺼번에 가져오기 vs 각각 도메인별 조회해서 합치기 
이두가지의 장단점이 무엇일까요?

2024-05-12 07:42 UTC, her0807 commented on src/test/java/roomescape/presentation/acceptance/ReservationAcceptanceTest.java
> +                .cookie("token");
테스트 시 토큰을 미리 세팅해두는군요 👍🏻

2024-05-12 10:00 UTC, kunsanglee commented on build.gradle
학습 테스트에서 작성된 버전을 그냥 사용했는데 구버전이었군요
감사합니다 수달😇

2024-05-12 10:21 UTC, kunsanglee commented on src/main/java/roomescape/application/AuthService.java
> +        String email = tokenRequest.email();
DTO인 request 객체 내에서 `@Valid` 적용하여 값 검증하도록 수정했습니다.
단순 값 또는 타입? 체크만 애너테이션 기반으로 검증하고,
그 외의 범위라고 판단되는 것 들은도메인에서 검증하려고 하는데 적절할까요?
아직 기준이 명확하지 않아서 케이스도 생각이 잘 안나네요🥲

2024-05-12 11:07 UTC, kunsanglee commented on src/main/java/roomescape/application/MemberService.java
> +    }
재사용성을 위해서 서비스에서 도메인을 반환하도록 하고, 
컨트롤러로 반환받은 도메인 객체를 response의 정적 팩터리 메서드로 바로 response 객체로 변환한다고 이해했는데 맞을까요?🤔

저는 이번에 도메인 서비스라는 개념을 약간 억지로 적용해봤습니다.
domain 계층의 객체에서 application 계층의 서비스 객체로 도메인을 반환하고,
application 계층에서 presentation 계층으로는 response 객체를 반환하도록 해봤어요.
이런 방법으로도 도메인을 반환하는 서비스를 재사용할 수 있었지만, 복잡도가 많이 올라가는 것을 느꼈습니다 🥲

수달이 말씀해주신 방법으로 하면 복잡도는 줄일 수 있겠지만, 서비스에서 컨트롤러로 반환된 도메인 객체를
다른 개발자가 response 객체로 반환하지 않고 멋대로 사용해버릴 가능성이 생기는 점에 대해서는 어떻게 생각하시나요??
답이 없다는게 참 어렵네요😬

2024-05-12 12:48 UTC, kunsanglee commented on src/main/java/roomescape/config/WebMvcConfig.java
> +
`ArgumentResolver`는 request에서 사용자 인증 정보를 가져와 컨트롤러 메서드 인자를 동적으로 조작하거나 전달할 때 사용할 수 있습니다.
`Interceptor`는 마찬가지로 controller로 매핑되기 직전에 요청을 가로채서 인증 체크, 로깅 등 애플리케이션 전반에 걸친 공통 전처리 후처리 작업을 할 때 사용합니다.😃

2024-05-12 14:38 UTC, kunsanglee commented on src/main/java/roomescape/infrastructure/auth/JwtTokenManager.java
> +        cookie.setMaxAge(MINUTE * 30);
토큰을 탈취당하면 탈취당한 유저의 토큰으로 해커가 토큰이 만료될 때 까지 악용할 수 있습니다.
그래서 엑세스 토큰의 유효기간을 짧게 설정하는 것이 보안상 좋습니다.
하지만 너무 짧은 유효기간은 사용자의 불편함을 초래합니다.

그래서 엑세스 토큰을 발급받을 때 리프레시 토큰을 같이 발급받아서 클라이언트의 헤더에 저장합니다.
또 리프레시 토큰은 서버 또는 인메모리 저장소에 저장합니다.

그래서 엑세스 토큰의 유효기간이 만료되면 헤더에 있는 리프레시 토큰과 서버에 저장된 리프레시 토큰을 확인하여
엑세스 토큰을 재발급 하는 과정으로 엑세스 토큰의 짧은 유효기간으로부터 발생하는 불편함을 일부 해소할 수 있습니다🙇🏽‍♂️

2024-05-12 14:56 UTC, kunsanglee commented on src/main/java/roomescape/infrastructure/auth/JwtTokenProvider.java
> +    }
아뇨 학습 테스트 자료에 있던 예시 코드를 가져다 사용했습니다.. 🥲

jwt의 구조는 header, payload, signature로 이루어져 있습니다.
header는 토큰의 유형과 서명을 해싱하기 위해 사용된 알고리즘 정보가 들어있습니다.
payload는 토큰에 담을 실제 정보가 포함됩니다. 토큰의 발행자, 만료시간, 주제 등과 같은 정보가 들어있습니다.
signature는 토큰의 유효성을 검증하기 위한 서명 부분입니다. 헤더와 페이로드를 각각 Base64로 인코딩 한 후 비밀키를 사용하여 지정된 알고리즘으로 해시하여 생성됩니다.

말씀해주신대로 payload에 email을 담아 식별했으나, id를 식별자로 사용하는 것이 적절할 것 같습니다.😅

2024-05-12 15:18 UTC, kunsanglee commented on src/main/java/roomescape/infrastructure/persistence/JdbcReservationQueryRepository.java
> +            on r.member_id = m.id
아뇨 left join 해야하는 특별한 이유는 없었습니다 😭
관련 정보 부재를 허용하지 않는 경우이기 때문에  inner join으로 변경하겠습니다!

2024-05-12 15:28 UTC, kunsanglee commented on src/main/java/roomescape/infrastructure/persistence/JdbcReservationQueryRepository.java
> +                """;
join으로 한꺼번에 데이터를 가져오는 경우 여러번의 쿼리를 날려서 조회하는 것 보다 일반적으로 성능이 더 빠를 수 있습니다. 그리고 한 번의 쿼리로 가져오기 때문에 데이터 일관성을 유지하기 쉽습니다. 하지만 단점으로는 쿼리가 복잡하여 유지보수하기 어렵다는 점이 있습니다. 또 과도한 조인으로 많은 중복 데이터를 가져올 수 있어 네트워크 부하가 생길 수 있습니다.

각각 도메인별 조회해서 합치는 경우 간단한 쿼리를 여러번 날리는 것이고, 변경이 생길 경우 도메인 별로 변경하면 되기 때문에 유지보수하기 쉽습니다. 하지만 여러번의 쿼리를 날려야 하기 때문에 일반적으로 join을 하여 한 번에 조회하는 것 보다 성능이 떨어지고, 데이터베이스 통신 비용이 증가합니다. 또 여러 번의 쿼리를 날리는 도중 데이터 변경이 생길 경우 데이터 일관성을 유지하기 어렵습니다.

어렵네요..🥲

2024-05-13 12:53 UTC, her0807 commented on src/main/java/roomescape/application/AuthService.java
> +        String email = tokenRequest.email();
음 필수로 검증되어야하는 기본값들이라면 DTO 가 아닌 도메인에서 검증하는 것을 추천드립니다 ㅎㅎ

2024-05-13 12:56 UTC, her0807 commented on src/main/java/roomescape/application/MemberService.java
> +    }
음 맞아요. 이상이 말씀하신대로 전부 트레이드 오프가 존재하는데요. 
현업에서는 그래서 어떤 계층에서 의존성을 끊어낼지 동료간 합의를 합니다.

합의를 했다면 그 부분은 믿고, 지속적인 코드리뷰를 통해 팀 컨벤션으로 정착시킬 수 있다고 생각해요!

2024-05-13 12:58 UTC, her0807 commented on src/main/java/roomescape/infrastructure/auth/JwtTokenManager.java
> +        cookie.setMaxAge(MINUTE * 30);
음 방법은 여러개가 있을 것 같은데요~ 

유효하지 않은 ip 와 리프레시 토큰을 사용해 비정상적인 접근을 하거나
비정상적인 행위를 하는 것을 트레킹할 수 있을 것 같아요

현업에서는 이상탐지를 하기 위한 여러 장치들이 있어요.

2024-05-13 12:59 UTC, her0807 commented on src/main/java/roomescape/infrastructure/persistence/JdbcReservationQueryRepository.java
> +                """;
현재 쿼리에서는 조금 과하게 조인이 많이 들어간것 같아 분리하면 좋을 것 같아 말씀드렸습니다.
조회되는 데이터의 특징이 실시간성이나 데이터가 급변하지 않는 특징을 지닌 것 같아
단발성 쿼리를 여러번 사용해도 될 것 같아서요~

꼭 반영하지 않아도 되고 이런 장단점이 있다는 것을 인지하는 것만으로도 충분한 학습이 된 것 같습니다!

2024-05-13 13:03 UTC, her0807 approved these changes
안녕하세요 이상 ~

이번 리뷰에는 특히 어려운 키워드에 대한 생각들을 많이 
물어봤었는데요! 그것들에 대해 깊게 고민하고 공유해주어 고마워요.
리뷰 시작보다 훨씬 발전한 모습이 보입니다. 

이번 미션이 다소 촉박해서 더 많은 얘기를 나누지 못해 아쉽지만,
필수로 나눠야하는 부분에 대해서는 충족된 것 같아 이만 머지하겠습니다.:)

수고 많으셨습니다. 🙂

2024-05-13 13:03 UTC, merged