[4 - 6단계 방탈출 사용자 예약] 폴라(장유진) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #149
Opened 2024-05-12 11:24 UTC by jinchiim

안녕하세요 미르! 🐉

1~3단계에서 주셨던 코멘트들은 **답글과 함께 수정완료**된 상태입니다!

일반 유저의 경우에는 `admin/**` 페이지를 들어가지 못한다는 요구사항들을 
확인하시기 편하도록 `data.sql`에 데이터들을 몇개 넣어두었습니다!

```sql
INSERT INTO member (name, email, password, role)
VALUES ('어드민', 'polla@gmail.com', 'pollari99', 'admin'),
       ('일반', 'polla@naver.com', 'pollari999', 'member');
```

이번 리뷰도 잘 부탁드립니다! ☺️

2024-05-12 11:43 UTC, jinchiim commented on src/main/java/roomescape/global/annotation/Auth.java
> +}
이건 궁금하실 것 같아 미리 자체 `QnA`를 해보겠습니다!

## 왜 어노테이션을 만드셨나요?

```java
public enum MemberRole {

    NON_MEMBER("nonMember"),
    MEMBER("member"),
    ADMIN("admin");

...
```
`Role`에서도 볼 수 있듯이, 저는 방탈출 페이지는 비 회원도 가능할 수 있어야 한다고 생각합니다.
또, **사장이나 매니저 알바 같이 권한은 다양**해질 수 있다고 생각했어요. 🤔

그래서 `Path` 만으로는 모든 것을 관리하기 힘들 수 있다고 판단했습니다.
만약 이처럼 관리를 한다면, `Path`와는 무관하게 1개든 2개든 여러개의 권한 설정(사장과 매니저 모두 가능 같이)을 
할 수 있을 것 같았어요!

2024-05-12 13:30 UTC, ddu0422 requested changes
안녕하세요 폴라! 미르입니다 :)
미션 구현 잘 해주셨네요~

몇 가지 코멘트 남겼으니 확인해주시면 감사하겠습니다 🙏🏻
궁금한 점 있으면 코멘트 남겨주시거나 언제든지 DM주세요!

2024-05-12 13:30 UTC, ddu0422 commented on src/main/java/roomescape/member/domain/Email.java
> +        validate(email);
saveEmailFrom에선 validate를 하지 않아도 괜찮을까요?

2024-05-12 13:30 UTC, ddu0422 commented on src/main/java/roomescape/member/domain/Member.java
> +    private final MemberRole memberRole;
꼼꼼한 객체분리 👍🏻 👍🏻

2024-05-12 13:30 UTC, ddu0422 commented on src/main/java/roomescape/member/role/MemberRole.java
> +        return false;
간단히 줄여볼 수는 없을까요?

2024-05-12 13:30 UTC, ddu0422 commented on src/main/java/roomescape/reservation/dao/ReservationJdbcDao.java
> +                INNER JOIN member m ON r.member_id = m.id
where 절을 제외하고 `findAllByThemeIdAndDate`와 쿼리가 동일하네요.
중복되는 내용을 제거할 수 없을까요?

2024-05-12 13:30 UTC, ddu0422 commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +    private static final Date TODAY = new Date();
date는 변경이 가능한 객체입니다.
불변 객체를 활용해보면 어떨까요?

2024-05-12 13:30 UTC, ddu0422 commented on src/test/java/roomescape/member/dao/MemberDaoTest.java
> +    @DisplayName("id를 정상적으로 찾아온다.")
id를 정상적으로 찾아오지 못하는 경우도 테스트 해보면 어떨까요?

2024-05-12 13:30 UTC, ddu0422 commented on src/test/java/roomescape/member/domain/EmailTest.java
> +    @DisplayName("정상적인 Email 형식일 경우 Email이 만들어진다.")
잘못된 Email / 올바른 Email 을 아래처럼 표현해보면 어떨까요?

<img width="402" alt="Screenshot 2024-05-12 at 10 21 03 PM" src="https://github.com/woowacourse/spring-roomescape-member/assets/43198414/e59f8d65-b3b8-41b0-b0f2-732459370a6d">

2024-05-12 13:30 UTC, ddu0422 commented on src/test/java/roomescape/member/integration/MemberIntegrationTest.java
> +    @DisplayName("가입한 회원들의 이름들을 가져올 수 있다.")
회원들의 ID를 가져오지 않을까요?

2024-05-12 13:30 UTC, ddu0422 commented on src/test/java/roomescape/member/repository/MemberRepositoryTest.java
> +    void shouldThrowException_WhenIdNotFound() {
올바르게 동작하는 테스트도 작성해보면 어떨까요?

2024-05-12 13:30 UTC, ddu0422 commented on src/test/java/roomescape/member/role/MemberRoleTest.java
> +    @DisplayName("같은 권한인지 확인한다.")
권한이 여러 개인 경우에도 테스트 해보면 어떨까요?

2024-05-12 13:30 UTC, ddu0422 commented on src/test/java/roomescape/theme/controller/ThemeControllerTest.java
> +                .andExpect(jsonPath("$.description").value(theme.getDescription()));
👍🏻 👍🏻

2024-05-12 13:31 UTC, jinchiim commented on src/main/resources/static/js/reservation-with-member.js
> +  re
어라...  마지막에 확인했는데 커밋하기 전에 오타가 들어갔나보네요 🥹
수정하겠습니다!

2024-05-13 05:36 UTC, jinchiim commented on src/main/resources/static/js/user-reservation.js
🥹 `name` 이 필요가 없어 지웠는데, `name` 을 받는 코드가 위에 있었네요

삭제했습니다! 감사합니다!

2024-05-13 07:42 UTC, jinchiim commented on src/main/java/roomescape/admin/controller/AdminController.java
> +    @Auth(role = MemberRole.ADMIN)
## 선언하지 않은 이유

사실 저도 메서드마다 붙는건 굉장히 보기 불편해서 
`Class Level`에 선언을 시도했지만, `Interceptor`에서 `Method`에 붙은 어노테이션만 찾아서 

```java
  if (auth == null) {
      return true;
  }
```
해당 부분에서 `true`를 반환해주더라구요.
그래서 단순히 `AOP` 를 사용해야 하나 고민했는데, 구현이 너무 복잡해지고 반복되는 것 같았습니다. 🥹
(~제가 잘못 구현했을 확률이 100입니다.~)


## 멍청 이슈

그런데 미르 말을 듣고 생각해보니,
`Interceptor`에서 클래스 레벨의 어노테이션의 존재유무를 보고 불러오기만 할 수 있다면,
문제가 없는 것 같더라구요. 🤔

그래서 `Auth`를 만드는 메서드를 따로 빼서

```java
    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) {
        if (!(handler instanceof HandlerMethod handlerMethod)) {
            return true;
        }

        Auth auth = getAuth(handlerMethod);
        ....
   }
...
    private Auth getAuth(HandlerMethod handlerMethod) {
        Auth classAuth = handlerMethod.getBeanType().getAnnotation(Auth.class);
        Auth methodAuth = handlerMethod.getMethodAnnotation(Auth.class);

        if (classAuth != null) {
            return classAuth;
        }
        if (methodAuth != null) {
            return methodAuth;
        }
        return null;
    }
```

처럼 추가해줬습니다!

![image](https://github.com/woowacourse/spring-roomescape-member/assets/105053478/7af93ba2-77d7-4625-a149-f8f68d9ca9fb)

좌잔.. 감사합니다 미르 🐉

2024-05-13 07:54 UTC, jinchiim commented on src/main/java/roomescape/admin/controller/AdminController.java
> +            @ModelAttribute ReservationFilterRequest reservationFilterRequest) {
기존에는 `@RequestParam`을 여러개를 넣은 방식이었는데요.
그렇게 하니 `Method`가 굉장히 보기 불편해졌습니다...

또 `Param`이 많은 만큼  객체로 받는 것이 그 중 하나에 변경사항이 생기거나 추가되더라도 더 변경에 유용하지 않을까 생각했습니다.
(`Service Method`에서 객체를 받고 있으니 `Param`이 추가되거나 삭제되더라도 `Controller`에는 변경사항이 없을 것 같았습니다.)

그리고 지금은 `null`이 들어가지 않고 모든 값이 들어와야 필터링하도록 구현했는데요.
이와 같이 구현하는 경우에 명확한 에러코드를 주는 것이 더 좋을 것 같아 `FilterInfo` 객체를 만들어 관리하는 방식으로
생각의 흐름이 진행되었습니다. 🤔

2024-05-13 08:25 UTC, jinchiim commented on src/main/java/roomescape/admin/domain/FilterInfo.java
> +        }
`Objects.isNull` 사용이 가능합니다!

다만, 해당 코드를 보면
![image](https://github.com/woowacourse/spring-roomescape-member/assets/105053478/c6753c66-30e8-4fbd-ab35-71ab219959cf)

이와 같은 내용이 적혀있었습니다.
완전한 의도는 모르겠지만 `Functional Interface`인 `Predicate`에서 사용하도록 만들어졌다고 명시되어 있어
개인적으로는 의도한 바와 다르게 사용하는 것 같아 좀 꺼려지더라구요. 🤔

그래서 현재는 `==` 연산자를 사용하는 것을 선호하긴 합니다!
미르는 다른 의견이 있다면 말씀해주세요! 🥰

2024-05-13 08:42 UTC, jinchiim commented on src/main/java/roomescape/auth/controller/AuthController.java
> +        ResponseCookie responseCookie = CookieProvider.setCookieFrom(token);
제가 알기로 가장 큰 차이는 

쿠키의 경우는 **클라이언트에서 저장을 하고, 세션은 서버에 저장하는 것**으로 알고 있습니다!

또, 쿠키의 경우는 **만료의 시점에 쿠키가 삭제**되고
세션은 **브라우저가 종료될 때 삭제**되어지며 이 두가지의 특징으로 인해서

따라서 전반적으로
`쿠키는 세션보다 보안이 약하지만 속도가 빠르고`,
`세션은 쿠키보다 보안이 강하지만 속도가 쿠키보다 느린 것`으로 알고 있습니다.

2024-05-13 08:52 UTC, jinchiim commented on src/main/java/roomescape/auth/exception/CookieException.java
> +    }
저도 그 부분을 고려해보았으나, `enum`은 상수 클래스로 상속을 받을 수 없어
위와 같이 구현하는 것이 한계였는데요.

그럼에도 상수 집합을 `Enum`으로 표현하는 것이 저에게는 더 인지적 부담이 덜고 자연스러워 그대로 유지했는데요.

이럴 경우 `Enum` 을 사용하기 보다는 단순 클래스를 만들어 사용하는 것이 좋은 것일까요?  😞
미르의 의견이 궁금합니다!

2024-05-13 10:20 UTC, jinchiim commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +        String accessToken = Jwts.builder()
`~.~.~` 과 같이 `.`을 기준으로 하여 구분되어지는 구조로 알고 있습니다!

첫번째 부분에서는 토큰의 타입과 해싱 알고리즘 정보를 넣어놓고,
두번째 부분에는 정보인 `Claim`이 들어갑니다.

그리고 마지막으로는 `signature` 값이 들어가게 되는 것으로 알고 있습니다!
`JWT` 공식 사이트에서도 `Decode`가 가능해서 가져왔습니다!

![image](https://github.com/woowacourse/spring-roomescape-member/assets/105053478/59866dd3-4595-4b46-9026-ee440446f39d)

2024-05-13 10:32 UTC, jinchiim commented on src/main/java/roomescape/auth/resolver/TokenResolver.java
> +        return Long.valueOf(tokenProvider.resolveToken(token));
당장은 우선 `id` 값만 받아 `name`을 주거나 해당하는 유저의 `Reservation`을 저장하는 등,
결과값이 모두 다른 상태이기 때문에, `id`로 바꿔만 주는 것이 확장성에 좋다고 생각했습니다. 🤔

또, 이 행위를 하는 객체의 이름이 `TokenResolver`이기 때문에 `Member` 정보를 가져오기 보다는,
토큰을 해석해 정보만 전달하는 것이 더 좋을 것이라고 판단했어요.

다만 만약 `id` 뿐만이 아닌 모두 **공통적으로 `role` 같은 정보가 필요하다면 그때는 `Member` 생성자를 만들어 `Member`를
전달해주는 방식으로 변경**하려고 합니다!

미르는 어떻게 생각하실까요?!

2024-05-13 10:33 UTC, jinchiim commented on src/main/java/roomescape/global/annotation/Auth.java
> +    MemberRole[] role() default MemberRole.MEMBER;
헉 그렇네요! 감사합니다!

2024-05-14 16:46 UTC, jinchiim commented on src/main/java/roomescape/member/domain/Email.java
> +        validate(email);
`saveEmailFrom()`과 같이 처음에 `save`를 하는 경우에는,
`Email` 정보가 없이 `null`이 들어가 `validate`가 필요하지 않았습니다!

다만 생각해보니, 메서드 이름에 너무 의존하고 있었던 것 같습니다. 
파라미터를 받을 수 있다보니, `String email`로 `save`할 수 있다는 느낌을 주는 것 같습니다. 🤔

그래서 이와 같이 파라미터를 받지 않도록 변경해보았습니다.
```java
    public static Email saveEmail() {
        return new Email(null);
    }
```

2024-05-14 16:47 UTC, jinchiim commented on src/main/java/roomescape/member/domain/Member.java
> +    private final MemberRole memberRole;
확실히 말씀하신대로 분리하니 각 도메인에서 검증할 수 있어 좋은 것 같습니다 👍🏻
1단계를 잊지않기..

2024-05-14 16:52 UTC, jinchiim commented on src/main/java/roomescape/member/role/MemberRole.java
> +        return false;
허가 가능한 `roles`안에 
지금 `id`인 유저의 `role`이 포함되어 있는지 보는 것 만으로도 가능한 것 같습니다! 🤔

```java
    public boolean hasSameRoleFrom(MemberRole[] roles) {
        return Arrays.asList(roles)
                .contains(this);
    }
```

2024-05-14 17:03 UTC, jinchiim commented on src/main/java/roomescape/reservation/dao/ReservationJdbcDao.java
> +                INNER JOIN member m ON r.member_id = m.id
지금 생각나는 가장 단순한 방법으로는 
쿼리가 `String`으로 이루어져 있으니, 중복되는 `Sting`문을 상수로 빼는 방식으로 고려할 수 있을 것 같습니다 🤔
(너무 간단히 생각한걸까요?)

```java
    private static final String getAllSql = """
                SELECT r.id, r.date,
                    t.id AS timeId, t.start_at,
                    th.id AS themeId, th.name AS themeName, th.description, th.thumbnail,
                    m.id AS memberId, m.name AS memberName, m.email, m.password, m.role
                FROM reservation r
                INNER JOIN reservation_time t ON r.time_id = t.id
                INNER JOIN theme th ON r.theme_id = th.id
                INNER JOIN member m ON r.member_id = m.id
            """;

    @Override
    public List<Reservation> findAllByUserIdAndThemeIdBetweenDate(long userId, long themeId, LocalDate fromDate,
                                                                  LocalDate toDate) {
        String findReservationsInOrderSql = getAllSql + """
                WHERE m.id = ? AND th.id = ? AND DATE BETWEEN ? AND ?
                ORDER BY r.date ASC, t.start_at ASC
                """;

        return jdbcTemplate.query(findReservationsInOrderSql, RESERVATION_ROW_MAPPER, userId, themeId, fromDate,
                toDate);
    }
```

2024-05-14 17:27 UTC, jinchiim commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +    private static final Date TODAY = new Date();
`Jwts.builder()`에서 `Date()` 타입 만을 받아 이와 같이 작성하게 되었습니다 🥹

혹시 다른 방법이 있을까요 🥲

2024-05-14 17:31 UTC, jinchiim commented on src/test/java/roomescape/member/dao/MemberDaoTest.java
> +    @DisplayName("id를 정상적으로 찾아온다.")
없는 `id`일 경우 빈 값을 가져오는 테스트를 추가했습니다! 😄

```java
    @Test
    @DisplayName("없는 id일 경우 빈 값을 가져온다.")
    void getNotExistMemberId() {
        Optional<Long> id = memberJdbcDao.findIdByEmailAndPassword("email@ndkd.com", "password");

        assertEquals(id, Optional.empty());
    }
```

2024-05-14 17:38 UTC, jinchiim commented on src/test/java/roomescape/member/integration/MemberIntegrationTest.java
> +    @DisplayName("가입한 회원들의 이름들을 가져올 수 있다.")
아앗.. 처음에 `id`를 가져오다가 `JS`파일을 보고 수정했는데,
`DisplayName`은 그대로 사용해버렸네요 🥲

아이디를 가져오는 것으로 수정했습니다!

2024-05-14 17:42 UTC, jinchiim commented on src/test/java/roomescape/member/repository/MemberRepositoryTest.java
> +    void shouldThrowException_WhenIdNotFound() {
일치하는 멤버를 가져오는 테스트도 추가 구현했습니다! 🥰
~다음 미션에서 많은게 바뀌다보니 성공 테스트도 굉장히 소중하더군요..~ 🤔

```java
    @Test
    @DisplayName("일치하는 멤버를 가져올 수 있다.")
    void getJoinedMember() {
        when(memberJdbcDao.findIdByEmailAndPassword(TEST_EMAIL, TEST_PASSWORD))
                .thenReturn(Optional.of(1L));

        Long id = memberRepository.findIdByEmailAndPassword(TEST_EMAIL, TEST_PASSWORD);

        assertEquals(id, 1L);
    }
```

2024-05-14 17:44 UTC, jinchiim commented on src/test/java/roomescape/member/role/MemberRoleTest.java
> +    @DisplayName("같은 권한인지 확인한다.")
여러개의 값은 확인을 안했었네요!

```java
    @Test
    @DisplayName("여러개의 권한 중 하나라도 포함이 되면 true를 반환한다.")
    void hasSameRule() {
        MemberRole[] memberRoles = new MemberRole[]{MemberRole.MEMBER, MemberRole.ADMIN};

        assertAll(
                () -> assertTrue(MemberRole.MEMBER.hasSameRoleFrom(memberRoles)),
                () -> assertTrue(MemberRole.ADMIN.hasSameRoleFrom(memberRoles)),
                () -> assertFalse(MemberRole.NON_MEMBER.hasSameRoleFrom(memberRoles))
        );
    }
```

테스트를 추가했습니다!
꼼꼼한 리뷰 감사합니다!

2024-05-15 09:29 UTC, ddu0422 commented on src/main/java/roomescape/admin/controller/AdminController.java
> +    @Auth(role = MemberRole.ADMIN)
구현 잘 해주셨네요~

2024-05-15 09:32 UTC, ddu0422 commented on src/main/java/roomescape/admin/domain/FilterInfo.java
> +        }
```java
Objects.requireNonNull(memberId, () -> {
    throw new RoomEscapeException(ReservationExceptionCode.MEMBER_INFO_IS_NULL_EXCEPTION);
});
```

이런 방법도 있다는 내용으로 확인해주시면 될 것 같습니다~

2024-05-15 09:47 UTC, ddu0422 commented on src/main/java/roomescape/auth/exception/CookieException.java
> +    }
Enum으로 표현하는 방법도 괜찮으나 `반복하는 내용을 줄이는 게 중요하다고 생각`하기 때문에 RoomEscapeException을 확장하여 `CookieIsNullException`과 `CookieValueIsNotFoundException`을 만들지 않을까 싶습니다.

2024-05-15 09:49 UTC, ddu0422 commented on src/main/java/roomescape/auth/resolver/TokenResolver.java
> +        return Long.valueOf(tokenProvider.resolveToken(token));
저는 id를 활용하는 방식이 괜찮다고 생각합니다 :)
jwt 토큰은 decode가 가능하기 때문에 role, email 등 주요 정보가 담기면 안된다고 생각해요.

2024-05-15 09:53 UTC, ddu0422 commented on src/main/java/roomescape/reservation/dao/ReservationJdbcDao.java
> +                INNER JOIN member m ON r.member_id = m.id
괜찮을 것 같습니다 ㅎㅎ

2024-05-15 09:54 UTC, ddu0422 commented on src/main/java/roomescape/auth/provider/JwtTokenProvider.java
> +    private static final Date TODAY = new Date();
라이브러리에서 Date를 받고 있기 때문에 없습니다.
date가 가변 객체임을 인지하고 있는지 확인하기 위한 질문이었습니다 :)

2024-05-15 10:34 UTC, ddu0422 approved these changes
안녕하세요 폴라! 미르입니다 :)

오래 고민한 흔적이 보이는 내용들이 많았네요.
많은 학습을 진행하여 이번 미션은 머지하려고 합니다!

미션 진행하느라 고생하셨어요~
다음 미션도 화이팅입니다 😄

2024-05-15 10:34 UTC, ddu0422 commented on src/main/java/roomescape/global/interceptor/MemberRoleInterceptor.java
> +        return null;
```suggestion
        if (classAuth != null) {
            return classAuth;
        }
        return methodAuth;
```

2024-05-15 10:34 UTC, merged