[1 - 3 단계 방탈출 사용자 예약] 냥인(최가희) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #17
Opened 2024-05-02 07:54 UTC by cutehumanS2

2024-05-02 14:19 UTC, ddu0422 requested changes
안녕하세요 낭인! 미르입니다 :)
미션 구현 잘 해주셨네요~
몇 가지 코멘트 남겼으니 확인해주시면 감사하겠습니다 🙏🏻 
궁금한 점이 있으면 언제든지 코멘트 남겨주시거나 DM 보내주세요!

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/exception/NotFoundException.java
> +    private final String message;
message를 필드로 가져아하는 이유가 있을까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/domain/ReservationTime.java
> +            throw new IllegalArgumentException("예약 시간은 10분 단위입니다.");
예외 메시지에 작성한 `10`도 재활용하는건 어떨까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    }
해당 생성자는 어떤 책임을 지고 있는 걸까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
사용하지 않는 메서드는 제거하는건 어떨까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/dao/ThemeDao.java
> +public class ThemeDao implements ThemeRepository {
Dao와 Repositroy는 무슨 차이가 있는걸까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/dao/ThemeDao.java
> +                    COUNT(r.id) AS reservation_count
count를 활용하고 있는 부분은 어디일까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/dao/ThemeDao.java
> +                LEFT OUTER JOIN
outer join과 inner join은 어떤 차이가 있을까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +            return Optional.empty();
정말 비어있는 경우와 에러가 발생해서 비어있는 경우는 어떤 방식으로 구분할 수 있을까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/dao/ReservationDao.java
> +                SELECT EXISTS (
count / limit 1 등이 아닌 exists 함수를 사용한 이유가 있을까요?

2024-05-02 14:19 UTC, ddu0422 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +@RestControllerAdvice
`RestControllerAdvice`와 `ControllerAdvice`는 어떤 차이가 있을까요?

2024-05-04 22:57 UTC, cutehumanS2 reviewed
안녕하세요, 미르! 냥인입니다.

원래도 생각하는 게 좀 오래 걸리는 편인데,
스프링 테스트에 대해 모르는 게 너무 많아 더 오래 걸렸습니다. 
많이 부족해서 이해하지 못한 질문도 몇 개 있습니다. 😿

이번 리뷰도 잘 부탁드립니다.
감사합니다.

2024-05-04 22:57 UTC, cutehumanS2 commented on src/test/java/roomescape/controller/UserControllerTest.java
> +class UserControllerTest extends ControllerTest {
아래 컨트롤러 메서드를 예시로 들자면,
```java
@GetMapping("/")
public String mainPage() {
	return "/index";
} 
```

각 어노테이션으로 설정하고 테스트를 실행했을 때 출력되는 로그는 아래와 같았습니다.

- `@Controller`
```
... 
ModelAndView:
        View name = /index
             View = null
            Model = null
...

MockHttpServletResponse:
           Status = 200
    Error message = null 
          Headers = [Content-Language:"en", Content-Type:"text/html;charset=UTF-8"]
     Content type = text/html;charset=UTF-8
             Body = <!DOCTYPE html>
<html lang="ko">
... html code ...
```
- `@RestController`
```
...

ModelAndView:
        View name = null
             View = null
            Model = null
...

MockHttpServletResponse:
           Status = 200
    Error message = null
          Headers = [Content-Type:"text/plain;charset=UTF-8", Content-Length:"6"]
     Content type = text/plain;charset=UTF-8
             Body = /index
...
```

어노테이션이 `@Controller`일 경우  index라는 이름의 뷰(html 파일)를 찾아 response body에 담아 내려 줍니다. `@RestController`일 경우 response body에 “/index”라는 문자열 값을 담아 내려 줍니다.

응답하는 값은 다르지만 두 경우 모두 상태 코드 200을 반환하는 것은 같아서, 어느 어노테이션을 사용하든 테스트는 항상 성공하고 있습니다.

아래처럼 view 이름과 contentType 검증까지 추가하는 게 더 좋을까요?
```java
    @Test
    @DisplayName("사용자 메인 페이지를 반환한다.")
    void mainPage() throws Exception {
        // when & then
        mockMvc.perform(get("/"))
                .andDo(print())
                .andExpect(status().isOk())
                .andExpect(view().name("/index"))
                .andExpect(content().contentType("text/html;charset=UTF-8"));
    }
```

2024-05-04 22:57 UTC, cutehumanS2 commented on src/test/java/roomescape/domain/ReservationTimeTest.java
> +    @DisplayName("예약 시간은 10분 단위이다.")
미르의 의견에 동의합니다. 
테스트명을 명확하게 변경하고, 올바른 값이 들어왔을 때 성공하는 케이스를 추가하였습니다. 😸

2024-05-04 22:57 UTC, cutehumanS2 commented on src/test/java/roomescape/repository/ThemeRepositoryTest.java
> +class ThemeRepositoryTest extends RepositoryTest {
미르 죄송합니다. 질문의 내용을 잘 파악하지 못했습니다.😹

```java
    @Test
    @DisplayName("테마 목록을 조회한다.")
    void findAll() {
        // given
        String insertSql = "INSERT INTO theme (name, description, thumbnail) VALUES (?, ?, ?)";
        jdbcTemplate.update(insertSql, WOOTECO_THEME_NAME, WOOTECO_THEME_DESCRIPTION, THEME_THUMBNAIL);

        // when
        List<Theme> themes = themeRepository.findAll();

        // then
        assertThat(themes).hasSize(1);
    }
```
위와 같은 테스트가 있을 때 given 절에서 jdbcTemplate으로 삽입 쿼리를 직접 날리지 말고, 
`themeRepository.save(theme)` 같이 repository의 메서드를 직접 사용하는 방식으로 변경하는 게 어떤지 권해주신 게 맞을까요?

2024-05-04 22:57 UTC, cutehumanS2 commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +@ExtendWith(MockitoExtension.class)
이 부분은 사실 스스로 Mockito의 필요성을 느끼고 사용한 게 아니라, Mockito를 적용한 페어의 코드를 기반으로 진행해서 그대로 사용하게 되었습니다.

그래서 이번에 왜 Mockito를 사용해야 했는지 스스로 생각해 보았습니다.

단위 테스트를 작성하면서 DB 등 외부 의존성을 끊고, 원하는 기능만 테스트하고 싶었습니다. 그러다 보니 테스트 더블을 적용해야 했는데요, 지난 체스 미션 때 적용해 본 Fake를 떠올릴 수 있었습니다. 그러나 Fake는 페이크 객체를 추가로 만들어줘야 한다는 점, 그리고 페이크 객체의 내부 로직이 복잡해진다면 이 또한 테스트의 대상이 될 수도 있다는 점이 이번 미션에서 단점으로 다가와서 Mockito를 사용하게 되었습니다. 시간은 정해져 있는데, Fake를 사용할 경우 할 일이 두 배가 되는 것 같았거든요. 게다가 이미 꽤 많은 테스트 로직이 Mockito로  작성되어 있기도 했고요. ㅎ ㅎ

Mockito를 사용하니 목 객체를 생성하는 과정이 단순해져서 확실히 편리했습니다. 행위 검증에 초점을 맞출 수도 있었고요! 물론 Mockito를 사용했을 때 우려되는 점도 있었습니다. 실제 객체의 동작이 변경되어도 목 객체의 동작은 변경되는 것은 아니라 실패해야 하는 테스트가 성공할 수도 있으니, 테스트에 대한 신뢰도가 떨어질 것 같아요.

이번 미션에서는 Mockito를 선택했지만, 아직 테스트 작성 경험이 적어 둘 중 어느 것이 더 좋은지는 아직 잘 모르겠습니다. 그리고 결국 두 방법 모두 실제 운영 환경과 동일하지는 않기 때문에 DB에 의존하는 통합 테스트를 별도로 작성해야 하나라는 생각도 듭니다.

미르의 생각은 어떠신가요? 😺

2024-05-04 22:57 UTC, cutehumanS2 commented on src/test/resources/test-schema.sql
> +CREATE TABLE theme
프로덕션과 테스트의 스키마가 다른 경우, 한쪽이 변경되면 반대쪽도 반드시 변경해 줘야 합니다. 그렇지 않으면 프로덕션 환경과 테스트 환경 간 데이터 불일치가 발생할 것이고, 결과적으로 프로덕션에 대한 테스트를 충분히 수행할 수 없게 될 거로 생각합니다.

현재는 테이블들을 drop한 후 다시 생성해 주고 있는데, truncate를 해주는 쪽이 더 나을까요? 아니면 다른 더 좋은 방법이 있을까요??

2024-05-06 00:54 UTC, ddu0422 commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +@ExtendWith(MockitoExtension.class)
[런던파와 고전파](https://kukim.tistory.com/107)라는 내용이 있습니다.
각 장단점을 직접 느껴보고 필요한 상황에 따라 적용해보면 어떨까하는 생각이 있습니다.

둘 다 직접 경험해보았고 현재는 작은 프로젝트지만 점점 복잡하고 커지는 프로젝트를 경험하며 본인에게 맞는 방법을  택할 수 있으리라 생각됩니다. :)

2024-05-06 00:56 UTC, ddu0422 commented on src/test/java/roomescape/repository/ThemeRepositoryTest.java
> +class ThemeRepositoryTest extends RepositoryTest {
네 맞습니다.
인터페이스를 테스트 한다면 구현체가 어떤 내용이든지 테스트가 성공해야한다고 생각해요.

현재는 SQL을 사용하는 DB를 테스트하는 내용으로 정한 후 테스트되어있죠.
만약 SQL이 아닌 NoSQL을 사용한다면 테스트 전체가 변경되어야 하지 않을까요?

2024-05-06 00:59 UTC, ddu0422 commented on src/test/java/roomescape/controller/UserControllerTest.java
> +class UserControllerTest extends ControllerTest {
`어떤 내용까지 검증해야할까?`는 냥인이 진행하며 찾아봐도 괜찮을 듯 합니다 ㅎㅎ
다만, `Annotation이 변경되었음`에도 실패해야 할 테스트 코드가 통과했기 때문에 저는 그 부분만 수정되면 괜찮다고 생각해요.

2024-05-06 01:08 UTC, ddu0422 commented on src/main/java/roomescape/dao/ThemeDao.java
> +public class ThemeDao implements ThemeRepository {
저는 domain 영역에 속하는 저장소를 작성할 때 Repository 네이밍을 사용합니다. :)

2024-05-06 01:16 UTC, ddu0422 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +            return Optional.empty();
```java
    @Nullable
    public <T> T queryForObject(String sql, RowMapper<T> rowMapper, @Nullable Object... args) throws DataAccessException {
        List<T> results = (List)this.query((String)sql, (Object[])args, (ResultSetExtractor)(new RowMapperResultSetExtractor(rowMapper, 1)));
        return DataAccessUtils.nullableSingleResult(results);
    }
```

```java
    @Nullable
    public static <T> T nullableSingleResult(@Nullable Collection<T> results) throws IncorrectResultSizeDataAccessException {
        if (CollectionUtils.isEmpty(results)) {
            throw new EmptyResultDataAccessException(1);
        } else if (results.size() > 1) {
            throw new IncorrectResultSizeDataAccessException(1, results.size());
        } else {
            return results.iterator().next();
        }
    }
```

내부 코드입니다.

- 에러가 발생할 경우가 한 가지 더 있습니다. `(IncorrectResultSizeDataAccessException)`
-  `EmptyResultDataAccessException`가 발생한 경우 예외를 발생하지 않고 빈 옵셔널로 반환한 이유가 있을까요?

2024-05-06 01:19 UTC, ddu0422 commented on src/test/resources/test-schema.sql
> +CREATE TABLE theme
Production Schema가 변경되면 Test Code가 당연히 실패해야한다고 생각해요.

`관리 포인트가 늘어나지 않았을까?`하는 질문이었어요.
만약, Production Schema를 변경했지만 Test Schema 변경없이 Test Code가 성공하는 경우가 있다면 어떨까요?

2024-05-06 01:24 UTC, ddu0422 commented on src/test/java/roomescape/controller/ControllerTest.java
> +abstract class ControllerTest {
가장 이상적인 내용은 둘 다 작성하는 방향이 되어야한다고 생각해요.
하지만 리소스를 효율적으로 사용해야 하기 때문에 현업에서는 이상적인 내용을 전부 챙기기 어렵습니다. 😭

어떤 테스트가 냥인에게 더 적합하고 상황에 따라 어떤 테스트를d 적용해야 할 지 학습해보면 어떨까요?

2024-05-06 01:43 UTC, ddu0422 approved these changes
안녕하세요 냥인! 미르입니다 :)
현재 미션은 대체로 잘 구현해주셔서 빠르게 머지할게요 ㅎ_ㅎ
나머지 코멘트는 다음 미션을 진행하며 확인해주시면 될 것 같습니다.

궁금한 내요은 코멘트 남겨주시거나 DM주세요!

2024-05-06 01:43 UTC, ddu0422 commented on src/main/java/roomescape/dao/ThemeJdbcDao.java
> +    public List<Theme> findTopThemesByReservationCountDuringPeriod(final int period, final int limit) {
지금은 사용하는 곳이 많지  않아서 따로 언급하지 않았었는데요.

`LocalDate.now().minusDays()`도 business logic이 아닐까 싶습니다 :)
왜 business logic일까 하는 고민도 해보면 괜찮을 듯 합니다.

결론) 매개변수를 int가 아닌 LocalDate로 받아보는건 어떨까요?

2024-05-06 01:43 UTC, ddu0422 commented on src/main/java/roomescape/domain/Reservation.java
> +    private final String name;
1단계 미션을 진행하며 Name이라는 새로운 객체를 만들었지 않았을까요?

2024-05-06 01:43 UTC, ddu0422 commented on src/main/java/roomescape/service/ThemeService.java
> +    private static final int POPULARITY_LIMIT = 10;
해당 부분 또한 business logic에 해당하지 않을까요?
domain에게 책임을 위임해보면 어떨까요?

2024-05-06 01:43 UTC, ddu0422 commented on src/test/java/roomescape/controller/UserControllerTest.java
> +class UserControllerTest extends ControllerTest {
해당 부분은 혹시 변경이 되지 않을걸까요?

2024-05-06 01:43 UTC, merged

2024-05-10 13:00 UTC, cutehumanS2 commented on src/main/java/roomescape/dao/ThemeJdbcDao.java
> +    public List<Theme> findTopThemesByReservationCountDuringPeriod(final int period, final int limit) {
말씀해 주신 대로 해당 부분(period, limit)을 비즈니스 로직으로 분리하고, 매개변수도 LocalDate로 받도록 변경해 보았습니다. 비즈니스 로직으로 적절히 분리했는지는 확신이 서지 않습니다.😅

2024-05-10 13:04 UTC, cutehumanS2 commented on src/main/java/roomescape/domain/Reservation.java
> +    private final String name;
이번에 새로 적용하였습니다.😸

2024-05-10 13:04 UTC, cutehumanS2 commented on src/main/java/roomescape/service/ThemeService.java
> +    private static final int POPULARITY_LIMIT = 10;
말씀해 주신 대로 도메인에게 책임을 위임해 보았습니다.😺

2024-05-10 13:06 UTC, cutehumanS2 commented on src/test/java/roomescape/repository/ThemeRepositoryTest.java
> +class ThemeRepositoryTest extends RepositoryTest {
인터페이스의 테스트는 구현체가 어떻든 성공해야 한다는 것을 고려하지 못했네요. ㅎ ㅎ NoSQL을 사용하면 테스트 코드 전체를 변경해야 한다는 점도요. 
말씀해 주신 대로 인터페이스의 메서드를 사용하여 테스트하도록 변경하였습니다.😸