[1 - 3단계 방탈출 사용자 예약] 호티(윤주호) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #28
Opened 2024-05-02 08:13 UTC by Ho-Tea

안녕하세요 영이!
처음 뵙겠습니다 🙇‍♂️
이번 단계는 구현을 제일 우선으로 두고 최대한 간단하게 구성하는 것에 집중하였습니다.

2024-05-03 05:18 UTC, choijy1705 requested changes
안녕하세요 호티
미션 잘 진행해주셨습니다👍
코멘트가 많아져서 한번 끊었다 갈께요
코멘트 확인해보시고 반영부탁드려요!

2024-05-03 05:18 UTC, choijy1705 commented on src/main/java/roomescape/time/dao/ReservationTimeDao.java
> +    }
list조회시 정렬은 필요없을까요?

2024-05-03 05:18 UTC, choijy1705 commented on src/main/java/roomescape/time/service/ReservationTimeService.java
> +        }
이미 예약이 되어 있는 시간을 지우는 경우 DB단에서 에러가 발생하고 이를 catch하여 처리하고 있네요
사용자 관점에서는 원치않는 이해하기 힘든 메세지일 수 있고 뿐만아니라 다른 개발자 입장에서도 이 코드를 보고 어떤 경우에 에러가 발생하는지 쉽게 이해하기 힘들것 같아요!
해당 시간으로 예약된 예약이 있는지 조회를해보고 적절히 예외를 발생하는게 어떨까요?
(지금은 코드만 클라이언트로 넘기고 있어서 어떤 상황에서 에러가 발생했는지 조차 메세지로 알 수 없겠네요)

2024-05-03 05:18 UTC, choijy1705 commented on src/main/resources/schema.sql
> +       ('Evan Wright', '2024-04-29', 7, 2);
schema sql 과 data sql로 잘 분리되면 좋을것 같아요

2024-05-03 05:18 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        boolean isExist = reservationDao.checkReservationExists(reservation.getDate().toString(), requestDto.timeId(), requestDto.themeId());
이 부분은 validateDuplicateReservation 에서 처리하는게 좋을것 같아요!

2024-05-03 05:18 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    }
validateReservationAvailable 과 같이 하나의 validate 메서드로 묶어도 좋을것 같습니다!

2024-05-03 05:18 UTC, choijy1705 commented on src/main/java/roomescape/theme/service/ThemeService.java
> +    public List<ThemeResponseDto> findPopular() {
메서드명이 추상적인것 같아요
findPopularThemes?

2024-05-03 05:18 UTC, choijy1705 commented on src/main/java/roomescape/theme/service/ThemeService.java
> +        List<Theme> themes = themeDao.findPopular(today.minusWeeks(1).toString(), today.minusDays(1).toString());
한줄이 너무 긴것 같아요 적절히 개행해주면 좋을것 같아요

2024-05-03 05:18 UTC, choijy1705 commented on src/main/java/roomescape/theme/service/ThemeService.java
> +        List<Theme> themes = themeDao.findPopular(today.minusWeeks(1).toString(), today.minusDays(1).toString());
왜 전날까지 정보로 조회하나요? 오늘로 해도 될것 같아서요

2024-05-03 05:18 UTC, choijy1705 commented on src/main/java/roomescape/time/controller/ReservationTimeController.java
> +    public List<ReservationTimeResponseDto> findAll() {
여기도 ResponseEntity 사용을 통일하면 좋을것 같아요!

2024-05-03 05:53 UTC, Ho-Tea commented on src/main/java/roomescape/exception/NullPointDateException.java
> +    public NullPointDateException(String message) {
해당 예외는 `NullPointerException`으로 충분히 대체될 수 있을 것 같습니다
반영하였습니다!

2024-05-03 06:20 UTC, Ho-Tea commented on src/main/java/roomescape/exception/handler/GlobalExceptionHandler.java
> +@ControllerAdvice
특별한 이유가 존재하지는 않았고 `ControllerAdvice`에서 `ResponseEntity`를 통해 반환을 하였을 때에도 원하는 상태코드와 응답 값이 주어져 사용했던 것 같습니다.
해당 `ResponseEntity`를 객체로 수정하였을 때 `TemplateInputException`이 발생하는 것을 확인 할 수 있었고,
현재 특정 오류페이지를 응답해주는 것이 아닌 에러 메시지를 전달하는 목적으로 사용되므로 `RestContollerAdvice`로 수정하는 것이 더 나을 것 같아 반영하였습니다!

2024-05-04 06:59 UTC, Ho-Tea commented on src/main/java/roomescape/exception/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
`GlobalExceptionHandler`에서 처리하지 않은 예외의 경우에는 원하는 형식대로 예외가 처리되지 않을 것 같습니다
예상치 못한 에러가 발생하지 않게끔 모든 예외사항을 고려해서 설계하라는 말씀이실까요..!

2024-05-04 07:04 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    }
뷰가 추가되어 다른 `Controller`에서 해당 `Service`를 호출하게 되는 경우 
현재는 `ReservationResponseDto`로 특정 뷰의 응답값을 반환하기에 `findAll()`메서드를 재사용하지 못할것이다라고 이해하여, 
해당 메서드의 반환형을 `DTO -> Domain`으로 변경하여 필요한 응답값을 생성하는 부분은 `Controller`에게 위임하였습니다!
말씀하신 것이 해당 리팩터링 방향과 다른 부분이 있다면 말씀 부탁드릴게요..!

2024-05-04 07:13 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +    }
> delete 해서 ResponseCode를 반환하는건 어색한것 같아요!

다시 생각해보니 어색한 부분이 많은 것 같습니다. 해당 부분 리팩터링 진행하였습니다!

> 또한 DataAccessException이 발생할 가능성이 있나요??

`해당 프로젝트에서 참조무결성을 위반하는 경우 : 이미 A 시간에 특정 예약이 존재하는데 A시간을 삭제할려고 하는 경우`
참조 무결성을 위반한 경우 `DataAccessException`의 하위 `Exception`인 `DataIntegrityViolationException`을 발생하는 것으로 알고있어 해당 예외를 `RestControllerAdvice`에서 전역적으로 처리하게끔 재구성하려고 했으나

`DataIntegrityViolationException` 이 발생하는 경우는 참조무결성을 제외하고도 여러가지 제약이 위반된 경우도 해당하여 
참조 무결성을 제외한 다른 예외가 발생하여도 의도치 않게 해당 `DataIntegrityViolationException`을 처리할 수도 있겠다는 생각이 들었습니다.

해당 부분은 시간을 삭제를 진행하기전 예약 리스트 중 해당 시간을 사용하고 있는 예약이 있는 경우 참조 무결성 제약 조건을 위반하여 예외가 던져지는 것이 아닌 다른 예외를 던지게 하는 것으로 리팩터링 해보았습니다!

2024-05-04 07:14 UTC, Ho-Tea commented on src/main/java/roomescape/theme/controller/ThemeController.java
> +    public List<ThemeResponseDto> findPopular() {
코드의 일관성이 지켜지게끔 재구성하겠습니다!

2024-05-04 07:15 UTC, Ho-Tea commented on src/main/java/roomescape/response/ResponseCode.java
> +public enum ResponseCode {
현재는 특정 예외에 대한 메시지를 통합 관리할 필요가 없다고 느껴져 불필요한 클래스라고 판단되어 삭제하였습니다!

2024-05-04 07:16 UTC, Ho-Tea commented on src/main/java/roomescape/theme/domain/Theme.java
> +    }
해당 부분 검증 부분 추가하였습니다!

2024-05-04 07:17 UTC, Ho-Tea commented on src/main/java/roomescape/time/dao/ReservationTimeDao.java
> +    }
정렬을 통해 시간을 순서대로 보여주는것이 더 직관적일 것 같습니다!
수정하였습니다!

2024-05-04 07:18 UTC, Ho-Tea commented on src/main/java/roomescape/time/service/ReservationTimeService.java
> +        }
1. 참조무결성 제약 위반으로 인한 예외가 던져지게 한다.
2. 특정 시간에 예약된 예약이 있는지 조회를 하고 적합한 예외를 던진다

참조무결성 제약 위반으로 던져지는 예외는 다른 제약을 위반했을 때도 동일한 예외를 던진다는 사실을 통해 명확한 예외처리가 이루어지지 않을 수 있겠다는 생각으로 2번으로 리팩터링 진행하였습니다! 감사합니다 😊

2024-05-04 07:20 UTC, Ho-Tea commented on src/main/java/roomescape/theme/service/ThemeService.java
> +    public List<ThemeResponseDto> findPopular() {
조금 더 구체적으로 네이밍 해보겠습니다!

2024-05-04 07:22 UTC, Ho-Tea commented on src/main/java/roomescape/theme/service/ThemeService.java
> +        List<Theme> themes = themeDao.findPopular(today.minusWeeks(1).toString(), today.minusDays(1).toString());
> 왜 전날까지 정보로 조회하나요? 오늘로 해도 될것 같아서요

요구사항에 아래와 같은 문구가 존재하여 조회기준을 현재 날찌 전날까지로 잡게 되었습니다!
`예를 들어 오늘이 4월 8일인 경우, 게임 날짜가 4월 1일부터 4월 7일까지인 예약 건수가 많은 순서대로 10개의 테마를 조회할 수 있어야 합니다.`

2024-05-04 07:22 UTC, Ho-Tea commented on src/main/java/roomescape/time/controller/ReservationTimeController.java
> +    public List<ReservationTimeResponseDto> findAll() {
코드의 일관성.. 명심하겠습니다..!!

2024-05-06 14:35 UTC, choijy1705 requested changes
호티 피드백 잘 반영해주셨어요👍
추가 코멘트 남겼어요 reservation, reservationTime, theme 모두 공통적인 내용인데 반복 코멘트인것 같아 reservation에 주로 남겼습니다!
확인해보시고 도메인 모두에 통일되게 반영해보면 좋을것 같아요!

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/admin/controller/AdminController.java
> +        return "admin/reservation-new";
얘는 왜 reservation 뒤에 new가 붙나요??

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/exception/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
모든 예외사항을 고려하라는 뜻은 아니였습니다!
모든 예외사항을 고려할 수 없기때문에 
그때 내려줄 수 있는 에러를 클라이언트가 어느정도 이해할 수 있게 핸들링 해줘야한다는 이야기였습니다
RuntimeException을 handling 할 수 있도록 고려가 필요해보입니다

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +        List<ReservationResponseDto> responseDtoList = reservationService.findAll().stream()
```suggestion
        List<ReservationResponseDto> responseDtos = reservationService.findAll().stream()
```
자료구조를 변수명에 나타내는것은 안좋은 방법일것 같아요!

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    public ResponseEntity<ReservationResponseDto> save(@RequestBody final ReservationRequestDto request) {
requestDto에 대한 validation은 필요없을까요?

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/dao/ReservationDao.java
> +    public boolean checkExistReservationOf(final LocalDate date, final long timeId, final long themeId) {
다른 메서드 처럼 ~ByXXX 명칭이 좋지 않을까 싶네요!

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/dao/mapper/ReservationRowMapper.java
> +    public Reservation mapRow(final ResultSet resultSet, final int rowNum) throws SQLException {
별도의 클래스로 관리하면 가독성이 안 좋지 않을까요?

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +        validateDateIsNotNull(date);
validation은 주생성자에서 하도록 해야하지 않을까요?

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +        validateDateIsNotNull(date);
정적 팩토리 메서드의 필요성도 잘 못느끼겠어요 🤔

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                                         new EmptyDataAccessException("timeId : %d에 해당하는 시간이 존재하지 않습니다.", requestDto.timeId()));
findById 말고 getById 혹은 fetchById 를 만들어서 조회하고 없다면 error를 내는 메서드를 dao에 만들어서 관리하는건 어떨까요?

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        return new Reservation(reservationId, reservation);
적절히 개행을 해주는게 가독성에 좋을것 같아요🙏

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        }
해당 로직은 코드의 의도가 명확하게 드러나지 않는다고 생각해요
없는값을 지우려고 시도할때 에러를 내고 싶다면 차라리 조회를 하고 없을때 에러를 내는 방향이 의도를 명확히 드러낼 수 있을것 같아요

(없는 값을 지우는게 비즈니스적으로 크리티컬하지 않다면 굳이 에러를 낼 필요도 없을것 같네요!)

2024-05-06 14:35 UTC, choijy1705 commented on src/main/java/roomescape/theme/domain/Theme.java
> +    }
description, thumbnail 은 null이더라도 name은 null이면 안될것 같아서요!

2024-05-06 16:56 UTC, Ho-Tea commented on src/main/java/roomescape/admin/controller/AdminController.java
> +        return "admin/reservation-new";
급하게 미션을 했던 흔적이 남아있는것 같습니다...🥲
수정하였습니다!

2024-05-06 16:59 UTC, Ho-Tea commented on src/main/java/roomescape/admin/controller/AdminController.java
> +        return "admin/reservation-new";
주어진 `html` 페이지 명이 `reservation-new`로 구성되어 있어 위와같이 구성했습니다!

2024-05-06 17:02 UTC, Ho-Tea commented on src/main/java/roomescape/exception/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
예상할 수 있는 예외상황에 대해 보다 클라이언트 쪽에서 직관적으로 이해되게끔 
에러 메시지나 상태코드등을 구체적으로 작성해아 한다 라고 이해하였는데,
의도하신 피드백 방향과 일치할까요..!?

2024-05-06 17:16 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    public ResponseEntity<ReservationResponseDto> save(@RequestBody final ReservationRequestDto request) {
현재 프로젝트의 규모가 작아 `DTO`와 `Domain`에서의 검증이 크게 필요하지 않다고 느껴져 구성하지 않았었는데,
다시 생각해보니 검증과 관련된 부분에서는 더 깊이 `layer`를 타고 들어온 후 검증하여 예외를 발생시키는 것 보다,
우선적으로 검증 하여 빠르게 예외를 발생시키는 것이 비용적으로 더 나을 것 같습니다!

`DTO`가 검증한 부분을 `Domain`이 이중으로 검증하는 것에 대해 고민이 되었는데,
우선은 `DTO`가 검증하는 부분을 `Domain`에서도 다시 검증하는 것으로 구현하였습니다!

(외부에서 `API`를 통해 유입되는 것 제외하고도 내부 `Service`에서 `Domain` 객체를 임의로 생성하여 비즈니스로직을 수행하게 될 때 실수로 잘못된 값을 넣어 `Domain`객체를 생성되게 하는 경우도 존재할 수 있기에 검증을 진행하였습니다)

2024-05-06 17:51 UTC, Ho-Tea commented on src/main/java/roomescape/exception/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
추가로 현재 제가 구성한`CustomException`이 필요 이상으로 많다고 판단되고,
모든 `CustomException`이 같은 형식으로(`RuntimeException` 상속 후 생성자 하나 유지)만 구성되고, 
다른 부분은 단지 예외 클래스명이라고 생각되어집니다. 

추후 유지보수에서도 해당 `Exception`들을 관리하는 것은 불필요한 작업을 수반할 것 같다는 생각도 들어
(`A`예외가 추가되면 `A`예외 클래스 생성 후 `ControllerAdvice`에 추가해야한다) 
 해당 예외를 한가지의 예외로 묶고 예외 메시지를 세분화 하는 방법도 고민중에 있는데,
 이에 대해 영이의 의견이 궁금합니다..!

2024-05-06 18:01 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    public ResponseEntity<ReservationResponseDto> save(@RequestBody final ReservationRequestDto request) {
추가로 `DTO`에 대한 검증이 정상적으로 이루어지는지 테스트하기 위해 `Controller` 단위테스트(`@WebMvcTest`)를 진행해야 한다고 생각되어지는데, 
현재 인수테스트(`ReservationAcceptanceTest`)와 공통되는 부분이 많다고 판단되어 인수테스트를 없애고,
(모든 빈을 컨테이너에 등록하는 것을 통해 인수테스트를 진행하여 테스트 시간이 생각보다 많이 소모되는 것 같습니다..)
비교적 가벼운 단위테스트로 대체해야 할지 고민이 되었습니다 🥲

``` java

public record ReservationRequestDto(
        @NotBlank(message = "예약자의 이름을 입력해야 합니다.") String name,
        @NotNull(message = "예약날짜를 입력해야 합니다.") String date,
        @Min(value = 1, message = "올바른 예약 시간 ID를 입력해야 합니다.") long timeId,
        @Min(value = 1, message = "올바른 예약 테마 ID를 입력해야 합니다.") long themeId) {

    public Reservation toReservation(final ReservationTime reservationTime, final Theme theme) {
        return Reservation.of(null, name, date, reservationTime, theme);
    }
}

```

2024-05-07 04:55 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/dao/ReservationDao.java
> +    public boolean checkExistReservationOf(final LocalDate date, final long timeId, final long themeId) {
코드 일관성을 위해 메서드 네이밍 변경하겠습니다!

2024-05-07 05:36 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/dao/mapper/ReservationRowMapper.java
> +    public Reservation mapRow(final ResultSet resultSet, final int rowNum) throws SQLException {
`RowMapper`를 따로 클래스로 분리하면 한 클래스 내의 `Mapper`가 존재하지 않아 가독성이 떨어질 수 있는 단점이 존재할 수 있지만,
해당 클래스를 따로 객체로 분리하면서 테스트가 용이해질 수 있는 장점이 있을 것 같습니다!

2024-05-07 05:43 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +        validateDateIsNotNull(date);
`Service -> Dao`를 통해 객체가 저장될 때 id가 필요없고(id가 정해지지 않은 상태),
`Dao -> Service`를 통해 객체가 꺼내어져 올 때 id가 필요(id가 정해진 상태)하다고 판단되었습니다.
`save`와 `find`할 때 서로 다른 객체를 사용할까도 고민되었지만, 현재는 필요하지 않다고 판단되어 정적팩터리메서드로 구분하게 되었습니다.
기본 생성자는 `private`으로 구성하였고 아래와 같이 새롭게 구성해보았는데 이에 대해 영이의 의견이 궁금합니다!
(이러한 방향은 다른 개발자에게 오해의 소지를 불러일으킬 수 있을수도 있지 않을까 걱정되기도 합니다)

2024-05-07 06:26 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +                                         new EmptyDataAccessException("timeId : %d에 해당하는 시간이 존재하지 않습니다.", requestDto.timeId()));
`dao`에서 만들어 관리를 하게되면 코드의 중복도 사라질 것 같습니다!
반영하였습니다!

2024-05-07 06:50 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        }
없는 값을 지우려고 할 때 자체적으로 예외가 발생하지 않기 때문에 현재 비즈니스적으로 크리티컬하지 않다고 판단되었습니다
해당 부분 반영하였습니다!

2024-05-07 11:19 UTC, choijy1705 requested changes
호티 이번 단계의 막바지에 온것 같아요!
한번만 더 피드백 반영해보면 좋을것 같습니다🙏
에러 처리에 대한 피드백과 추가 리뷰들 챙겨봐주세요!

2024-05-07 11:19 UTC, choijy1705 commented on src/main/java/roomescape/reservation/controller/ReservationController.java
> +    public ResponseEntity<ReservationResponseDto> save(@RequestBody final ReservationRequestDto request) {
dto 의 검증과 도메인의 검증은 우선 둘다 필요하다고 생각해요
1. 말씀 주신것처럼 dto는 fast fail 이 가장 큰 목적일것 같아요. 실제로 비즈니스 로직이 복잡해지면 에러를 반환하는 시간이 오래걸릴 수 도 있으니까요
2. 도메인의 경우는 비즈니스 로직으로 객체값이 변경하면서 새롭게 객체를 생성하는 경우에도 반드시 검증이 되어야하기 때문에 반드시 필요할것 같습니다. 실제 db에 저장되는것은 무엇보다도 도메인이기 때문에 도메인은 반드시 필요할 것 같아요

테스트에서는 도메인 위주로 테스트하면 충분할 것 같아요. 테스트는 커버리지를 채우기 위한것이 아니라 코드 변경시 놓치는 부분이 없는지를 확인하는 용도입니다. 최소한의 테스트로 호티가 짠 코드를 본인 스스로 신뢰할 수 있다면 필요한 테스트만 잘 짠 코드일것 같습니다.

2024-05-07 11:19 UTC, choijy1705 commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +        validateDateIsNotNull(date);
개인적으로 정적팩토리 메서드의 일반적인 네이밍과도 조금 다른것 같고
부 생성자를 만들어 충분히 처리할 수 있는데 
클래스만 복잡하게 만드는것 같은 느낌입니다...😭😭

2024-05-07 11:19 UTC, choijy1705 commented on src/main/resources/schema.sql
> +);
같은 날짜, 같은 시간, 같은 테마는 하나만 존재할것 같은데
거기에 대한 유니크 고려도 해보면 좋을것 같네요!

2024-05-07 11:19 UTC, choijy1705 commented on src/main/java/roomescape/time/service/ReservationTimeService.java
> +    }
과거의 date는 예약을 할 수 없도록 처리하려면 어떻게 할 수 있을지도 고민해보면 좋을것 같네요!

2024-05-08 06:05 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/domain/Reservation.java
> +        validateDateIsNotNull(date);
정적팩터리 메서드 대신 부생성자를 통해 표현하겠습니다!
영이가 보시기에도 현재 프로젝트 구조상 생성과 조회에 따른 다른 도메인을 만드는 것보다 
현재 도메인에서 생성자를 여러개 구성해 표현하는 것이 더 적합하다고 생각하시는 걸까요..!

2024-05-08 07:18 UTC, Ho-Tea commented on src/main/java/roomescape/reservation/dao/mapper/ReservationRowMapper.java
> +    public Reservation mapRow(final ResultSet resultSet, final int rowNum) throws SQLException {
한 클래스 내에 해당 `RowMapper`를 유지했을 경우 이해하기 쉬운 코드 즉 가독성이 올라가고, 
다른 클래스로 `RowMapper`를 따로 두었을 때는 객체의 분리를 통해 테스트하기 쉬워져 
해당 객체가 정상수행되는지 쉽게 검증, 판단할 수 있다는 것

두 가지를 고민했을 때 말씀처럼 현재는 프로덕션 코드의 가독성을 우선시하여 
이해하기 좋은 코드를 구성하는 것이 더 바람직 할 것 같습니다! 
반영하였습니다!

2024-05-08 08:48 UTC, Ho-Tea commented on src/main/resources/schema.sql
> +);
유니크 제약조건을 추가해 데이터베이스 스키마 상에서 제약조건을 걸어주는 형식으로 리팩토링 반영하였습니다!

2024-05-08 16:12 UTC, choijy1705 approved these changes
호티 이번 단계는 머지하겠습니다!
컨벤션이 조금 평범하지 않은것 같아요! 다른 크루들과 비교해보시고 조금 평범한 컨벤션을 적용해보면 좋을것 같아요🙏
몇가지 추가 코멘트도 남겼으니 다음 단계 진행하면서 반영해보면 좋을것 같습니다!

2024-05-08 16:12 UTC, choijy1705 commented on src/main/java/roomescape/time/dto/ReservationTimeRequestDto.java
> +        @NotBlank(message = "예약 시간을 입력해야 합니다.") String startAt) {
```suggestion
        @NotBlank(message = "예약 시간을 입력해야 합니다.") String startAt
) {
```

ReservationTimeResponseDto 랑 컨벤션이 달라서 둘중 하나로 통일되면 좋을것 같아요

2024-05-08 16:12 UTC, choijy1705 commented on src/main/resources/schema.sql
> +    UNIQUE (date, theme_id, time_id)
👍

2024-05-08 16:12 UTC, choijy1705 commented on src/test/resources/schema.sql
> +);
schema.sql을 프로덕션과 테스트 각각 이중으로 관리하면 어떤 문제가 있을지 고민해보면 좋을것 같습니다!

2024-05-08 16:12 UTC, choijy1705 commented on src/test/resources/data.sql
> +       ('Evan Wright', '2024-04-29', 7, 2);
```suggestion
       ('Evan Wright', '2024-04-29', 7, 2);
       
```

2024-05-08 16:12 UTC, choijy1705 commented on src/test/resources/data.sql
> +INSERT INTO reservation_time (start_at)
테스트 값들을 이렇게 넣으면
테스트 메서드에서는 어떤 값을 넣었는지 파악하기 어려워서 혼란을 줄 수 있을것 같습니다!
웬만하면 테스트 메서드 안에서 given-when-then으로 나눠서
given에서 테스트 데이터를 db에 넣는 방법으로 짜면 좋을것 같아요!

2024-05-08 16:12 UTC, choijy1705 commented on src/main/java/roomescape/exception/handler/GlobalExceptionHandler.java
> +        return ErrorResponse.builder(ex, HttpStatus.BAD_REQUEST, ex.getMessage()).build();
예상치 못한에러라서 상태코드는 internalServerError가 더 적절할것 같네요

2024-05-08 16:12 UTC, merged

2024-05-09 04:13 UTC, Ho-Tea commented on src/main/java/roomescape/exception/message/ExceptionMessage.java
> +    FAIL_PARSE_TIME("형식에 맞지 않은 시간입니다.", HttpStatus.BAD_REQUEST);
예외가 발생되는 메서드에서 해당 에러 메시지를 관리하는 것으로 반영하였습니다.

2024-05-09 04:43 UTC, Ho-Tea commented on src/test/resources/schema.sql
> +);
프로젝트에서 사용하는 스키마 구조가 변경되었을 때 두가지 스키마 파일을 관리해야 한다는 단점이 존재할 것 같습니다!
반영하였습니다!