[1 - 3단계 방탈출 사용자 예약] 트레(이충렬) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #3
Opened 2024-05-02 06:38 UTC by takoyakimchi

2024-05-02 06:45 UTC, takoyakimchi reviewed
.

2024-05-02 15:11 UTC, her0807 requested changes
안녕하세요 트레~

이번 미션 리뷰를 맡게 된 수달이라고 합니다 🙂
PR 내용에 고민사항을 잘 적어주셔서, 해당 고민에 대한 제 생각과 더불어
함께 고민하면 좋을 키워드 적어두었습니다.
즐거운 리뷰 되었으면 좋겠습니다 :)

2024-05-02 15:11 UTC, her0807 commented on src/main/java/roomescape/exception/PastReservationException.java
> +    public PastReservationException() {
> 어떨 때 커스텀 Exception 을 사용하는게 좋을까요?


우선 커스텀 예외클래스를 사용하는 이유부터 생각 해볼까요? 
저는 예외가 발생했을 때 서버와 클라이언트 모두 예외가 일어난 원인을 보다 더 쉽게 특정하고 
빠른 조치를 취할 수 있게 하기 위해서 사용한다고 생각하는데요. 

사실 예외가 발생할때는 예외 메세지도 함께 전달이 되기 때문에 저는
 예외 클래스를 도메인마다 만들지 않고 메세지나, 오류 코드로 통신을 하기도 해요. 

이건 굉장히 주관적인 생각이기 때문에 여러 방법을 시도해보면서 어떤 점이 좋은지 직접 체험해보면 좋을 것 같아요.

2024-05-02 15:11 UTC, her0807 commented on src/main/java/roomescape/dto/app/ReservationTimeAppRequest.java
> +}
불필요한 공백이나 바디는 제거해도 좋을 것 같아요

2024-05-02 15:11 UTC, her0807 commented on src/main/java/roomescape/domain/ThemeRepository.java
> +    boolean isNameExists(String name);
isNameExists 는 isExists 으로 표현해도 좋을 것 같아요.
테마명은 겹치지 않으니까 테마가 존재하냐? 이렇게만 물어도 소통이 될 것 같거든요!

2024-05-02 15:11 UTC, her0807 commented on src/main/java/roomescape/domain/Theme.java
> +    }
1. 잘못된 테마 이름이 공백과 블랭크 말고 또 존재할 것 같아요. 
예를 들면 111 이런 테마가 가능한가요? 한글과 영문이 반드시 1단어 이상 존재해야 한다 와 같이 
트레만의 추가적인 요구사항이 있으면 더 사용자 친화적인 서비스가 될 것 같아요.


이런 맥락에서 썸네일과 ,디스크립션, 테마 이름 모두 원시값 포장이 가능할 것 같은데요. 
현재 테마 자체에서 스스로 가지는 행위가 없지만, 만약 디스트립션을 수정한다던가 이런 행위가 생기면
검증로직 때문에 중요한 로직이 가려지게되는 것 같아요.

2024-05-02 15:11 UTC, her0807 commented on src/main/java/roomescape/controller/ThemeController.java
> +    }
@ExceptionHandler 핸들러는 어떤 용도일까요?

각각의 Controller 뿐만아니라 Global Exception Handler 라는 키워드로 한번 찾아보시면 좋을 것 같아요. 

그리고 해당 예외를 핸들링 할것인지. 말것인지에 따라 예외를 처리하는 액션도 달라지니까 그것들도 고민해보면 좋을 것 같고요. 아래에 checked / unchecked 라는 키워드 남겨두었는데요. 이부분에 대한 공부를 하고 리팩터링해서 알려주시면 좋을 것 같아요.

2024-05-07 04:22 UTC, takoyakimchi commented on src/test/java/roomescape/repository/JdbcReservationRepositoryImplTest.java
> +@SpringBootTest
TRUNCATE를 사용하는 방식으로 수정해 보겠습니다!  :)

2024-05-07 04:37 UTC, takoyakimchi commented on src/main/resources/schema.sql
> +    date     VARCHAR(255) NOT NULL,
`TIME`, `DATE` 타입 사용하도록 수정하였습니다!

`date` 컬럼명은 강의자료에서 주어진 자료를 그대로 사용하였는데, 확실히 예약어랑 헷갈릴 가능성이 있겠네요.
그런데 js를 포함해서 수정해야 하는 부분이 너무 많아 일단은 그대로 유지하고
문제가 생기거나 나중에 시간이 나면 그 때 반영해 보도록 하겠습니다!

2024-05-07 05:39 UTC, takoyakimchi commented on src/main/java/roomescape/domain/ThemeRepository.java
> +    boolean isNameExists(String name);
반영하였습니다!

`테마명이 겹치면 같은 예약으로 간주한다`라는 비즈니스 로직을 전달하기 위한 작명이었는데
메소드 시그니처로도 충분히 전달될 수 있다는 생각이 드네요.

2024-05-07 05:51 UTC, takoyakimchi commented on src/test/java/roomescape/repository/JdbcReservationTimeRepositoryImplTest.java
> +        List<ReservationTime> expected = List.of(save1, save2);
반영하였습니다! 
코드가 더 깔끔해졌어요! 👍

2024-05-07 07:39 UTC, takoyakimchi commented on src/main/java/roomescape/service/ThemeService.java
> +    private void validateDuplication(ThemeAppRequest request) {
Model에서 처리해야 할 로직이 너무 많아져서, 이것을 분리한 것이 Service layer라고 알고 있습니다!
기존 코드에서도 service 계층에서는 request dto를 사용하지 않는 형태였는데
클래스명과 패키지 분리가 명확하지 않았던 것 같아요.

dto 패키지 분리 및 다음과 같이 클래스명 변경 진행하였습니다!

요청-응답 DTO: `~Request` `~Response`
컨트롤러 -> 서비스로 전달되는 DTO: `~Dto`

2024-05-07 07:44 UTC, takoyakimchi commented on src/main/java/roomescape/repository/JdbcThemeRepository.java
> +            LEFT JOIN reservation AS r ON th.id = r.theme_id AND r.date BETWEEN TIMESTAMPADD(DAY, -8, NOW()) AND TIMESTAMPADD(DAY, -1, NOW())
반영하였습니다!
`최근 한 달 내 인기 테마`도, 큰 무리 없이 조회할 수 있겠네요 :)

최근 일주일 내 예약 건수가 0회인 테마도 화면에 띄워주기 위해서 LEFT JOIN을 사용했습니다!
만약 실제 서비스라고 고려해보았을 때
최근 예약 횟수가 0회이더라도 인기 테마로서 화면에 띄우는 것이 마케팅적으로 이득이라고 판단하였습니다!

2024-05-07 09:13 UTC, takoyakimchi commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +        @RequestParam LocalDate date, @RequestParam Long id) {
더 알아보니 다음과 같은 것을 알 수 있었어요~!
GET에서 검색 조건이 필요하면 무조건 쿼리 파라미터를 사용해야겠군요! 🫢

도움 주셔서 감사합니다!

- HTTP/1.1에 따르면 GET이 검색 이외의 동작을 수행하는 것을 권장하지 않음.
- HTTP/1.1에 따르면 GET 메서드는 Request-URI로 식별되는 정보를 검색하는 것을 의미.
- GET 요청은 캐시될 수 있는데, GET 요청을 간단하게 유지하여 캐시를 관리하기 쉽도록 해야 함.
- GET 요청은 안전 및 멱등해야 함. body를 허용하지 않음으로써 안전 & 멱등을 보장할 수 있음.

2024-05-07 11:19 UTC, takoyakimchi commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +    @Mock
좋은 단위 테스트에 대해 알아보았습니다!

- 회귀 방지: 코드 수정 후 버그가 있었는데 테스트가 통과하면 안 된다.
- 리팩토링 내성: 테스트를 바꾸지 않고도 기존 코드를 리팩토링할 수 있는 척도
- 빠른 피드백: 오래 걸리면 안 된다.
- 유지보수성: 이해하기 쉽고 실행하기 쉽도록 만들어야 한다.

mocking을 하게 되면 아무래도 특정 값을 리턴한다고 가정하고 테스트를 진행하기 때문에 견고하게 테스트를 짤 수 없겠네요.

실제 객체에 의존하도록 수정해 보겠습니다!

2024-05-07 12:02 UTC, takoyakimchi commented on src/test/java/roomescape/controller/ReservationTimeControllerTest.java
> +@WebMvcTest(ReservationTimeController.class)
덕분에 테스트 관련해서 이것저것 찾아볼 수 있었습니다!
저번 미션에서는 컨트롤러 계층에서 테스트해도 충분하다는 생각이 들었는데요.
이번 미션 들어오면서 점점 로직도 복잡해지고 코드에 확신이 없기도 해서
페어의 코드 따라서 모든 레이어에서 테스트를 작성해 보았습니다.

하지만 시간이 없는 경우라면 주어진 요청에 따라 올바른 값을 응답하고 있는가? 만 테스트 해도 좋을 것 같다는 생각이 들어요!
물론 충분한 단위 테스트 + 튼튼한 테스트 케이스가 뒷받침되어야겠네요!

### E2E 테스트

- 테스트하고자 하는 기능에서 필요로 하는 모든 컴포넌트들이 올바르게 협업해서 최종적으로 원하는 결과를 내는지 테스트 → **기술적 관점**
- 블랙박스 테스트 - 내부 코드에 관심을 안 가짐

### 인수 테스트(Acceptance Test)

- 테스트하고자 하는 기능을 비즈니스적인 관점에서 올바르게 동작하는지 확인하는 테스트
- 기술적인 관점과 상관없이, ‘클라이언트가 기대하는’ 동작에 대한 검증을 진행 → **사용자 관점**
- 계약 명세에 따라 잘 수행하고 있나?
- 사용자 시나리오에 맞게 테스트

### 단위 테스트(Unit Test)

- 테스트 가능한 가장 작은 소프트웨어를 실행하여 예상대로 동작하는지 테스트
- 단위의 크기는 엄격하게 정해지지 않음

### 통합 테스트(Integration Test)

- 단위 테스트보다 더 큰 동작을 달성하기 위해 여러 모듈들을 모아 이들이 의도대로 협력하는지 확인하는 테스트
- 외부 라이브러리, DB 등등 개발자가 변경할 수 없는 부분까지 묶어서 테스트함
- 유닛 테스트보다 복잡하게 만들어짐, 에러 검출이 명확하지 않을 수 있음, 따라서 유닛 테스트에 더 집중하기

2024-05-07 12:25 UTC, takoyakimchi commented on src/test/java/roomescape/repository/JdbcReservationRepositoryImplTest.java
> +@Transactional
다음과 같은 방법이 있겠네요!
수달은 테스트 코드에서 `@Transactional`을 아예 안 쓰시나요?

- 테스트 더블 → 테스트에 사용되는 객체를 만들어서 사용하는 방식
    - Mocking을 하여 공유자원으로부터 의존 관계 제거
- `@Transactional` → 테스트 메소드가 종료될 때
    - `RANDOM_PORT`, `DEFINED_PORT` 를 쓰면 별도의 스레드에서 스프링 컨테이너가 실행
    - 따라서 올바르게 롤백되지 않고 `@Transactional`을 쓰는 의미가 없어짐
- SQL Truncate (현재 사용중인 방법!)

2024-05-07 12:53 UTC, takoyakimchi commented on src/test/java/roomescape/domain/ReservationTest.java
> +}
현재는 자명한 assertion 로직만 있기 때문에 큰 효과는 없는 테스트인 것 같습니다!
따라서 유지비용과 비교해서 검증 효과는 크지 않다고 생각합니다.

2024-05-07 12:54 UTC, takoyakimchi commented on src/main/java/roomescape/repository/JdbcThemeRepository.java
> +        return jdbcTemplate.query(sql, (rs, rowNum) -> new Theme(
하나의 rowMapper로 묶어 줄 수 있겠네요!

2024-05-07 12:55 UTC, takoyakimchi commented on src/main/java/roomescape/exception/PastReservationException.java
> +    public PastReservationException() {
클라이언트 입장에서는 예외 메시지만 확인이 가능하고
어떤 형태의 Exception이 터졌는지 모르도록 구현하였기 때문에
커스텀 예외가 아직까지는 크게 효과적이지 않은 것 같아요!

아직은 예외 메시지만으로도 충분하겠네요.

2024-05-07 13:06 UTC, takoyakimchi commented on src/main/java/roomescape/exception/PastReservationException.java
> +    public PastReservationException() {
지금 단계에서는 에러 메시지만 포장해주는 역할을 하기 때문에
커스텀 예외 분리가 다소 과했던 것 같아요!

그렇지만 `IllegalArgumentException`을 그대로 사용하는 것도,
예상치 못했던 원인으로 인해 예외가 발생하면 raw한 예외 메시지가 클라이언트에게 그대로 전달되는 문제가 생기겠네요.

커스텀 예외를 하나로 통합해 보겠습니다!

2024-05-08 04:36 UTC, takoyakimchi commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +            .isInstanceOf(DuplicatedThemeException.class);
도메인의 검증 로직에 있는 예외 메시지까지 서비스 테스트에서 사용하다 보니
protected로 바꾸는 것보다는 일단은 하드코딩으로 넣고 문제가 생기면 수정하는 방향으로 가보겠습니다!

2024-05-08 06:17 UTC, takoyakimchi commented on src/main/java/roomescape/exception/ThemeNotFoundException.java
> +public class ThemeNotFoundException extends RuntimeException {
언체크예외입니다!

### 체크 예외

- `RuntimeException`의 하위 클래스가 아니면서 `Exception`의 하위 클래스인 예외
- try-catch나 throw로 반드시 예외처리를 해야 한다. (컴파일 단계에서 확인)
- 예외 발생해도 트랜잭션 롤백 X

### 언체크 예외

- `RuntimeException`의 하위 클래스들
- 런타임에 발생할 수 있는 예외
- 개발자의 실수로 발생
- 예외 발생 시 트랜잭션 롤백

2024-05-08 06:19 UTC, takoyakimchi commented on src/main/java/roomescape/domain/Theme.java
> +    }
원시값 포장 및 검증 로직 분리 진행하였습니다!

2024-05-08 06:20 UTC, takoyakimchi commented on src/main/java/roomescape/domain/Theme.java
> +    }
레벨1을 잠시 잊고 있었네요 ... ㅎㅎ 😭

2024-05-08 06:20 UTC, takoyakimchi commented on src/main/java/roomescape/controller/ThemeController.java
> +    }
무의미하게 커스텀 예외를 많이 만들었다는 생각이 들었고
하나의 커스텀 예외로 통일 + RuntimeException은 예외 메시지가 노출되지 않도록 별도 처리하였습니다!

2024-05-08 06:32 UTC, takoyakimchi commented
안녕하세요 수달!
연휴 때 여행을 다녀 오느라 PR 요청이 늦었네요... 🥺
리뷰 미리 감사드립니다 :) 

# 수정 사항 및 질문

### 테스트 정리
- mock 사용을 전부 제거하고 실제 객체에 의존하도록 수정하였습니다.
- 테스트 코드 스타일을 일관성 있게 변경하였습니다.
- 컨트롤러 테스트에서는, API 요청에 대해 올바른 응답을 해주는지 통합 테스트 진행하였습니다. (이런 게 인수 테스트인가요...?)

### DTO 패키지 분리
- controller에서 사용하는 dto와 service에서 사용하는 dto를, 각각의 패키지로 분리하였습니다.
- 그런데 service -> controller로 전달해 주는 DTO는 어디에 넣는 것이 좋을까요...? (일단은 service 패키지 내에 넣었습니다)

### 원시값 포장
- 원시값 포장 + 검증 분리 진행하였습니다.
- 서비스에 있던 도메인 검증 로직을 해당 도메인으로 옮겼습니다.

### 커스텀 예외
- 커스텀 예외가 json을 응답하도록 변경하였습니다.
- 자바 표준 예외를 클라이언트에게 보여주지 않도록 수정하였습니다.
- 커스텀 예외를 하나로 통합하였습니다.
- 기타 언체크 예외는 모두 500 에러와 함께 `서버 내부 에러가 발생하였습니다.`라는 메시지를 응답하도록 변경하였습니다.

2024-05-08 14:36 UTC, her0807 commented
> 컨트롤러 테스트에서는, API 요청에 대해 올바른 응답을 해주는지 통합 테스트 진행하였습니다. (이런 게 인수 테스트인가요...?)

이 부분이 살짝 헷갈릴 수 있는 부분인데요 ~ 통합테스트라고해서 모두 인수테스트는 아닙니다! 
인수테스트는 시나리오 테스트로 사용자의 입장에서 내부 행위는 드러내지 않고(블랙박스) 원하는 결과값이 돌아오는지 검증하는 테스트입니다. 

>  service -> controller로 전달해 주는 DTO는 어디에 넣는 것이 좋을까요...? 

controller -> service 의존하고 있음 
service 에 dto 위치하고 있으면 controller -> service 도 의존해서 양방향의존성이 생깁니다. 

그래서 저는 controller에 둘 것 같습니다

2024-05-08 14:37 UTC, her0807 approved these changes
안녕하세요 트레~

여행다녀오셨군요  🖐🏻
리프레시가 잘 되신 것 같네요 ㅎㅎ
질문주신 내용에 대해서 간단한 코멘트 남겨두었고,
요구사항 모두 만족된 것 같아 머지하겠습니다.
이번 단계 수고하셨어요!

2024-05-08 14:37 UTC, merged