[1 - 3단계 방탈출 사용자 예약] 명오(김형호) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #32
Opened 2024-05-02 08:20 UTC by HyungHoKim00

안녕하세요 썬! 이번 미션에서 리뷰이로 만나게 된 명오입니다!

이번 미션은 제 코드로 진행하게 되었는데요, 미숙한 점이 많아 코드 리팩터링하는데에도 시간을 많이 썼습니다.

미션을 급박하게 진행하게 되어, 코드 스타일적으로 미숙한 부분이 많을 것 같다는 생각이 드네요.

스프링은 전에 사용해 본 적 없고, 우테코 와서 처음으로 학습해보았습니다!

잘 부탁드립니다!

2024-05-02 15:45 UTC, syoun602 requested changes
안녕하세요 명오! 이번 리뷰를 맡게된 썬입니다 ☀️

방탈출 사용자 예약 1단계 잘 구현해주셨네요 👍
몇가지 코멘트 남겨보았으니 확인 후 재요청 주세요!

2024-05-02 15:45 UTC, syoun602 commented on docs/APISpecification.md
> +## API 명세서
명세서 추가 👍👍

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/controller/AdminController.java
> +        return "admin/reservation-new";
두개로 나눠진 이유가 있을까요?

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.created(URI.create("admin/reservation")).body(reservationResponse);
uri created에 무엇을 넣어야할까요?

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +    public ResponseEntity<List<ReservationTimeWithBookStatusResponse>> findReservationTimesWithBookStatus(
filter보다 더 좋은 네이밍을 찾아보면 좋을 것 같아요.
search는 어떨까요?

---
해당 경로가 제대로 동작하는지 확인하려면 화면상에서 어떻게 조작해야하는지 알려주세요!

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/controller/RoomThemeController.java
> +        return ResponseEntity.notFound().build();
서비스 로직에서 예외를 생성하고 그걸 만들어두신 ExceptionHandler에서 처리해볼 수 있을 것 같습니다~!

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/dao/ReservationDao.java
> +        String selectSQL = """
일반적으로는 query라고 작성해볼 수 있을 것 같아요

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/dao/ReservationDao.java
> +        RowMapper<Reservation> rowMapper = (rs, rowNum) -> new Reservation(
재사용성을 위해 상수로 분리해볼까요?

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +        return jdbcTemplate.query("SELECT * FROM reservation_time",
여기는 정확히 똑같은 코드가 사용되고 있네요. 이전에 말씀드린 것처럼 rowmapper를 분리해봅시다~!

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +        return reservationTime.withId(id);
어떤 메서드인지 잘 인지되지 않습니다 😢
차라리 직관적인 setter를 사용하거나 새로운 객체를 여기서 구성해서 반환해도 좋을 것 같아요

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/domain/Name.java
> +            throw new IllegalArgumentException("이름에 null 혹은 빈문자열을 입력할 수 없습니다.");
null이라는 단어가 사용자 친화적인지 고민해보아요

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
우선 contains라는게 어떤 역할의 메서드인지 잘 모르겠습니다 !

또한, 스프링 어플리케이션을 개발하기 시작하면 레벨 1에서 진행했던 부분들을 놓치는 경우가 많은데,
레벨 1에서 학습했던 것을 한번 전체적으로 복기해봤으면 좋겠어요.
startAt에 대한 비교를 다른 객체에게 물어볼 수 있을 것 같습니다.

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        List<Reservation> reservations = reservationDao.findAll();
findAll을 매번 호출하는건 좋지 않습니다. 
극단적으로 예약이 1000만개가 넘어가면 매번 모든 데이터를 불러와서 
자바 어플리케이션 내에서 필터링하게 될 것 같은데 좋은 방법은 아닌 것 같아요.
이번 기회에 쿼리를 학습하고 적극적으로 활용해보면 좋을 것 같습니다. 

hint: grouping과 count 등과 같은 키워드를 활용해봅시다

2024-05-02 15:45 UTC, syoun602 commented on src/main/resources/data.sql
> +insert into reservation(name, date, time_id, theme_id) values('썬', '2024-05-01', 1, 2);
ㅋㅋㅋ 감사합니다 🙇‍♂️

2024-05-02 15:45 UTC, syoun602 commented on src/test/java/roomescape/controller/RoomThemeControllerTest.java
> +    }
질문) 기존엔 dirtiesContext를 사용했었을 것 같은데, 이렇게 변경하신 이유가 있나요~?

2024-05-02 15:45 UTC, syoun602 commented on src/test/java/roomescape/domain/ReservationTimeTest.java
>  class ReservationTimeTest {
도메인에 서비스까지 테스트 잘 추가해주셨네요 💯

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/handler/GlobalExceptionHandler.java
> +            IncorrectResultSizeDataAccessException.class})
요거는 언제 발생하는 예외일까요?

2024-05-02 15:45 UTC, syoun602 commented on src/main/java/roomescape/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
개발자가 예상하지 못한 예외가 발생하면 무슨 일이 일어날까요?

2024-05-03 06:03 UTC, HyungHoKim00 commented on src/main/java/roomescape/handler/GlobalExceptionHandler.java
> +            IncorrectResultSizeDataAccessException.class})
1. request의 입력이 null일 때 발생합니다.
2. 날짜 혹은 시간 입력 양식이 다를 때 발생합니다.
3. 지나간 날짜 예약, 중복된 시간 저장 등의 잘못된 시도를 할 때 발생합니다.
4. queryForObject(findById 메서드) 실행 시, 응답값이 존재하지 않거나 한개가 아닐 때 발생합니다.

이에 대해 얘기하던 중, 1번(NPE)이 조금 위험하다는 의견을 들었습니다. 제가 의도하지 않은 NPE가 발생했을 때도, 400을 응답할 가능성이 있기 때문입니다.

validation 의존성을 추가하여, null 입력을 처리할 수 있도록 변경했습니다.

2024-05-03 06:10 UTC, HyungHoKim00 commented on src/main/java/roomescape/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
500번대의 예외가 발생할 것 같습니다. 개발자가 예상하지 못하는 예외가 발생한다는 것은, 서버 측의 실수이기에 500을 응답하는 것이 올바른 응답이라고 생각합니다.

2024-05-03 06:12 UTC, HyungHoKim00 commented on src/test/java/roomescape/controller/RoomThemeControllerTest.java
> +    }
dirtiesContext는 모든 테스트마다 spring을 다시 불러오기 때문에, 시간이 오래 걸립니다.
테스트는 프로덕션 코드가 변경될 때 마다 계속 불러와야 하기 때문에, 오래 걸리면 안된다고 생각하여 수정했습니다.

2024-05-03 06:13 UTC, HyungHoKim00 commented on src/main/java/roomescape/domain/Name.java
> +            throw new IllegalArgumentException("이름에 null 혹은 빈문자열을 입력할 수 없습니다.");
null이라는 단어는 썬의 말처럼 사용자 친화적이라고 보기 어렵다고 생각합니다.
빈 문자열이라는 말 역시도 친화적으로 느껴지진 않네요..

수정했습니다!

2024-05-03 06:35 UTC, HyungHoKim00 commented on src/main/java/roomescape/controller/RoomThemeController.java
> +        return ResponseEntity.notFound().build();
제가 학습하기로는, try/catch가 비용이 많이 드는 작업이라고 알고 있습니다.
그래서 반환값이 없는 메서드를 사용하고, 작업이 올바르게 수행됨을 boolean을 통해 알 수 있는 경우에 ExceptionHandler를 사용하지 않고 boolean 반환값에 따라 수행하려고 했습니다.
혹시 ExceptionHandler에서 일관성있게 처리하는 것이 더 좋은 방법일까요?

2024-05-03 06:39 UTC, HyungHoKim00 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.created(URI.create("admin/reservation")).body(reservationResponse);
공부하기 전에는 응답할 페이지를 입력하는 것이라고 알고 있었고, 그래서 id를 반환하는 것에 의문을 가졌습니다.
오늘 학습하기로는, 해당 자원에 접근하기 위한 식별자라고 학습했습니다. 그래서 고유한 주소를 반환해야 하는데, 이때문에 id값을 붙인 uri를 반환해야 한다고 느꼈습니다.

2024-05-03 06:56 UTC, HyungHoKim00 commented on src/main/java/roomescape/controller/AdminController.java
> +        return "admin/reservation-new";
질문을 잘 이해하지 못했습니다 ㅜㅜ 다시 설명해주실 수 있나요?

reservation-new로 주소가 바뀐 이유는, 테마 정보가 포함된 페이지가 reservation-new이기 떄문입니다.

2024-05-03 07:14 UTC, HyungHoKim00 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +    public ResponseEntity<List<ReservationTimeWithBookStatusResponse>> findReservationTimesWithBookStatus(
시간에 쫓겨 코딩하다보니, 네이밍 부분에 시간을 많이 투자하지 못했던 것 같습니다.
하지만,  `times?date=&themeId=` 을 사용하면 바로 위의 메서드의 GetMapping과 충돌하여 실행하지 못하는 경우가 생겼습니다.
`times?date=&themeId=`을 어떻게 사용할 수 있는 지 여쭤봐도 될까요?

2024-05-03 07:26 UTC, HyungHoKim00 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +        return reservationTime.withId(id);
새로운 객체를 반환할 때, 실수를 방지하기 위해 해당 메서드를 사용했었습니다.
하지만 썬의 말처럼 직관적이지 않다면, 실수를 유발하고 읽기도 어렵다는 생각이 드네요.
새로운 객체를 반환하도록 변경했습니다!

2024-05-03 07:36 UTC, HyungHoKim00 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
맞는 말씀입니다!

2024-05-03 08:50 UTC, HyungHoKim00 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +        List<Reservation> reservations = reservationDao.findAll();
findAll()을 자주 사용하는 것이 위험하겠네요..
쿼리문을 사용하는 방법으로 수정하였습니다!

2024-05-03 08:56 UTC, HyungHoKim00 commented
안녕하세요 썬!

리뷰를 바탕으로 수정해보았습니다.

리뷰를 보고 수정하지 않고 제 생각을 말씀드린 부분은 눈알 이모지를 달았으니, 확인해주시면 감사하겠습니다!

이번에도 잘 부탁드립니다!

2024-05-04 02:56 UTC, syoun602 requested changes
안녕하세요 명오!

피드백 빠르게 반영해주셨네요 💯
몇가지 더 남겨보았는데 확인 부탁드립니다~

2024-05-04 02:56 UTC, syoun602 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +    public ResponseEntity<List<ReservationTimeWithBookStatusResponse>> findReservationTimesWithBookStatus(
아 겹치는 것을 딱히 고려하고 말씀드린 것은 아닌데 잘 변경해주셨네요!
말씀하신 충돌 부분은 `@RequestMapping` 어노테이션을 활용해볼 수 있을 것 같아요 😊

2024-05-04 02:56 UTC, syoun602 commented on src/main/java/roomescape/controller/RoomThemeController.java
> +        return ResponseEntity.notFound().build();
스프링 어플리케이션을 개발하면서 try/catch 비용에 대해서는 크게 신경써보진 않은 것 같아요. (예전에는 중요했을 수도 있지만) 지금처럼 하드웨어의 기술이 발전된 상황에서 이정도 비용을 고려하기 보다는 코드의 가독성이나 일관성을 더 중요시 하는 것 같습니다. 제가 코멘트를 드린 의도는 컨트롤러에서 일어나야할 로직이 맞을까? 입니다. 삭제할 대상이 없어서 예외적인 처리가 필요하다면 비즈니스 로직이 아닐까요?

이 부분은 논란이 있는 부분이라 명오가 판단하시기 나름일 것 같아요. 우선은 204, 404로 나뉘게 개발하셨으니, 이걸 기준으로 말씀드리자면 404를 반환한다는 것 자체가 서버는 특정 id에 대한 작업을 부여 받았는데 요청 받은 리소스를 찾을 수 없었다는 것을 의미하신 것 아닌가요?

2024-05-04 02:56 UTC, syoun602 commented on src/main/java/roomescape/dto/request/ReservationTimeRequest.java
> +        @NotNull(message = "예약 시간 입력이 존재하지 않습니다.") String startAt) {
bean validation 잘 사용하셨네요 👍
NotNull, NotEmpty, NotNull은 어떤 차이가 있을까요?

2024-05-04 02:56 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationService.java
> +            throw new IllegalArgumentException("지난 날짜에는 예약할 수 없습니다.");
일반적으로 그럴 일은 없겠지만, 라이브러리 또는 자바 프로그램에서 저희가 일반적으로 사용하는 예외 클래스가 문제가 될 수 있습니다. 따라서 방탈출 사용자 예약이라는 서비스에서 정의한 예외를 내보내도록 커스텀 예외를 정의해봐도 좋을 것 같아요~!

2024-05-04 02:56 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationService.java
>          validateDuplicatedDateTime(reservation.getDate(), reservationTime.getId());
DB와 통신하기 전에 미리 예외를 발생시키면 네트워크 오버헤드를 줄일 수 있겠네요

2024-05-04 02:56 UTC, syoun602 commented on src/main/java/roomescape/dao/ReservationTimeDao.java
> +    public List<ReservationTimeWithBookStatusResponse> findAllWithBookStatus(String bookedDate,
👍👍

2024-05-07 01:07 UTC, HyungHoKim00 commented on src/main/java/roomescape/controller/RoomThemeController.java
> +        return ResponseEntity.notFound().build();
1. 말씀을 듣고 나니, 컨트롤러에서 일어날 로직은 아니라고 느껴지네요. 일관성있는 처리가 다른 개발자가 보았을 때 확인하기도 쉬울 것이구요.
2. 맞습니다! 이 부분은 크루들과 많이 이야기해보았는데, 사람마다 의견이 다르더라구요. 썬의 의견도 궁금해서 여쭤보았습니다 ㅎㅎ.

2024-05-07 02:12 UTC, HyungHoKim00 commented on src/main/java/roomescape/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
다른 예외들과 같은 포맷으로 응답하도록 Exception을 처리하는 ExceptionHandler를 생성하여 500을 응답하도록 했습니다.
예외 메시지를 get해서 응답하는 것은 서버의 취약점을 나타낼 것 같기에, body없이 응답하도록 했습니다!

2024-05-07 02:19 UTC, HyungHoKim00 commented on src/main/java/roomescape/dto/request/ReservationTimeRequest.java
> +        @NotNull(message = "예약 시간 입력이 존재하지 않습니다.") String startAt) {
세개는 validation의 범위에 차이가 있습니다.
notNull은 null값만 잡아내고, notEmpty는 null과 "", notBlank는 null, "", " "를 허용하지 않습니다.
empty와 blank를 검증하는 것은 도메인 로직이라고 생각하여 validation을 진행하지 않았는데, 그 기준이라면 notNull도 마찬가지일 수 있고 notBlank로 빠르게 잡아주면 객체 생성 비용도 줄어들 것이라고 생각하여 수정했습니다!

2024-05-07 03:41 UTC, HyungHoKim00 commented on src/main/java/roomescape/service/ReservationService.java
> +            throw new IllegalArgumentException("지난 날짜에는 예약할 수 없습니다.");
IllegalArgumentException을 생성하는 부분에서의 예외는 커스텀으로 처리했습니다.

하지만, 커스텀 예외를 사용하기 위해 예외가 발생하는 부분을(ex -> queryForObject) 예외를 잡아서 저희가 만든 커스텀 예외로 다시 발생시키는 작업을 해야 하는 것인가요?

의도하지 않은 예외가 잡힌다는 단점은 해소할 수 있지만, 코드가 복잡해진다는 단점이 있을 것 같습니다. 

또한, 저는 Request에서 LocalTime으로 인자를 받고 있는데, 여기에서 발생하는 HttpMessageNotReadableException을 잡고 커스텀 예외를 던지기 힘들것 같다는 생각이 듭니다. 이 부분은 설계상의 문제일까요?

2024-05-07 05:24 UTC, HyungHoKim00 commented
안녕하세요 썬! 친절한 대답과 꼼꼼한 리뷰에 감사드립니다.

리뷰를 보고 질문을 한 부분은 눈알 이모지를 달았으니, 확인해주시면 감사하겠습니다!

이번에도 잘 부탁드립니다!

2024-05-07 14:22 UTC, syoun602 approved these changes
안녕하세요 명오 👋

리뷰 반영 잘해주셨네요. 이번 단계는 충분한 것 같아서 이만 머지해도 될 것 같습니다 💯
다음 단계에서 다시 뵐께요!

2024-05-07 14:22 UTC, syoun602 commented on src/main/java/roomescape/controller/ReservationController.java
> +        return ResponseEntity.noContent().build();
👍

2024-05-07 14:22 UTC, syoun602 commented on src/main/java/roomescape/handler/GlobalExceptionHandler.java
> +    }
공통된 예외 포맷이라면 여기서 메시지를 던져주어도 되겠네요!
```suggestion
    @ExceptionHandler(Exception.class)
    public ResponseEntity<Void> handleException() {
        return ResponseEntity.internalServerError()
            .body(new ExceptionDto("서버에 ~~."));
    }
```

2024-05-07 14:22 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationService.java
> +            throw new IllegalArgumentException("지난 날짜에는 예약할 수 없습니다.");
아니요 잘 작성해주셨어요 👍
말씀드렸던건 자바에 대한 예외였고 `HttpMessageNotReadableException` 이거는 스프링 프레임워크에서 제공하는 예외입니다 !

2024-05-07 14:22 UTC, syoun602 commented on src/main/java/roomescape/domain/RoomTheme.java
> +    private void validateBlank(String name, String description, String thumbnail) {
질문) 도메인에 추가적인 검증을 또 하는건 중복일까요?

2024-05-07 14:22 UTC, merged

2024-05-08 04:03 UTC, HyungHoKim00 commented on src/main/java/roomescape/domain/RoomTheme.java
> +    private void validateBlank(String name, String description, String thumbnail) {
도메인에서 추가적인 검증을 하는 것은 중복이 아니라고 생각합니다.
1. RequestDto에만 검증이 존재하면 Response 상황에서 객체를 생성할 때 검증할 수 없습니다.
2. 도메인에만 검증이 존재하면 빠르게 감지할 수 있는 잘못된 입력에 대해 더 큰 비용을 지불해야 합니다.