[1 - 3단계 방탈출 사용자 예약] 에버(손채영) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #35
Opened 2024-05-02 08:21 UTC by helenason

2024-05-02 15:39 UTC, her0807 requested changes
안녕하세요 에버 ~ 

오랜만이네요 ㅎㅎ 이렇게 또 만나게 되어서 반갑습니다.
간단한 코멘트 남겨두었어요. 확인해주시고 어려운 부분이 있다면 코멘트남겨주시고 
빠르게 리뷰 요청해주세요! 🙂

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Void> deleteReservation(@PathVariable("id") long id) {
long 과 Long 에 차이는 무엇일까요? ㅎㅎ

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +    @PostMapping("/reservations")
prefix 로 반복되는 reservations 을
`RequestMapping` 이라는 키워드를 사용하여  최상위로 올려볼까요?

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<Reservation>> getReservations() {
도메인을 바로 반환하고 있는데요~

response dto로 변환해볼까요?

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationController.java
> +        List<MemberReservationTimeResponse> response = reservationService.getMemberReservationTimes(date, themeId);
RequestParam 과 RequestBody 의 차이점은 무엇이고 각각 어떨때 쓰면 좋을까요?

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +        return ResponseEntity.ok().build();
Delete 를 했을 때 no content 라는 http statue 도 존재하는데요

HTTP 상태 코드의 종류와 사용 용도를 간단히 학습하고 설명해주시면 좋을 것 같습니다!

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/request/ReservationRequest.java
> +
Request 에서 검증을 하고 싶을 때 @valid  를 사용하여 엄청 간단하게 검증할 수 있어요~ ㅎㅎ

참고:https://ddol.tistory.com/59

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/request/ReservationTimeRequest.java
> +    }
이 부분은 어떤 용도로 만들어져있는건가요?

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/response/MemberReservationTimeResponse.java
> +    private boolean alreadyBooked;
[Boolean 변수에 적절한 이름을 지어주기](https://frogand.tistory.com/211)

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/controller/response/MemberReservationTimeResponse.java
> +    }
setter 보다 조금더 적절한 변수명을 지어줄까요?? 혹은 행위를 나태내도 좋고요.
지금 같은 경우는 boolean 값을 주입할 수 있는데 행위로 예약이 되면  상태를 true 로 변경하도록 행위로 표현할 수도 있을 것 같아요.

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
@ExceptionHandler(value = BadRequestException.class, DuplicatedException.class)

이렇게 여러개의 예외 클래스 타입을 하나로 핸들링할 수 있어요.

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +
에버 ~ 어떤 기준으로 예외 핸들링을 하고 있나요?

가장 중요한 RunTimeException 과 Exception 에 대한 핸들링도 필요할 것 같아요.
이 두가지의 차이점 아시나요? 현재 에버가 만들어준 커스텀 exception 들은 RunTimeException 을 상속받고 있는데요.

checked exception 과 unChecked 키워드로 함께 설명해주시면 좋을 것 같아요~

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/model/Reservation.java
> +public class Reservation {
에버 ~

검증 로직이 현재 requestDto 에 모두 존재하고 있는데요. 

이렇게 되면 도메인은 불완전한 상태로 만들어질 수 있어요. 

요청은 여러곳에서 올 수 있는데 그럴 때 마다 같은 request 로 오진 않으니까요. 

그래서 저는 검증 로직이 꼭 한곳에만 있어야한다고 하면 도메인에 존재해야한다고 생각해요. 에버는 어떠신가요?

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/model/Theme.java
> +    }
toString 은 어떤 용도로 쓰는 것일까요?

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/repository/ReservationTimeDAO.java
> +}
COUNT vs EXISTS

count 를 하게되면 데이터베이스에 존재하는 모든 데이터를 스캔하면서 성능저하가 발생할 수 있어요. 

현재 이 로직을 수행하는 이유가 기존에 존재하는지 유무를 판단하기 위한거라면 EXISTS 을 써보면 어떨까요?

참고 : https://hungseong.tistory.com/73

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
하나의 메서드가 너무 많은 책임을 가지고 있는 것 같아요. 

리팩터링을 해볼까요?

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/service/ReservationTimeService.java
> +public class ReservationTimeService {
여기도 전체적으로 리팩터링이 필요할 것 같습니다.

2024-05-02 15:39 UTC, her0807 commented on src/main/java/roomescape/service/ThemeService.java
> +    }
조건을 외부로 부터 주입 받아서 유지보수 하기 좋게 개발되었네요 👍🏻

2024-05-02 15:39 UTC, her0807 commented on src/main/resources/schema.sql
> +    name        VARCHAR(255) NOT NULL,
이름에 유니크 조건을 걸어볼까요?

2024-05-02 15:39 UTC, her0807 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +        jdbcTemplate.update("INSERT INTO reservation (name, date, time_id, theme_id) VALUES (?, ?, ?, ?)", "브라운", "2030-08-05", "1", "1");
데이터 생성 로직을 추출해볼까요?

2024-05-02 15:39 UTC, her0807 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +class ReservationControllerTest {
Controller test 는 인수테스트인가요 통합테스트 인가요?

어떤 목적으로 테스트 하셨는지 궁금합니다.

2024-05-02 15:39 UTC, her0807 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
데이터 격리 방식이 여러가지가 존재하는데 `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)` 이것으로 격리하신 이유도 궁금합니다 ㅎㅎ

2024-05-02 15:39 UTC, her0807 commented on src/test/java/roomescape/service/FakeReservationRepository.java
> +class FakeReservationRepository implements ReservationRepository {
고전파 방식으로 테스트를 하셨군요 ~ 👍🏻

어땠나요?

2024-05-02 15:39 UTC, her0807 commented on src/test/java/roomescape/controller/ReservationTimeControllerTest.java
> +
### 도메인 테스트에 대하여

현재 request 에만 검증로직이 있기 때문에 
중요한 도메인에 대한 테스트가 이뤄지지 않은 것 같아요. 

검증 로직을 도메인으로 내리게 된다면 테스트도 함께 작성해주시면 좋을 것 같습니다. 


추가로 에버는 어떤 경우에 `인수테스트`, `통합테스트`, `단위테스트를` 작성하시는지 궁금합니다.

2024-05-03 09:13 UTC, helenason commented on src/main/java/roomescape/controller/response/MemberReservationTimeResponse.java
> +    private boolean alreadyBooked;
클라이언트 코드에 제공된 필드명을 그대로 사용한 것이었습니다. 이전에는 시간에 쫓겨 고민해보지 않았지만, 다시 생각해보니 더욱 boolean다운 이름을 사용하는 게 좋겠네요!

2024-05-03 09:26 UTC, helenason commented on src/main/java/roomescape/repository/ReservationTimeDAO.java
> +}
H2의 exists 문법을 찾을 수가 없어서 count를 사용했는데 존재했었군요...🥹

2024-05-06 10:38 UTC, helenason commented on src/main/java/roomescape/controller/ReservationController.java
> +        List<MemberReservationTimeResponse> response = reservationService.getMemberReservationTimes(date, themeId);
두 어노테이션 모두 HTTP 요청 시에 클라이언트로부터 전송된 데이터를 바인딩하기 위해 사용됩니다. `@RequestBody`는 request의 바디에 JSON 형식으로 전송된 데이터를 추출할 때 사용됩니다. 보통 POST 메서드로 전송된 데이터를 추출할 때 사용되는 어노테이션입니다. 반면 `@RequestParam`은 URL을 통해 단일 파라미터로 전송된 데이터를 추출할 때 사용됩니다.

해당 API에서 `@RequestParam`을 선택했던 이유는, 정보를 저장하는 API가 아닌 조회하는 API였기 때문에 POST보다 GET 요청에 가깝다고 생각했습니다. 따라서 자연스레 `@RequestBody`가 아닌 `@RequestParam` 방식으로 데이터를 추출하도록 하였습니다!

2024-05-06 10:46 UTC, helenason commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +        return ResponseEntity.ok().build();
맞습니다.. 저번 미션에서 delete 역할의 API의 경우 no content 상태코드를 사용하기로 하였는데, 시간에 쫓겨 구현하는 과정에서 그 부분을 놓쳤네요 🥲

이 실수를 기회 삼아 http status에 대해 정리해보았습니다!

Http status는 http 요청에 대해 응답할 때 요청을 성공적으로 처리하였는지, 실패하였는지, 실패했다면 어떤 이유로 실패하였는지 등의 정보를 다양하게 담아낼 수 있는 규약입니다. 상태 코드의 종류는 대표적으로 아래와 같습니다.

### 성공: 2xx
- 200 ok: 요청을 성공적으로 처리하였을 때 반환합니다.
- 201 created: 성공적으로 리소스를 생성하였을 때
- 204 no content: 성공적으로 리소스를 삭제하였을 때

### 실패: 4xx
- 400 bad request: 해당 요청을 처리하는 API가 존재하지 않을 때? 즉 요청의 형식이 잘못되었을 때?
- 404 not found: 해당 요청에 해당하는 페이지가 없을 때?

### 서버 측 실패: 5xx
- 500: 서버 사이드에서 오류가 발생했을 때

(조사 중)

2024-05-06 11:13 UTC, helenason commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +        jdbcTemplate.update("INSERT INTO reservation (name, date, time_id, theme_id) VALUES (?, ?, ?, ?)", "브라운", "2030-08-05", "1", "1");
네! 테스트 코드를 정리하지 못해서 많이 복잡했었을텐데, 전체적으로 리팩터링하면서 `@BeforeEach`를 통해 매 테스트 전 데이터를 생성하도록 하였습니다!

2024-05-06 11:26 UTC, helenason commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +class ReservationControllerTest {
전체 API를 테스트하기 위한 코드입니다! 사용자의 입장으로 직접 프로그램을 실행해보는 테스트라고 보았습니다. 이전에는 인수 테스트에 대한 개념이 명확하지 않았어서 저는 이를 통합 테스트라고 생각했는데, 수달의 코멘트를 통해 인수 테스트에 대해 조사해보니 저의 컨트롤러 테스트는 인수테스트에 가깝다고 생각돼요!

### 인수 테스트
- 단위 테스트, 통합 테스트와는 달리 비즈니스 쪽에 초점을 둔다.
- 주로 API를 확인하는 방식으로 이루어진다.
- 소프트웨어 인수를 목적으로 하는 테스트이다. 소프트웨어를 인수하기 전, 명세한 요구사항(인수 조건)대로 잘 작동하는지 검증하는 테스트이다.
- 소프트웨어 내부 구조나 구현 방법을 고려하기보다는 실제 사용자 관점에서 테스트하는 경우가 많다. 따라서, 소프트웨어 내부 코드에 관심을 가지지 않는 블랙박스 테스트이다.

2024-05-06 12:02 UTC, helenason commented on src/test/java/roomescape/service/FakeReservationRepository.java
> +class FakeReservationRepository implements ReservationRepository {
저번 미션의 페어 코드로 이번 미션을 진행하였기 때문에 페어의 방식을 그대로 가져와 이어 구현하였습니다. 레벨1에서 구현해본 경험이 있던 터라 어색하지 않게 구현할 수 있었지만, 이번 미션에서는 조금 어렵게 느껴진 부분이 있었습니다.

이전 코드에서는 FakeRepository 객체의 생성자에서 테스트 케이스를 초기화하였습니다. 하지만 그러한 경우 몇가지 단점이 존재했습니다. 먼저, 모든 fake 객체 같은 값으로 초기화되기 때문에 테스트 케이스를 커스텀하기 어려웠습니다. 또한, 테스트 코드를 작성하면서 테스트 케이스를 확인해야할 때마다 다른 클래스의 코드를 확인해야하는 작업이 번거롭게 다가왔습니다. 따라서 이번 리팩터링 과정에서 테스트 데이터를 주입하는 로직을 외부로 추출하였습니다. 페어와도 이야기하였으나 시간 상 진행하지 못했던 작업이라 혼자 진행해보았습니다!

2024-05-06 13:34 UTC, helenason commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<Void> deleteReservation(@PathVariable("id") long id) {
long은 원시 타입으로, null을 가질 수 없습니다. 반면에 Long은 참조 타입 객체로, null을 저장할 수 있습니다.

PathVariable의 id 타입을 long과 Long으로 설정하여 null을 입력해보았습니다. 두 경우 모두 400 또는 405 에러 코드를 반환함을 확인했습니다. 즉, 저의 코드의 경우 id 변수를 어떤 타입으로 설정하든 id 자리에 null 값이 입력되면 해당 컨트롤러를 호출할 수 없음을 알게 되었습니다. 따라서 저의 코드는 null 값이 입력되면 해당 컨트롤러 자체가 호출되지 않기에 큰 문제가 없다고 판단했습니다.

다른 케이스를 테스트해보기 위해 `@PathVariable`의 required 옵션을 false로 설정해보았습니다. 그럼에도 엔드포인트를 "/{id}"로 지정해두었기에 id가 null인 경우 마찬가지로 해당 컨트롤러가 동작하지 않았습니다.

다음으로, required 옵션은 계속 false로 둔 채, 엔드포인트를 ""와 "/{id}" 두가지로 설정해보았습니다. 이 경우 id 자리에 null 값이 입력되면 long과 Long의 차이에 따라 아래와 같은 차이가 드러났습니다.

- 참조 타입 Long의 경우: NullPointerException 예외 발생
<img width="500" alt="스크린샷 2024-05-06 22 24 04" src="https://github.com/woowacourse/spring-roomescape-member/assets/88581911/fd909cb4-a44a-4ed7-b1be-4d8ec043cd6c">

- 원시 타입 long의 경우: IllegalStateException 예외 발생
<img width="500" alt="스크린샷 2024-05-06 22 24 43" src="https://github.com/woowacourse/spring-roomescape-member/assets/88581911/4e4c7f6e-27a7-43e5-9416-e5257eba8f02">

참조 타입의 경우, null을 저장할 수 있기 때문에 개발자가 처리할 수 있는 범위 내에 있고, 원시 타입의 경우 null 값 저장 자체가 불가하기 때문에 개발자가 처리할 수 있는 범위 밖에 있다고 생각합니다.

따라서, 현재 저의 코드는 타입 선택에 따라 큰 변화가 없겠으나, 이후에는 그래도 개발자의 통제 하에 프로그램이 진행될 수 있도록 참조 타입 Long으로 설정하는 것이 좋아보입니다!

(수정 중)

2024-05-06 15:43 UTC, helenason commented on src/main/java/roomescape/controller/request/ReservationTimeRequest.java
> +    }
기본 생성자가 존재하지 않을 경우 아래와 같은 에러가 발생합니다.
> com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `roomescape.controller.request.ReservationTimeRequest` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

파라미터가 하나인 생성자의 경우에는 기본 생성자를 선언해주어야만 Jackson이 데이터를 문제없이 바인딩할 수 있습니다.

더 자세한 내용 추후에 추가하도록 하겠습니다!

2024-05-06 15:48 UTC, helenason commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +
Checked exception은 컴파일 시점에 발생하는 에러이고, unchecked exception은 런타임 시점에 발생하는 에러입니다. Checked exception을 처리하지 않으면 컴파일 자체가 되지 않으며, unchecked exception은 처리하지 않아도 컴파일은 성공합니다.

저의 코드에서 모든 예외에 대해 상속받은 RuntimeException은 unchecked exception이기 때문에 컴파일에는 문제가 없으나 프로그램 실행 중 마주하게 되면 예기치 못한 버그가 발생할 수 있습니다. 따라서 모든 예외에 대해 핸들링해주는 것이 좋겠네요!

2024-05-06 16:01 UTC, helenason commented on src/main/java/roomescape/model/Theme.java
> +    }
디버깅 및 에러 로깅에 사용된 메서드입니다! 이번 미션에서 유독 자주 사용했습니다. 필요에 의한 메서드만 선언해두었는데, 앞으로 계속 사용할 것 같아 전체적으로 선언해두려 합니다.

2024-05-06 18:41 UTC, helenason commented on src/main/java/roomescape/model/Reservation.java
> +public class Reservation {
도메인이 아닌 DTO에 검증 로직을 추가했던 이유는, 불완전한 객체(어차피 예외를 반환할 객체)를 서비스와 레포지토리 계층까지 가져가고 싶지 않았어요. 불필요한 흐름이라고 생각했거든요! 그렇기에 컨트롤러 계층에서 최대한 필터링하려고 했습니다.

하지만 수달의 의견에도 동의해요. 도메인 생성 과정에서 검증을 해야 더욱 무결한 도메인이 되는 것이니까요. 따라서 저는 DTO에서 가벼운 검증을 통해 빠르게 필터링할 수 있는 요청을 걸러내고, 도메인에서 또 다시 검증함으로써 더욱 무결한 객체가 되도록 하였어요!

추가로 각 계층이 할 수 있는 검증의 책임을 계층에 맞게 부여하였습니다!

2024-05-07 02:07 UTC, helenason commented on src/main/java/roomescape/controller/request/ReservationRequest.java
> +
오! 되게 간단하게 검증할 수가 있었네요. 이후에 검증 로직이 너무 많아져서 관리하기 힘들 때 한번 사용해보겠습니다!

2024-05-07 02:09 UTC, helenason commented on src/main/java/roomescape/service/ThemeService.java
> +    }
네 맞습니다 ㅎㅎ 신경썼던 부분이었어요. 감사합니다!

2024-05-07 04:07 UTC, helenason commented on src/main/resources/schema.sql
> +    name        VARCHAR(255) NOT NULL,
네, theme의 name 외에도 reservation_time의 start_at과 reservation의 {date, time_id, theme_id}에 대해서도 UNIQUE 조건 추가해주었습니다!

2024-05-07 06:19 UTC, helenason commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
`@DirtiesContext`를 사용했던 이유는 하나의 테스트 당 독립적인 스프링 서버를 띄우기 위함이었습니다. 그러나 더 본질적으로, '왜 새로운 스프링 서버를 띄워야 하지?'에 대해 고민했고, 데이터베이스를 초기화하기 위함이라고 결론내렸습니다.

저희의 코드는 `@BeforeEach`에서 truncate 명령문을 통해 테이블의 데이터를 초기화하고 있었습니다. `@DirtiesContext`를 통해 DB 풀을 새로 주입 받음과 동시에 테이블을 초기화하는 로직까지 존재했습니다. 불필요하게 데이터베이스를 두 번이나 리셋하는 상황이었습니다...! 이런 줄도 모르고 테스트 속도만 느려졌었네요 ㅎㅎ

리팩터링하는 과정에서 이 외에도 `@DirtiesContext`에 대해 알아보고 싶던 내용이 있었고, 관련해서 [글](url)을 적어보았습니다!

결론은, `@DirtiesContext` 어노테이션을 사용하는 방식과 truncate 명령문을 통해 데이터베이스 테이블의 데이터를 제거하는 방식 중 선택해야했습니다. 두 경우에 대해 `@DirtiesContext`가 약 1.5배 더 느린 속도로 동작했기 때문에 `@DirtiesContext` 어노테이션을 삭제하기로 하였습니다!

2024-05-07 06:20 UTC, helenason commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
`@DirtiesContext`를 사용했던 이유는 하나의 테스트 당 독립적인 스프링 서버를 띄우기 위함이었습니다. 그러나 더 본질적으로, '왜 새로운 스프링 서버를 띄워야 하지?'에 대해 고민했고, 데이터베이스를 초기화하기 위함이라고 결론내렸습니다.

저의 코드는 `@BeforeEach`에서 truncate 명령문을 통해 테이블의 데이터를 초기화하고 있었습니다. `@DirtiesContext`를 통해 DB 풀을 새로 주입 받음과 동시에 테이블을 초기화하는 로직까지 존재했습니다. 불필요하게 데이터베이스를 두 번이나 리셋하는 상황이었습니다...! 이런 줄도 모르고 테스트 속도만 느려졌었네요 ㅎㅎ

리팩터링하는 과정에서 이 외에도 `@DirtiesContext`에 대해 알아보고 싶던 내용이 있었고, 관련해서 [글](url)을 적어보았습니다!

결론은, `@DirtiesContext` 어노테이션을 사용하는 방식과 truncate 명령문을 통해 데이터베이스 테이블의 데이터를 제거하는 방식 중 선택해야했습니다. 두 경우에 대해 `@DirtiesContext`가 약 1.5배 더 느린 속도로 동작했기 때문에 `@DirtiesContext` 어노테이션을 삭제하기로 하였습니다!

2024-05-07 06:37 UTC, helenason commented on src/test/java/roomescape/controller/ReservationTimeControllerTest.java
> +
사실 저는 테스트 코드를 작성하기 전에 인수테스트인지 통합테스트인지 단위테스트인지를 결정하고 코드를 작성하진 않는 것 같아요. 하나의 클래스에 대한 테스트 코드를 작성하고, 해당 로직이 순수 저의 코드를 테스트하면 단위 테스트, 직접 개발한 코드가 아닌 데이터베이스와 같은 외부 라이브러리에 의존하는 코드를 테스트한다면 통합 테스트, 사용자의 입장에서 서비스의 전체적인 흐름을 테스트하는 코드라면 인수 테스트라고 분류하는 것 같아요!

2024-05-07 08:59 UTC, helenason commented
안녕하세요 수달 🦦

코드 전체적으로 리팩터링하고 싶은 부분과, 깊이있게 학습해보고 싶었던 개념들이 많이 있어 조금 늦게 리뷰 요청 드립니다.

DAO가 오직 하나의 테이블에만 의존할 수 있게 하고 싶어 join 쿼리를 모두 제거하고, 관련 책임을 repository 계층에 위임하였습니다.

이 외에도 여러 변경 사항이 있어요. 이번 리뷰도 잘 부탁드려요!

2024-05-07 14:14 UTC, her0807 approved these changes
> DAO가 오직 하나의 테이블에만 의존할 수 있게 하고 싶어 join 쿼리를 모두 제거하고, 관련 책임을 repository 계층에 위임했습니다!

DB 에서 데이터를 조인 하여 가져오는 것과 어플리케이션 레벨에서 조립하는 것과 어떤 장단점이 있나요?
성능상 이점이 어떤 상황에 어떤 것이 더 큰지, 의존성을 분리해야겠다 느낀 문제는 무엇이었는지 같이 얘기해보면 좋을 것 같아요! 

다음 스텝을 개발하시면서 같이 고민해주시고 공유해주시면 좋을 것 같습니다 :)
요구사항이 모두 만족된 것 같아 이만 머지하겠습니다.
수고하셨어요 에버 :)

2024-05-07 14:14 UTC, merged