[1 - 3단계 방탈출 사용자 예약] 카고(정민호) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #38
Opened 2024-05-02 08:24 UTC by devhoya97

작성예정입니다.

2024-05-02 09:07 UTC, devhoya97 commented on src/main/java/roomescape/controller/reservation/ThemeController.java
> +        if (limit != null) {
Controller에서 URL 파라미터가 들어왔는지 분기처리하고 있습니다. 왜냐하면 컨트롤러는 이미 URL에 따라 분기처리하는 역할을 수행하고 있기 때문에 URL 파라미터에 따라 분기처리하는 것도 컨트롤러의 역할이라고 생각했기 때문입니다.

이에 대한 범블비의 생각은 어떤지 궁금해요!

2024-05-02 12:10 UTC, ddaaac requested changes
안녕하세요 카고 👋 

구현 잘 해주셨습니다

몇 가지 코멘트 남겼으니 확인해주세요.

2024-05-02 12:10 UTC, ddaaac commented on src/main/java/roomescape/service/ReservationService.java
> +                .filter(reservation -> reservation.getDate().isBefore(LocalDate.now()))
reservation.isRecent7Days() 등의 표현과는 어떤 차이가 있을까요?

2024-05-02 12:10 UTC, ddaaac commented on src/test/java/roomescape/controller/reservation/ReservationControllerTest.java
> +    void doesNotContainJdbcTemplate() {
이 테스트는 어떤 의미가 있나요?

2024-05-04 06:39 UTC, devhoya97 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    private final Boolean alreadyBooked;
사용자가 예약하려는 날짜와 테마를 선택했을 때, 이미 예약된 시간은 클릭 버튼이 disable되어 나타나야 합니다. 위 요구사항을 인지하지 못하고 PR을 제출하여 늦게나마 이와 관련된 기능 구현하였습니다..!

이 때 `alreadyBooked` 필드는 사실 DB table이 컬럼으로 갖지 않지만 `ReservationTime`이라는 도메인 객체가 필드로 갖고, 이에 맞게 DTO인 `ReservationTimeResponse`도 위 필드를 갖도록 변경했어요. 비록 이 필드가 필요 없는 요청도 존재하지만, `id`와 마찬가지로 특정 필드가 null값을 가지고 객체가 생성되는 경우가 생길지라도 크게 문제가 없는 것 같다고 생각했기 때문입니다. 

위 생각이 적절해보이나요? 아니면 새로운 클래스를 등장시키는 게 좋을까요? 범블비의 생각이 궁금합니다!

2024-05-04 08:43 UTC, devhoya97 commented on src/main/java/roomescape/service/ReservationService.java
> +    public List<ReservationResponse> findPopularThemes(Long limitCount) {
처음 생각했을 땐 `인기 있는 테마`는 `현재까지 특정 테마가 몇 번이나 예약됐는가?`를 알아야 하므로 결국 `현재까지의 예약`에 대해 알아야 하고 따라서 예약 정보를 알고 있는 `ReservationService`에게 묻는게 적절하다고 생각했습니다.

그런데 다시 생각해보니 `Controller` 입장에서는 결국 `테마 목록을 가져오는 일`이므로 `ThemeService`에게 묻는게 훨씬 직관적인 것 같아요. 반영하였습니다!

2024-05-04 08:59 UTC, devhoya97 commented on src/main/java/roomescape/controller/reservation/ThemeController.java
> +        if (limit != null) {
현재 인기TOP10 테마를 가져오기 위한 API는 `/themes?limit=10`입니다. 

페어와 고민했던 내용 중에 `파라미터가 늘어나면 null을 체크하는 분기 로직이 계속 추가될 것이고 한 메서드가 너무 길어지지 않을까?` 생각했어요. 따라서 `/themes/trending?limit=10`과 같이 API를 만들까 고민했습니다. 

그렇게 하면 나중에 공포, 코믹 등의 카테고리 분류가 추가돼도 `/themes/category`, `/themes/category/trending?limit=10`과 같이 응용이 가능할 것 같아서요!

혼자 더 고민해보니 위와 같은 API가 더 확장성에 유리한 것 같은데 어떻게 생각하시나요 ?!

2024-05-04 09:19 UTC, devhoya97 commented on src/main/java/roomescape/service/ReservationService.java
> +                .filter(reservation -> reservation.getDate().isBefore(LocalDate.now()))
`LocalDate.now()`를 활용해서 해당 메서드 내에선 현재의 날짜를 하나로 특정해 로직을 수행하는게 의도였는데, `LocalDate.now()`의 호출이 두 번 일어나서 언급해주신 경우에는 두 번째 줄에서 사용하는 날짜가 다음 날이 되겠네요. 생각해보지 못했는데 중요한 포인트인 것 같습니다..!

다른 코멘트를 반영하는 과정에서 메서드는 조금 변경됐는데 핵심 포인트는 변하지 않은 같아요. 아래와 같이 반영하였습니다!
```java
        LocalDate now = LocalDate.now();
        LocalDate trendingStatsStart = now.minusDays(7);
        LocalDate trendingStatsEnd = now.minusDays(1);
```

2024-05-04 09:45 UTC, devhoya97 commented on src/main/java/roomescape/repository/reservation/ReservationH2Repository.java
> +            throw new IllegalArgumentException("과거 시간은 예약할 수 없습니다.");
`Repository`에서 검증하도록 하는 현재 코드는 `Reservation` 객체의 상태를 getter로 꺼내와서 대신 로직을 수행해주는 것 같아요. 캡슐화, 책임분리 관점에서 문제가 있는 것 같습니다. 또한 과거 시간이나 중복 예약의 경우 예약을 거부하는 로직은 비즈니스 로직에 가까운 것 같아서 `Repository`보단 `Service`가 갖도록 변경했어요.

따라서 `ReservationService`는 `Reservation`을 통해 과거 시간인지 물어보고, `Reservation`은 `ReservationTime`에게 연쇄적으로 물어보는 형태가 되도록 리팩토링했습니다!

2024-05-04 13:09 UTC, devhoya97 commented on src/main/java/roomescape/controller/reservation/GlobalExceptionHandler.java
> +    }
`@ExceptionHandler`에서 찾지 못한 예외는 스프링 프레임워크 내에 내장된 규칙에 따라 예외를 처리할 것 같아요.

혹시 어떤 경우를 말씀하시는 건가요?!

2024-05-04 14:30 UTC, devhoya97 commented on src/main/java/roomescape/controller/reservation/GlobalExceptionHandler.java
> +        return e.getMessage();
보안상에 문제가 될 수 있는 정보들까지 의도치않게 전달될 수도 있을 것 같아요.

유저에게 전달할 메시지가 담긴 예외는 `UserException`이라는 커스텀예외를 던지도록 변경했습니다!

2024-05-04 14:39 UTC, devhoya97 commented on src/main/java/roomescape/service/ReservationService.java
> +                .filter(reservation -> reservation.getDate().isBefore(LocalDate.now()))
이 부분도 `Reservation`에게 직접 물어봐야 캡슐화/책임분리를 지킬 수 있을 것 같아요.

`인기 테마`를 가져오는 로직을 SQL문으로 처리하도록 변경하면서 위 로직은 제거되었습니다! 아마 로직을 유지했다면 `reservation.isDateBetween(start, end)`와 같은 메시지를 던지도록 변경했을 것 같아요.

2024-05-04 14:42 UTC, devhoya97 commented on src/test/java/roomescape/controller/reservation/ReservationControllerTest.java
> +    void doesNotContainJdbcTemplate() {
LMS에 학습용도로 적혀있던 테스트를 그대로 가져와서 쓰다가 제거를 미처 못했네요..! 삭제했습니다!

2024-05-05 06:28 UTC, devhoya97 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
테스트 충돌 문제는 테스트용 `schema.sql`을 따로 두고 테이블을 생성하는 쿼리에서 `IF NOT EXISTS` 를 활용해 해결하였습니다!

그 후 아래 사진과 같이 `ReservationServiceTest`만 `NONE`으로 해두고 나머지는 기존의 `DEFINED_PORT`를 유지하며 테스트를 돌렸더니 `ReservationTimeService`에서 문제가 발생했어요. 아마 `ReservationServiceTest`가 사용하던 `ApplicationContext`가 달라져서 문제가 생긴 것 같은데 혼자 오랜시간 고민해봤는데도 잘 모르겠네요...! 혹시 조언 부탁드려도 될까요🥲
<img width="1438" alt="image" src="https://github.com/woowacourse/spring-roomescape-member/assets/146502065/5766faf6-742a-40ec-a36c-bafcc91c39dd">

2024-05-07 00:11 UTC, devhoya97 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
`DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD`의 `BEFORE -> AFTER`로 바꾸니 해결되네요! 

![DirtiesContext](https://github.com/woowacourse/spring-roomescape-member/assets/146502065/bed25b56-2967-4788-a675-34ed8b5ecea6)

다만 `@DirtiesContext`가 테스트 코드 수행 시간에 악영향을 미치므로 이를 사용하지 않고도 테스트 할 수 있으면 좋겠네요..!

2024-05-07 03:58 UTC, ddaaac requested changes
안녕하세요 카고 👋 
리뷰가 늦어져서 죄송합니다 🙇 

리뷰 반영 잘 해주셨습니다.

몇 가지 코멘트 남겼으니 확인해주세요.

2024-05-07 03:58 UTC, ddaaac commented on src/main/java/roomescape/domain/Name.java
> +public class Name {
어떤 Name인지 명시하면 좋을 것 같아요.

2024-05-07 03:58 UTC, ddaaac commented on src/main/java/roomescape/service/ThemeService.java
> +        }
멀티 스레드 환경에서 같은 이름을 add하는 요청이 여러번 빠르게 올 경우 이 검증 로직을 통과할 수 있습니다.
이런 경우는 db에 unique 인덱스를 넣어줄 수 있을 것 같네요.

이번 미션에서 고려할만한 내용은 아니지만 언젠가 한번쯤은 겪을 수 있는 에러라 서비스 단의 검증 로직은 항상 이런 부분을 생각하면 좋을 것 같아서 남긴 코멘트입니다.

2024-05-07 03:58 UTC, ddaaac commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +ReservationServiceTest {
😄

2024-05-07 03:58 UTC, ddaaac commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
오호 스스로 문제를 해결하셨네요 👍 
이런 트러블 슈팅 경험은 앞으로도 정말 많은 도움이 될 거에요.
글로 예쁘게 정리해주셔서 저도 어떤 문제였고 어떻게 해결했는지 알기도 편했구요.

[테스트 db 초기화](https://velog.io/@junho5336/%ED%85%8C%EC%8A%A4%ED%8A%B8%EB%B3%84%EB%A1%9C-DB-%EC%B4%88%EA%B8%B0%ED%99%94%ED%95%98%EA%B8%B0) 방법은 여러가지가 있습니다. 이런저런 방법들 모두 고민해보시면 좋을 것 같네요.

2024-05-07 03:58 UTC, ddaaac commented on src/main/java/roomescape/controller/reservation/ThemeController.java
> +        if (limit != null) {
경로에 대한 정의를 명확히 할 수 있다는 점에서 지금 방법도 좋네요.
다만 페이지네이션 정도는 일반 API에서도 흔히 제공하는 기능이란 걸 생각하면 limit 정도는 기존과 같이 받고, 나중에 파라미터가 추가되면 그 다음 단계를 고민해도 되지 않을까 싶긴합니다. (물론 지금 방식도 좋습니다. 이유도 명확하구요)

2024-05-07 03:58 UTC, ddaaac commented on src/main/java/roomescape/domain/ReservationTime.java
> +    private final Boolean alreadyBooked;
- 자바는 nullable에 대한 처리가 없기 때문에 nullable한 필드가 존재한다면 개발자는 항상 이 ReservationTime#alreadayBooked 필드가 null인지 아닌지를 체크해야합니다. nullable한 필드는 제거해주세요.
- Response DTO가 alreadyBooked를 갖는 건 어색하지 않아보이는데요, ReservationTime이 이 필드를 가져야할 이유가 있을까요?

2024-05-07 03:58 UTC, ddaaac commented on src/main/java/roomescape/controller/reservation/GlobalExceptionHandler.java
> +    }
GlobalExceptionHandler에 정의되지 않은 예외입니다. 예를 들어 RuntimeException, Exception 등등이 있겠네요.

2024-05-07 03:58 UTC, ddaaac commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
https://github.com/woowacourse/spring-roomescape-admin/pull/187#discussion_r1582761869

2024-05-07 03:58 UTC, ddaaac commented on src/test/java/roomescape/repository/theme/ThemeH2RepositoryTest.java
> +        assertThat(count).isEqualTo(INITIAL_THEME_COUNT - 1);
직접 쿼리문을 사용하는 테스트에 대해서도 생각해보시면 좋을 것 같네요.
findById를 이용해서 테스트를 할 수도 있지 않을까요?

2024-05-07 04:20 UTC, devhoya97 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +ReservationServiceTest {
헉! 빈라인 삭제했습니다. 커밋하기 전에 파일의 변경사항을 더 꼼꼼하게 확인해야겠네요..!

2024-05-07 05:32 UTC, devhoya97 commented on src/main/java/roomescape/controller/reservation/ThemeController.java
> +        if (limit != null) {
인지하지 못하고 있었는데 여기서 limit이 페이지네이션이란 개념이었군요!

말씀해주신 것처럼 현재는 테마를 limit하는 기준이 `인기` 밖에 없으므로 사실상 단순 페이지네이션이라고 볼 수 있고, 따라서 `/themes?limit=10`이라는 표현도 무리가 없겠네요!

2024-05-07 05:50 UTC, devhoya97 commented on src/main/java/roomescape/controller/reservation/GlobalExceptionHandler.java
> +    }
아하 정의하지 않은 예외가 발생하면 클라이언트 입장에서는 어떤 예외가 발생했는지에 대한 구체적인 정보 없이 500 상태 코드를 받게 될 것 같아요.

```java
    @ExceptionHandler(Exception.class)
    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
    public String handleException() {
        return "서버에서 예기치 않은 오류가 발생했습니다.";
    }
```
위와 같은 코드를 추가하는 것 정도밖에 생각이 나질 않는데 어떻게 대응하는게 최선인가요?!

2024-05-07 09:10 UTC, devhoya97 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    private final Boolean alreadyBooked;
> Response DTO가 alreadyBooked를 갖는 건 어색하지 않아보이는데요, ReservationTime이 이 필드를 가져야할 이유가 있을까요?

사실 Response DTO가 alreadyBooked을 갖는 방법을 먼저 떠올렸지만, `ReservationTimeH2Repository`가 domain에만 의존하고 DTO에는 의존하게 만들고 싶지 않아서(만약 DTO가 수정되어도 `Repository`까지 영향을 미치지 않기 위해) domain의 필드로 alreadyBooked를 추가하는 방법으로 진행했어요!

그런데 코멘트를 보고 다시 생각해보니 도메인이 nullable한 필드를 갖는건 피해야겠네요!

우선 추가적인 도메인 객체 생성 없이 `findAllWithAlreadyBooked` 메서드의 반환 값을 `Map<ReservationTime, Boolean>`으로 만들었습니다. 만들다보니 그냥 `alreadyBooked`필드를 갖는 도메인 객체를 새로 만들걸 그랬나? 라는 생각도 드는데 범블비는 어떻게 생각하시나요?!

2024-05-07 09:50 UTC, devhoya97 commented on src/main/java/roomescape/domain/Name.java
> +public class Name {
예약자명과 테마명을 별 생각없이 같이 사용하고 있었네요 ..! `ReservatorName`과 `ThemeName`으로 분리했습니다!

2024-05-07 10:19 UTC, devhoya97 commented on src/test/java/roomescape/repository/theme/ThemeH2RepositoryTest.java
> +        assertThat(count).isEqualTo(INITIAL_THEME_COUNT - 1);
맞습니다!! 사실 `findById`를 이용하는 방법을 먼저 생각해봤어요.

그런데 생각해보니 이 테스트는 `delete`가 잘 작동하는지 테스트하는 것인데, `findById`의 동작이 보장되어야만 테스트할 수 있다는 사실이 조금 거슬렸어요. 그래서 직접 쿼리문을 사용했는데요, 혹시 이에 대한 범블비의 생각은 어떤가요?!

2024-05-08 04:27 UTC, devhoya97 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
좋은 자료 감사합니다! 주변에 mock이란 걸 쓰는 크루들도 있는 것 같길래 궁금했는데 대략적으로 사용 이유를 이해할 수 있었어요!

> 저는 최대한 도메인 영역에 로직을 두려고 합니다. 슬라이스나 통합 테스트가 최대한 필요해지지 않게요.

이 부분이 핵심인 것 같군요! [앞서 이야기 나눈](https://github.com/woowacourse/spring-roomescape-member/pull/38#discussion_r1589943924) 부분에서 도메인이 로직을 가져야 하는 이유 중 하나로 추가해도 될 것 같네요!

2024-05-08 05:00 UTC, devhoya97 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT)
좋은 자료 감사합니다!

> `@SQL` 어노테이션을 사용하여 매 테스트 실행 전 SQL 스크립트를 실행하여 테이블을 다시 만들 수 있다.

공유해주신 글을 보니 매 테스트메서드마다 테이블을 DROP 시키면 격리성을 쉽게 얻을 수 있을 것 같아 `@DirtiesContext` 대신 사용해봤더니 테스트 시간이 훨씬 빨라졌네요! 기회가 되면 테스트별 DB격리를 위해 다른 방법들도 하나씩 사용해보겠습니다 !!

2024-05-08 05:22 UTC, devhoya97 commented on src/main/java/roomescape/controller/reservation/GlobalExceptionHandler.java
> +        return e.getMessage();
클래스명이 너무 불명확한 것 같아서, 케이스에 따라 아래와 같이 나눠보았습니다!

![그림](https://github.com/woowacourse/spring-roomescape-member/assets/146502065/0d50f6a9-e0d6-47b7-b23a-27b271879b2d)

2024-05-08 13:19 UTC, ddaaac approved these changes
안녕하세요 카고 👋 

리뷰 반영 잘 해주셨습니다.

다음 단계 진행해주세요~

2024-05-08 13:19 UTC, ddaaac commented on src/main/java/roomescape/domain/ReservationTime.java
> +    private final Boolean alreadyBooked;
조금 쿼리가 복잡해진다는 생각이 드네요. date, theme에 해당하는 reservation들을 찾아오고 그 다음에 해당 예약들의 time id를 기반으로 로직을 짜서 ResponseDto에 넣어줄 수 있지 않을까요?

2024-05-08 13:19 UTC, ddaaac commented on src/main/java/roomescape/service/ThemeService.java
> +        }
https://github.com/woowacourse/spring-roomescape-member/pull/33#discussion_r1593974872

2024-05-08 13:19 UTC, ddaaac commented on src/test/java/roomescape/repository/theme/ThemeH2RepositoryTest.java
> +        assertThat(count).isEqualTo(INITIAL_THEME_COUNT - 1);
그렇게 생각하면 jdbcTemplate의 동작이 보장돼야 하지 않을까 싶기도 하네요.
적당히 테스트를 하면 되지 않을까 싶어요.

2024-05-08 13:19 UTC, merged

2024-05-09 02:58 UTC, devhoya97 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    private final Boolean alreadyBooked;
그렇네요. 무의식적으로 `ReservationTimeService`는 `ReservationTimeH2Repository`에만 최대한 의존하는 방식으로 구현하고 싶은 것 같아요. 외래키 사용으로 인해 `ReservationTimeH2Repository`에서도 충분히 다른 `reservation`테이블에 접근이 가능해서 더 그랬던 것 같습니다.

말씀해주신 것처럼 쿼리가 복잡하다는 것 자체가 해당 쿼리를 수행하는 메서드가 복잡한 일을 수행하고 있다는 걸 뜻하는 것 같아요. 기존 `findAllWithAlreadyBooked` 메서드는 예약 시간을 가져오되 이미 예약되어 있는지에 대한 여부를 함께 가져오라는 의미를 갖는데 이는 말씀해주신 것처럼 `date, theme에 해당하는 예약을 확인해줘` + `예약 여부를 기준으로 time을 분류해줘` 라는 최소단위업무로 분리하는게 좋을 것 같아요.

아래와 같이 반영하였습니다! 
```java
    public List<ReservationTimeResponse> findTimesWithAlreadyBooked(LocalDate date, Long themeId) {
        List<Long> alreadyBookedTimeIds = reservationRepository.findAlreadyBookedTimeIds(date, themeId);

        return reservationTimeRepository.findAll()
                .stream()
                .map(reservationTime -> new ReservationTimeResponse(
                        reservationTime,
                        alreadyBookedTimeIds.contains(reservationTime.getId())
                        )
                )
                .toList();
    }
```

효율적인 테스트를 위해 도메인에게 최대한 로직을 부여하기 위해서 `ReservationTimes`라는 일급컬렉션을 만들고 아래와 같은 메서드를 갖도록 하여 `Service`단의 로직을 최대한 줄이는 것도 좋지 않을까? 생각해봤는데 이 생각은 너무 과할까요?
```java
List<ReservationTime> getAlreadyBookedTimes(List<Long> alreadyBookedTimeIds);
List<ReservationTime> getAvailableTimes(List<Long> alreadyBookedTimeIds);
```

2024-05-09 05:12 UTC, devhoya97 commented on src/main/java/roomescape/service/ThemeService.java
> +        }
말씀해주신게 아래와 같은 형태가 맞을까요?!

```java
public ThemeResponse addTheme(ThemeAddRequest themeAddRequest) {
    validateDuplicatedName(themeAddRequest);
    try {
        Theme theme = themeRepository.save(themeAddRequest.toTheme());
        return new ThemeResponse(theme);
    } catch (DuplicateKeyException e) {
        throw new DuplicationException("이미 존재하는 테마 이름입니다.");
    }
}

private void validateDuplicatedName(ThemeAddRequest themeAddRequest) {
    if (themeRepository.hasTheme(new ThemeName(themeAddRequest.name()))) {
        throw new DuplicationException("이미 존재하는 테마 이름입니다.");
    }
}
private void validateDuplicatedName(ThemeAddRequest themeAddRequest) {
    if (themeRepository.hasTheme(new ThemeName(themeAddRequest.name()))) {
        throw new DuplicationException("이미 존재하는 테마 이름입니다.");
    }
}
```

2024-05-09 05:21 UTC, devhoya97 commented on src/test/java/roomescape/repository/theme/ThemeH2RepositoryTest.java
> +        assertThat(count).isEqualTo(INITIAL_THEME_COUNT - 1);
동의합니다 ! 
`ThemeH2Repository`에는 `findById` 메서드가 구현되어 있어서 `delete` 테스트 시 이를 활용하는 방식으로 반영하였습니다. 다만 `ReservationH2Repository`에는 `findById`메서드가 구현되어 있지 않아서 기존 코드를 유지했습니다!