[1 - 3단계 방탈출 사용자 예약] 위브(김기범) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #4
Opened 2024-05-02 06:43 UTC by jimi567

.

2024-05-02 15:57 UTC, lxxjn0 requested changes
안녕하세요, 위브! 레벨1 때 만나고 다시 만나뵙네요 ㅎㅎㅎ 성장한 위브의 모습 기대해보겠습니다 :)

미션이 이전 단계에 비해서 조금은 더 복잡해졌는데 어플리케이션 동작 시에 발생할 수 있는 다양한 오류 상황에 대해서 꼼꼼하게 방어로직을 작성해주신 것 같아요 👍🏼 이번 리뷰에서는 프로덕션 코드만 우선 리뷰를 남겨봤는데 한번 참고하셔서 피드백 반영 부탁드릴게요!

추가로 서비스 별로 다른 도메인에 대한 Repository를 의존하면서 동일한 기능을 중복해서 사용하는 경우나 또는 이미 구현된 기능을 Repository 의존으로 인해 재구현하는 경우도 있는 것 같아요. 한번 Service를 의존해서 사용하는 것이 어떨지? 그리고 서비스를 의존한다는 방식에 대해서 어떠한 생각을 가지고 있는지도 한번 이야기해보면 좋을 것 같아요!

남겨주신 질문도 제가 남긴 리뷰 중 참고하실만한 아티클 링크를 남겨두었어요. 해당 글을 읽어본 후 다시 이야기해보면 더 좋을 것 같습니다.

마지막으로 에러 상황에 대해서 AdviceController로 잘 처리했는데 정작 프론트에서는 console 로그가 아닌 이상은 파악이 어려운 경우가 대부분인 것 같습니다. 결국 사용자에게 어떠한 이유로 실패를 했는지 보여주는 것 또한 API에서의 예외 처리가 가지는 장점이 아닐까 싶습니다. 발생한 예외에 대해서 사용자가 인지할 수 있도록 프론트 코드를 조금 수정해보는 것도 좋을 것 같습니다!

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/dto/app/ReservationAppRequest.java
> +public record ReservationAppRequest(String name, String date, Long timeId, Long themeId) {
Request를 두가지로 나눈 이유가 무엇인가요? 선택 기준이 있다면 나누는 것과 나누지 않는 것에는 어떠한 트레이드 오프가 존재하나요?

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/exception/DuplicatedReservationException.java
> +public class DuplicatedReservationException extends RuntimeException {
커스텀 예외에 대해서는 아래의 글을 한번 참고해보면 좋을 것 같습니다. 그런 이후 코드에 작성된 예외에 대해서 다시 한번 생각해보고 이야기 나눠보면 좋을 것 같아요 :) 지금 바로 저의 의견을 말씀드리면 생각을 하는데 있어서 제약을 가지고 올 수도 있을 것 같아서요 😢 

https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/controller/ReservationController.java
> +            new ReservationAppRequest(request.name(), request.date(), request.timeId(), request.themeId()));
해당 부분은 Request를 (위브 기준으로) App, Web으로 나눈 부분에 이어서 생각해 볼 수 있을 것 같습니다. 

Service에서 값을 반환할 때는 따로 Response를 감싸지 않고 도메인 객체 그대로 반환했는데 혹시 해당 부분은 위 Request 부분과 어떠한 생각의 차이로 코드를 작성하였을까요?

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    }
해당 도메인은 id가 식별자인데 VO 객체처럼 동등성을 구현하신 이유가 있을까요?

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
name과 마찬가지로 해당 도메인을 생성하는 곳에서 언제든 date, time, theme에도 null을 전달할 수 있는데 유효성 검증이 되지 않은 것 같아요.

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/repository/JdbcReservationRepositoryImpl.java
> +package roomescape.repository;
개인적인 제안인데 기존에 저장하는 Repository 명세를 이미 도메인의 영역으로 관리하고 있으니 아래와 같이 외부 라이브러리(인프라)와 연관을 가지고 있는 구현체의 경우 infrastructure와 같은 이름으로 관리해보는 것은 어떨까요?

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
해당 코드 중 유효성 검증을 하는 부분을 보면 생성을 요청하는 요청 객체의 데이터에 대한 검증이 될 것 같아요! 예외를 검증하는 위치를 해당 객체로 옮기면 어떨까요? 기존의 코드에 비해 어떠한 장점을 얻을 수 있을까요?

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/service/ReservationService.java
> +        }
동일한 예외를 발생하는 조건문이 두 개로 나뉘어져 있습니다. 조건을 판단하는 메서드를 따로 뽑아보는 것은 어떨까요? 그리고 적절한 이름을 지어준다면 좀 더 명확해보이는 코드가 될 수도 있을 것 같습니다 👍🏼

2024-05-02 15:57 UTC, lxxjn0 commented on src/main/java/roomescape/service/ThemeService.java
> +        return themeRepository.findPopular(MAX_POPULAR_THEME_COUNT);
레포지토리의 해당 메서드가 어떠한 파라미터를 받고 해당 파라미터로 어떠한 역할을 수행하는지 조금 더 명확히 드러내보면 어떨까요? sql문의 용어를 활용해봐도 좋을 것 같습니다 :)

2024-05-03 07:50 UTC, jimi567 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    }
말씀하신 것처럼 id가 식별자가 별도로 존재하기 때문에 다른 필드까지  비교할 필요가 없을 것 같습니다.

2024-05-03 18:14 UTC, jimi567 commented on src/main/java/roomescape/repository/JdbcReservationRepositoryImpl.java
> +package roomescape.repository;
미션 1에서 dao와 repository의 차이를 공부하다가 구조가 이렇게 나왔습니다.
말씀해주신 것처럼 명세와 구현체를 구분한다는 관점에서  infrastructure라는 패키지명이 더 적합할 것 같습니다.
좋은 제안 감사합니다.

2024-05-03 18:21 UTC, jimi567 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
제가 기존에 원했던 방향은 값에 대한 유효성 검증은 최대한 도메인 쪽에서 해결하는 것 입니다.
사실 시간 부족으로 모든 부분을 완벽하게 분리하진 못했던 것 같습니다.

제안해주신 방향의 장점으로는 객체 간 역할 분리와 비슷한 맥락으로 
비즈니스 로직에서 발생할 수 있는 예외와 값 검증에 대한 예외를 적절한 위치에서 발생 시켜, 유지보수 측면에서 이점이 있을 것 같습니다.

2024-05-03 18:24 UTC, jimi567 commented on src/main/java/roomescape/service/ReservationService.java
> +        }
제안해주신 방향과는 다른 것 같지만, Reservation이 가지고 있는 날짜와 시간 정보가 현재( = now() ) 기준 과거인지 아닌지를 판단하는 기능을 추가해서 가독성을 향상 시켜봤습니다.

2024-05-03 18:36 UTC, jimi567 commented on src/main/java/roomescape/dto/app/ReservationAppRequest.java
> +public record ReservationAppRequest(String name, String date, Long timeId, Long themeId) {
일단 현재 베이스가 되는 미션1의 코드는 제 코드를 가지고 왔습니다. 미션1 단계에서도 저는 표현 계층에서 사용하는 dto와 서비스 계층에서 사용하는 dto를 분리했습니다.

그 이유는 현재 아키텍처에서 가장 변경 가능성이 높은 레이어가 표현 계층이라고 생각해서 입니다.

어떻게 설계를 해야 최대한 표현 계층과 그 아랫단의 계층을 철저하게 분리할 수 있을까? 현재 내 코드는 표현 계층이 바뀌어도 서비스 게층과 영속 계층을 재사용할 수 있을까? 라는 고민하다가 dto를 분리하게 됐습니다.

이점으로는 제가 기대한 재사용성 향상입니다. 솔직히 말씀드리면 실제로 표현계층이 변경돼서 재사용해본 경험이 없어서 정말 제 기대대로 dto 분리가 재사용성 향상에 도움이 될까는 잘 모르겠습니다. ㅠㅠ

단점으로는 dto의 갯수가 늘어나서 관리해야 할 클래스가 많아진다는 것이 단점인 것 같습니다.

2024-05-03 18:45 UTC, jimi567 commented on src/main/java/roomescape/controller/ReservationController.java
> +            new ReservationAppRequest(request.name(), request.date(), request.timeId(), request.themeId()));
도메인의 경우 서비스 레이어에서 주로 사용되는 객체로 이해하고 있습니다.
표현 계층의 경우 서비스 계층에 의존하기 때문에 표현 계층에 도메인이 드러나도 크게 문제가 없다고 생각해서 response로 감싸지 않고 그대로 도메인을 반환했던 것 같습니다. 앞서 request를 왜 나누었는지에 대한 질문에서 제가 생각했던 단점인 dto 클래스가 많아진다는 단점을 최대한 줄이기 위해 제가 타협한 것이 AppResponse는 추가하지말자 였습니다.

하지만, 

미션1 마지막 단계에서 리뷰어분이 approve 해주시면서 
> Controller의 노출된 Domain을 누군가가 변경한다면 어떻게 될까요?
라는 코멘트를 남겨주셨습니다. 이런 관점에서는 response로 감싸서 controller에 보내는게 더 나을 것 같다는 생각이 듭니다. 이 부분은 명확한 정답이 없다고 생각합니다.
.스티치의 의견이 궁금합니다.!!

2024-05-03 19:16 UTC, jimi567 commented on src/main/java/roomescape/service/ThemeService.java
> +        return themeRepository.findPopular(MAX_POPULAR_THEME_COUNT);
제가 개발 경험이 적기도하고 네이밍 센스가 없는지... 메소드명이나 필드명 짓기가 아직 까지도 어려운 것 같네요..ㅠㅠ
고민을 해봤습니다만, 제 네이밍 센스로는 findMostReservedThemesInPeriod가 최선인 것 같습니다..

2024-05-04 07:05 UTC, jimi567 commented on src/main/java/roomescape/exception/DuplicatedReservationException.java
> +public class DuplicatedReservationException extends RuntimeException {
제공해주신 글을 보며 개인적으로 생각을 더 해봤습니다.!!

미션을 진행하면서도 커스팀 예외를 구체적으로 작성하려고 하다 보니 도메인도 굉장히 적은 상황임에도 관리해야 될 클래스 수가 너무 많아지더라고요. 어느 정도 규모가 있는 도메인을 개발하게 된다면, 개발자가 모든 커스텀 예외를 관리하기는 현실적으로 어렵다는 생각을 하게 됐습니다. 또 직접 커스텀 예외를 추가하지 않은 동료 개발자가 보기에 어떤 커스텀 예외가 존재하는지 파악하는 리소스도 커질 것 같습니다.

지금 제가 내린 결론은 최대한 자바에서 제공해주는 표준 예외를 활용하되, 현재 개발하는 비즈니스 로직 상 정말 중요하다 싶을 때만 추가하는게 어떨까? 라는 생각을 하게 됐습니다.

최대한 표준 예외를 사용할 수 있도록 코드를 리팩터링 했습니다.!

2024-05-04 10:01 UTC, jimi567 commented
안녕하세요.  남겨주신 리뷰, 코멘트 확인 했습니다.! 아래는 서비스 간의 협력에 대한 제 생각입니다.

> 추가로 서비스 별로 다른 도메인에 대한 Repository를 의존하면서 동일한 기능을 중복해서 사용하는 경우나 또는 이미 구현된 기능을 Repository 의존으로 인해 재구현하는 경우도 있는 것 같아요. 한번 Service를 의존해서 사용하는 것이 어떨지? 그리고 서비스를 의존한다는 방식에 대해서 어떠한 생각을 가지고 있는지도 한번 이야기해보면 좋을 것 같아요!

레벨1 때를 상기해보면, Service가 협력할 수 있도록 설계를 하면  좋을 것 같다는 생각이 들어요.! 코드도 재사용 할 수 있고, 응집도 관점에서도 좋은 코드가 될 것 같습니다.
하지만, 이번 미션에서는 Service끼리 의존하게 될 경우 순환 참조가 발생할 것 같다는 생각이 들어서 repository를 의존하게 만들었던 것 같습니다.  
1. time이나 theme에서는 삭제를 하기 전에 해당 데이터를 사용하는 예약 정보가 존재하는 지를 확인하고, 
2. 예약 도메인에서는 도메인을 생성하는 과정에서 time과 theme가 필요할 것 같습니다. 

미션에서 주어진 스키마에서는 외래키를 사용하고 있기 때문에 db단에서 발생하는 참조 무결성을 통해 1번을 해결한다면, 순환 참조는 발생하지 않을 것 같지만, 실무에서는 대부분 외래키를 사용하지 않는 다고 알고 있어서 Service에서 확인하게 구현 했습니다.

2024-05-05 02:49 UTC, lxxjn0 commented on src/main/java/roomescape/dto/app/ReservationAppRequest.java
> +public record ReservationAppRequest(String name, String date, Long timeId, Long themeId) {
사실 개발자 사이에서 가장 크게 의견이 갈리는 부분이라고 생각합니다. 이건 정답은 없으니 위브의 선택을 가져가시면 될 것 같아요!! 말씀하신 트레이드 오프는 잘 이해하고 계신 것 같고 본인이 느끼기에 적절한 상황에 맞게 선택하시면 될 것 같습니다.

질문을 드렸던 이유는 지금 코드에서는 같은 형태를 반복해서 작성하고 있는 느낌이라 아직은 나눌 필요가 없지 않을까? 라는 생각이 들어서 한번 여쭤봤던 거였습니다 :)

2024-05-05 02:51 UTC, lxxjn0 commented on src/main/java/roomescape/exception/DuplicatedReservationException.java
> +public class DuplicatedReservationException extends RuntimeException {
말씀대로 모든 상황에 맞는 예외 클래스를 생성하는 것은 현실적으로 어렵다고 생각합니다. 특정한 서비스나 도메인의 범위 내에서 발생하는 예외를 따로 처리하기 위해서, 또는 특정한 예외에 대해서 비즈니스 로직으로 처리해야 하는 상황이 있을 경우에 보통 커스텀 예외를 사용하고 그렇지 않은 경우는 자바에서 제공되는 예외를 적극적으로 사용했던 것 같아요!

2024-05-05 02:55 UTC, lxxjn0 commented on src/main/java/roomescape/controller/ReservationController.java
> +            new ReservationAppRequest(request.name(), request.date(), request.timeId(), request.themeId()));
제가 위브 코드를 보면서 request를 나눈 이유는 위브가 설명한 그대로 각 계층 간의 의존성을 최대한 끊어내기 위함이라고 생각했습니다. 그런데 도메인 객체를 그대로 controller로 반환한 부분에서는 위의 관점에 일치하지 않는 느낌이 들었어요. 

아까 dto를 계층 간에 만들지 말지는 개발자의 선택이라고 이야기 했던 것 같습니다. 그러나 그 선택에 대한 관점과 기준은 코드 전반적으로 통일되어야 한다고 생각합니다. 계층 간의 의존을 끊기 위해서 request를 나누었다면 그와 맞게 response도 나뉘어야 한다고 생각하고, 만약 어느 정도의 트레이드 오프를 고려해서 적절한 영향 범위까지만 객체를 공유하자고 결정했다면 응답도 그런 기준으로 선택이 가능할 수 있고요. request를 나누는 것보다는 도메인을 표현 계층에 노출시키지 않는 것이 코드를 관리하는 입장에서 더 중요한 부분이라고 생각하는데 두 과정에서 생각의 일관성이 느껴지지 않아서 질문드려봤어요. 혹시 제가 이해한 부분과 위브의 생각이 다른 점이 있었을까요?

2024-05-05 02:58 UTC, lxxjn0 commented on src/main/java/roomescape/service/ThemeService.java
> +        return themeRepository.findPopular(MAX_POPULAR_THEME_COUNT);
앗, 제가 조금 헛갈리게 말씀드렸네요. 서비스 메서드의 이름이 아닌 Repository의 이름에 대한 질문이었습니다 ㅠㅠ

`findPopular`라는 메서드에 카운트가 파라미터로 넘어가는데 단순히 메서드 이름만 본다면 파라미터로 어떠한 값이 넘어가게 되는지 직접 쿼리를 보지 않는 이상 어려울 것 같아요. 레포지토리 메서드가 받는 파라미터가 어떠한 역할을 하게 될 지 이름에 노출시켜주면 더 좋지 않을까 생각했습니다!! `findById(Long id)`와 같은 메서드 이름을 본다면 제가 말씀드리고자 하는 부분이 어떤 포인트인지 이해하시기 더 쉽지 않을까 싶어요 :)

2024-05-05 03:09 UTC, lxxjn0 requested changes
위브, 피드백 반영하시느라 수고하셨습니다 :)

프로덕션 코드는 추가로 리뷰 드릴만한 부분은 별로 없는 것 같아서 간단한 피드백만 작성했습니다. 추가로 요청 객체의 경우 `@Valid`라는 어노테이션을 확인해보면 도움이 되실 수 있을 것 같습니다. 테스트에 대해서는 궁금한 부분만 코멘트 남겨두었는데 워낙 꼼꼼히 잘 작성해주셔서 부족한 점은 없는 것 같아요!

이전 리뷰에 대한 피드백도 함께 참고해서 마무리하고 다음 단계 진행하면 될 것 같습니다 👍🏼

2024-05-05 03:09 UTC, lxxjn0 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
ID는 DB를 사용하는 이상 많은 도메인의 기본적인 식별자로 사용되게 될 것입니다. 그렇다면 ID를 가지는 모든 도메인 객체는 동등성을 부여해야 할까요? 또는 부여하는 것이 적절할까요?

2024-05-05 03:09 UTC, lxxjn0 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +    private MockMvc mvc;
RestAssured가 아닌 Mockito를 사용하셨네요. 해당 라이브러리를 선택한 이유가 있을까요??

2024-05-05 09:53 UTC, jimi567 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +    private MockMvc mvc;
각 레이어별로 단위테스트를 작성할 수 있도록 노력해봤습니다.

Controller의 테스트에는 Controller의 역할인  http 요청과 그에 대한 응답만을 테스트하는 것이 적절하다고 생각해서,
표현 계층 관련된 Been만 등록해서 테스트 할 수 있는 WebMvcTest를 사용하게 됐습니다.

추가적으로, 제가 1단계에서는 Mockmvc를 사용해서 Controller를 테스트했습니다. 
반면에, 페어와 합의 하에 이번 미션에서 새로 생긴ThemeController에서는 RestAssured를 사용해서 테스트를 작성 했습니다.

2024-05-05 10:16 UTC, jimi567 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
개발하는 비즈니스에 따라 부여해야 할 수도 있고, 필요가 없다면 부여할 필요가 없다고 생각합니다. 
제가 웹 개발이나 db를 활용한 개발을 해본 경험이 없어서, 일반적으로 뭐가 옳은건지는 잘 모르겠습니다..ㅠㅠ

다만, 식별자를 가지는 엔티티의 경우, id가 동일하면 다른 상태가 달라도 동등하다고 봐야 되는건가? 아니면 다른 필드까지 모두 동등해야 동등하다고 봐야하는 건가? 모호한 부분이 있을 것 같습니다.
 
 이전에 말씀해주신 것처럼 엔티티의 경우는 vo와는 다르기 때문에 객체 지향 관점에서 동등성을 부여하는게 어색하다고는 생각합니다. 

이번 미션에 한해서 db에 저장되는 도메인의 경우 동등성을 굳이 부여할 필요가 없다고 생각합니다.
단지, tdd로 미션을 진행하는 과정에서 테스트 코드 작성에 생각보다 시간이 많이 소요돼서, 추가하게 됐습니다.
불필요한 동등성 부여라고 생각 돼서, 시간이 많은 지금 리팩터링을 통해서 지우도록 하겠습니다.!

2024-05-06 07:54 UTC, lxxjn0 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
> 다만, 식별자를 가지는 엔티티의 경우, id가 동일하면 다른 상태가 달라도 동등하다고 봐야 되는건가? 아니면 다른 필드까지 모두 동등해야 동등하다고 봐야하는 건가? 모호한 부분이 있을 것 같습니다.

이 부분은 엔티티에 대해서 좀 더 학습해보시면 이해를 하는데 도움이 되지 않을까 싶습니다. 

식별자는 말 그대로 데이터, 도메인을 식별하는 인자입니다. 즉 해당 값의 유일성을 보장해주기 위한 값인데 '식별자가 동일한데 상태가 다르면'이라는 가정 자체가 불가능하다고 생각합니다. 이는 다른 식별자를 가져야하는 값이거나 또는 해당 식별자의 값이 변경되었다고 보는게 적절하지, 식별자가 같은데 다른 상태를 가지는 두 값이 존재한다는 말은 식별자라는 의미 자체에 모순되는 가정일 것 같아요. 아마 이전 레벨의 도메인이라는 개념에서 엔티티의 개념이 겹쳐지면서 혼동이 있으실 수 있을 것 같아요. 이 부분은 한번 꼼꼼히 학습해보시면 더 좋을 것 같습니다 :)

2024-05-06 07:57 UTC, lxxjn0 approved these changes
위브, 피드백 반영하시느라 수고하셨습니다. 코드가 전체적으로 마무리가 된 것 같아서 다음 단계 진행해주셔도 될 것 같아요! 추가로 반영하고자 하는 부분은 다음 단계 진행하시면서 반영하시면 될 것 같고 이전 리뷰에 대한 코멘트도 추가해뒀으니 한번 확인해주세요 :)

2024-05-06 07:57 UTC, merged