[1 - 3단계 방탈출 사용자 예약] 제리(김민정) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #47
Opened 2024-05-02 08:33 UTC by mzeong

2024-05-03 04:40 UTC, sihyung92 requested changes
안녕하세요 제리! 리뷰어 웨지입니다.
코드 구현이 마음에 드는 부분이 많았네요~ 잘 구현해주셨다고 생각합니다.
리뷰 남겼으니 확인해보셔요! 
감사합니다.

2024-05-03 04:40 UTC, sihyung92 commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +        ));
**질문 답변 >** 

반복되는 상황에 대해선 메서드 추출 후 이터레이션(for문)이라는 개발자가 가장 익숙한 방식이 있을겁니다 ㅎ

2024-05-03 04:40 UTC, sihyung92 commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +        ));
그나저나 조이썬과 페어시군요 반갑네요 ㅎ

2024-05-03 04:40 UTC, sihyung92 commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +//@Import(TestConfig.class)
TestConfig 객체는 없어보이네요?

2024-05-03 04:40 UTC, sihyung92 commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +        jdbcTemplate.update("SET REFERENTIAL_INTEGRITY TRUE");
테스트 부팅 시 프로필 설정이나, 컨피그 설정이 없어 운영환경의 테이블을 날릴까봐 무섭습니다 ㅋㅋ

이런 쿼리를 만드실 때는 운영DB 밀어버릴 염려는 없는지 꼭 생각해주세요~ TRUNCATE와 같은 DDL은 Trasanctional 에 적용대상이 아니어서 롤백도 안 됩니다. 
운영디비를 도깨비나 귀신으로 생각해주시고 항상 겁내주세요 (경험에서 우러난 충고입니다..ㅠㅠ)

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/controller/api/ExceptionAdvice.java
> +public class ExceptionAdvice {
이전 리뷰이 코드 복붙 한 번 하겠습니다 ㅎ

이런 예외 핸들러는 controllerAOP를 활용하긴 하지만 웹서버 성격상 cotroller에 모든 오류가 throw되기 때문에 이 코드는 전역 처리기처럼 동작하게 됩니다.
그 성격에 맞게 해당 코드를 찾기 쉽도록 보통 controller 패키지와 동일한 depth에 config, exception, aop 등 별도의 패키지로 구성을 하는 경우가 많습니다

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/controller/api/ReservationTimeApiController.java
> +    public ResponseEntity<List<ReservationTimeResponse>> getAllReservationTimes() {
이전 크루의 리뷰를 복붙 한번 하겠습니당. 222

응답객체는 Collection이 아닌 Object 형식으로 내려주는게 유연한 설계입니다.
page 요구사항이 추가되어 응답객체에 data size만 추가되어도 API break change가 됩니다 (기존 API가 하위버전에 호환되지 않는 것을 break change라고 합니다. 이 경우 반드시 서버와 프론트엔드가 반드시 동시 배포해야 하고, 배포 과정 중 오류가 발생하는 것을 피할수 없으므로 동일한 역할을 하는 새로운 API를 제공하게 되는 안티패턴이 됩니다)
프론트 입장에서 생각해보시면 {} 와 []는 다루는 방법이 다르기 때문입니다

최근에 끄덕끄덕하면서 본 [아티클](https://blog.stackademic.com/creating-a-high-quality-rest-api-201819325356)인데, Don’t return arrays as top-level responses. 라는 조언이 이 리뷰에 해당합니다.

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/domain/VisitDate.java
> +            throw new IllegalArgumentException(String.format("%s 는 유효하지 않은 값입니다.(EX: 10:00)", date));
실제로 서비스를 굴려보니  `는 유효하지 않은 값입니다.` 라는 오류메시지를 자주 보고 있습니다.
그런데 어떤 필드가 문제인지 확인 할 수 없어 좋은 예외메시지는 아니라고 생각합니다.
어떤 맥락인지 풍부화 해주세요. 이 예외메시지는 입력값과 예시에 대해 설명해주므로 좋은 메시지의 조건들을 갖추고 있지만, 맥락이 나타나지 않아 좋은 오류메시지는 아닙니다.

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/domain/VisitDate.java
> +public record VisitDate(LocalDate date) {
VO 구현 좋네요.

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/exception/ExistReservationException.java
> +public class ExistReservationException extends IllegalArgumentException {
커스텀 예외 사용 좋습니다 :+1:

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/controller/api/ReservationTimeApiController.java
> +    @GetMapping("/available")
타 크루의 코드보다 품질이 좋다고 생각한 이유가 되는 API입니다. 
이 API 덕분에 서비스 사용성이 훨씬 우수해졌습니다.

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/controller/api/ExceptionAdvice.java
> +        return new ResponseEntity<>(exception.getMessage(), HttpStatus.BAD_REQUEST);
오류메시지는 String 보다 에러 객체를 정의해서 내려주는 걸 권장드립니다.
확장성의 차이가 있습니다.

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/dao/dto/AvailableReservationTimeResponse.java
> +public record AvailableReservationTimeResponse(boolean alreadyBooked, long timeId, String startAt) {
해당 객체는 왜 domain까지 못 들어오고 여기 서있나요? 
예컨데 VisitDate와 VO로서의 가치는 비슷해보이는데, 이 객체는 dto로 분류하고 visitDate는 vo로 분류한 기준이 있나요?

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/domain/Thumbnail.java
> +    public static final String ALLOW_EXTENSIONS_PATTERN = String.join("|", ALLOW_EXTENTIONS);
꼼꼼한 처리네요 :+1:

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/domain/Thumbnail.java
> +    private static final Pattern PATTERN = Pattern.compile(
PATTERN은 너무 모호한 표현입니다. 
정규표현식을 보자마자 한눈에 어떤 역할인지 파악할 수 있는 개발자는 많지 않습니다 (경험상)
이 패턴이 어떤 패턴인지 구체적인 상수명을 지어주세요

2024-05-03 04:40 UTC, sihyung92 commented on src/main/java/roomescape/domain/Thumbnail.java
> +            throw new IllegalArgumentException(String.format("%s 확장자만 가능합니다.", ALLOW_EXTENSIONS_PATTERN));
커스텀 예외를 활용중이시니 IllegalArgumentException를 그대로 throw 하기보다는 서비스에서 IllegalArgumentException를 대용할만한 범용적 커스텀 예외를 만들어주시는 것도 방법입니다.

2024-05-06 05:51 UTC, youngsu5582 commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +        ));
ㅋㄱㅋㄱㅋㄱㄱㅋ 저도 제리 리뷰어 웨지 인거 보고 되게 반가웠습니다! 🙂🙂
( 제리한테 남기는 리뷰도 잘 챙겨보겠습니다! 🫡🫡 )

2024-05-08 08:14 UTC, mzeong commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +//@Import(TestConfig.class)
시간과 날짜를 반환하는 DateTimeFormatter 인터페이스를 생성해서
- 프로덕션 코드에서는 `LocalDate.now`, `LocalTime.now`를 이용한 NowDateTimeFormatter 구현체를 사용
- 테스트 코드에서는 임의의 시간을 지정한 PastDateTimeFormatter 구현체를 사용 

위와 같이 하고 싶었는데 잘 안 되어서... TestConfig가 잠시 사라졌습니다

이후 TestConfiguration과 Primary 어노테이션으로 테스트에서 원하는 구현체를 사용하도록 하여 다시 TestConfig가 생겼습니다!

2024-05-08 08:34 UTC, mzeong commented on src/main/java/roomescape/dao/dto/AvailableReservationTimeResponse.java
> +public record AvailableReservationTimeResponse(boolean alreadyBooked, long timeId, String startAt) {
VisitDate는 날짜 형식 검증과 하루, 일주일 전 날짜를 반환하는 로직을 가지고 있어서 vo로 분류하였으나
AvailableReservationTime은 startAt, timeId, alreadyBooked를 응답해주기 위한 것이라 dto로 분류하였어요

그런데 이렇게 하니 다른 dao 메서드들은 도메인을 반환하고 있는데, findAvailable 메서드만 dto를 반환하고 있어 일관성이 없어 보여요 AvailableReservationTime이라는 도메인 객체를 만드는 것이 좋을까요?

2024-05-08 08:38 UTC, mzeong commented on src/main/java/roomescape/domain/VisitDate.java
> +            throw new IllegalArgumentException(String.format("%s 는 유효하지 않은 값입니다.(EX: 10:00)", date));
오류 메세지가 예외 발생 지점, 발생 이유, 입력값을 포함하도록 수정했습니다!!

2024-05-08 08:39 UTC, mzeong commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +        jdbcTemplate.update("SET REFERENTIAL_INTEGRITY TRUE");
테스트용 데이터베이스에서 테스트가 진행되도록 수정했습니다!!

2024-05-08 08:45 UTC, mzeong reviewed
안녕하세요 웨지 🥔 
연휴 잘 보내셨나요? 저는 이번 연휴에 미션 하지 않기를 실천해보았더니 조금 늦게 리뷰를 반영하게 되었어요 🫨
충전의 시간을 가진 만큼 남은 미션 기간 동안 파이팅해보겠습니다 🏃🏃

2024-05-09 03:31 UTC, sihyung92 commented on src/main/java/roomescape/dao/dto/AvailableReservationTimeResponse.java
> +public record AvailableReservationTimeResponse(boolean alreadyBooked, long timeId, String startAt) {
꼭 만들라는 조언은 아니고요, 팀 전체가 납득할만한 규칙(일관성)이 있으면 됩니다.
AvailableReservationTime은 대응되는 도메인 개념이 없어서 Dto로만 있다면 다소 재활용성이 떨어진다는 생각은 듭니다.
특정 API에서만 활용될 것이 자명하다면 그런것도 괜찮긴한데요

2024-05-09 03:42 UTC, sihyung92 approved these changes
안녕하세요 제리~ 리뷰어 웨지입니다!
리뷰 반영 잘 해주셔서 머지하겠습니다 :)
사소한 리뷰가 있으니 확인해보셔요.
다음 스텝에서 뵙겠습니다~

2024-05-09 03:42 UTC, sihyung92 commented on src/main/java/roomescape/exception/InvalidInputException.java
> +    }
정적팩토리를 메서드 활용하실거라면 해당 생성자를 private로 만들어 제약하는 것도 좋겠네요

2024-05-09 03:42 UTC, sihyung92 commented on src/main/java/roomescape/service/ReservationService.java
> +            throw ExistsException.of(String.format("date 가 %s 이고 reservationTimeId 가 %d인 reservation", reservation.getDate(), reservation.getId()));
사용성이 불편해보이는 예외입니다. 이럴거라면 차라리 full text를 여기서 전달하는게 좋겠어요
(ExistsException 내부의 메시지를 클라이언트가 넘겨주던지, 그 반대로)

`date 가 %s 이고 reservationTimeId 가 %d인 reservation 이 존재합니다.`

2024-05-09 03:43 UTC, sihyung92 commented on src/test/java/roomescape/service/ReservationTimeServiceTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
좀 늦게 봤네요 ㅎ
RANDOM_PORT는 무슨 의미일까요?
그리고 이 테스트에서 필요한 설정일까요?

2024-05-09 03:43 UTC, merged