[1 - 3단계 방탈출 사용자 예약] 배키(백은희) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #51
Opened 2024-05-02 08:37 UTC by ehBeak

안녕하세요. 썬! 레벨1 두번째 미션에서 뵈었었는데, 이번에도 레벨2 2번째 미션에서 뵙네요! 잘 부탁드립니다~

2024-05-02 16:59 UTC, syoun602 requested changes
안녕하세요 배키! 또 만나게 되서 반갑습니다 👋

전체적으로 잘 구현해주셨네요 👍
몇가지 코멘트 남겨봤는데 확인 후 재요청 주세요!
또한 데이터가 조금 더 추가되었으면 좋겠습니다 👀

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/model/Reservation.java
> +    public Reservation(String name, LocalDate date, ReservationTime time, Theme theme) {
부생성자라면 기본 생성자를 활용해 객체를 만들어보아요
`this(null, ...);`

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/model/Theme.java
> +    public boolean equals(Object o) {
eq&hc + tostring 👍
근데 어떤 도메인은 아예 없고 어떤 도메인은 eq&hc만 정의되어 있네요
전체적인 컨벤션을 맞춰주세요~

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/repository/ReservationDAO.java
>          return jdbcTemplate.query(sql, (resultSet, rowNum) ->
RowMapper 객체를 재사용 가능하도록 상수화해봅시다~

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/repository/ReservationDAO.java
>  public class ReservationDAO implements ReservationRepository {
일반적인 클래스명이라면 DAO보다는 Dao로 작성될 것 같아요!

---
또한 Dao랑 Repository의 차이는 무엇인가요? Repository를 구현한게 Dao가 맞을까요?

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/repository/ReservationDAO.java
> +                """;
쿼리를 작성할때 select,as,from과 같은 예약어는 대문자로 작성하면 가독성이 좋습니다~!

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationService.java
> +        }
해당 validation은 DB에 연결되기 전에 검증할 수 있지 않을까요?

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationService.java
> +        }
null나오면 중복 예약인가요??

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/service/ReservationService.java
> +    public List<MemberReservationTimeResponse> getMemberReservationTimes(LocalDate date, long themeId) {
getMemberReservationTimes 어떤 행위인지 잘 이해가 안됩니다 😢 
메서드명을 조금 더 직관적으로 변경해주세요!

추가적으로 
1. 시간순으로 정렬이 되어야 할 것 같아요
2. 데이터가 너무 없습니다 😢 검증하려면 하나하나 데이터를 추가해야되는데 여러 데이터셋이 있으면 좋을 것 같아요. 테마의 경우도 popular가 10개라면 최소 11개는 있어야 될 것 같고, 예약도 몇가지 케이스를 추가해주세요!

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/model/ReservationTime.java
>  public class ReservationTime {
항상 00초에 고정이라면 꼭 보여줘야 하는 데이터인지 의문이 있습니다!
<img width="885" alt="image" src="https://github.com/woowacourse/spring-roomescape-member/assets/67397679/856bafa6-c382-4a6c-a189-89929deffc0c">

2024-05-02 16:59 UTC, syoun602 commented on src/main/java/roomescape/controller/ReservationController.java
>  public class ReservationController {
admin에서의 방탈출 예약 기능이 동작하지 않아요 😢 전체적인 실행도 한번 검증해주세요!

2024-05-02 16:59 UTC, syoun602 commented on src/test/java/roomescape/service/ThemeServiceTest.java
> +}
no new line 경고가 뜨는 파일들이 몇개 있네요!

2024-05-02 16:59 UTC, syoun602 commented on src/test/java/roomescape/controller/ThemeControllerTest.java
> +        assertThat(popularThemes).containsExactly(
두개의 assert문이라면 assertAll을 활용해주세요~
근데 컨트롤러 테스트에서 사실 200만 검증해도 되지 않나요?
데이터 검증을 위한 통합 테스트를 service에서 진행해보는건 어떨까요?

2024-05-02 16:59 UTC, syoun602 commented on src/test/java/roomescape/service/FakeThemeRepository.java
> +    public List<Theme> findThemeRankingByDate(LocalDate before, LocalDate after, int limit) {
FakeDao를 만드신 것 👍
Repository의 쿼리가 복잡한데, 이렇게 하드 코딩된 값을 반환하면 무엇을 위한 테스트인지 고민해보면 좋을 것 같습니다!

2024-05-03 06:24 UTC, ehBeak commented on src/main/java/roomescape/controller/ReservationController.java
>      @GetMapping("/reservations")
`ReservationController`클래스 상단에 `@RequestMapping("/reservation")`을 이용할 수도 있습니다 :)
하지만 아래와 같은 이유로 `RequestMapping`을 통해 추출하지 않았습니다!

**(1) 이후에 컨트롤러가 많아지고 그에 따라 url이 많아진다면 url을 검색할 때, 검색이 어려워집니다.**
   예를 들어, 개발자가` /reservations/{id}` 라는 url을 검색하고 싶을 때, 보통` /reservation/{id}`라고 검색합니다. 그런데 `RequestMapping`을 통해 `/reservations`를 추출한다면 검색이 어려워집니다.

**(2) url 전체를 쓰면 개발자 입장에서 알아보기 쉽고 직관적입니다.**
`RequestMapping`을 통해 `/reservations`를 추출하면 메서드 상단에는 `@GetMapping("")`이나, `@GetMapping("/{id}")`등으로 남습니다. 무엇을 나타내는지 직관적으로 이해하기 힘들 것이라 생각했습니다..!

2024-05-03 07:09 UTC, ehBeak commented on src/main/java/roomescape/controller/ReservationTimeController.java
> -import org.springframework.web.bind.annotation.RestController;
wild card import의 단점은 namespace를 혼잡하게 하여, 컴파일 충돌이 일어날 수 있습니다.
 예를 들어, 개발자가 개발하면서 java.awt.Event를 와일드 카드 임포트를 사용해서 Event 객체를 사용하고 있는 상황이라고 가정합시다. 시간이 흐른 후 다른 개발자가 com.mycompany.calendar.Event를 사용하기 위해 해당 라이브러리를 와일드 카드 임포트를 사용한다면 문제가 컴파일 오류가 발생합니다.

반면에 명시적으로 import를 한다면 내가 사용한 클래스를 명시적으로 말해줄 수 있고 코드를 쉽게 만든다는 장점이 있습니다!

저도 wild card import를 안 쓰는 편인데, 왜 이게 wild card import로 되었는지 모르겠네요😅 수정했습니다 :)

2024-05-03 07:19 UTC, ehBeak commented on src/main/java/roomescape/controller/ThemeController.java
> +    @GetMapping("/themes/rank")
네 현재 설계된 API에는 조회하는 데이터에 대한 정보가 부족한 것 같습니다! 수정하겠습니다. 감사합니다~

2024-05-04 08:44 UTC, ehBeak commented on src/main/java/roomescape/controller/request/ReservationRequest.java
> +            throw new BadRequestException("[ERROR] 유효하지 않은 요청입니다.");
> 메시지 부분은 중복되는데 BadRequestException 내부에 상수로 가지고 있어도 좋겠네요.

네! 예외마다 메시지가 거의 비슷해서 상수로 가져도 좋을 것 같습니다.

> 근데 예외가 조금 더 사용자 친화적이면 더 좋을 것 같아요

이 점을 고려해서 메시지를 조금 구체적으로 두고, 상수로 둘 수 있는 것은 상수로 두겠습니다~

2024-05-04 09:55 UTC, ehBeak commented on src/main/java/roomescape/controller/request/ReservationTimeRequest.java
> +    }
controller.request 패키지에 있는 ~Request클래스는 `@RequestBody`에 의해 역직렬화 되는 객체입니다.
다른 ~Request 클래스와 다르게, ReservationTimeRequest는 startAt이라는 하나의 필드만을 가지고 있습니다. 
어떤 이유에서인지 모르겠지만, 클래스의 필드가 하나인 경우 매개변수를 가지는 ReservationTimeRequest 생성자를 호출하지 못하는 것으로 보입니다. 때문에 기본생성자를 선언하고 리플랙션을 이용하여 객체를 매핑하도록 했습니다!

2024-05-05 03:17 UTC, ehBeak commented on src/main/java/roomescape/controller/request/ReservationTimeRequest.java
> +    }
> 어떤 이유에서인지 모르겠지만,

조금 더 찾아본 뒤 코멘트 올리겠습니다!

2024-05-05 03:23 UTC, ehBeak commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
앗.. 그렇네요. 제 의도는..` controller.request` 패키지의 클래스 내부 생성자 매개변수 중 `LocalDate`와 `LocalTime`을 매핑해줄 때 다른 형식으로 매핑되면 예외가 발생합니다. 그런데 이 외에도 또 다른 예외가 발생할 수 있네요. 그래도 해당 핸들러가 작동하고요..!
이를 해결하기 위해서는 `DateTimeParseException`이 `request` 생성자 내부에서 발생할 때, 제가 커스텀한 예외로 바꿔줘야 할 것 같습니다~

추가로, request 내부에 해당 예외를 처리해주면 requestDTO가 생길 때마다 중복이 발생할 것 같아, 도메인에서 예외를 처리하도록 변경했습니다!
추가로,

2024-05-05 05:07 UTC, ehBeak commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(exception.getMessage(), HttpStatus.NOT_FOUND);
> ResponseEntity 내부에 static 메서드들을 살펴봅시다~ 조금 더 쉽게 작성해볼 수 있을 것 같아요!

네 확인해 보니, 빌더를 통해 응답할 수 있네요~ 수정했습니다!

2024-05-05 05:44 UTC, ehBeak commented on src/main/java/roomescape/repository/ReservationDAO.java
>  public class ReservationDAO implements ReservationRepository {
>일반적인 클래스명이라면 DAO보다는 Dao로 작성될 것 같아요!

네 수정했습니다!

2024-05-05 06:07 UTC, ehBeak commented on src/main/java/roomescape/repository/ReservationDAO.java
>  public class ReservationDAO implements ReservationRepository {
> 또한 Dao랑 Repository의 차이는 무엇인가요? Repository를 구현한게 Dao가 맞을까요?

### 처음에 (제가) 의도했던 repository
처음에 제가 respository라는 인터페이스를 사용한 이유는 test를 위한 FakeDao가 필요했고 이를 위해서는 Dao를 추상화한 인터페이스가 필요했습니다. 그때 해당 인터페이스의 이름을 어떻게 해야 할까 고민하다가, '레이어드 계층에 따르면 dao는 repository 계층이기 때문에 Repository로 인터페이스 명을 지으면 되겠다!'라고 생각했습니다.

그런데 찾아보니 repository는 제가 생각한 개념이 다른 개념이네요😅

---

### Dao vs Respository

Dao는 테이블과 `일대일로 매핑`되는 객체로, 서비스 레이어와 db에 저장 로직을 완전히 분리하기 위해 사용됩니다. 예를 들어 `reservation`테이블, `reservation_time`테이블을 각각 매핑합니다. 해당 dao는 테이블에 접근하기 위한 쿼리문이 있습니다.

Repository는 객체의 참조를 캡슐화 하는 역할을 합니다. 예를 들어, 현재 `Reservation`객체는 `ReservationTime`객체를 참조합니다. 즉, `Reservation`을 저장할 때, `ReservationTime`을 같이 저장해야 합니다. 이러한 이유로 `ReservationService`는 `ReservationDao`와 `ReservationTimeDao`를 가지고 있습니다. `ReservationService`를 통해 `Reservation`이 `ReservationTime`을 참조하고 있다는 것을 알 수 있습니다. 이를 추상화 시켜주는 것이 repository입니다.

---

### 수정 사항
(1) 먼저 제가 인터페이스로 작성한 `~Repository`는 DAO를 추상화한 것이므로 `~Dao` 로 네이밍을 수정했습니다. 밑의 구현체는 Impl 등을 써서 Dao임을 명시했습니다.
(2) 현재 제 `ResrvationService`는 참조에 대한 값이 노출되었기 때문에 repository 개념을 도입해서 해당 참조를 캡슐화했습니다.

2024-05-05 08:32 UTC, ehBeak commented on src/main/java/roomescape/service/ReservationService.java
> +        }
해당 검증 로직을 거치기 위해서는 아래와 같은 단계를 거쳐야 합니다.
(1) 사용자가 `예약 날짜`,` 예약 시간 아이디` 등으로 예약 등록을 요청합니다.
(2) `예약 시간 아이디`로 실제 `예약 시간`을 조회합니다. **<- 이 과정에서 DB에 연결되어야 합니다.**
(3) `예약 시간`과 '예약 날짜'를 통해 `LocalDateTime` 타입인 `reqestDateTime` 변수를 생성합니다.
(4) reqestDateTime 객체가 LocalDateTime.now() 보다 이전 시간이면 예약할 수 없습니다.

때문에 DB와 연결되어야 검증할 수 있는 로직입니다!

2024-05-05 08:56 UTC, ehBeak commented on src/main/java/roomescape/service/ReservationService.java
> +        }
변수인 `countReservation`로 받는 과정에서 `queryForObject` 메서드를 사용합니다. [공식 문서](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html#queryForObject(java.lang.String,java.lang.Class))에 따르면, `queryForObject`는 쿼리 실행 결과가 `null`일 때 `null`을 반환합니다. 

쿼리의 실행 결과가 왜 `null`이 나올 수 있는 경우가 있을 지는 감이 안 잡히나, '중복 예약'인 경우에만 쿼리의 실행 결과가 `null`이 나오는 것은 아닌 것 같습니다😅 해당 부분은 삭제했습니다!

다만, null을 반환되는 경우는 쿼리가 정상적으로 실행되지 않은 것이기 때문에 `NPE`를 메시지와 함께 발생시키도록 예외처리 했습니다!

2024-05-05 09:05 UTC, ehBeak commented on src/main/java/roomescape/service/ReservationService.java
> +    public List<MemberReservationTimeResponse> getMemberReservationTimes(LocalDate date, long themeId) {
> getMemberReservationTimes 어떤 행위인지 잘 이해가 안됩니다 😢

`getMembersReservationTimes`은 예약이 되어있는 시간인지 아닌지 확인하기 위해 호출하는 함수입니다.
이 뜻을 잘 살리기 위해서 함수 명을 `getIsReservedTime` 으로 수정했습니다. 또한 반환하는 `MemberReservationTimeResponse` 객체 또한 `IsReservedTimeResponse`으로 변경했습니다!

2024-05-05 09:20 UTC, ehBeak commented on src/main/java/roomescape/service/ReservationService.java
> +    public List<MemberReservationTimeResponse> getMemberReservationTimes(LocalDate date, long themeId) {
> 시간순으로 정렬이 되어야 할 것 같아요
데이터가 너무 없습니다 😢 검증하려면 하나하나 데이터를 추가해야되는데 여러 데이터셋이 있으면 좋을 것 같아요. 테마의 경우도 popular가 10개라면 최소 11개는 있어야 될 것 같고, 예약도 몇가지 케이스를 추가해주세요!

넵 맞습니다.. 저도 그 부분이 부족하다고 생각했는데, 시간이 없어서 반영을 못했습니다..🥲 반영하겠습니다!

2024-05-06 05:40 UTC, ehBeak commented on src/main/java/roomescape/model/ReservationTime.java
>  public class ReservationTime {
네 `responseDto`와 `JsonFormat`을 사용하여 수정했습니다~

2024-05-06 06:03 UTC, ehBeak commented on src/test/java/roomescape/controller/ThemeControllerTest.java
> +        assertThat(popularThemes).containsExactly(
> 두개의 assert문이라면 assertAll을 활용해주세요~

assertThat을 사용하면, 중간에 테스트를 실패하면 테스트가 멈추지만, assertAll을 사용하면 멈추지 않고 끝까지 테스트할 수 있습니다. assertSoftly 또한 assertAll과 같은 역할을 합니다. assertSoftly는 assertAll과 달리 기대값과 실제값만 보여주는 것이 아니라 실패한 코드 라인의 위치를 표시해 준는 장점이 있습니다. 때문에 assertSoftly를 사용했습니다!

2024-05-06 07:11 UTC, ehBeak commented on src/test/java/roomescape/controller/ThemeControllerTest.java
> +        assertThat(popularThemes).containsExactly(
> 근데 컨트롤러 테스트에서 사실 200만 검증해도 되지 않나요?
> 데이터 검증을 위한 통합 테스트를 service에서 진행해보는건 어떨까요?

요청부터 데이터 접근까지 모두 테스트하는 통합 테스트가 필요하다 생각했는데, 통합 테스트를 제일 상단 레이어인 컨트롤러 테스트에서 하게 되었네요😅 

컨트롤러 테스트에서는 어떤 값을 보통 검증하나요?
상태 코드만을 검증하면 될까요? 현재 제 코드에서는 컨트롤러가 아래와 같은 역할을 합니다.
* service에서 받은 도메인을 반환하거나 response 객체로 매핑한 뒤 반환한다.
* 헤더의 값을 초기화 한다.
* 상태 코드를 반환한다.

여기서 서비스를 이용해서 '헤더의 값을 초기화 한다'와 '상태 코드를 반환한다'를 검증할 수 있는 방법은 있지만, 
서비스에서 받은 값을 제대로 매핑하는지, 반환하는지 확인하기 위해서는 fake 객체를 써야 할까요?

2024-05-06 07:16 UTC, ehBeak commented on src/test/java/roomescape/controller/ThemeControllerTest.java
> +        assertThat(popularThemes).containsExactly(
추가로, 제가 이해한 통합 테스트는 http 요청부터 응답까지 전 과정을 테스트 하는 것으로 이해했는데요..! 
service에서 통합 테스트를 진행하면 현재 ServiceTest에서 사용 중인 FakeDao를 없애고 http 요청을 위해 RestAssured를 사용하여 요청을 보내는 것을 말씀하시는 걸까요?

'service 또한 단위 테스트로 진행되어야 하는 것이 아닌가?'라는 생각이 들어서요..! 통합 테스트를 따로 만들어야 하는 것이 아닌지 궁금합니다!

2024-05-06 07:46 UTC, ehBeak commented on src/test/java/roomescape/service/FakeThemeRepository.java
> +    public List<Theme> findThemeRankingByDate(LocalDate before, LocalDate after, int limit) {
이렇게 하드 코딩을 하면 Fake객체를 사용하는 테스트가 Fake객체에 상당히 의존적이게 됩니다.
때문에 Fake 객체 내부의 값이 조금이라도 바뀌면 테스트가 깨지고 테스트를 작성할 때, Fake 객체 내부의 값을 알아야 합니다.
이러한 이유로 `findThemeRankingByDate` 메서드의 내부 구현을 하드코딩하지 않고 구현하도록 수정해야 합니다. 

그런데, 해당 메서드인 `findThemeRankingByDate`가 실제로 동작하도록 구현하려면 `FakeThemeRepository` 뿐만 아니라 `Theme` 객체와 연관된 `Reservation` 객체의 레포지토리인 `FakeReservationRespository`와 `FakeRservationTimeRepository`를 이용해야 합니다. `FakeThemeRepository`가 `FakeReservationRepository`와 `FakeReservationTimeRepository`까지 사용하면서 복잡하게 내부 구현을 해야 하는지 의문이 듭니다.. 때문에 하드 코딩을 한 것이고요..! 

(사실 이렇게 복잡한 내부 구현을 어떻게 해야 할 지 감이 오지 않아 하드코딩을 한 것도 있습니다...😢)

2024-05-06 07:48 UTC, ehBeak commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
>개발자가 의도하지 않은 예외는 어떻게 처리되나요? 

혹시 개발자가 의도하지 않은 RuntimeException 과 같이 최상위 Exception이 터지는 경우를 말씀하시는 걸까요?
이 부분에 대해서 예외가 발생하면 서버 에러로 응답을하도록 수정했습니다!

2024-05-06 09:40 UTC, ehBeak commented
안녕하세요! 썬 😁

리뷰를 반영하다보니, 요청이 많이 늦어졌네요..🥲 최대한 반영하려고 했지만 많이 부족한 점이 보일 것 같습니다..!
리뷰어님 덕분에 많은 것을 고민해볼 수 있는 기회가 되었어요. 감사합니다 :)
다음 요청 때까지 더 고민하고 최대한 반영해 보겠습니다~

2024-05-07 14:06 UTC, syoun602 requested changes
안녕하세요 배키!

리뷰 반영하신거 확인했습니다 👍
추가적인 코멘트 남겨봤는데, 거의 답변 또는 사소한 코멘트라 
빠르게 변경가능할 것 같아서 확인 후 재요청주세요 😊

2024-05-07 23:35 UTC, ehBeak commented on src/main/java/roomescape/repository/ReservationDAO.java
>  public class ReservationDAO implements ReservationRepository {
네 맞습니다..! Repository 개념을 도입했으나, 로직이 더욱 복잡해지는 것 같아 다시 service 계층에서 dao를 바로 사용하는 것으로 수정했습니다😄

2024-05-08 00:46 UTC, ehBeak commented on src/main/java/roomescape/repository/ReservationDaoImpl.java
> +        Map<String, Object> parameters = new HashMap<>(4);
> 숫자를 넣게되면 추후 유지보수가 불편할 것 같은데 어떻게 생각하시나요?

HashMap의 초기 용량은 16이기 때문에, 최대한 메모리를 덜 쓰기 위해서 위와 같이 초기 용량을 정해줬던 것 같습니다..😅 그런데 나중에 인자가 바뀌거나 할 때, 놓치기 쉬운 부분인 것 같아요. 인자가 늘어나면 오히려 더 비용이 들고요..! 이 부분 수정하겠습니다~

2024-05-08 00:49 UTC, ehBeak commented on src/main/java/roomescape/repository/ReservationDaoImpl.java
> +        Map<String, Object> parameters = new HashMap<>(4);
> 또한, SqlParameterSource에 대해 알고 계실까요~?

잘 몰라서 찾아보니, `map`을 이용해서 인자를 넣는 것이 불편한 경우 사용되는 인터페이스라고 합니다. ([글](https://docs.spring.io/spring-framework/reference/data-access/jdbc/simple.html#jdbc-simple-jdbc-parameters)) 객체를 바로 넣어줄 수 있네요..! `BeanPropertySqlParameterSource`를 사용하도록 수정했습니다~

2024-05-08 01:54 UTC, ehBeak commented on src/main/java/roomescape/service/ReservationService.java
> +        if (count == null || count <= 0) {
앗.. 맞습니다. `reservationDao`의 `countReservationById`함수는 null 값을 반환하면 0을 반환하도록 구현했습니다. 

이 메서드는 개수를 반환하는 메서드입니다. 만약 해당 메서드가 null을 반환한다면 반환할 것이 없다는 뜻이고 이는 0으로 반환할 수 있다고 봤기 때문입니다.

때문에 반환 값을 Long 타입이 아닌 long 타입을 반환하도록 하고 reservationDao를 사용하는 service 계층에서 null 체크를 하지 않도록 구현했습니다!

2024-05-08 01:54 UTC, ehBeak commented on src/main/java/roomescape/service/ReservationService.java
> +        if (count == null || count <= 0) {
리뷰 주신 내용은 삭제했습니다 :) 감사합니다!

2024-05-08 13:54 UTC, syoun602 approved these changes
안녕하세요 배키! 

리뷰 반영해주신 것 모두 확인했습니다 👍👍
충분히 얘기해본 것 같아서 다음 단계 진행해주세요 고생 많으셨습니다 😊

2024-05-08 13:54 UTC, merged