[1 - 3단계 방탈출 사용자 예약] 이든(최승준) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #57
Opened 2024-05-02 08:40 UTC by PgmJun

안녕하세요 웨지! 이든입니다.

2024-05-02 14:30 UTC, PgmJun commented on README.md
> +| GET    | `/reservations/themes/{themeId}?date` | 특정 날짜의 특정 테마 예약 정보 조회 |                                        | `@RestController` |
API URI를 최대한 RESTful하게 설계해보려고 노력했는데요.
`/reservations` 컬렉션 내부에 서브 컬렉션인 `/themes`를 넣어준 이 URI Endpoint는 어떻게 설계하면 좋을 지 고민이 많이 되었던 부분입니다.
자원을 적절하게 명시해주고 있는 지, 그리고 변경해야할 것 같다면 어떻게 변경하면 좋을 지 웨지의 의견이 궁금합니다!

2024-05-02 14:59 UTC, PgmJun commented on README.md
> +| GET    | `/themes/top?count`                   | 인기순 테마 조회             |                                        | `@RestController` |
이 부분도 Endpoint를 설계할 때 너무 고민이 됐어요.
top으로 인기순 테마 조회 Endpoint를 설계해보았는데 괜찮을 지 의견 남겨주시면 감사하겠습니다!

2024-05-02 15:44 UTC, PgmJun commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<ReservationAvailableTimeResponse>> readAvailableTimeReservations(
이 부분은 List로 return하는 것도 괜찮을까요?
아니면 List<ReservationAvailableTimeResponse>를 감싼 DTO 객체로 리턴해주는 것이 좋을까요?
개인적으로는 DTO로 리턴해야 Response하는 데이터의 변경에 유연해질 것 같아요
웨지의 생각은 어떤지 궁금해요!

2024-05-02 15:47 UTC, PgmJun commented on src/main/java/roomescape/controller/ThemeController.java
> +@RequestMapping("/themes")
현재는 모든 코드들이 이렇게 공통 endpoint를 묶어 관리하고 있는 형태인데요.
이 코드를 제거하고 각각의 매핑 애노테이션에서 endpoint 전체를 가지고 있게 변경하려고 합니다.
그렇게 관리해야 엔드포인트로 컨트롤러 메서드를 탐색하는 과정이 훨씬 수월해져서 유지보수에 이점이 있을 것 같아요!
웨지는 어떻게 생각하시나요?

2024-05-02 15:49 UTC, PgmJun commented on src/main/java/roomescape/controller/ReservationController.java
> +            @DateTimeFormat(pattern = "yyyy-MM-dd") LocalDate date) {
이 부분은 개행이 많이 어색해서 변경해보겠습니다!

2024-05-02 15:51 UTC, PgmJun commented on src/main/java/roomescape/controller/ThemeController.java
> +    public ResponseEntity<List<ThemeResponse>> readTopNThemes(@RequestParam int count) {
현재는 거의 모든 메서드의 인자에 final 처리가 되어있지 않은 상태인데요.
메서드의 인자 값에 변경이 필요하지 않은 부분들은 final로 재할당을 막아
예상치 못한 인자 값 변경으로 인한 사이드 이펙트를 방지해 볼 생각인데
이런 처리를 해주는 것에 대해서 웨지는 어떻게 생각하시나요??

2024-05-02 15:56 UTC, PgmJun commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +        String name,
`@NonNull` 처리가 되어있어도
정상적인 요청값이 아닌 Blank는 입력이 가능해서 이 부분은 개선하기 위한 로직을 구현해볼 생각입니다.

그런데 요청을 받는 측에서만 입력값을 검증할 지, 아니면 요청부와 도메인 객체 내부에서 모두 검증할 지 고민이 되어 웨지의 생각은 어떠신지 궁금합니다.

또한 간편한 검증을 위해 미션 상에서는 아직 알려주진 않았지만 `Spring-Validation` 의존성을 추가해서 처리해보는 것에 대해서는 어떻게 생각하시는지 궁금합니다!

2024-05-02 16:02 UTC, PgmJun commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +    public Reservation toReservation(Time time, Theme theme) {
DTO 객체에서 내부 값을 활용하여, 관련된 도메인 객체를 생성하는 책임을 갖는 것이 괜찮은 로직인지 궁금합니다.

크게 문제될 것은 없어보이지만, 저는 미션을 수행할 때 잘 모르겠어서 이렇게 구현하지 않았었는데 페어의 이런 코드를 보니 간편하고 좋아보였습니다.
이런 로직도 괜찮을까요?

2024-05-02 16:08 UTC, PgmJun commented on src/main/java/roomescape/repository/ReservationRepository.java
> +        return jdbcTemplate.query(sql, ROW_MAPPER, date, themeId);
이 메서드는 특정 date의 특정 themeId를 통해
특정 날짜에 예약이 되어있는 테마의 예약 시간 정보(reservation_time.id, reservation_time.start_at) 를 조회하기 위해 사용됩니다.

하지만 예약 시간 정보만 필요함에도 불구하고 TimeRepository가 아닌 ReservationRepository에 있습니다.
때문에 이 부분을 TimeRepository로 이전할 예정입니다.
쿼리도 time 테이블을 기준으로 reservation 테이블과 JOIN하도록 변경될 예정입니다.

2024-05-02 16:09 UTC, PgmJun commented on src/main/java/roomescape/repository/ReservationRepository.java
> +    public int delete(Long id) {
id를 바탕으로 delete 처리를 해주는데 그저 delete라고만 표시하는 메서드의 네이밍이 어색해서,
deleteById로 변경해볼 예정입니다!

2024-05-03 02:44 UTC, PgmJun commented on src/main/java/roomescape/repository/ReservationRepository.java
> +public class ReservationRepository {
시간 상 바꾸진 못했지만 Repository라는 네이밍은 Dao로 변경하려고 합니다.
Repository 패턴보다는 Dao에 가까운 것 같다고 생각해서요!

2024-05-03 04:50 UTC, PgmJun commented on src/test/java/roomescape/service/TimeServiceTest.java
> +    }
Repository를 다루는 테스트는 직접 생성하지 않고도 `@Import` 애노테이션으로 깔끔하게 처리해볼 수 있을 것 같아서, 변경을 해볼까합니다! 괜찮을까요?

그리고 웨지는 `@JdbcTest`를 사용하는 경우, `Repository` 또는 `Service` 와 같은 스프링 컨테이너에 등록 되어있는 빈들을 어떻게 사용하시나요?? 궁금합니다!

(추가로 `@SpringBootTest`를 사용하지 않은 이유는 필요 이상의 빈들을 생성하는 해당 애노테이션을 사용하기 보단 `@JdbcTest`를 통해 최소한의 빈만 생성하여 다루기 위함이었습니다.)

2024-05-03 05:21 UTC, sihyung92 requested changes
안녕하세요 이든~ 리뷰어 웨지입니다!
남겨주신 코멘트 들에 대한 답변과 리뷰를 남겼으니 확인해주셔요!
감사합니다!

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/controller/ThemeController.java
> +    public ResponseEntity<List<ThemeResponse>> readTopNThemes(@RequestParam int count) {
전 모든 파라미터 / 지역 변수 final에 대해 부정적인 편입니다
final 이라는 제약이 주는 코드의 유지보수성 향상에 대해선 동의합니다만
java라는 언어가 자동 final을 지원하지 않는데서 주는 불편감이 더 큽니다

인자 final 규칙은 모든 코드에 적용해야만 비로소 효과가 생기는데 (final이 붙어 있지 않으면 가변임을 예상할 수 있음) 자동으로 처리가 안 되다 보니 팀원들에게 강요하기가 어렵습니다. 의식하고 있어도 자주 빠지기도 하구요.
지켜지지 못할 규칙이라면 없는게 낫다고 생각하기 때문에 굳이 final를 권장하진 않습니다.
하겠다는 사람 말리지도 않지만요.

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/global/exception/ExceptionController.java
> +        return new ResponseEntity<>("요청 형식이 잘못되었습니다.", HttpStatus.BAD_REQUEST);
예외는 String body 응답보다는 예외 객체를 하나 정의하셔서 응답하시는 걸 권장합니다.
확장성 측면에서 유리합니다.

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +public class ReservationRepository {
이든이 생각하시는 repository와 dao의 차이점은 뭔가요?

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +        return jdbcTemplate.query(sql, ROW_MAPPER, date, themeId);
time 테이블에 left 조인을 통해서 1번의 쿼리로 찾아오시겠다는 아이디어로 보이는데, 새롭게 코드 개편해주시면 보겠습니다.
현재 방식 (시간 findAll -> 해당 시간 예약 찾기 -> 어플리케이션에서 조합)보다는 좋아보이네요

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/repository/ThemeRepository.java
> +    public List<Theme> findTopNByReservationCount(LocalDate startDate, LocalDate endDate, int count) {
마지막 인자 count 는 limit에 전달하니 limit라고 명시해주는게 나아보이네요.

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/repository/ThemeRepository.java
> +                SELECT t.*, COUNT(r.theme_id)
COUNT(r.theme_id)는 활용하지 않는데 select 절에 선언하지 않아도 되겠네요.

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/service/ThemeService.java
> +
좀더 유연한 API 설계를 하려면 이런 변수들은 API 파라미터로 추가하는 게 좋습니다. 
validation도 필요해지겠지만요.

이렇게 할 경우 앞으로 다양한 요구사항에 대해 재수정 / 재배포 없이 대응할 수 있는 코드가 됩니다

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +        String name,
의존을 받는 방향을 생각해보세요. 컨트롤러는 도메인을 알지만 도메인은 컨트롤러를 모릅니다.
그렇다면 도메인을 구현할 때는 컨트롤러에서의 방어에 의존하기 보다는, 자체적인 보호수단을 갖추어야 합니다.

즉 "도메인은 컨트롤러에서의 validation이 있는지 모른다"는 전제하에 코드를 짜야 하므로, controller에서 적절한 예외 응답을 위한 예외처리와 별도로 자체적으로 방어코드를 구현해야합니다.

Spring-Validation은 학습을 위해 반대하겠습니다 ㅋ.ㅋ 쉽게 얻은 것은 쉽게 잃는 법이라는게 제 지론입니다

2024-05-03 05:21 UTC, sihyung92 commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +    public Reservation toReservation(Time time, Theme theme) {
네 괜찮다고 생각합니다. 어차피 controller 패키지 중 어떤 class라도 domain 패키지를 안다면, 패키지간의 의존관계가 생성되었다고 볼 수 있습니다. 패키지간 의존관계가 양방만 아니라면, 이정도의 편의메서드는 좋은 패턴입니다.

2024-05-04 06:30 UTC, PgmJun commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<ReservationAvailableTimeResponse>> readAvailableTimeReservations(
만약 지금처럼 List로 전송하는 API가 있을 때,
다음 버전의 서버 애플리케이션에서 어떠한 데이터를 추가로 보내주게 되면 그때서야 객체로 response할텐데
이 시점에서 서버의 Response JSON이 List에서 객체로 되기 때문에 []에서 {}로 형태로 변경되기 때문에
클라이언트에서도 변경이 발생해야하는 문제를 말씀하신 거군요!

거기까지는 생각해보지 못했는데 정말 좋은 의견인 것 같습니다.
데이터 변경에 유연해진다는 장점만을 가진 줄 알았는데 훨씬 중요한 이유가 있었네요.
감사합니다:)

2024-05-04 06:33 UTC, PgmJun commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<ReservationAvailableTimeResponse>> readAvailableTimeReservations(
이때 Endpoint를 통해 버전을 관리하는 방식(ex. /api/v1/reservations/themes/1 -> /api/v2/reservations/themes/1) 으로 해결해볼 수도 있지 않을까 싶지만
그렇게 하더라도 Json 파싱 방식이 변경되는 건 클라이언트 측에도 귀찮은 문제가 되겠네요:)
바로 반영해보겠습니다!

2024-05-04 06:50 UTC, PgmJun commented on src/main/java/roomescape/controller/ThemeController.java
> +    public ResponseEntity<List<ThemeResponse>> readTopNThemes(@RequestParam int count) {
저도 다 처리해줄 게 아니면 오히려 의도가 불분명한 코드가 될 수도 있다는 생각이 있는데요

인텔리제이에 자동으로 final 키워드를 추가해주는 기능이 있기도하고 개인적으로 사이드이펙트를 방지하는데에 좋다는 생각이 들어서
저는 처리해보겠습니다:)

https://stackoverflow.com/questions/9579403/intellij-idea-automatically-add-final-keyword-to-the-generated-variables

2024-05-04 06:52 UTC, PgmJun commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +        String name,
"도메인은 컨트롤러에서 검증을 하는지 모른다."가 정말 공감되는 내용이네요:)
한번 처리해보겠습니다.
Spring-Validation없이..! 한 번 해보겠습니다 ㅋㅋㅋㅋ 화이팅..!!!

2024-05-04 07:51 UTC, PgmJun commented on src/main/java/roomescape/service/ThemeService.java
> +
동의합니다:)
이 부분도 웨지가 말씀하셨던 것처럼 고민하던 부분이었는데, TODO를 적어두지 않아서 잊힐 뻔했네요!
감사합니다.

추가적으로 이렇게 날짜/시간 데이터를 
API 파라미터가 아닌 애플리케이션 코드 내에서 관리하는 경우에 대해 제가 생각했던 문제도 공유드릴테니 괜찮은 근거인지 봐주시면 감사하겠습니다!

만약 당일까지 신청가능한 어떤 행사에 대해
유저가 행사 신청 요청을 23:59:59에 보냈다고 했을 때,
API에서 요청시간을 관리하지 않으면 서버로 데이터가 도달하는 동안, 시간이 다음날 00:00:00으로 지나버려서
제 시간 내에 신청했음에도 불구하고 신청이 불가능해지는 상황도 있을 거라고 생각이 들었습니다.

지금 만드는 서비스에서도 방탈출을 예약할 때 위와 같은 상황이 발생해서
바로 방탈출을 즐길 수 있었음에도 불구하고 서버에서 현재 시간을 확인하기 때문에 예약에 실패해서 다음 시간대까지 기다려야하는 문제가 발생할 수 있을 것 같다고 생각이 드네요.

제가 근거를 잘 생각한 것이 맞을까요??

2024-05-04 07:56 UTC, PgmJun commented on src/main/java/roomescape/service/ThemeService.java
> +
추가적으로 today 데이터를 Request로 받아야하는 이유는 아래와 같은 이유도 있을 것 같아요!

만약 당일까지 신청 가능한 어떤 행사에 대해
유저가 행사 신청 요청을 23:59:59에 보냈다고 했을 때,
API에서 요청 시간을 받지 않으면 서버로 데이터가 도달하는 동안, 시간이 다음날 00:00:00으로 지나버려
제 시간 내에 신청했음에도 불구하고 신청이 불가능해지는 상황도 있을 거라고 생각이 들었습니다.

지금 만드는 서비스에서도 방탈출을 예약할 때 위와 같은 상황이 발생해서
바로 방탈출을 즐길 수 있었음에도 불구하고 서버로 요청이 도달하는 동안 시간이 지나, 예약에 실패해서 다음 시간대까지 기다려야하는 문제가 발생할 수 있을 것 같다고 생각이 드네요.

제가 근거를 잘 생각한 것이 맞을까요??

2024-05-04 08:03 UTC, PgmJun commented on src/main/java/roomescape/repository/ThemeRepository.java
> +                SELECT t.*, COUNT(r.theme_id)
그렇네요! 제거하겠습니다
확인 감사합니다!

2024-05-04 15:58 UTC, PgmJun commented on README.md
> +| GET    | `/reservations/themes/{themeId}?date` | 특정 날짜의 특정 테마 예약 정보 조회 |                                        | `@RestController` |
결론적으로 얻고자하는건 시간까지 포함된 예약 여부와 예약 시간들인데 `times`가 빠지니 어색하게 느껴지긴 하네요!
`/reservations/themes/{themeId}/times?date` 이렇게 변경해보면 좋을까요?

2024-05-04 16:06 UTC, PgmJun commented on README.md
> +| GET    | `/themes/top?count`                   | 인기순 테마 조회             |                                        | `@RestController` |
그렇게도 처리해줄 수 있겠네요:)
지금 상황에서 어떤 게 더 좋은 설계일지 한번 고민해보겠습니다. 감사합니다!

2024-05-04 16:09 UTC, PgmJun commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +    public Reservation toReservation(Time time, Theme theme) {
의존관계 때문에 조금 찝찝한 부분이 있었는데
양방향 의존관계가 아니라면 고려해보아도 괜찮은 메서드군요!
이 부분에 대한 기준이 머릿속에 조금 자리가 잡힌 것 같습니다. 감사합니다

2024-05-04 16:18 UTC, PgmJun commented on src/main/java/roomescape/repository/ReservationRepository.java
> +public class ReservationRepository {
제가 조금 학습해본 내용을 바탕으로 설명드려보겠습니다.

### Repository와 DAO의 차이

일반적으로 데이터베이스 테이블과 1:1 매핑되는 `DAO`는 매핑된 DB 테이블에 대한 CRUD 작업을 캡슐화하며
비즈니스 로직과 데이터 엑세스 로직을 분리하기 위해 사용한다고 알고 있습니다.

`Repository`는 DDD 관점에서 도메인 엔티티 객체의 컬렉션 역할을 수행하기 위해 등장한 패턴이며,
때문에 DB와 더 가까운 DAO와는 다르게 도메인에 가까운 객체인 것으로 알고 있습니다.

이러한 `Repository`는 하나의 도메인 엔티티와 관련된`DAO`들을 사용하여
해당 도메인 엔티티 객체의 컬렉션과 같은 로직을 수행하는 것으로 알고 있는데 제대로 알고 있는 것이 맞을까요?

2024-05-04 16:23 UTC, PgmJun commented on src/main/java/roomescape/global/exception/ExceptionController.java
> +        return new ResponseEntity<>("요청 형식이 잘못되었습니다.", HttpStatus.BAD_REQUEST);
위에 Response를 List로 전달할지 Object로 전달할 지에 대해 질문드렸던 내용과 비슷한 맥락인 것 같네요.
한 번 반영해보겠습니다.

2024-05-04 16:24 UTC, PgmJun commented on src/main/java/roomescape/repository/ThemeRepository.java
> +    public List<Theme> findTopNByReservationCount(LocalDate startDate, LocalDate endDate, int count) {
count보단 limit가 훨씬 명확하겠네요!
바로 변경해보겠습니다.

2024-05-05 01:55 UTC, sihyung92 commented on src/test/java/roomescape/service/TimeServiceTest.java
> +    }
> Repository를 다루는 테스트는 직접 생성하지 않고도 @Import 애노테이션으로 깔끔하게 처리해볼 수 있을 것 같아서, 변경을 해볼까합니다! 괜찮을까요?

넵넵 ㅎ

> 웨지는 @JdbcTest를 사용하는 경우, Repository 또는 Service 와 같은 스프링 컨테이너에 등록 되어있는 빈들을 어떻게 사용하시나요?

JdbcTest와 같은 슬라이스 테스트 전용 어노테이션을 사용할 때는 `@ComponentScan`을 활용하여 추가빈들을 주입하는 편입니다
(한 두 개면 직접 Import하는 경우도 있는데 프로젝트 규모가 켜지면 패키지 단위의 범용적인 규칙을 설정할 수 있는 ComponentScan 등을 활용하게 되는 것 같습니다)

2024-05-05 02:02 UTC, sihyung92 commented on README.md
> +| GET    | `/reservations/themes/{themeId}?date` | 특정 날짜의 특정 테마 예약 정보 조회 |                                        | `@RestController` |
아 해당 리뷰는 제 착각에서 비롯된 것도 있네요 죄송합니다 🙇‍♂️

잘못 생각한 부분 -> 
- `/reservations/themes`만 있고 `/themes`는 없음
- `/times`는 있음
-> 리소스 상 theme는 reservation의 하위 개념으로 명시되는데 times는 별도 리소스로 취급한 것으로 생각

그런데 말씀주신것처럼 해당 API의 응답 결과가 themes가 아닌 theme의 시간인거 같아서 말씀주신 방향으로 수정하는게 좋을거 같네요 (뒷걸음질 치다 쥐 잡았네요ㅎ)

2024-05-05 05:27 UTC, PgmJun commented on src/test/java/roomescape/service/TimeServiceTest.java
> +    }
컴포넌트 스캔을 활용하는 방법도 있겠군요
좋은 인사이트를 얻은 것 같습니다 감사합니다:)

지금은 프로젝트 규모가 크지 않으니 Import로 처리하겠습니다!

2024-05-05 15:21 UTC, PgmJun commented on src/main/java/roomescape/repository/ReservationRepository.java
> +        return jdbcTemplate.query(sql, ROW_MAPPER, date, themeId);
처리해보겠습니닷!

2024-05-06 02:48 UTC, sihyung92 commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<ReservationAvailableTimeResponse>> readAvailableTimeReservations(
> 이 경우 반드시 서버와 프론트엔드가 반드시 동시 배포해야 하고, 배포 과정 중 오류가 발생하는 것을 피할수 없으므로 동일한 역할을 하는 새로운 API를 제공하게 되는 안티패턴이 됩니다

이 부분이 말씀해주시는 API 버저닝과 관계있습니다 ㅎ
버전이 하나씩 늘어날수록 클라이언트 뿐만 아니라 서버도 관리해야하는 코드가 늘어나고, 항상 하위버전을 신경써야합니다 
그렇다고 하위버전을 Deprecated 하는 것도 매우 어렵습니다

외부사에 API를 제공하는 경우 API 버전을 올렸다고 맞춰달라고 하는것조차 쉽지 않기 때문입니다 (상대 회사의 개발력을 투입해야함) 
그게 중대한 기능변경이라면 요청이 가능하겠지만 사소한 이유로 버전을 변경할 경우 설득 조차 쉽지 않겠죠 ㅎ

인하우스 기능(사내 서버만 활용하는 API)이라고 쉽냐고 물어보면 그렇지도 않습니다. 회사 전체 채널로 3개월씩 공지해도 각자의 일로 바쁘므로 하위버전 API를 계속 사용하는 팀이 나옵니다

손쉬운 해결책으로 보여도 매우 고난한 길이니 가급적 가시지 않기를 권합니다 ㅋㅋ

2024-05-06 02:51 UTC, sihyung92 commented on src/main/java/roomescape/repository/ReservationRepository.java
> +public class ReservationRepository {
넵 적절히 학습해주신 것 같습니다 ㅎ

2024-05-06 02:56 UTC, sihyung92 commented on src/main/java/roomescape/service/ThemeService.java
> +
말씀하신 `요구하지 않던 데이터`의 성격에 따라 달라집니다.

가능한 범용적인 API 한개에서 제공하면 좋습니다만, 
검색조건 이라는 건 보통 테이블의 join을 통해 이루어집니다. 
만약 기존 API 요구사항의 비기능적 요구사항(성능 등)을 못 지킬 정도의 검색조건이 추가되면 분리될 필요가 생기겠죠

> 결국 의도가 불분명한 API로 변질될 수 있다는 우려가 있어

이건 추가되는 검색조건 파라미터 명으로 충분히 표현될거라고 생각합니다
정말 의도가 모호해질만큼의 검색조건이라면 (그런게 뭐가 있을지 싶지만) 분리도 고려해볼 수 있겠죠

2024-05-06 03:46 UTC, PgmJun commented on src/main/java/roomescape/controller/ReservationController.java
> +    public ResponseEntity<List<ReservationAvailableTimeResponse>> readAvailableTimeReservations(
실무의 세계란 정말 고려할 사항들이 많네요!
웨지 덕분에 넓은 관점을 배워가는 것 같아요 🙂

2024-05-06 03:47 UTC, sihyung92 requested changes
안녕하세요 이든~ 리뷰어 웨지입니다!
리뷰 반영 잘 해주셨어요 ㅎ
추가 리뷰 남겨두었으니 확인해주세요. 
감사합니다!

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/global/dto/response/ApiResponse.java
> +        boolean isSuccess,
꼭 필요한가? 싶긴 한 필드입니다 ㅎ
success = true인 상황은 항상 2xx이고, 반대는 4xx나 5xx인 상황이라서요
오히려 2xx일 때 false거나 4xx일 때 true로 내려오면 더 헷갈릴거 같네요

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/global/exception/model/ConflictException.java
> +public class ConflictException extends CustomException {
ValidateException과 ConflictException의 차이점을 잘 모르겠습니다.
다른 개발자가 다른 비즈니스를 개발하다가 둘 중 하나를 골라야한다면 언제 어떤 오류를 선택해야할까요?

그리고 이걸 매번 설명하는 것보다 좀더 분명한 의미의 오류명이면 더 좋겠죠.

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/global/exception/error/ErrorType.java
> +    BAD_REQUEST("요청 형식이 잘못되었습니다."),
같은 코드끼리 뭉쳐놓는 것 아니었나요? `INVALID_ERROR` 와 `BAD_REQUEST`는 내외하는 이유가 있나요? ㅎㅎ

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +            throw new ValidateException(ErrorType.INVALID_ERROR, String.format("유효하지 않은 값입니다.%n%s", this.toString()));
너무 모호한 오류명입니다. 어떤 값이 왜 유효하지 않은지 설명해줘야하는데, 맥락없이 유효하지 않은 값이라고 하면 사용자에게 불친절한 API가 됩니다.
불친절한 API는 서버개발자에게 직통 전화로 연결되는 결과로 이어지니, 24시간 유선연락 대기조를 하고 싶은 게 아니시라면 가급적 친절한 API를 구성하시길 권합니다

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/global/dto/response/ApiResponse.java
> +        return new ApiResponse<>(false, errorType.getDescription(), null);
이렇게 처리되면 유저에겐 errorType의 description만 내려가게 되는데, errorType description이 범용적으로 구성되어있어 클라이언트에게 실질적인 내용을 전달하지 못합니다. 
오류 로깅용 메시지와 클라이언트 오류 응답용 메시지를 구분하는 것은 좋지만 클라이언트가 너무 불편해지지 않도록 신경써주세요.

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/service/ReservationService.java
> +            throw new ConflictException(ErrorType.RESERVATION_PERIOD_CONFLICT, "지난 날짜나 시간은 예약이 불가능합니다.");
기준이 되었던 현재날짜와 입력날짜를 응답하여 오류내용을 풍부화 해주면 좋습니다.

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/controller/ReservationController.java
> +        response.setHeader("Location", "/reservations/" + reservationResponse.id());
Location이라는 변수명이 실수할 여지가 있어서 수정 전 방식대로 활용하시는 것도 좋다고 생각합니다 ㅎ

이런 방법도 있습니다.
```java
    @PostMapping("/reservations")
    public ResponseEntity<ApiResponse<ReservationResponse>> saveReservation(
            @RequestBody final ReservationRequest reservationRequest
    ) {
        ReservationResponse reservationResponse = reservationService.addReservation(reservationRequest);

        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .path("/{id}")
                .buildAndExpand(reservationResponse.id())
                .toUri();

        return ResponseEntity.created(location).body(ApiResponse.success(reservationResponse));
    }
```

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/service/ThemeService.java
> +
이후 코드리뷰 중 themes/top API를 봤는데요, 해당 API의 경우 말씀하신것처럼 특정 용도에만 사용하도록 생성한 API이므로 너무 다른 요구사항을 많이 받아들이는 건 안 좋습니다 (사용자가 헷갈립니다)

직전 코멘트는 themes/search 처럼 범용적인 API를 구축한 경우에 해당해 말씀드렸습니다

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/dao/TimeDao.java
> +                ) rvt ON rt.id = rvt.id
보고 15초 정도 생각하다 생각을 멈췄습니다 ㅋ_ㅋ
제 생각엔 reservation_time와 reservation의 조인 1번으로 충분한 요구사항입니다 (LEFT JOIN 내부에서의 join은 불필요)

아마 이 쿼리는 DB 내 쿼리 옵티마이저 (쿼리 최적화 도구)가 1회 조인만 하도록 변경할 가능성이 높습니다.
1회 조인만 하도록 변경해보셔요 (불가능하다고 생각되면 말씀주셔요. 저도 개선 쿼리 안 짜봐서요)

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/service/ReservationService.java
> +public class ReservationService {
repository와 dao를 교환함으로써 어떤 아키텍처를 결정하시게 된 것인지 인지하고 계시면 좋습니다.

repository 패턴을 활용할 경우 도메인에서 데이터 전달체를 모르게 됩니다 (도메인에서 repository 인터페이스를 정의하고 구현체는 persistence layer에서 주입합니다)
이 경우 비즈니스 로직을 데이터 소스 종류와 상관없이 재활용 할 수 있게되지만 도메인 보호계층이 생겨서 복잡성이 증대됩니다.

dao를 도메인이 직접 의존하면 작성하신 코드 대로입니다. 비즈니스 로직(service 로직)이 특정 데이터소스 (DB)에 종속되어 있으므로 재활용이 어려우나 코드가 간결해지고 DB 요구사항에 직접적으로 맞출 수 있습니다.

특히 우테코는 어렵고 복잡하면 좋은 것이라고 생각하는 경향성이 있으나, 저는 반대입니다. 복잡성 자체가 악입니다. 복잡성을 도입하려면 타당한 이유가 있어야한다고 생각합니다. 

좀 더 적다가 너무 개인 의견이 많이 들어가서 생략했습니다 ㅋㅋ
두 패턴의 장단점에 대해 생각해보셔요. 둘 중 정답은 없습니다.

2024-05-06 03:47 UTC, sihyung92 commented on src/main/java/roomescape/service/ReservationService.java
> +                .isBefore(LocalTime.now()))) {
내부 조건식 가독성이 떨어져요.
깨진 유리창 효과 때문에 이런식으로 조건식을 만들어두면 다른 개발자들이 계속 || 와 괄호로 감싸진 조건식을 덧대게 됩니다

`requestDate.isBefore(today)`와 `(requestDate.isEqual(today) && time.getStartAt()
                .isBefore(LocalTime.now())`는 같은 추상화 수준이니 뒤 조건식을 메서드로 추출해서 더 쉽게 파악되도록 해주세요
```suggestion
        if (requestDate.isBefore(today) || 
            something(today, time)) {
```

2024-05-06 15:20 UTC, PgmJun commented on src/main/java/roomescape/global/exception/model/ConflictException.java
> +public class ConflictException extends CustomException {
검증 관련 예외는 ValidateException,
데이터 충돌(이미 존재하는 데이터를 다시 추가, 특정 데이터에 FK로 연관되있는 데이터를 삭제하려함) 관련 예외는 ConflictException으로 구분해보았는데
가독성이 많이 저하되어 보이나요?? 🥲

2024-05-06 15:21 UTC, PgmJun commented on src/main/java/roomescape/global/exception/error/ErrorType.java
> +    BAD_REQUEST("요청 형식이 잘못되었습니다."),
앗 이 부분은 실수입니다..! 처리해두겠습니다 감사합니다!

2024-05-06 15:32 UTC, PgmJun commented on src/main/java/roomescape/global/dto/response/ApiResponse.java
> +        return new ApiResponse<>(false, errorType.getDescription(), null);
서버의 어떤 데이터가 존재하지 않고, 왜 실패했는 지 등의 정보를 노출하는 것이 보안에 좋지 않다는 이야기를 많이 들어서
이렇게 처리하게 되었네요..
어느정도까지 노출할 지에 대한 기준을 잘 정하는 것이 중요하겠네요..
클라이언트에게 조금 더 친절한 정보를 내려주도록 변경해보겠습니다!

그리고 클라이언트의 요청 실패 시, 클라이언트에게 어느정도까지 정보를 내려줘야하는지에 대한 웨지의 기준이 궁금합니다!

2024-05-06 15:33 UTC, PgmJun commented on src/main/java/roomescape/service/ReservationService.java
> +            throw new ConflictException(ErrorType.RESERVATION_PERIOD_CONFLICT, "지난 날짜나 시간은 예약이 불가능합니다.");
확실히 더욱 이해하기 수월할 것 같다는 생각이 듭니다.
변경해보겠습니다!

2024-05-06 16:24 UTC, PgmJun commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +            throw new ValidateException(ErrorType.INVALID_ERROR, String.format("유효하지 않은 값입니다.%n%s", this.toString()));
> 24시간 유선연락 대기조를 하고 싶은 게 아니시라면 가급적 친절한 API를 구성하시길 권합니다

보안적인 부분을 생각한다는 것이 불친절한 응답값으로 이어졌네요..
이 내용을 기반으로 연락이 오지 않을 정도의 정보를 넘겨주도록 최대한 개선해보겠습니다!

2024-05-06 16:40 UTC, PgmJun commented on src/main/java/roomescape/controller/ReservationController.java
> +        response.setHeader("Location", "/reservations/" + reservationResponse.id());
`HttpHeaders.LOCATION` 을 활용하는 방식은 어떤가요??

2024-05-07 03:12 UTC, PgmJun commented on src/main/java/roomescape/service/ThemeService.java
> +
웨지 그렇다면 혹시 아래와 같은 코드는 어떨까요??
`API의 유연성`도 고려하고 싶고 `클라이언트의 편의성`도 고려하고 싶어
고민하는 과정에서 defaultValue를 활용해보면 어떨까 싶었습니다.

특정 용도에만 사용하는 API이기 때문에 클라이언트는 아무런 파라미터 없이도 `/themes/top` 에 요청을 보냄으로써
서버의 비즈니스 로직에서 정해놓은 범위의 값을 얻을 수 있고,
이후에 파라미터 값만 다른 API가 필요하다면 새로 API를 만들 필요 없이 해당 API를 재활용할 수 있어
유연한 코드라고 생각이 듭니다.
웨지의 생각은 어떠신가요??

```java
@GetMapping("/themes/top")
@ResponseStatus(HttpStatus.OK)
public ApiResponse<ThemesResponse> getTopNThemesBetweenDate(
        @RequestParam(required = false, defaultValue = "10") final int count,
        @RequestParam(required = false, defaultValue = "#{T(java.time.LocalDate).now().minusDays(7)}") final LocalDate startAt,
        @RequestParam(required = false, defaultValue = "#{T(java.time.LocalDate).now().minusDays(1)}") final LocalDate endAt
) {
    return ApiResponse.success(themeService.findTopNThemesBetweenDate(count, startAt, endAt));
}
```

2024-05-07 04:39 UTC, PgmJun commented on src/main/java/roomescape/dao/TimeDao.java
> +                ) rvt ON rt.id = rvt.id
으악 죄송합니다ㅋㅋㅋ
의미없는 조인을 해버렸네요..
의도하신 쿼리가 이게 맞나요?!

```sql
SELECT
    rt.id, start_at, IFNULL(is_reserved, 'False') AS is_reserved
    FROM reservation_time rt
    LEFT JOIN (
        SELECT r.time_id, 'True' AS is_reserved
        FROM reservation r
        WHERE r.date = ? AND r.theme_id = ?
) r ON rt.id = r.time_id
```

2024-05-07 04:49 UTC, PgmJun commented on src/main/java/roomescape/service/ReservationService.java
> +                .isBefore(LocalTime.now()))) {
```java
    private boolean isReservationInPast(final LocalDate requestDate, final Time requestTime, final LocalDateTime now) {
        LocalDate today = now.toLocalDate();
        LocalTime nowTime = now.toLocalTime();

        // 날짜가 지난 경우
        if (requestDate.isBefore(today)) {
            return true;
        }
        // 날짜가 오늘이지만, 지난 시간인 경우
        if (requestDate.isEqual(today) && requestTime.getStartAt().isBefore(nowTime)) {
            return true;
        }
        return false;
    }
```
혹시 검증 메서드의 이름을 지난 날짜에 대한 예약인 지 검증한다는 뜻의 isReservationInPast 로 설정하여 같은 추상화 수준을 만들어주고
위와 같이 조건문을 2개로 분리후 주석으로 의미를 정확히 표기해주는 것은 어떤가요??
필요하다면 메서드를 분리해주는 것도 좋지만, 같은 추상화 수준으로 묶어줄 수 있을 것 같아서요!

2024-05-07 05:00 UTC, PgmJun commented on src/main/java/roomescape/global/dto/response/ApiResponse.java
> +        boolean isSuccess,
우선 저는 웨지와 함께 코드를 만들어가는 중이고
웨지가 복잡성을 느끼셨기 때문에 isSuccess 필드를 제거하긴 하였습니다.

하지만
HTTP API 스팩은 지켜서 요청을 보냈지만, 내부 검증 과정에서 문제가 발생한 경우 400 에러를 보내게 되면
“너가 보낸 요청이 정해둔 Api Spec과 달라” 라고 전달하는 느낌이기 때문에
요청이 애플리케이션에 도달한 경우 200을 Response 해주되, 내부에서 isSuccess 는 false로 전달하여
요청 방식에는 문제가 없지만 내부적으로 조건이 충족되지 않음을 표현해준다는 [김영한님의 글](https://www.inflearn.com/questions/111465/5xx-%EA%B4%80%EB%A0%A8-%EC%A7%88%EB%AC%B8%EC%9E%88%EC%8A%B5%EB%8B%88%EB%8B%A4)에도 공감이 갔었기에
이 부분에 관해서 웨지는 어떻게 생각하시는지 의견을 듣고싶었어요!

사실 클라이언트와 소통할 수 있었다면 함께 편한 방식을 정하면 끝이었겠지만
서버와 클라이언트를 다 다루고 있으니 처리방식이 고민되었던 것 같네요

내용을 길게 설명하느라 핵심적인 궁금 포인트가 빠졌습니다..!
결론적으로 궁금한 내용은
`”평균적으로 어떤 방식이 더 클라이언트에 혼란을 주지 않는 방식일까?“` 였습니다.

2024-05-07 05:50 UTC, PgmJun commented on src/main/java/roomescape/service/ReservationService.java
> +public class ReservationService {
자세한 설명 감사합니다.
저도 처음부터 각종 디자인 패턴 등등을 도입해서 복잡한 구현을 하려다 오히려 코드가 망가진 경험을 레벨1에서 겪어보았기에
타당한 이유없는 복잡한 코드를 선호하지 않아요:)

Repository 패턴의 탄생 배경은
이전에는 Service 계층의 비즈니스 로직에서 DAO를 통해 데이터를 관리하다가
Service 계층에서 다루는 도메인 엔티티 객체에 대한 DAO가 늘어남에 따라
Service 계층의 비즈니스 로직에 계속해서 수정이 발생하고 복잡도가 증가해서 유지보수성이 저하되었고
이에 대한 해결책으로 Repository 패턴이 탄생한 것으로 알고 있는데요!

때문에 저또한 현재는 지금처럼 Dao만 다루어 관리하다가
코드의 복잡성이 더욱 늘어나 가독성 및 유지보수성이 저하되어 분리가 필요한 시점이라고 느껴지면
그때 Repository 패턴을 적용해볼 예정입니다!

2024-05-07 11:03 UTC, sihyung92 commented on src/main/java/roomescape/global/dto/response/ApiResponse.java
> +        return new ApiResponse<>(false, errorType.getDescription(), null);
프론트 입장을 겪어보시면 좋은데요, 실제로 happy case에서 조금만 수틀리면 500 내려버리거나 400 이라면서 설명은 없는 API들을 많이 만나게 됩니다 ㅋㅋ
이러면 서버 개발자를 향한 적개심이 차오르게 되는데요, 엄청 까칠한 질문 DM("500 나는데 확인좀요..")을 받고 싶으신게 아니라면 상대가 validation 실패 시 뭐가 필요할지 생각해보세요 
보내주지 않은 필드, 잘못된 필드, 정책을 지키지 못한 경우 등을 응답해주면 될겁니다

이 부분을 다 수정해서 보내면 "정상적인 API 요청" 이 될텐데요, 이게 보안상 문제가 될까요?
보안의 문제가 되는 것은 내 서버가 어떤 스택으로 구성되어있는지 오류메시지로 힌트를 줘버리거나, 응답값으로 개인정보가 새나가는 구멍은 없는지 등입니다

2024-05-07 11:05 UTC, sihyung92 commented on src/main/java/roomescape/controller/ReservationController.java
> +        response.setHeader("Location", "/reservations/" + reservationResponse.id());
네네 우려하는 부분은 매직넘버이니 좋은 처리입니다 ㅎ

2024-05-07 11:07 UTC, sihyung92 commented on src/main/java/roomescape/dao/TimeDao.java
> +                ) rvt ON rt.id = rvt.id
조인절 내에서 서브쿼리를 활용하시는 이유가 있을까요? 아래처럼도 가능할거 같은데용

```SQL
SELECT
    rt.id, start_at, IFNULL(r.time_id, 'False') AS is_reserved
    FROM reservation_time rt
    LEFT JOIN reservation r ON rt.id = r.time_id
WHERE r.date = ? AND r.theme_id = ?
```

2024-05-07 11:08 UTC, sihyung92 commented on src/main/java/roomescape/service/ReservationService.java
> +public class ReservationService {
넵 좋은 접근법이라 생각합니다

2024-05-07 11:11 UTC, sihyung92 commented on src/main/java/roomescape/service/ReservationService.java
> +                .isBefore(LocalTime.now()))) {
네네 이것도 좋은 방법이라고 생각합니다

대신 주석은 필요없다고 생각합니다 ㅎ 
코드와 동어 반복인 주석은 공해입니다 (주석도 유지보수 대상인데 둘이 달라지면 더 헷갈리겠죠 보통 주석을 믿거든요)

주석에 대해선 제가 뭐라고 하는 것 보다 우테코에 많다고 알고있는 [좋은코드 나쁜코드](https://www.yes24.com/Product/Goods/109366833) 5.2 주석문의 적절한 사용 (127p) 를 봐주세용

2024-05-07 11:16 UTC, sihyung92 approved these changes
안녕하세요 이든~~ 리뷰어 웨지입니다.
코멘트 답변을 포함해 리뷰 남겼으니 확인해보셔요!
다음 step 때 반영해주셔도 될거같아 머지 할테니 다음 step에서 반영해주세요.
감사합니다~~

2024-05-07 11:16 UTC, sihyung92 commented on src/main/java/roomescape/domain/reservation/Reservation.java
> +            throw new ValidateException(ErrorType.RESERVATION_REQUEST_DATA_BLANK,
케이스 별로 자르는게 낫지 않냐는 리뷰를 남기려다가 뒤늦게 this를 봤습니다
영리한 해법이네요 ㅎ

2024-05-07 11:16 UTC, sihyung92 commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +                    String.format("공백 또는 null이 포함된 요청입니다. [values: %s]", this));
"예약" 이라는 설명이 빠졌네요 ㅎ

2024-05-07 11:16 UTC, sihyung92 commented on src/main/java/roomescape/dto/theme/ThemeRequest.java
> +                    String.format("공백 또는 null이 포함된 요청입니다. [values: %s]", this));
여기도요!

2024-05-07 11:16 UTC, sihyung92 commented on src/main/java/roomescape/dto/time/TimeRequest.java
> +                    String.format("공백 또는 null이 포함된 요청입니다. [values: %s]", this));
여기도요2!

2024-05-07 11:16 UTC, sihyung92 commented on src/main/java/roomescape/global/dto/response/ApiResponse.java
> +        return new ApiResponse<>(errorType.getDescription(), null);
이 부분을 그대로 두시고 오류 메시지를 상수화 하셨군요? 
이번에 수정해주신 오류메시지가 내려가는 게 더 좋다고 생각합니다
상수에 정의해주신 메시지로는 (ex. `테마(Theme) 생성에 유효하지 않은 값(null OR 공백)이 입력되었습니다.`) 난 분명히 다 잘 보냈다고 생각하는 프론트를 만족시킬 수 없습니다

2024-05-07 11:16 UTC, sihyung92 commented on src/main/java/roomescape/service/ReservationService.java
> +        // 날짜가 지난 경우
요 부분은 코멘트 답변 중 남겨두었습니당~

2024-05-07 11:16 UTC, merged

2024-05-08 11:46 UTC, PgmJun commented on src/main/java/roomescape/service/ReservationService.java
> +        // 날짜가 지난 경우
확인하겠습니다!

2024-05-08 11:51 UTC, PgmJun commented on src/main/java/roomescape/global/dto/response/ApiResponse.java
> +        return new ApiResponse<>(errorType.getDescription(), null);
프론트를 만족시킬 수 없다는 내용이 웨지가 직접 경험해보신 내용인 것 같아서 더욱 와닿네요 🤣
어느 부분이 잘못되었는 지 직접 확인할 수 있도록 구체적인 내용도 함께 보내는 방식으로 변경해보겠습니다

2024-05-08 11:56 UTC, PgmJun commented on src/main/java/roomescape/dto/reservation/ReservationRequest.java
> +                    String.format("공백 또는 null이 포함된 요청입니다. [values: %s]", this));
놓치고 지나친 부분이네요..! 체크 감사합니다!
아래 리뷰들도 반영하였습니다!

2024-05-08 12:01 UTC, PgmJun commented on src/main/java/roomescape/global/dto/response/ApiResponse.java
> +        return new ApiResponse<>(false, errorType.getDescription(), null);
> 보안의 문제가 되는 것은 내 서버가 어떤 스택으로 구성되어있는지 오류메시지로 힌트를 줘버리거나, 응답값으로 개인정보가 새나가는 구멍은 없는지 등입니다

제가 너무 가벼운 내용까지 감춰야한다고 생각했나봐요.
웨지 덕분에 인사이트를 많이 얻어가는 것 같습니다 :)

2024-05-08 12:10 UTC, PgmJun commented on src/main/java/roomescape/dao/TimeDao.java
> +                ) rvt ON rt.id = rvt.id
<img width="330" alt="image" src="https://github.com/woowacourse/spring-roomescape-member/assets/84304802/88668c28-a982-4526-b701-441b33d68148">

저도 처음에 웨지 말씀처럼 쿼리를 작성했다가 서브쿼리를 활용하게 된 이유는
위의 SQL 결과와 같습니다 🥲

구하고자 하는 내용은 `등록된 모든 시간대의 start_at`, `예약이 되었는지에 대한 여부 is_reserved` 인데요
서브쿼리 없이 LEFT JOIN 처리 후 date나 theme_id 등 reservation 테이블에만 존재하는 컬럼을 통해 조건문을 사용하게 되면
예약이 안되어있는 시간대는 조회결과에서 사라지게 됩니다.

때문에 방법을 고민하다가 서브쿼리로 해결하게 되었는데요
혹시 서브쿼리를 사용하지 않고도 해결할 수 있는 더 좋은 방법이 있을까요??

2024-05-08 12:13 UTC, PgmJun commented on src/main/java/roomescape/service/ReservationService.java
> +                .isBefore(LocalTime.now()))) {
동어 반복 + 로직 변경 시 주석도 변경을 잊어버리게 되면 문제가 생긴다는 점에서 제거하는 편이 좋겠네요!
좋은 의견 감사합니다.
주석 처리하고 내일 캠퍼스에 가면 책도 바로 읽어보겠습니다

2024-05-08 12:37 UTC, PgmJun commented on src/main/java/roomescape/service/ReservationService.java
> +            throw new DataConflictException(ErrorType.RESERVATION_DUPLICATION_CONFLICT,
자세히 설명해보자면 다음과 같은 상황에 사용하고자 만든 예외였습니다.

**[이미 존재하는 데이터를 다시 추가]**
- 이미 예약이 존재하는 시간에 예약 요청을 보낸 경우
  - (ex. theme_id=1, time_id=1 에 이미 예약이 있음에도 불구하고 같은 theme_id, time_id 로 예약 추가 요청이 들어온 경우)
- 이미 특정 시간의 레코드가 존재하는데, 또다시 같은 시간 등록을 요청한 경우
  - (ex. reservation_time 테이블에 start_at이 17:00 인 레코드가 이미 존재하는데, start_at이 17:00인 reservation_time의 등록 요청이 들어온 경우)

**[특정 데이터에 연관되어 있는 데이터를 삭제하려함]**
- 예약이 존재하는 시간대를 삭제하려고 하는 경우
  - (ex. 17:00에 예약이 존재하는데 reservation_time에서 17:00 을 삭제하려고 하는 경우)

그런데 제가 조금 잘못 알고 있던 부분이 있었습니다.
저는 409 Conflict가 위와 같은 경우에 발생시키는 상태코드인 것으로 알고 있었는데
웨지의 말씀대로 정합성이 깨진 상황에 발생시키는 예외라고 MDN의 문서에 작성되어 있네요!

하지만 그렇다고 해서 DB에서 발생하는 모든 예외를 처리해줄 의도는 아니기 때문에
DBException 등 과 같은 네이밍보다는 조금 더 의도를 드러낼 수 있는 좋은 네이밍을 고려해보고 변경하겠습니다.
그리고 Conflict 로 리턴하던 상태코드도 다른 상태코드로 변경해보겠습니다!

2024-05-08 23:54 UTC, sihyung92 commented on src/main/java/roomescape/dao/TimeDao.java
> +                ) rvt ON rt.id = rvt.id
is null 조건문과 or로 활용해보셔요 ㅎ
(r.date is null or r.date = '2024-05-05')

2024-05-09 02:03 UTC, PgmJun commented on src/main/java/roomescape/dao/TimeDao.java
> +                ) rvt ON rt.id = rvt.id
```sql
SELECT
    rt.id,
    rt.start_at,
    CASE WHEN r.time_id IS NOT NULL THEN 'True' ELSE 'False' END AS is_reserved
FROM reservation_time rt
LEFT JOIN reservation r ON rt.id = r.time_id AND r.date = ? AND r.theme_id = ?;
```

생각해보니 JOIN의 ON절에서 애초에 r.time_id와 rt.id 가 묶여서 애초에 예약에 예약시간이 존재하지 않으면
WHERE 절에 조건을 작성하니까 조회자체가 안되네요 🥲

그래서 ON절에 조건을 작성했더니 이런식으로도 해결 가능했습니다!