[1 - 3단계 방탈출 사용자 예약] 비토(오상훈) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #58
Opened 2024-05-02 08:41 UTC by unifolio0

2024-05-02 15:57 UTC, kimhodol requested changes
안녕하세요 비토 :)

요구사항 구현 잘 해주셨네요!

코멘트 확인 부탁드립니다~

P.S. "TDD를 한 것처럼" 느껴지도록 테스트를 추가하며 리팩토링을 해보면 좋을 것 같아요!

---

> 호돌은 위의 2가지 방안에 대해서 어떻게 생각하시나요?

개인적으로 2가지 방안 모두 괜찮다고 생각하지만, postReservation를 별도 테스트 유틸 클래스로 분리해서 사용할 것 같습니다.

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/GlobalExceptionHandler.java
> +    }
의견) IllegalArgumentException 외의 예외가 났을 때도 처리할 수 있는 핸들러를 추가하면 좋을 것 같아요.

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(reservationTimeResponse);
의견) ResponseEntity.created()를 사용해주면 어떨까요?

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/domain/Reservation.java
> +    }
질문) 특정 메소드들에만 필드 접근 시 this를 붙여준 이유가 있나요?

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/domain/ReservationTime.java
> +        this(0L, startAt);
질문) 다른 엔티티들의 id값은 object인데 여기서만 primitive를 쓴 이유가 있나요?

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/repository/H2ReservationRepository.java
> +                        "theme_id", reservation.getTheme().getId()))
의견) getTImeId나 getThemeId를 만들어도 좋을 것 같네요.

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/repository/H2ReservationTimeRepository.java
> +    public void deleteById(long id) {
의견) 여기서도 primitive long을 사용하고 있는데, 특별한 이유가 없다면 object를 사용할지 primitive를 사용할지 통일해주는게 나을 것 같아요.

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationService.java
> +    }
의견) 도메인 객체의 책임으로 넘겨도 될 것 같네요.

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/service/ReservationTimeService.java
> +    private List<ReservationTime> getBookedReservationTimes(final LocalDate date, final long themeId) {
의견) final 제어자를 붙이는 것도 일관성을 지켜주세요.

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/service/ThemeService.java
> +    private final ReservationRepository reservationRepository;
의견) static 필드와 아닌 필드 사이에 공백을 넣어주는 것도 괜찮을 것 같아요.

2024-05-02 15:57 UTC, kimhodol commented on src/main/java/roomescape/service/ThemeService.java
> +    }
질문) 해당 로직을 SQL에서 녹이지 않고 어플리케이션 레벨에서 구현한 이유가 궁금해요.

2024-05-02 15:57 UTC, kimhodol commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +        return 0L;
질문) return 0이 필요한 이유가 있나요?

2024-05-03 04:45 UTC, unifolio0 commented on src/main/java/roomescape/domain/Reservation.java
> +    }
급하게 진행하면서 통일성을 놓친 것 같습니다... 원래는 this키워드는 생성자를 제외하곤 잘 사용하지 않습니다.

2024-05-03 06:23 UTC, unifolio0 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
과거의 예약인지 아닌지 판단하는 로직을 Reservation으로 넘겨줬습니다!

2024-05-03 06:26 UTC, unifolio0 commented on src/main/java/roomescape/domain/ReservationTime.java
> +        this(0L, startAt);
급하게 진행하면서 체크를 못 했던 것 같습니다. object로 수정했습니다.

2024-05-03 06:39 UTC, unifolio0 commented on src/test/java/roomescape/acceptance/ReservationAcceptanceTest.java
> +        return 0L;
ReservationTimeAcceptanceTest에 있는 duplicateReservationTest와 같이 저장이 실패하는 경우를 테스트 할 시 
```
if (expectedHttpCode == 201) {
    return response.jsonPath().getLong("id");
}
return null;
```
위 처럼 if문으로 감싸지 않으면 jsonPath로 id를 추출하지 못 해 테스트가 실패하게 됩니다. 그래서 실패하는 테스트를 위해서 default값을 0으로 반환하도록 하였습니다.

지금은 null값을 반환하도록 수정하였습니다.

2024-05-03 06:50 UTC, unifolio0 commented on src/main/java/roomescape/service/ThemeService.java
> +    }
1) 불러온 예약 목록 들을 같은 테마끼리 그룹핑하고 각각의 갯수를 계산하여 정렬하고 상위 10개의 테마를 도출하는 부분은 비즈니스 코드라고 판단했습니다. 따라서 해당 부분은 영속성 계층이 아닌 서비스 계층에서 이루어지는 것이 맞다고 판단했습니다.

2) sql로 너무 많은 기능을 실행하게 되면 이후에 요구사항이 변경될 때마다 각각의 sql을 새로 작성해야 됩니다. 하지만 sql은 실수를 할 여지가 높다고 판단해 가능한 sql문을 새로 작성하는 일이 거의 없도록 구현하고 싶었습니다. 그래서 위의 로직을 어플리케이션 레벨에서 구현했습니다.

2024-05-03 06:53 UTC, unifolio0 commented on src/main/java/roomescape/GlobalExceptionHandler.java
> +    }
`@Order`로 순서를 규정해 IllegalArgumentException일 때는 400 상태코드를 그 외 기타 예외가 발생했을 시 500 상태코드를 반환하도록 수정했습니다!

2024-05-03 14:18 UTC, unifolio0 commented
안녕하세요 호돌 🐅! 비토입니다!
인수 테스트는 작성완료했습니다!
하지만 추가적인 테스트에 관해서 질문이 있어서 코멘트로 적습니다!

### 테스트
우선 인수 테스트는 제가 충분하다고 생각하고 리뷰 요청을 보냅니다! 만약 부족한 부분이 있다면 지적 부탁드립니다!
지금 단위 테스트는 작성을 안 했습니다.
이유는 인수 테스트(E2E테스트)를 통해 이미 전체적인 기능을 테스트 했고 추가로 단위 테스트를 하는 것은 중복 테스트라고 생각했기 때문에 리소스를 줄이기 위해 인수 테스트로 마무리 지었습니다.

저는 리소스를 줄이기 위해 인수 테스트로 마무리 지었는데 호돌은 이에 대해 어떻게 생각하시나요?

추가로 인기 테마 테스트를 작성하는 부분에 대해 질문이 있습니다!
인기 테마는 과거 일주일을 기준으로 가장 예약을 많이 한 테마를 뽑습니다.
하지만 예약을 할 때는 과거 시간은 예약이 불가능하도록 코드를 짰습니다.
그래서 인기 테마를 정확히 도출하는지 테스트할 때 JdbcTemplate을 사용하여 sql문을 통해 과거 예약을 삽입했습니다.
이 부분에 대해 호돌은 어떻게 생각하는 지 궁금합니다!
과거 예약에 대한 부분을 따로 서비스나 dao에 메서드를 만들지, 아니면 지금 방법을 유지하는 게 좋을까요?
호돌은 비즈니스 코드랑 테스트 상황이 서로 충돌할 때 어떤 기준으로 코드를 작성하시나요?

2024-05-04 06:36 UTC, kimhodol requested changes
안녕세요 비토 :)

피드백 잘 반영해주셨네요!

코멘트 확인 부탁드립니다~

2024-05-04 06:36 UTC, kimhodol commented on src/main/java/roomescape/GlobalExceptionHandler.java
> +    @Order(1)
의견) ExceptionHandler 문서를 읽어보면 좋을 것 같아요. Order가 필요 없을 수 있습니다.

2024-05-04 06:36 UTC, kimhodol commented on src/main/java/roomescape/controller/request/ReservationRequest.java
> +        Objects.requireNonNull(themeId);
의견) 개인적으로 NPE가 발생하면 개발자가 의도한것인지 실수로 난 것인지 파악하기 어려워서 NPE보다는 IllegalArgumentException을 선호합니다.

2024-05-04 06:46 UTC, kimhodol commented on src/main/java/roomescape/service/ThemeService.java
> +    }
지금 레벨에서 다룰만한 내용인지는 모르겠지만, 기획이나 정책에 따라서 모든 예약을 불러올 때 너무 많은 객체들이 메모리에 올라가면 OOM이 날 수 있습니다. 그래서 큰 데이터를 다룬다는 가정하에 전체에 대한 통계를 내는 작업들은 서비스 계층에서 하는 것을 지양하고 SQL 쿼리 최적화를 우선적으로 진행하기도 합니다 :)

2024-05-04 10:17 UTC, unifolio0 commented on src/main/java/roomescape/GlobalExceptionHandler.java
> +    @Order(1)
`@ControllerAdvice`를 2개 이상 사용할 때만 '@Order`이 필요하네요! 하나의 `@ControllerAdvice` 내에선 자식 예외 처리가 먼저 호출되네요! `@Order` 어노테이션 삭제했습니다!

2024-05-04 11:40 UTC, unifolio0 commented on src/main/java/roomescape/controller/request/ReservationRequest.java
> +        Objects.requireNonNull(themeId);
`@Valid` 어노테이션을 사용하는 방식으로 변경했습니다!

2024-05-04 13:23 UTC, unifolio0 commented
안녕하세요 호돌 🐅! 비토입니다!
fake 객체를 추가하고, 단위 테스트를 작성했습니다! 

### 리뷰에 대한 추가 의견
#### 과거 시간 저장
>저도 비토랑 비슷하게 작성했을 것 같습니다. 비즈니스 로직은 그대로 두고 JdbcTemplate이나 픽스쳐 등을 활용해서 과거 내역들을 넣었을 것 같아요. 물론 우선적으로, 레벨1 때 랜덤에 대한 의존을 제거하려고 했듯이 ThemeService에서 LocalDate.now()에 대한 의존을 제거하려고 했을 것 같긴해요.

해당 리뷰에 대해 고민해서 나온 결론은 Reservation의 isBeforeNow 메서드에 매개변수로 기준 날짜를 전달하는 방식이었습니다. 다만 그렇게 되면 save 메서드에도 매개변수로 기준 날짜를 전달해야 될 것 같습니다. 
해당 방식으로 변경하는데 리소스 소모가 크지 않아 해당 방식으로 변경할까 고민하다가 JdbcTemplate을 통해 우회적으로 저장하는 방식이 있는데 저 방식으로 변경해서 매개변수의 갯수를 늘리고 싶지 않아 변경하지는 않았습니다!

#### SQL문 VS 어플리케이션 레벨
>지금 레벨에서 다룰만한 내용인지는 모르겠지만, 기획이나 정책에 따라서 모든 예약을 불러올 때 너무 많은 객체들이 메모리에 올라가면 OOM이 날 수 있습니다. 그래서 큰 데이터를 다룬다는 가정하에 전체에 대한 통계를 내는 작업들은 서비스 계층에서 하는 것을 지양하고 SQL 쿼리 최적화를 우선적으로 진행하기도 합니다 :)

이 부분은 ThemeRepository에 주석으로 해당 내용을 반영한 코드를 작성했습니다
```
public List<Theme> findTopThemesDurationOrderByCount(LocalDate startDate, LocalDate endDate, Integer limit) {
        final String sql = """
                SELECT 
                    t.id as theme_id, 
                    t.name as theme_name, 
                    t.description, 
                    t.thumbnail
                FROM theme AS t
                LEFT JOIN reservation AS r
                ON t.id = r.theme_id
                WHERE r.date BETWEEN ? AND ?
                GROUP BY t.id
                ORDER BY COUNT(r.id) DESC
                LIMIT ?
                """;

        return jdbcTemplate.query(sql, rowMapper, startDate, endDate, limit);
    }
```
주석으로만 작성하고 코드를 바꾸지 않은 이유는 아직까진 프로그램의 규모가 크지 않고 사용자도 없기 때문입니다. 따라서 큰 데이터를 다룰 일이 없어 이후에 요구사항이 변경되도 sql문을 변경할 가능성이 가장 적은 현재 코드가 더 장점이 크다고 판단했기 때문입니다!

2024-05-05 09:09 UTC, kimhodol requested changes
안녕하세요 비토 :)

피드백 반영 잘 해주셨네요.

코멘트 확인 부탁드릴게요~

2024-05-05 09:09 UTC, kimhodol commented on src/main/java/roomescape/domain/Name.java
> +    public static void validateLength(String value) {
의견) public일 필요도, static일 필요도 없어 보이네요!

2024-05-05 09:09 UTC, kimhodol commented on src/main/java/roomescape/domain/Name.java
> +        Objects.requireNonNull(value);
여기에 아직 NPE가 남아있네요!

2024-05-05 09:09 UTC, kimhodol commented on src/main/java/roomescape/repository/H2ThemeRepository.java
> +    }*/
의견) 주석으로 남겨둘 필요는 없을 것 같아요! 리뷰 전에 불필요한 주석은 모두 제거해주세요 ㅎㅎ

2024-05-05 09:09 UTC, kimhodol commented on src/main/java/roomescape/domain/Reservation.java
> +public class Reservation {
의견) 도메인 객체들도 단위 테스트 작성 부탁드릴게요!

2024-05-05 11:43 UTC, unifolio0 commented
안녕하세요 호돌 🐅! 비토입니다!
>roomescape.service.ReservationTimeServiceTest#findAllWithAvailability 테스트가 통과되지 않는 것 같으니 확인해주세요~

시간이 지남에 따라 테스트가 깨질 수 있는 가능성을 없애기 위해 고정된 시간을 사용하지 않으려고 바꾸던 중 놓친 부분이 있었던 것 같네요... 다시 전체적으로 체크하고 수정했습니다!
추가로 sql문에도 현재의 시간을 구하고 시간을 +- 할 수 있는 기능을 찾아서 sql문도 전체적으로 수정했습니다!
덕분에 날짜의 범위가 중요한 비즈니스 코드의 테스트도 시간에 따라 터질 가능성을 거의 없앨 수 있었습니다!

2024-05-06 07:58 UTC, kimhodol approved these changes
안녕하세요 비토 :)

이번 단계는 여기서 마무리해도 될 것 같아요.

고생하셨습니다!

2024-05-06 07:59 UTC, merged