[1 - 3단계 방탈출 사용자 예약] 릴리(최윤서) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #66
Opened 2024-05-02 08:46 UTC by lilychoibb

수정 예정입니다.

2024-05-02 12:04 UTC, jinyoungchoi95 requested changes
안녕하세요 릴리 😄

방탈출 사용자 예약 미션의 리뷰어를 맡은 오리입니다.

몇가지 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-02 12:04 UTC, jinyoungchoi95 commented on src/test/java/roomescape/service/ReservationServiceTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
default값이 아닌 `NONE`옵션을 사용한 이유가 있을까요?

2024-05-02 12:04 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler {
`@ControllerAdvice`는 테스트가 필요없을까요?

2024-05-03 07:27 UTC, lilychoibb commented on src/main/java/roomescape/domain/ThemeName.java
> +public class ThemeName {
1단계 이후 Theme 도메인을 추가하면서 기능 구현에 집중하느라 빠진 예외 처리가 있네요 🥹
수정하겠습니다!

2024-05-04 09:32 UTC, lilychoibb commented on src/main/java/roomescape/dao/ReservationTimeJDBCRepository.java
> +        String sql = "SELECT * FROM reservation_time WHERE id NOT IN (SELECT time_id FROM reservation WHERE date =? AND theme_id=?)";
테이블의 컬럼 수가 많지 않아서 `*` 을 사용했었는데, 지금은 다른 단점보다도 ResultSet 의 컬럼 순서에 rowMapper 가 의존하고 있어서 추후에 컬럼이 추가되거나 수정된다면 영향을 받을 수 있겠네요!
수정하도록 하겠습니다 :)

2024-05-04 10:25 UTC, lilychoibb commented on src/main/java/roomescape/service/ThemeService.java
> +        }
데이터베이스에 unique key를 거는 것은 좋은 방법인 것 같습니다 :)
하지만 unique key 를 건다고 해도 어플리케이션 단에서 exist 와 같은 검증 로직은 있어야 한다고 생각합니다.
왜냐하면 일단 오리가 말씀해주신 '예외가 명시적으로 난다' 라는 것은 제가 생각하기에 데이터베이스가 던지는 예외보다 서비스가 던지는 메시지를 포함한 커스텀 예외가 더 명시적이라고 생각합니다. 그런데 이 부분은 사람마다 명시적이라고 생각하는 예외가 다를 수 있을 것 같아요!
그리고 만약 나중에 데이터베이스 관리자가 unique key 를 거는 것을 빼먹었다고 하더라도 도메인을 보호할 수 있는 방법이라고 생각합니다. (= 도메인 데이터를 데이터베이스와 같은 외부 환경에 의존한다고 생각이 듭니다.)
이런 이유로 

> exist를 어플리케이션단에서 구현하면서 로직 하나하나에 넣어야하는 것을 신경쓰는 것

은 어쩔 수 없는 부분이지 않을까요?

그런데 `themeRepository.existsByName(themeRequest.name())` 와 같은 쿼리를 한 번 더 날려야 하는 비용이 드는 것에 대해서는 고민이 되는 부분 같습니다.
오리는 어떻게 생각하시나요?

2024-05-04 16:45 UTC, lilychoibb commented on src/test/java/roomescape/dao/ReservationTimeJDBCRepositoryTest.java
> +        reservationRepository.save(reservation);
지금 조회 테스트 메서드는 다시 보니 조회 보다는 `save()` 가 잘 되었는지 테스트 하는 메서드 같네요.
`save()` 에 의존하지 않고 조회만 해서 테스트 하도록 수정하겠습니다!

2024-05-05 04:10 UTC, lilychoibb commented on src/main/java/roomescape/service/ReservationService.java
> +    }
`find vs get` 의 네이밍 컨벤션이 있군요 ..!
그런데 T getReferenceById(ID id) 에서 id 가 식별자라고 하는데, '식별자' 라는 것이 테이블의 primary key 를 말하는 것인지, getReferenceByDateAndTheme 와 같이 date 와 theme 을 식별자로 조회해오겠다 라는 의미로 사용해도 되는 건지 헷갈리네요
전자라면 Repository 에서 findById 또는 getReferenceById 둘 중 하나만 존재하는 건가요?

2024-05-05 06:41 UTC, lilychoibb commented on src/main/java/roomescape/service/ThemeService.java
> +    private static final String END_DATE = LocalDate.now().minusDays(1).format(DateTimeFormatter.ISO_DATE);
아 ..!!! static 으로 가지고 있으면 안되겠네요 👍
메서드 내에서 계산하는 게 맞겠네요
감사합니다 :)

2024-05-05 07:43 UTC, lilychoibb commented on src/test/java/roomescape/service/ReservationServiceTest.java
>  @SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
서비스 레이어의 테스트는 웹 환경을 구성할 필요가 없다고 생각했습니다.
또한 `NONE` 옵션을 명시하면 불필요한 리소스를 소비하지 않기 때문에 테스트를 좀 더 빠르게 실행할 수 있어 사용했습니다!

2024-05-05 07:44 UTC, lilychoibb commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +            themeRepository.deleteById(theme.getId());
data.sql 을 사용해보겠습니다 :)

2024-05-05 08:23 UTC, lilychoibb commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
다른 예외는 `InvalidReservationException` 으로 처리 & `try-catch` 문을 통해 잡고 있어서 괜찮을 것 같고, 추가적으로 `NullPointerException`, `HandlerMethodValidationException` 과 혹시 모를 예외를 위해 `Exception` 까지 추가하였습니다.
그런데 보통 예외 컨트롤 범위는 어떻게 정해지나요? 일단 `Exception` 으로 잡고 추후에 예외가 발생하면 구체적으로 컨트롤하는 걸까요?

2024-05-05 10:01 UTC, lilychoibb commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
>  public class GlobalExceptionHandler {
`@ControllerAdvice` 를 테스트 해야하는지 몰랐네요 :) !
mock 객체를 사용해서 테스트 코드를 짜봤는데, 잘 된건지 잘 모르겠네요 ,, 피드백 부탁드립니다 🤗

2024-05-05 10:11 UTC, lilychoibb commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +        themeId = (int) RestAssured.given().contentType(ContentType.JSON).body(themeRequest)
`(int)` 를 삭제하게되면 테스트가 전부 깨집니다 🥲
이 부분이 아쉬워서 계속 고민중이긴 한데 왜 안 되는지 잘 모르겠네요 
조금 더 고민해보겠습니다 🤔

2024-05-06 07:33 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/ThemeService.java
> +        }
네 릴리가 해준 이야기도 틀린말은 아니기 때문에 공감합니다 :)

다만 몇가지 생각하면 좋을 부분은
> 왜냐하면 일단 오리가 말씀해주신 '예외가 명시적으로 난다' 라는 것은 제가 생각하기에 데이터베이스가 던지는 예외보다 서비스가 던지는 메시지를 포함한 커스텀 예외가 더 명시적이라고 생각합니다. 그런데 이 부분은 사람마다 명시적이라고 생각하는 예외가 다를 수 있을 것 같아요!

(동시요청에 대한 처리에 대한 이야기로 넘어가셔도 됩니다.) exist를 validation하는 이유는 이미 존재하는 값에 대한 생성을 막기 위함일텐데요. 로직이 "동시에" 실행된다면 두개의 요청은 exist를 무난히 통과할테고, create로직이 들어가게 되어요. 그럼 이미 존재하는 값에 대한 생성을 못막는 것 아닐까요? 더불어 unique를 보조적으로 건다면 exist validation exception도 발생할 수 있고 unique exception도 발생할 수 있어 혼용되는 예외에 대한 처리가 되지 않을까요?

> 그리고 만약 나중에 데이터베이스 관리자가 unique key 를 거는 것을 빼먹었다고 하더라도 도메인을 보호할 수 있는 방법이라고 생각합니다.

그럼 id에 auto increment를 거는 것도 빼먹을 수 있는 것 아닐까요? unique key를 빼먹는 것과 auto increment를 빼먹는 것은 둘다 똑같은 코드 한줄이기 때문에 잊을수 있는 상황은 동일하다고 생각해요. (물론 id에 대한 중요도는 더 높을 수 있겠지만요)

unique key를 빼먹을 수 있기 때문에 application에 검증로직을 두다는 이유는 한번 더 생각해보시면 좋을 것 같아요.

> 그런데 `themeRepository.existsByName(themeRequest.name())` 와 같은 쿼리를 한 번 더 날려야 하는 비용이 드는 것에 대해서는 고민이 되는 부분 같습니다.

네. 비용입니다. 사실 단순한 조회쿼리의 경우에는 크게 속도가 저하되는 경우는 없어서 지금도 충분하다고 생각하는데 "굳이"의 영향범위에 있는 로직은 가능하면 제거하는 것이 좋다고 생각해요.

2024-05-06 07:38 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
어디의 `getReferenceById`를 말씀하시는걸까요? Spring Data Jpa의 메소드를 말씀하시는 것이라면 현재의 학습범위가 아니기 때문에 참고자료로 사용하지 않으셔도 될 것 같아요. Spring Data Jpa 자체에서도 get을 메소드 네임으로 사용하다 deprecated되고 사용을 지양하고 있습니다.

`find`와 `get`을 말씀드린건 Spring data jpa와 별개로 자바진영에서 두 네이밍에 대한 관습적인 차이가 있기 때문이에요.

- `get`: 단순히 "가져온다"의 의미를 내포하고 있어 복잡한 로직에서는 지양되어 사용되며, 관습적으로 무조건 가져온다의 의미를 내포하고 있기 때문에 Optional과 같은 nullable한 값은 반환하지 않아요. nullable한 값인 경우 "없다"로 논리적으로 판정되기 때문에 예외를 발생시키는거죠.
- `find`: 조금 더 넓은 케이스에요. Spring Data Jpa에서 이를 주도해서 사용한 것이 아닌 관습적으로 `find`라는 네이밍이 사용되고 있고 Spring Data Jpa는 이를 활용한 것뿐이죠. 관습적으로 읽는 값에 대해서 nullable함을 모두 포함해요.

일반적으로 데이터베이스에서 가져올 때 값이 없는 경우에 대한 처리를 호출하는 측에서 처리하길 바라기 때문에 find를 주로 사용하긴합니다.

2024-05-06 07:45 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    }
일반적으로 잡는 예외들이나 커스텀 예외를 우선적으로 잡고 말씀하신대로 `Exception`을 건 후 필요에 따라서 컨트롤하는 예외를 추가해요.

어떤 예외들이 핸들링 필요한가는 정답처럼 고정된 것은 없고 사실 경험적인 부분이 대부분이기 때문에 여러 요청을 날려보면서 이럴때 이런 예외가 발생하는구나를 보며 학습하시면 도움이 될 것 같아요.

2024-05-06 07:53 UTC, jinyoungchoi95 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +        themeId = (int) RestAssured.given().contentType(ContentType.JSON).body(themeRequest)
https://stackoverflow.com/questions/58056944/java-lang-integer-cannot-be-cast-to-java-lang-long

`(int)`가 정석적인 parsing의 과정을 거친것은 아니기 때문에 제거하고 다른 방법에 대한 내용을 언급했던 부분이었어요. 위 자료를 참고해보시면 좋을 것 같아요.

2024-05-06 08:19 UTC, jinyoungchoi95 requested changes
안녕하세요 릴리 😄

코멘트 주신 내용에 대한 답변과 추가 코멘트 남겨두었으니 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-06 08:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/domain/ThemeName.java
> +    }
일반적으로 `Object`의 override 메소드들은 기능이라기보다는 객체의 속성에 가까워 외부에서 호출되는 메소드보다 관심사가 떨어지는 취급이라 getter보다 밑의 최하단에 두는 편인 것 같아요.

2024-05-06 08:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/ThemeService.java
> +        String endDate = LocalDate.now().minusDays(1).format(DateTimeFormatter.ISO_DATE);
starDate와 endDate를 가지는 도메인 클래스로 분리할 수 있지 않을까요?

2024-05-06 08:19 UTC, jinyoungchoi95 commented on src/main/java/roomescape/dao/ThemeJDBCRepository.java
> +    };
```suggestion
    private final RowMapper<Theme> rowMapper = (resultSet, rowNum) -> new Theme(
            resultSet.getLong("id"),
            resultSet.getString("name"),
            resultSet.getString("description"),
            resultSet.getString("thumbnail")
    );
```
단순 값 리턴이어서 이렇게 표현되는게 더 간단하겠네요.

2024-05-06 08:19 UTC, jinyoungchoi95 commented on src/test/java/roomescape/controller/ThemeControllerTest.java
> +    //TODO: 현재보다 이전으로 일정 설정 불가 검증으로 인한 테스트 불가
controller test도 sql을 사용한다면 다른 api 요청에 의존하지 않고 테스트할 수 있지 않을까요?

2024-05-06 08:19 UTC, jinyoungchoi95 commented on src/test/java/roomescape/dao/ReservationJDBCRepositoryTest.java
> +                "https://i.pinimg.com/236x/6e/bc/46/6ebc461a94a49f9ea3b8bbe2204145d4.jpg"));
`test_data.sql`을 사용하고 있는데 여기서 굳이 save하는 이유가 있을까요?

2024-05-06 08:19 UTC, jinyoungchoi95 commented on src/test/java/roomescape/dao/ThemeJDBCRepositoryTest.java
> +        ;
```suggestion
```

2024-05-06 08:19 UTC, jinyoungchoi95 commented on src/test/java/roomescape/exception/GlobalExceptionHandlerTest.java
> +public class GlobalExceptionHandlerTest {
Controller도 마찬가지겠지만 ExceptionHandler를 어디까지 테스트할 것인가에 따라서 다를 것 같아요.

단순히 내가 원하는 status나 body를 담은 `ResponseEntity`를 반환하는 것까지만 빠르게 테스트하고 피드백받는 구조로 만들고 싶다라고 하면 단위테스트로 만드는 것이고, 지금처럼 요청에 대한 api 반환값을 확인하고 싶다면 지금의 구조도 좋다고 생각해요.

2024-05-07 02:21 UTC, lilychoibb commented on src/main/java/roomescape/service/ThemeService.java
> +        }
아하 그렇군요 :)
예외 처리는 빠르고 많을 수록 좋다고 생각했는데 왜 두 곳에서 검증하는 것이 굳이 일까? 에 대해서 생각을 해봤는데요,
결국에 도메인에서도 데이터 베이스에 조회 쿼리를 날리는 방식으로 예외 처리를 하고 있어서 그런 것 같네요.
- 빠른가? -> X (DB 까지 다녀와야 함)
- 많은가? -> O 이지만 여러가지 단점 존재(동시성 문제, 혼용되는 예외, 비용 등)

그렇다면 현재 이미 존재하는 테마 이름 검증을 도메인과 DB 에서 하고 있는 방식이 같은 방식인가?
- 예외를 날리는 주체만 달라질 뿐 확인은 데이터베이스가 한다
- 그럼 굳이 동시성 문제로 예외 처리가 안 될 수 있고 혼용되는 예외에 대한 처리가 될 수 있는 로직을  넣어야 할까?
- 관리 포인트는 줄어드는 것이 좋겠다
- 무조건 많다고 좋은 것은 아니구나

그럼 DB 에서 제약 조건이 있는 경우에 도메인에서 검증하지 않아도 되는건가?
- 그래도 되는 경우의 조건
데이터 베이스의 값을 조회해서 검증하는 경우 (?)

이 정도로 생각해봤는데, 좀 더 보충해야 할 부분이 있을까요? 잘못 생각한 부분도 있을 것 같아서 피드백 주시면 좋을 것 같습니다!
감사합니다 🤗

2024-05-07 04:03 UTC, lilychoibb commented on src/main/java/roomescape/service/ReservationService.java
> +    }
앗 참고한게 Spring Data Jpa 자료였나보네요!
정리해주셔서 감사합니다 🙂

2024-05-07 05:01 UTC, lilychoibb commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +                .body(new ExceptionTemplate(exception.getMessage()));
internalServerError 로 수정했습니다 :)

2024-05-07 05:14 UTC, lilychoibb commented on src/main/java/roomescape/domain/Theme.java
> +    private final String thumbnail;
Reservation 의 필드도 객체로 모두 분리되어있어서 Theme 도 분리해도 좋을 것 같아요!
수정하겠습니다 :)

2024-05-07 05:27 UTC, lilychoibb commented on src/main/java/roomescape/domain/ThemeName.java
> +    }
오 그렇군요! 몰랐네요
감사합니다 :)

2024-05-07 05:53 UTC, lilychoibb commented on src/main/java/roomescape/service/ThemeService.java
> +        String endDate = LocalDate.now().minusDays(1).format(DateTimeFormatter.ISO_DATE);
😮 헉 그렇네요!
꼼꼼하게 봐주셔서 감사합니다 :)

2024-05-07 06:13 UTC, lilychoibb commented on src/test/java/roomescape/controller/ThemeControllerTest.java
> +    //TODO: 현재보다 이전으로 일정 설정 불가 검증으로 인한 테스트 불가
sql 사용하니까 reservation 과 time api 요청을 하지 않아도 돼서 테스트도 더 깔끔해지고 좋네요 👍
감사합니다 :)

2024-05-07 06:25 UTC, lilychoibb commented on src/test/java/roomescape/dao/ReservationJDBCRepositoryTest.java
> +                "https://i.pinimg.com/236x/6e/bc/46/6ebc461a94a49f9ea3b8bbe2204145d4.jpg"));
`test_data.sql ` 에서 가져와서 사용하면 되겠네요 😅
새로운 예약을 생성할 때 time 과 theme 객체가 필요해서 save 한 것 같은데, 오리가 말씀주신 것처럼 불필요해보여서 제거했습니다 !

2024-05-07 06:31 UTC, lilychoibb commented
안녕하세요 오리 🤗
전체적으로 제가 신경쓰지 못한 부분까지 꼼꼼하게 봐주셔서 깨닫는게 많은 리뷰인 것 같아요
리뷰 남겨주셔서 감사합니다!

2024-05-07 07:41 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/ThemeService.java
> +        }
사실 트레이드오프의 영역이기 때문에 정답은 따로 없어요. 지금은 현재 고민해주신 영역까지가 적절해보이고 다음단계 혹은 4레벨때 더 깊게 고민하실 시간이 있으니 그때 더 고민해보시면 좋을 것 같아요.

2024-05-07 07:47 UTC, jinyoungchoi95 approved these changes
안녕하세요 릴리 😄

현재 단계에 충분한 학습과 구현을 진행하신 것 같아 머지하겠습니다. 코멘트에 대한 답변과 추가 코멘트 남겨두었으니 다음미션 진행하면서 함께 확인부탁드려요.

궁금하거나 고민이 되는 부분이 있으시다면 언제든 pr 코멘트 또는 dm으로 요청 부탁드립니다.
감사합니다 🙇‍♂️

2024-05-07 07:47 UTC, jinyoungchoi95 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler()
```suggestion
    @ExceptionHandler
```

2024-05-07 07:47 UTC, jinyoungchoi95 commented on src/main/java/roomescape/service/ThemeService.java
> +                LocalDate.now().minusDays(7), LocalDate.now().minusDays(1));
`ReservationTerm`이라는 도메인도 좋다고 생각하는데요. `PopularTheme`이라는 기간을 알고있는 도메인으로 바로 생성해주어도 좋을 것 같아요. 혹은 `ReservationTerm`에서 정적팩토리로 제공해주어도 좋을 것 같고요.

2024-05-07 07:47 UTC, merged