[1 - 3단계 방탈출 사용자 예약] 리니(이예린) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #69
Opened 2024-05-02 08:48 UTC by linirini

안녕하세요, 스티치! 저는 우아한테크코스 백엔드 6기 리니입니다🖐️

이번 미션의 변경 사항은[링크](https://github.com/woowacourse/spring-roomescape-member/pull/69/files/44b8880d387574a5648bdf07fcb5c56782ff1bd5..e1b943253c7ff3bfc042c0bb6055d3910a1317e7)와 같습니다.

### 현재 배경 지식 수준
저는 프로젝트에 참여하면서 스프링을 사용하여 로컬에서 개발한 경험이 있습니다. 하지만 프로젝트에서는 상대적으로 간단한 서비스들에 한해 리드 개발자의 코드를 함께 보면서 동작 원리에 대한 이해 없이 개발에 참여했었기 때문에 스프링을 잘 모르는 상태였고, 이번에 레벨 2에서야 스프링 학습을 제대로 시작했습니다!

### 미션 진행 상황
발생 가능한 예외 상황을 최대한 자세하게 작성해봤습니다.! API 문서도 꼼꼼하게 작성해보려고 했습니다.
아쉽게도 이번에 급하게 미션 마무리하느라 3단계와 테스트 대해서는 리팩터링이 부족하고, 예외 케이스 없이 해피 케이스만 구현된 상태입니다. 그래서 아래 다음 리뷰 요청 때, 함께 반영할 리팩토링 사항을 간단하게 정리해봤습니다.

### 리팩토링 방향
1. `@Disabled` 테스트
지금 테스트 중에서 `@Disabled` 처리된 테스트가 2개 존재하는데요,
`현재보다 이전으로 일정을 설정할 수 없다`는 검증이 `Schedule` 도메인 내에 존재하기 때문에, `오늘을 기준으로 이전 일주일 간 예약이 많았던 10개 테마를 보여준다`는 테스트를 수행할 수 없었습니다. 
그 과정에서 `현재보다 이전으로 일정을 설정할 수 없다`는 **도메인의 검증 사항이 아닌 비즈니스 검증 사항**이라는 점을 깨달을 수 있었고, 서비스 계층으로 해당 검증을 리팩토링하여 문제를 해결할 계획입니다.
2. 테스트
테스트를 위해 필요한 데이터를 미리 생성하는 등의 작업으로 인해 가독성이 떨어져서 리팩토링을 진행해보고자 합니다. 우선은 Fixture 클래스를 분리하는 방향으로 진행할 계획입니다.
3. 예약이 조회하는 시간 미조회
테마와 날짜로 시간 조회 시 예약 존재 여부(alreadyBooked)도 조회한다는 부분을 놓쳤습니다. 이부분도 함께 반영할 예정입니다!

부족한 상태로 리뷰 요청을 하게 되어 아쉽지만, 앞으로 2주간의 코드 리뷰 잘 부탁드립니다🙇‍♀️

2024-05-03 03:12 UTC, lxxjn0 requested changes
안녕하세요, 리니. 이번에 리뷰를 맡게된 스티치입니다 :)

이전 미션보다 조금 더 요구사항도 많고 검증할 부분도 많은데 꼼꼼하게 잘 작성해주신 것 같아요!! 이번 리뷰에서는 프로덕션 코드 위주로 리뷰 작성했습니다. 따라서 테스트에 관련된 부분은 다음 리뷰에 추가로 확인해보도록 하겠습니다.

우선 제가 궁금한 부분이나 몇 가지 눈에 보이는 부분들에 대해서 피드백 남겨두었는데 한번 확인해보시고 이전에 구현하지 못한 기능이나 예외 케이스에 대한 처리도 이번에 같이 작업해주시면 좋을 것 같아요. 

또한 예외에 대한 처리를 어플리케이션 코드에서는 했지만 프론트에서는 노출되지 않는 것 같아요. 발생한 예외에 대해서 사용자가 인지할 수 있도록 프론트 코드를 수정해보시는 것도 좋을 것 같습니다. 현재는 콘솔로 들어가서 확인하지 않고선 동작을 하는지 문제가 발생했는지 파악이 어려운 상황인 것 같아요. 이 부분도 시간이 된다면 같이 확인해주시면 좋을 것 같습니다 :)

2024-05-03 03:12 UTC, lxxjn0 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    private final static String TIME_FORMAT = "HH:mm";
해당 포맷은 외부에 전달하기 위한 정보로 보는게 적절하지 않을까요? 도메인에서 관리해야 하는 정보로 적절한지 한번 고민해보면 좋을 것 같아요 :)

2024-05-03 03:12 UTC, lxxjn0 commented on src/main/java/roomescape/domain/Schedule.java
> +public class Schedule {
일정을 도메인으로 뽑아서 관리하셨네요 👍🏼 단순히 미션에서 제안한 부분만을 도메인으로 관리하려는 것이 아닌, 리니의 생각에 도메인이라고 생각되는 부분을 이렇게 코드로 만드신 점이 좋은 것 같습니다.

2024-05-03 03:12 UTC, lxxjn0 commented on src/main/java/roomescape/domain/Schedule.java
> +    }
이 부분은 리니가 인지한 부분이라고 생각되어서 체크만 해두겠습니다 :)

2024-05-03 03:12 UTC, lxxjn0 commented on src/main/java/roomescape/exception/ExceptionTemplate.java
> +public record ExceptionTemplate(String message) {
단순히 예외에 관한 메시지만 보내는데 객체로 관리하신 이유가 있을까요?

2024-05-03 03:12 UTC, lxxjn0 commented on src/main/java/roomescape/exception/InvalidReservationException.java
> +public class InvalidReservationException extends RuntimeException {
커스텀 예외를 구현하셨네요. 아래의 글을 한번 참고해보는 것도 좋을 것 같습니다 :)

https://tecoble.techcourse.co.kr/post/2020-08-17-custom-exception/

2024-05-03 03:12 UTC, lxxjn0 commented on src/main/java/roomescape/service/ReservationService.java
> +        Theme theme = findThemeById(reservationRequest.themeId());
해당 라인의 순서를 바꿔보는 것은 어떨까요? time과 theme의 존재 여부에 대한 체크가 중복 체크보다 뒤에 나오는게 어색한 것 같아요. 사실 존재하지 않는 time과 theme이면 중복을 체크할 필요가 없는데 불필요한 쿼리 요청이 한번 더 발생하는 상황이 되지 않을까요?

2024-05-03 03:12 UTC, lxxjn0 commented on src/main/java/roomescape/service/ReservationService.java
> +    }
이 부분은 개인적인 의견이니 참고만 해주세요. 지금처럼 특정 도메인의 Repository를 직접 의존해서 이렇게 코드를 작성하고 관리할 수 있지만 어떻게 보면 해당 도메인에 이러한 응답을 내려주는 메서드를 구현해두고 사용하는 것은 어떨까요? 이후 코드에 대한 변경에 대응하기도 더 쉬울 수 있을 것 같고요. 리니는 어떻게 생각하시는지 궁금합니다 :)

2024-05-03 03:12 UTC, lxxjn0 commented on src/main/java/roomescape/service/dto/ReservationRequest.java
> +        @Pattern(regexp = "^([12]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]))$", message = "올바르지 않은 날짜입니다.") String date,
바로 LocalDate 타입으로 받으면서 JsonFormat을 통한 확인도 가능할 것 같아요! 그로 인해 발생되는 예외를 AdviceController에서 처리하는 것도 가능하지 않을까요?

2024-05-05 08:13 UTC, linirini commented on src/main/java/roomescape/service/dto/ReservationRequest.java
> +        @Pattern(regexp = "^([12]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]))$", message = "올바르지 않은 날짜입니다.") String date,
LocalDate로 받아서 JsonFormat으로 시간과 날짜를 처리할 수 있도록 리팩토링을 시도해보았는데요!

JsonFormat은 `HttpMessageNotReadableException.class`로 exceptionHandling을 해야하며, message를 설정할 수 있는 속성을 가지지 않아 JsonFormat으로 잡히는 모든 예외에 대해서 하나의 메시지로만 처리할 수 있다는 점에서 아쉬웠습니다.
추가로, 포맷만 확인할 뿐 유효한 날짜인지(ex: 2024-02-31)는 JsonFormat으로 확인이 불가능하여 도메인 레벨에서 해당 예외가 처리되는데 서로 다른 ExceptionHandler에서 처리되면서 메시지도 통일된 메시지를 줄 수 없었습니다.
(ex: HttpMessageNotReadable -> 유효하지 않은 입력 형식입니다. InvalidReservationException -> 올바르지 않은 날짜입니다.)
리팩토링을 진행하면서 여러 필드에 JsonFormat을 사용하면서 예외 메시지에 일관성이 떨어지는 경험을 했고, 이를 극복할 적절한 방안을 찾지 못해서 우선 남겨두었습니다.

스티치는 이와 같이 여러 필드를 JsonFormat으로 형식 검증을 하고자 할 때는 예외 핸들링을 어떻게 하시는지 조금 더 구체적인 설명을 부탁드려도 될까요?

2024-05-06 07:20 UTC, lxxjn0 commented on src/main/java/roomescape/controller/ReservationTimeController.java
> +                                                                       @RequestParam(value = "themeId") long themeId) {
추가로 `@ModelAttribute` 어노테이션도 참고해보시면 좋을 것 같습니다!

2024-05-06 07:21 UTC, lxxjn0 commented on src/main/java/roomescape/dao/ReservationRepository.java
> +public interface ReservationRepository {
꼼꼼히 학습하신 수 그에 대한 내용도 정리해주셨네요 👍🏼

2024-05-06 07:30 UTC, lxxjn0 commented on src/main/java/roomescape/service/dto/ReservationRequest.java
> +        @Pattern(regexp = "^([12]\\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01]))$", message = "올바르지 않은 날짜입니다.") String date,
저는 보통 일자와 관련된 부분을 `@DateTimeFormat`을 사용해서 처리했는데 위와 같은 이슈가 발생하는 케이스를 따로 보질 못해서 인지하지 못했을 수도 있겠네요. 

패턴을 사용해서 유효성 검증을 하면 정규표현식을 이해하고 해당 식을 이해해야하는데 가독성도 떨어지고 어떠한 형식을 테스트하고자 하는지 바로 명확히 드러나지 않는 단점이 존재하는 것 같아요. 그래서 만약 위의 어노테이션도 적절하지 않다고 생각하신다면 오히려 String으로 그냥 받고 사용하는 부분에서 LocalDate로 변환하면서 발생하는 예외를 통해 처리할 것 같아요. 숫자를 nextLine으로 입력받아서 parse 메서드를 사용해 변환하는 방식과 같은 맥락으로 이해해주시면 좋을 것 같아요 :)

2024-05-06 07:50 UTC, lxxjn0 approved these changes
리니, 피드백 반영하시느라 수고하셨습니다.

전체적으로 수정이 완료된 것 같아서 일정을 맞추려면 이번 단계는 여기서 마무리해도 괜찮을 것 같아요! 이전 리뷰에 대한 피드백도 남겨두었고 이번 리뷰에서 수정하면 좋을 부분들을 코멘트 추가로 남겨두었는데 확인 후 다음 단계 진행하시는 과정에 반영해주시면 좋을 것 같아요 👍🏼

2024-05-06 07:50 UTC, lxxjn0 commented on src/main/java/roomescape/domain/ReservationTime.java
> +    }
해당 도메인은 ID가 식별자인데 동등성을 부여하신 이유가 있을까요?

2024-05-06 07:50 UTC, lxxjn0 commented on src/main/java/roomescape/infrastructure/ReservationJdbcRepository.java
> +package roomescape.infrastructure;
적절한 패키지 분리 👍🏼

2024-05-06 07:50 UTC, lxxjn0 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +@Sql(scripts = {"classpath:truncate.sql"}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
적절한 어노테이션 활용 👍🏼

2024-05-06 07:50 UTC, lxxjn0 commented on src/test/java/roomescape/controller/ReservationControllerTest.java
> +public class ReservationControllerTest {
해당 클래스의 테스트 메서드를 보면 시나리오를 테스트하는 경우가 주가 되는 것 같아요. 이런 경우에는 다이나믹 테스트를 한번 학습해보신 후 적용해보셔도 좋을 것 같아요 :)

2024-05-06 07:50 UTC, lxxjn0 commented on src/test/java/roomescape/service/ReservationTimeServiceTest.java
> +    private ReservationRepository reservationRepository;
해당 코드는 사실 단위테스트인데 Repository의 의존성으로 인해 스프링 어플리케이션을 띄워서 테스트하고 있는 것 같아요. Repository를 인터페이스로 변경했으니 mocking 객체를 만들어서 활용해보시는 것은 어떨까요? 또는 Mockito라는 라이브러리를 사용해보는 것도 방법이 될 수 있을 것 같아요. 테스트 더블이라는 키워드로 검색해보면 위의 개념들에 대한 설명을 얻을 수 있을 것 같습니다 :)

2024-05-06 07:51 UTC, merged