[1 - 3단계 방탈출 사용자 예약] 켬미(김경미) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #75
Opened 2024-05-02 08:53 UTC by kyum-q

안녕하세요 호돌 🐯 이번에 리뷰를 받게된 6기 BE 켬미라고 합니다 😊
이번에는 스프링을 공부해본 페어와 함께 프로그래밍하면서 스프링에 대해 조금은 더 알게 된 것 같아요 ! 그럼에도 몇가지 궁금증과 부족함이 많답니다 😁 

그리고 이번에는 리뷰어에게 제가 웹 개발을 해봤는지, 해봤다면 스프링을 사용해봤는지 여부를 말해달라 해서 간단하게 말해보겠습니다 !

저는 웹 개발 경험이 있나요? 라는 질문에 답변으로는 예. 웹 애플리케이션을 만들었지만 로컬에서만 서버를 띄워봤습니다. 라고 답할 수 있을 것 같아요 ! 😊 근데 일반적인 웹 애플리케이션이 아니라, IoT 장치의 소프트웨어 연결을 웹으로 구현했던 거라 해봤다고 말해도 될지 모르겠네요🤔 ([프로젝트](https://github.com/HINAPIA/CoMirror))

다음은 바로 이어지는 질문인 스프링 프레임워크을 사용했나요?라는 질문에 답변으로는 아니요라고 답할 것 같아요 ! ㅎㅎ

그래서 저는 웹에 대해서 조금은 안다고 할 수 있지만, 스프링에 대한 학습 경험은 대학교 때 수업으로 1학기 동안 배웠던 것이 전부입니다 ! 그것마저 1년 전이어서 거의 스프링을 모른다고 생각해주시면 감사할 것 같아요 ! 😊

그래서 이번에 호돌과 이야기하면서 스프링에 대해 배우면서 성장해가고 싶네요 !
많은 피드백과 생각할 거리를 주시면 열심히 생각해보도록 하겠습니다 😁

---

## 궁금합니다 !

### 인자로 null이 들어왔을 때,  nullPointerException 하고 IllegerArgumentException 중 무엇이 좋을까?

살짝 마이너한 질문일 수도 있지만, 도매인의 인자로 null이 들어왔을 때, nullPointerException 하고 IllegerArgumentException 중 무엇이 좋을지에 대해 페어와 이야기해봤습니다.

저는 **인자**로 null이 들어온 것이기 때문에, `인자가 잘못됐음`에 포인트를 둬서 `IllegerArgumentException` 이 좋지 않을까라고 생각했습니다.

하지만 페어와 이야기하면서 페어는 인자로 **null**이 들어온 것이기 때문에, `null이 아니어야함`에 포인트를 둬서 `nullPointerException`이 좋지 않을까라는 의견을 듣게 되었습니다 !

하지만 저는 그리고 찾아본 `nullPointerException` 은 실제 값이 아닌 null을 가지고 있는 객체/변수를 호출할 때 발생하는 예외 라고 생각합니다.
하지만 페어(이펙티브 자바 책)가 생각하는 `nullPointerException` 은 null을 허용하지 않은 메서드에 null을 주었을 때 발생하는 예외 라고 하였습니다.

물론 페어의 주장으로 하자면 nullPointerException도 좋은 선택지라고 생각하지만, 저는 여전히 인자가 잘못된 경우는 IllegerArgumentException 이 좋지 않을까라는 생각이 사라지지 않는 것 같아요 !

물론 답은 없겠지만..! 호돌이 생각하기에는 어떤 예외가 더 적절하다고 생각하시나요 개인적인 호돌의 의견이 궁금합니다 !

### 도메인에서 객체를 매핑하는 것과 외부에서 매핑된 값을 주입받는 것 중에 무엇이 좋을까? (ex. Reservation 의 Name)

페어와 코드를 작성하다가 Name이라는 객체를 생성하게 되었습니다.
생성 이유는 Name은 String 값이 "" 이 아닌지 판단하기 위해서 였습니다.

사실 String 값이 ""이 아닌지 판단하는 방법은 3가지가 있다고 생각합니다. 그리고 그에 대한 장단점을 페어와 이야기해봤습니다.

1. Reservation에서 validate 해준다.
 - 장점 : 간단하다, 다른 클래스간에 매핑 관계가 사라진다.
 - 단점 : validate가 필요할 때마다 로직을 반복해줘야한다. / reservatioin에서 자잘한 예외처리를 모두 해줘야한다.
2. Name으로 매핑해서 Name 객체를 생성할 때 validate 해준다.
 - 장점 : validate 로직을 reservation과 분리할 수 있다. / reservatioin에서 자잘한 예외처리를 모두 해주지 않아도 된다.
3. validate해주는 정적 팩토리 매서드를 구현한다. 
 - 장점: validate 로직을 reservation과 분리할 수 있다. / reservatioin에서 자잘한 예외처리를 모두 해주지 않아도 된다.
 - 단점: 다른 공간에서 사용될 수 있는 너무 큰 util 성 클래스 메서드가 생성된다.

여기서 생각나는 단점이 없는 2번 방법을 사용하기로 했습니다.

하지만 페어와 이야기를 더 나누게 된 부분은 이 다음 부분에서 있었습니다!

페어는 Reservation을 생성할 때는 name의 인자타입을 String으로 받는 게 좋을 것 같다고 하였고(Reservation에서 Name 생성),
저는 Reservation을 생성할 때부터 name의 인자타입을 Name으로 받는게 좋을 것 같다고 생각했습니다.(외부에서 변환해서 주입)

두 의견에 대한 주장은 다음과 같습니다.
- (페어) 먼저 DB와 연관지어서 생각해보면, RowMapper을 통해 객체를 생성할 때, dao에서 new Name() 해줘야한다. 이러면 Dao도 Name 객체에 의존되지 않는가?
-> (켬미) 먼저 DB와 연관지어서 생각해보면, RowMapper을 통해 객체를 생성할 때, dao에서 new Name() 해줘야하는 것이 안좋은 것은 알겠다. 그럼 name이 Name타입이 아닌 String 타입인 엔티티를 만들어서 한 단계 다시 바꿔주는 방식이 더 좋을 것 같다.

- (켬미) Name의 변경으로 Reservation의 변경이 없어진다.
-> (페어) 생성자의 변화는 없을테니 문제가 없지 않을까? 외부의 많은 변화보다 연관된 클래스의 한 변화가 나은 것 같다. (Reservation의 변화 하나가 Response와 Dao의 변화보다 나을 것 같다)

이런 대화를 하니 과연 Name을 클래스로 하는게 좋을까 하는 생각이 들었습니다.

단점이 없을 줄 알았던 Name 클래스 객체 도입이 오히려 주입한 후 데이터를 생성하기 때문에 Name과 Reservation 간에 연관성이 생기게 되고, Name의 변화로 결국에는 무엇가의 변화가 생긴다는 것이 좋지 않게 느껴졌습니다.

그래서 이렇게 문제가 많아지면, 오히려 나는 그냥 클래스 내에서 validate를 해주는게 가장 간단하지 않을까? 라는 의견으로 다시 돌아가게 되었습니다. ! ㅎㅎ

그러자 페어는 다음과 같은 이야기를 하였습니다. `한 클래스 내에 너무 많은 validation 을 갖는 것을 경계하고 싶다.` 
더 자세하게는 페어는 validate는 점차 늘어날 거고, 그러면 Reservation의 validate가 너무 커지지 않을까라는 생각이었습니다.

하지만 저는 당장 그 문제보다 Name 클래스를 Reservation 내에서 제작하므로써 생기는 결합성이 더 안좋게 느껴지는 것 같습니다. 🤔

혹시 호돌이 생각하기에는 저희의 이야기가 어떻게 들리시나요? ㅎㅎ 사실 이것도 답은 존재하지 않는다고 생각합니다 !
하지만 역시 호돌이 생각하기에 이런 경우에 어떤 선택을 했을지가 궁금해서 주저리 주저리 글을 남깁니다 !!

2024-05-02 17:06 UTC, kimhodol requested changes
안녕하세요 켬미 :)

요구사항 구현 잘 해주셨네요!

코멘트 확인 부탁드릴게요~

---

> 인자로 null이 들어왔을 때, nullPointerException 하고 IllegerArgumentException 중 무엇이 좋을까?

개인적으로는 IllegalArgumentException을 선호하는데요, https://stackoverflow.com/a/47710 의 본문하고 의견이 비슷해요. 제일 큰 이유는 NPE가 났을 때는 이것이 의도된 예외가 아닐 경우가 있어서, 혼동을 방지하기 위해 코드 작성시에 예외 처리시에 잘 사용하지 않습니다.

> 도메인에서 객체를 매핑하는 것과 외부에서 매핑된 값을 주입받는 것 중에 무엇이 좋을까? (ex. Reservation 의 Name)

우테코에서 배우는 객체지향에서의 관점으로는 Name 클래스가 별도로 존재해서 스스로 책임을 가지게 하는 것이 일단 맞는 것 같습니다. 현업에서는 뭐... 사람마다 코드 스타일이 다르지만 늘 우테코처럼 이상적인 방향을 바라보고 코딩하는 동료만 있는 것은 아니라서 간단한 검증이라면 해당 값을 가지고 있는 클래스에서 검증하는 패턴이 더 흔한 것 같긴하네요. 물론 복잡해지면 값객체를 사용하기도 합니다.

주신 질문에 대해 답을 하자면, 뭐 당연하지만 케바케라고 생각합니다. 지금처럼 Reservation같은 경우는 간단한 클래스다보니 생성시에 String으로 인자를 받아서 도메인 안에서 객체를 생성해서 검증로직을 맡길 것 같네요. 물론 다른 Repository를 참조해야하거나 하는 식의 복잡한 validation이 들어간다면 ReservationValidator이라는 컴포넌트를 별도로 만들었을 것 같아요.

저도 간단한 질문이 있습니다.
- DAO나 Reservation에서 Name에 대한 의존이 생기면 왜 좋지 않다고 생각하시는걸까요?
- 그렇다면 reservation.getName은 Name을 반환해야할까요 아니면 String을 반환해야할까요?

2024-05-02 17:06 UTC, kimhodol commented on src/main/java/roomescape/domain/Theme.java
> +    public Theme changeId(Long id) {
의견) changeId는 void 반환을 할 것 같은 이름이라, withId같은 네이밍은 어떨까요?

2024-05-02 17:06 UTC, kimhodol commented on src/main/java/roomescape/domain/ReservationTime.java
> +    }
질문) 이건 어디서 사용되나요?

2024-05-02 17:06 UTC, kimhodol commented on src/main/java/roomescape/domain/ReservationTime.java
> +        return new ReservationTime(id, this.startAt);
질문) 필드에 접근할 때 this를 붙이는 여부에 대한 어떤 기준이 있을까요?

2024-05-02 17:06 UTC, kimhodol commented on src/main/java/roomescape/service/ThemeService.java
> +        LocalDate endDate = currentDate.minusDays(1);
의견) 매직 넘버는 상수화해주세요.

2024-05-02 17:06 UTC, kimhodol commented on src/test/java/roomescape/integrated/AdminIntegratedTest.java
> +        RestAssured.given().log().all().when().get("/admin").then().log().all().statusCode(200);
의견) 메소드 체이닝 시에는 줄바꿈을 해주면 훨씬 가독성이 좋아져요.

2024-05-04 09:06 UTC, kyum-q commented on src/main/java/roomescape/controller/ThemeController.java
> +    }
구현하기 급급해서 학습테스트를 안해보니 해당 방법을 몰랐네요 !
호돌의 의견대로 ControllerAdvice를 이용해서 예외처리를 담당하는 Controller를 새로 구현하였습니다 !

2024-05-04 10:10 UTC, kyum-q commented on src/main/java/roomescape/domain/Reservation.java
> +        final String errorMessage = "인자 중 null 값이 존재합니다.";
해당 메시지를 ExceptionHandler에서 NullPointExcetion을 모두 다 catch해서 주자니 진짜 null로 인한 문제가 발생했을 시 판단에 방해가 될 것 같아 고민을 좀 하였습니다. !

그래서 해당 Excetion을 커스텀 Excetion을 제작하여 해당 Excetion 생성시 인자가 없으면 해당 메시지가 기본 값이 되도록 설정하였습니다 !
그렇게 되면 Object.requireNonNull 함수 사용할 수 없게 되어서 정적팩토리 메서드를 제작할지, Validate를 해주는 클래스를 컴포지션(합성)해서 사용하도록 할지 고민하다가, Validate 클래스를 Validate가 필요한 객체가 가지고 있고 필요에 따라 필요한 함수를 호출하도록 구현하였습니다!
(해당 클래스가 하는 일은 Object.requireNonNull 과 비슷합니다 !)

2024-05-04 10:13 UTC, kyum-q commented on src/main/java/roomescape/domain/Theme.java
> +    public Theme changeId(Long id) {
호돌의 의견처럼 저도 해당 메서드를 열심히 고민했던 것 같아요..! 
withId도 너무 좋은 아이디어 같아서 동일하게 적용하려다가 조금 더 구체화해주고 싶어서 `createWitdId`로 변경하였습니다 !

2024-05-04 10:29 UTC, kyum-q commented on src/main/java/roomescape/dao/ReservationDao.java
> +            preparedStatement.setLong(4, reservation.getTheme().getId());
get으로 시작하는 메서드 명은 너무 필드의 값을 가져오는 느낌이 크다고 생각해서 findTimeId() findThemeId() 를 구현하였습니다 !

2024-05-04 10:34 UTC, kyum-q commented on src/main/java/roomescape/domain/ReservationTime.java
> +    }
Test에서 동일한 값을 가지고 있는지 확인 시 사용되었습니다 !

그리고 추가적으로 해당 class가 불변 객체라고 생각되어서 record로 변경하였습니다 !
변경하면서 고민이 되었던 부분은 ReservationTime 생성 시 id를 입력했을 경우에는 id null이면 안된다고 제약하고자 id까지 null 체크를 하도록 하였습니다 !
하지만 도매인 자체에서 id가 null이 될 수 있는 값이기 때문에(id를 입력받지 않은 경우 id를 null이었다) 제약을 따로 하지 않아도 된다고 생각해서 id는 null 체크 안하도록 변경하였습니다 !

2024-05-04 10:36 UTC, kyum-q commented on src/main/java/roomescape/domain/ReservationTime.java
> +        return new ReservationTime(id, this.startAt);
객체 생성 시(생성자에서)는 this를 붙이는 편이여서, 생성을 도와주는 메서드인 해당 메서드에서도 this를 추가하였습니다 !

2024-05-04 10:38 UTC, kyum-q commented on src/main/java/roomescape/domain/ReservationTime.java
> +        return new ReservationTime(id, this.startAt);
혹시 호돌이 생각하는 필드에 접근할 때 this를 붙이는 기준이 있을까요? 😊

2024-05-04 10:53 UTC, kyum-q commented
안녕하세요 호돌 🐯
호돌의 리뷰 덕분에 코드가 점차 좋아지는 것 같아요 ! 그래서 이번에도 거침없는 리뷰와 생각할 거리를 주시면 감사하겠습니다 ! 😊

---

호돌의 질문들에 대해 저의 생각을 말해보겠습니다 !

### DAO나 Reservation에서 Name에 대한 의존이 생기면 왜 좋지 않다고 생각하시는걸까요?

Reservation이나 Dao 둘 다 의존성이 있으면 Name의 생성자 인자 추가 등 변화가 생겼을 때 Name 뿐만 아니라 의존성이 있는 객체도 변경되어야한다는 점이 안좋다고 생각합니다 !

둘 중 하나의 의존성을 제거해야한다면 저는 도메인 객체인 Reservation 객체에서 의존성이 제거되어야 한다고 생각했습니다 ! 그래서 Reservation 생성 시 name을 String이 아닌 Name으로 주입하는 것이 더 좋을 거라고 생각했습니다 ! 😊

### reservation.getName은 Name을 반환해야할까요 아니면 String을 반환해야할까요?

저는 getName이 Name을 반환해야한다고 생각합니다 ! 물론 외부에서 사용하기엔 String 반환이 더 좋을 수도 있겠지만, Name 객체 자체를 반환해서 이 또한 Name 메서드 변경이 일어났을 때, 변경되는 객체가 Name의 내부 값을 사용하는 클래스여야한다고 생각합니다. 그리고 Name의 string 값을 필요로하는 객체를 찾을 때 reservation.getName에서 string을 반환해준다면 해당 함수를 쓰는 객체를 찾아야하는데, Name을 반환해준다면 해당 함수를 쓰는 객체를 Name에서 바로 확인할 수 있다고 생각합니다 !

2024-05-04 11:34 UTC, kyum-q commented
안녕하세요 호돌 🐯
호돌의 리뷰 덕분에 코드가 점차 좋아지는 것 같아요 ! 그래서 이번에도 거침없는 리뷰와 생각할 거리를 주시면 감사하겠습니다 ! 😊

호돌의 질문들에 대해 저의 생각을 말해보겠습니다 !

DAO나 Reservation에서 Name에 대한 의존이 생기면 왜 좋지 않다고 생각하시는걸까요?
Reservation이나 Dao 둘 다 의존성이 있으면 Name의 생성자 인자 추가 등 변화가 생겼을 때 Name 뿐만 아니라 의존성이 있는 객체도 변경되어야한다는 점이 안좋다고 생각합니다 !

둘 중 하나의 의존성을 제거해야한다면 저는 도메인 객체인 Reservation 객체에서 의존성이 제거되어야 한다고 생각했습니다 ! 그래서 Reservation 생성 시 name을 String이 아닌 Name으로 주입하는 것이 더 좋을 거라고 생각했습니다 ! 😊

reservation.getName은 Name을 반환해야할까요 아니면 String을 반환해야할까요?
저는 getName이 Name을 반환해야한다고 생각합니다 ! 물론 외부에서 사용하기엔 String 반환이 더 좋을 수도 있겠지만, Name 객체 자체를 반환해서 이 또한 Name 메서드 변경이 일어났을 때, 변경되는 객체가 Name의 내부 값을 사용하는 클래스여야한다고 생각합니다. 그리고 Name의 string 값을 필요로하는 객체를 찾을 때 reservation.getName에서 string을 반환해준다면 해당 함수를 쓰는 객체를 찾아야하는데, Name을 반환해준다면 해당 함수를 쓰는 객체를 Name에서 바로 확인할 수 있다고 생각합니다 !

--- 

답을 적으면서도 현재는 Name을 지우고 String으로 받게 하였지만, Name으로 객체를 매핑한다면 외부에서 주입 받는게 맞다고 생각이 듭니다..! 🤔

제 생각과 다른 호돌의 의견이 있다면 편하게 말씀해주세요 ! 호돌의 생각도 많이 들어보고 싶습니다 !

2024-05-05 08:52 UTC, kimhodol requested changes
안녕하세요 켬미 :)

피드백 반영 잘 해주셨네요.

코멘트 확인 부탁드립니다!

2024-05-05 08:52 UTC, kimhodol commented on src/main/java/roomescape/controller/ControllerExceptionHandler.java
> +                // TODO: Response 메시지 변경
의견) TODO는 리뷰 요청 전에 삭제해주세요 :)

2024-05-05 08:52 UTC, kimhodol commented on src/main/java/roomescape/controller/ControllerExceptionHandler.java
> +public class ControllerExceptionHandler {
의견) 예상치 못한 예외를 처리하는 핸들러가 있으면 좋겠네요.

2024-05-05 08:52 UTC, kimhodol commented on src/main/java/roomescape/dao/ReservationDao.java
> +            preparedStatement.setLong(4, reservation.getTheme().getId());
개인적으로 find는 nullable임을 가정하고, get은 nonnull인 값을 가져올때 사용할때 쓰긴합니다 ㅎㅎ

2024-05-05 08:52 UTC, kimhodol commented on src/main/java/roomescape/domain/ReservationTime.java
> +        return new ReservationTime(id, this.startAt);
저는 1, 3처럼 this를 반드시 써야하는 경우가 아니라면 모두 생략하는 편이예요. (물론 팀 컨벤션이 우선되겠죠?)

2024-05-05 08:52 UTC, kimhodol commented on src/main/java/roomescape/service/ThemeService.java
> +        if (themeDao.isExistThemeByName(dto.name())) {
의견) boolean 반환이면 isExsist 대신 exists만 사용해도 괜찮을 것 같네요.

2024-05-05 08:52 UTC, kimhodol commented on src/test/java/roomescape/integrated/ReservationIntegratedTest.java
> +    void createReservation_whenNameIsNull() {
의견) 리뷰 요청 전에 테스트 통과 여부도 꼭 확인해주세요 :)

2024-05-05 11:23 UTC, kyum-q commented on src/main/java/roomescape/dao/ReservationDao.java
> +            preparedStatement.setLong(4, reservation.getTheme().getId());
오 그런 기준이 될 수도 있군요 ! 좀 더 고민을 해보니 find를 쓸만큼 복잡한 구현이 있는 거솓 아니고, getter의 느낌을 가져도 될 것 같아서 get_으로 변경하였습니다 😊
호돌의 find를 사용하는 기준을 알려주셔서 감사합니다 ㅎㅎ

2024-05-05 12:36 UTC, kyum-q commented on src/main/java/roomescape/controller/ControllerExceptionHandler.java
> +public class ControllerExceptionHandler {
예상치 못한 에러는 서버의 문제라고 판단되므로 statusCode 500 을 반환하도록 구현하였습니다!

```java
    @ExceptionHandler({Exception.class})
    public ResponseEntity<ProblemDetail> systemHandleException(Exception e) {
        ProblemDetail problemDetail = ProblemDetail.forStatusAndDetail(HttpStatus.INTERNAL_SERVER_ERROR, e.getMessage());
        return ResponseEntity
                .internalServerError()
                .body(problemDetail);
    }
```

2024-05-05 14:41 UTC, kyum-q commented
안녕하세요 호돌 🐯 이번에도 리뷰 부탁드릴게요 ㅎㅎ 😊
추가적으로 Dao 테스트를 추가해봤습니다 !
그리고 Service 테스트도 추가하고자 했는데 인터넷에 나온 코드들을 이해하기에 아직 어려움이 있네요..! ㅎㅎ 그래서 테스트를 어떤 방식(목, 스텁 등등)으로 하는 것이 더 좋을지 고민해보고 다음 리뷰 요청에 추가해보겠습니다 ! 😁

2024-05-07 06:03 UTC, kyum-q commented
안녕하세요 호돌 🐯 
코드의 변화는 service 테스트를 진행한 것 외에는 거의 없습니다 !

하지만 코드를 작성하면서 몇가지 궁금한 점이 생겨서 글로 남겨보겠습니다 !

## 궁금합니다 !

### DB의 추가/삭제 시 발생 가능한 예외를 어떻게 처리하는게 좋을까요?

DB 추가/삭제 시 발생 가능한 예외들이 있습니다.

> 예를 들면,
> 1. 해당 theme과 관련된 예약이 존재하는데 theme을 삭제하려 한 경우
> 2. 예약을 추가하는데 존재하지 않는 themId 혹은 tiemId 가 있는 경우

대다수에 이런 예외 상황들은 외래키가 있는 경우 발생합니다 !

그래서 저는 이를 처리하는 방법이 두가지가 있는 것 같아요 ! 두 가지에 대한 제가 생각하는 장단점도 적어볼게요 ! 😁

---

**1. 추가/삭제 전에 확인 목적으로 DB를 접근한다.**
> 예를 들어 현재 제 코드에 `exists`로 시작하는 메서드들을 의미합니다 !

- 장점
  - 에러가 발생하는 이유를 확실하게 알 수 있다.
  - Dao를 호출한 결과를 가지고 service 단에서 처리하기 때문에 DB와 관계 없다. (DB와 의존성이 없다)
  - 만약에 외래키 관계가 없어도 예외를 알아낼 수 있다.

- 단점
  - (2번 방법을 쓴다면) 하나의 쿼리로 처리할 수 있음에도, 여러 번 접근해서 속도 저하가 생긴다.


**2. 추가/삭제를 진행하고 DB 에러가 발생하면 에러를 catch 한다.**

- 장점
  - DB 접근을 한 번만 한다.

- 단점
  - service 에서 DB의 에러를 catch한다면 DB가 변경될 때마다 예외가 변경되어, DB와 의존관계가 커진다.  (DB의 변화에 service도 변한다)
  - dao에서 DB의 에러를 catch한다면, dao는 DB 접근만 담당한다고 생각하는데 예외를 잡고 처리하는 비즈니스 로직이 추가된다. (DAO의 역할과 service의 역할 구분이 무의미해진다고 생각한다)
  - 예외가 무엇때문에 발생하는지 명확하지가 않다. (외래키가 잘못됨 -> 무슨 외래키?)

---

이처럼 2번 방식의 단점이 더 많고, 1번 방식의 장점이 더 좋다고 생각해서 1번 방식을 선택했습니다. !
하지만 여전히 `너무 비효율적인 코드인가` 하는 생각이 제 머리속에서 사라지지 않는 것 같아요 (살짝의 찜찜합?) 😊

그래서 혹시 호돌이 생각하기에는 어떤 방식을 자주 사용하고 좋다고 생각하는지 궁금합니다 !

또한, DB 접근을 최소화하는 것이 효율적으로 좋다고 생각하는데 얼마나 DB 접근을 자제하는지 좋을지 판단이 모호해서 생기는 문제 같아서, 호돌의 경우는 DB에 접근하므로 체크하는 경우와 도메인 로직을 믿고 DB를 바로 실행시키는 경우가 어떻게 나눠지는지 기준이 있는지 궁금합니다 ! 🤔

추가적으로, 실무에서는 외래키를 잘 사용하지 않는다고, 들었는데 그럼 모든 위와 같은 예외 상황들의 경우의 수를 DB 접근으로 확인하는 건가요? 아니라면 보통 어떻게 처리하는지 궁금합니다 !

### 서비스 테스트 방식을 선호하는 방식이 있을까요?

기존에는 웬만해서 시스템 코드를 사용하도록 구현했는데, 이렇게 했을 시 속도도 너무 느리고 dao 에러도 service 단에 에러가 발생하기 때문에 service를 테스트할 때는 사용하지 않고 싶어서 이번에 처음으로 목테스트, 페이크테스트 등을 찾아봤던 것 같아요 ! 

Fake 객체는 말 그대로 기능에 따른 함수만 정의 해놓은 인터페이스를 제작하고, 구현체를 다르게 하는 것이었어요. (Fake는 DB 접근을 안하고 list나 map에서 얻어오도록)

Mock 객체는 의존성 주입을 하지 않은 가짜 객체를 생성하고, 필요에 따라 해당 객체의 함수들이 반환할 값을 지정해놓는 것이었어요. 

둘 중에 뭘 해도 크게 성능상도, 실행 동작 상도 다를게 없다고 저는 생각해서, 더 간단하게 구현할 수 있고, 필요할 때 필요한 메서드만 재정의할 수 있는 Mock을 사용해서 구현하였습니다.

혹시 호돌은 이렇게 service를 테스트할 때 어떤 방식을 사용하시나요? 그 방식을 더 자주 사용하는 이유가 있는지 궁금합니다 !

그리고 제가 아직 판단이 명확하지 않아서 일수도 있지만, fake와 mock의 차이가 무엇이라고 생각하는지 호돌의 생각도 궁금합니다 ! 😁


### `@Mock` 사용시 `lenient()`에 대해서 궁금합니다.

목 사용 시 예상치 못한 에러를 발견했습니다 ! 바로 `UnnecessaryStubbingException` 이었습니다 

이유를 찾아보니 `사용하지 않으므로써 불필요한 스텁이라고 판단해서 였습니다.` 이를 해결할 수 있는 방법은 두가지 였습니다. 

1. 해당 코드를 지운다. 
2. `lenient()`를 사용한다.

처음엔 간단한 1번을 사용하는게 좋겠다 해서 지웠습니다 ! 그런데 지우고보니 만약에 내가 실제 service 코드를 건들여서 코드 위치가 변경되면 문제가 발생할 것 같았습니다. 

예를 들어 다음 코드가 있을 때, 제가 재정의해야하는 메서드는 `readTimeById`와 `readThemeById` 입니다. 
근데 예약시간이 존재하지 않을 때 예외가 잘 발생하는지 판단할 때는 `readTimeById`만 해도 되니까 `readThemeById`는 정의하지 않았을 때 문제가 발생한다고 생각합니다. 만약 테마 예외를 먼저 확인하게 된다면, 테스트도 수정해야하게 됩니다.
``` java
    private Reservation createReservationFromDto(ReservationCreateRequest dto) {
        ReservationTime time = timeDao.readTimeById(dto.timeId())
                .orElseThrow(() -> new IllegalArgumentException("해당 예약 시간이 존재하지 않습니다."));
        Theme theme = themeDao.readThemeById(dto.themeId())
                .orElseThrow(() -> new IllegalArgumentException("해당 테마가 존재하지 않습니다."));

        Reservation reservation = dto.createReservation(time, theme);
        validateAvailableReservation(reservation);
        return reservation;
    }
```

그래서 저는 현재 필요한 메서드는 다 재정의하고 `lenient()`를 사용했습니다 !

혹시 호돌은 이런 경우에 `lenient()`를 사용하나요? 아니면 그냥 제거하나요? 호돌의 선택과 그 이유가 궁금합니다! 😁

---

갑자기 궁금한 점이 생겨서 이렇게 주저리 주저리 말이 길어졌네요 ! ㅎㅎ 이번 리뷰도 잘 부탁드립니다 😊

2024-05-07 14:58 UTC, kimhodol requested changes
안녕하세요 켬미 :)

나머지 코드도 잘 짜주셨네요.

코멘트 확인 부탁드릴게요!

---

> DB의 추가/삭제 시 발생 가능한 예외를 어떻게 처리하는게 좋을까요?

팀마다 다르고 상황마다 다르겠지만, 개인적인 의견을 물어보신 것이라 생각하고 답변드릴게요. 저는 `추가/삭제 전에 확인 목적으로 DB를 접근한다.` 방식으로 보통 접근하는데요, 이것 외에도 지나치게 많은 리소스가 소비되지 않는 이상은 **어플리케이션 단에서 대부분 비즈니스 로직을 처리하려는 편**이예요. 이유를 몇 가지 들자면 간단하게 이 정도가 생각이 나네요. 

1. 스스로를 비롯해 같이 일하는 동료들이 DB에 대한 지식보다는 어플리케이션 대한 지식이 더 많다(또는 경향성이 있다).
2. "DB에서 비즈니스 로직을 처리하지 않겠다는 것"을 기본 스탠스로 가져가면 디버깅을 어플리케이션에서 하면 대부분의 문제가 해결된다.

켬미가 언급하신, 쿼리가 여러번 나간다는 단점에 대해서는, SELECT문은 인덱스를 잘 타는 쿼리를 작성했다는 가정하에 현대 컴퓨팅 능력을 고려했을 때 그렇게 큰 문제가 아닐거라는 생각을 가지고 있습니다. 2배의 쿼리가 문제가 된다면 커넥션 풀을 늘리던지 더 비싼 서버를 사용하고 마음 편하게 살자는, 다소 게으르다고 할 수 있는 마인드라서요 ㅋㅋ 돈을 좀 더 쓰는 대신 어플리케이션 코드를 좀 더 빠르고 깔끔하게 짜고 버그가 안나게 하는게 낫지 않나라는... 그런 아주아주 개인적인 견해입니다.

> 호돌의 경우는 DB에 접근하므로 체크하는 경우와 도메인 로직을 믿고 DB를 바로 실행시키는 경우가 어떻게 나눠지는지 기준이 있는지 궁금합니다 !

DB 접근을 큰 비용이라고 생각하지 않습니다. 다만 SELECT문 하나에 1초씩 걸린다 그러면 큰 문제가 되긴하겠죠? 물론 N+1 문제 같이 어플리케이션에서 고칠 수 있는 부분은 반드시 고치고, Bulk 처리가 가능하면 꼭 해야겠지만, RDBMS를 사용하면서 전체 쿼리 오퍼레이션의 시간을 극단적으로 줄이려고 하지 않는 이상(이런 경우는 아직 짧은 경력 안에서는 없었던 것 같네요) DB 접근은 그냥 하는 것 같아요. 실제로 외부(또는 운영팀)에서 의도적으로 DB의 값들을 바꾸는 경우도 있어서, 개인적으로는 무조건 가져와서 확인하고 로직 실행하는 것 같습니다.

> 혹시 호돌은 이렇게 service를 테스트할 때 어떤 방식을 사용하시나요? 그 방식을 더 자주 사용하는 이유가 있는지 궁금합니다 !

이것도 완전 케이스마다 다르긴한데, 기본적으로는 Mock을 사용해서 서비스 계층만 격리해서 사용합니다. 사실 마음 속으로는 Fake를 선호하긴하는데(Mock이 안 좋다는 소리를 하도 많이 봐서...도 있을 것 같네요), 그냥 Mock을 쓰는게 정신건강에 이로운것 같아서 사용해요. Fake는 따로 또 구현을 해야하는데 그 비용이 너무 클 때가 있다고 느껴지긴해요 실제로 업무할때는. 물론 회사마다 팀마다 다를거예요!

> fake와 mock의 차이가 무엇이라고 생각하는지 호돌의 생각도 궁금합니다 ! 

글쎄요? Fake는 테스트용 객체를 직접 구현하는것이고, Stub이 결과값만 던져주는 상태검증, Mock이나 Spy가 행위검증으로 알고 사용하고 있습니다. 자세한 것은 검색해보는게 나을 것 같네요 ㅋㅋ

> 혹시 호돌은 이런 경우에 lenient()를 사용하나요? 아니면 그냥 제거하나요? 호돌의 선택과 그 이유가 궁금합니다! 😁

저는 한번도 사용해본적이 없어서 처음봤네요 사실 ㅋㅋ 저런 예외가 나면 "어 깜빡했네" 하고 그냥 추가해주고는 했는데, [문서](https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#lenient()) 찾아보니 strict하게 가지 않는 레거시 버전에서 파생되었다고 나와있고 strict한 버전을 권장하는 것 같아요.

Most mocks in most tests don't need leniency and should happily prosper with Strictness.STRICT_STUBS.

2024-05-07 14:58 UTC, kimhodol commented on src/test/java/roomescape/domain/exception/ValidatorTest.java
> +    void NonNull() {
의견) 테스트명이 대문자로 시작할 필요는 없을 것 같아요.

2024-05-08 04:36 UTC, kyum-q commented
호돌 친절한 답변 감사합니다 !

정말 호돌은 어떻게 생각할까가 궁금했었는데 친절하게 설명해주셔서 이해가 혹혹 되네요 !

호돌이 주신 피드백 반영해서 다시 리뷰 요청 드립니다 !
( 이외에 현재는 크게 수정해야 할 사항은 모르겠네요..!)

2024-05-08 08:47 UTC, kimhodol approved these changes
안녕하세요 켬미 :)

피드백 반영하시느라 고생하셨어요.

다음 단계도 화이팅입니다!

2024-05-08 08:47 UTC, merged