[방탈출 사용자 예약 - 1~3단계] 아토(이혜린) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #83
Opened 2024-05-02 10:03 UTC by hyxrxn

안녕하세요 안돌! 드디어 PR을 올릴 수 있게 되었네요... 🥹
이미 말씀 드렸지만 보시기 편하시라고 한 번 더 언급하겠습니다.
저는 프리코스 때 자바를 처음 사용해봤고, 레벨2 들어와서 스프링을 처음 사용해보았습니다.
그래서 학습 테스트를 잘 이용해보고자 했어요!

그리고 저번에 제 코드를 이용할 예정이라고 말씀 드렸었는데요,
구현을 조금 하다보니 제 코드가 그냥 재즈 코드처럼 바뀌어가는 상황이 자꾸 펼쳐지더라고요... 하핫 😅
그래서 쿨하게! 재즈 코드에서 시작하는 것으로 마음을 바꿨습니다 ㅋㅋㅋㅋ

원격 저장소의 커밋 하나를 뛰어넘은 채로 다른 커밋을 마구 작성해버려서 PR을 못 보내는 상황이 생긴 것 같아요.
그래서 뛰어넘은 커밋 이후에 다른 커밋들을 붙여넣는 방식으로 해결을 했습니다.

아무튼 이번 미션은 시간이 정말 모자랐어요.
어제도 캠퍼스 나와서 11시 맞춰 하교하고, 오늘도 1시간 일찍 등교했는데도 불구하고 아슬하게 마무리했습니다.
그래서 중간에 테스트하고자 했지만 못한 게 좀 있을 듯 해요.
저번 미션의 안돌의 가르침을 재즈에게 제대로 받아먹었을지 걱정이네요... ㅎㅎ

2024-05-03 14:34 UTC, andole98 requested changes
페어의 의견이 많이 들어간것 같긴 하지만 잘 구현해 주셨네요~

레벨1에서 배운 내용을 잘 활용한 모습이 매우 좋습니다. :+1:

몇가지 코멘트 남겼습니다. 살펴봐주세요

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationTimeApiController.java
> +    @ResponseStatus(HttpStatus.CREATED)
201 status code를 알아보고 적절한 규칙을 지켰는지 알아볼까요?

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/domain/Name.java
> +public class Name {
레벨1을 잊지 않으셨군요 매우 좋습니다.

일반 String이 Name이 되면서, 특별한 역할을 수행할 수 있게 되었네요.

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/domain/Reservation.java
> +        this(id, new Name(name), new Theme(themeId, themeName, description, thumbnail), new ReservationDate(date),
생성자를 잘 다루셨네요 :+1:

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/domain/Reservation.java
> +        return Objects.equals(id, that.id);
id만 갖고 동등성을 비교하는 이유가 있을까요?

id가 같고 나머지가 다른 객체는 같은객체로 봐도 될까요?

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/domain/ReservationDate.java
> +public class ReservationDate {
Name에 이어서 매우 좋은 시도에요 :+1:

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(new ErrorResult("죄송합니다. 서버에서 문제가 발생하여 요청을 처리할 수 없습니다."),
죄송합니다에서 조금 웃었네요ㅋㅋ

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler
ExceptionHandler로 마킹된 메서드의 파라미터의 타입으로도 예외처리가 가능하지만, 명시적으로 `@ExceptionHandler`에 대상 Exception 타입을 명시하는 경우가 많습니다.

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler
```suggestion
    @ExceptionHandler(HttpMessageNotReadableException.class)
```

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +        return findReservationById(savedId);
방금 db에 저장한 내용인데 다시 조회하는 이유가 있을까요?

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +                .addValue("timeId", timeId);
컬럼이름이 틀린것 같아요. time_id가 맞을것 같은데요?

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +        List<Integer> result = jdbcTemplate.queryForList(sql, parameterSource, Integer.class);
snake_case

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +        return jdbcTemplate.query(sql, paramMap, rowMapper).get(0);
`get(0)` 

만약 조회된 내용이 아무것도 없다면 어떻게 될까요? 그건 아토가 원하는 결과인가요?

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcReservationTimeRepository.java
> +                INNER JOIN theme AS th ON r.theme_id = th.id
theme 의 값은 쓰이지 않으니 theme과의 조인은 불필요하지 않을까요?

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcThemeRepository.java
> +
LIMIT을 열어줌으로써 사용하는 객체가 선택할 수 있게 배려했군요. 좋습니다.

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/service/ReservationService.java
> +        if (LocalDateTime.of(reservation.getDate(), time.getStartAt()).isBefore(LocalDateTime.now())) {
if 문 안의 condition은 메서드로 추출하면 좋을것 같네요.

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/service/ThemeService.java
> +
줄바꿈이 필요하다면 하나씩 나열하는것도 좋은것 같아요.

```java
List<Theme> topBookedThemes = themeRepository.findTopBookedThemes(LocalDate.now().minusDays(7), 
        LocalDate.now().minusDays(1), 
        10);

```

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/service/dto/ReservationTimeRequestDto.java
> +
이 validation들은 적절하게 잘 구성하신 것 같아요.

2024-05-03 14:34 UTC, andole98 commented on src/main/java/roomescape/service/dto/ReservationTimeResponseDto.java
> +    private final Boolean alreadyBooked;
`boolean`인게 좋을것 같은데 Boolean인 이유는 null이 들어갈수 있어서네요.

`ReservationTime` 이라는 리소스는 alreadyBooked 라는 필드가 항상 필요한가요?

사용되는 맥락이 다르다면 다른 리소스로 표현될수도 있지 않을까요?

만약 예약가능한 시간에 더해서 이벤트 시간, 할인 시간, 붐비는 시간 등이 추가되면 이 객체에 필드가 추가되어야 할까요?

2024-05-03 14:34 UTC, andole98 commented on src/test/java/roomescape/controller/ThemeApiControllerTest.java
> +        ThemeRequestDto requestDto = new ThemeRequestDto("안돌", "안녕하세요", "hello.png");
:wave:

2024-05-03 14:34 UTC, andole98 commented on src/test/java/roomescape/repository/DatabaseCleanupListener.java
> +        return testContext.getApplicationContext().getBean(JdbcTemplate.class);
이 코드가 갖고 있는 의미를 이해할 수 있으면 좋겠네요.
spring context, bean 과 같은 키워드가 있는데요, 아마 미션을 진행하며 다시 만나게 될거에요.
그때 테스트에서 이렇게 썼었는데~? 를 기억하며 알아보면 도움이 될것 같네요.

2024-05-03 14:34 UTC, andole98 commented on src/test/java/roomescape/repository/JdbcReservationRepositoryTest.java
> +class JdbcReservationRepositoryTest {
이 테스트는 생각해볼게 좀 있어보이네요.

학습테스트라면 충분히 장려할만하지만, 만약 그렇지 않다면

db를 테스트 범위에 포함할것인지? 어떤 의미를 갖는지? 사실상 repository가 갖고 있는 `sql` 을 테스트하는게 아닌지? 그렇다면 이러한 테스트가 적절한지?

변경을 요구하는건 아니지만 한번쯤 생각해보면 좋을것 같아요. 우리는 테스트를 왜 하는걸까?

2024-05-03 14:34 UTC, andole98 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@ExtendWith(MockitoExtension.class)
좀 어려웠을것 같은데 괜찮았나요?

2024-05-03 14:34 UTC, andole98 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +    @DisplayName("모든 예약 정보 조회 및 의존 객체 상호작용 테스트")
"상호작용 테스트"가 아니라

`예약 리스트를 조회할땐 findAllReservation이 호출되어야 한다` 가 적절한 설명인것 같아요.

2024-05-03 14:34 UTC, andole98 commented on src/test/java/roomescape/MissionStepTest.java
> +@Sql("/truncate.sql")
이런것도 알아봤군요 
truncate와 delete는 무엇이 다른가요?

2024-05-04 10:56 UTC, hyxrxn commented on README.md
> +# API 명세
저도 미션 중 여러 예시를 보며 감을 잡는 중입니다... ㅎㅎ

2024-05-04 11:04 UTC, hyxrxn commented on src/main/java/roomescape/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler
안써도 된다고 해서 생략했는데, 쓰는 경우가 더 많다면 따르겠습니다!

2024-05-04 11:12 UTC, hyxrxn commented on src/main/java/roomescape/domain/Reservation.java
> +        return Objects.equals(id, that.id);
여기는 이번에 추가한 부분은 아니긴 한데요...! Theme에도 비슷한 부분이 있어 여기에 답변 달겠습니다.

DB에서 id가 같을 수 없는 것이 보장이 되어있으니 나머지를 비교할 필요가 없다고 생각했습니다!

2024-05-04 11:41 UTC, hyxrxn commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +        return findReservationById(savedId);
request를 이용해 만든 reservation은 시간 아이디와 테마 아이디만 갖고 있는 상태입니다.
없는 정보(아이디, 테마의 이름, 내용, 썸네일, 시작 시간)를 기존의 reservation에 추가하려면 어차피 db 조회를 한 후 setter를 이용해야 해 저장된 정보를 한 번에 불러 새로운 객체를 만들었습니다.

2024-05-04 12:09 UTC, hyxrxn commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +                .addValue("timeId", timeId);
`:timeId`에서 : 뒤의 timeId 말하시는거죠?
`addValue("timeId", timeId)`에서 뒤의 timeId와 맞추는 게 덜 헷갈릴 것 같기도 하고,
저 부분에 timeId의 값을 넣어 주는 것은 아무튼 자바라고 생각해서 자바 문법을 따랐습니다.
: 뒤에도 snake case를 사용하는 게 국룰(?)... 규칙인가요?
스프링 공식 문서를 봐도 잘 모르겠어서 여쭤봅니다!

2024-05-04 12:14 UTC, hyxrxn commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +        return jdbcTemplate.query(sql, paramMap, rowMapper).get(0);
어차피 저장 이후에만 쓰이는 메서드라고 생각해서 당연히 있을 거라고 봤는데... 제가 안일했군요.

고려해서 고쳐보도록 하겠습니다

2024-05-04 12:44 UTC, hyxrxn commented on src/main/java/roomescape/repository/JdbcReservationTimeRepository.java
> +                INNER JOIN theme AS th ON r.theme_id = th.id
헉 그러네요

2024-05-04 13:06 UTC, hyxrxn commented on src/main/java/roomescape/service/dto/ReservationTimeResponseDto.java
> +    private final Boolean alreadyBooked;
맞습니다...
목요일에 급하게 구현하느라(대략 제출 마감을 3시간 남기고..) 분리하면 좋겠다는 생각만 하고 일단 존재하는 코드를 수정했어요.
고칠 기회가 왔으니 고쳐보겠습니다

2024-05-04 13:35 UTC, hyxrxn commented on src/test/java/roomescape/repository/DatabaseCleanupListener.java
> +        return testContext.getApplicationContext().getBean(JdbcTemplate.class);
레벨1 때 김영한님의 `스프링 핵심 원리 - 기본편` 강의를 들으며 정리하는 스터디를 했는데요,
그 때 맛보기 대충 해봤습니다.

앞으로의 미션에서 이 테스트도 꼭 같이 기억하며 공부해보겠습니다

2024-05-04 13:46 UTC, hyxrxn commented on src/test/java/roomescape/repository/JdbcReservationRepositoryTest.java
> +class JdbcReservationRepositoryTest {
레벨1에서 배웠던대로 테스트를 이것저것 많이 해보려고 작성한 것은 맞습니다!
실제로 이 `JdbcReservationRepositoryTest`에서 initialize 시에 테마 정보를 insert하지 않고 테스트를 돌려 실패하기도 했거든요...
왜 실패하는지 이유를 찾으며 놓친 부분을 알 수 있었습니다.

그런데 저는 RepositoryTest들 덕에 제가 작성한 sql문이 원하는 역할을 잘 한다고 좀 더 확신할 수 있어서 좋기도 했어요.
sql을 테스트할 필요는 없는건가요??
좀 더 고민해보도록 하겠습니다

2024-05-04 13:51 UTC, hyxrxn commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +@ExtendWith(MockitoExtension.class)
100% 이해했다고는 할 수 없지만
```
if(조건) {
    state 1
} else {
    state 2
}
```
문을 쓰면 조건 달성 시 state 1이, 미 달성 시 state 2가 실행된다는
그 정도의 이해로 넘어갔습니다!

재즈가 설명을 열심히 해줬어요 ㅋㅋㅋㅋ

2024-05-05 08:22 UTC, hyxrxn commented on src/test/java/roomescape/MissionStepTest.java
> +@Sql("/truncate.sql")
truncate가 delete보다 좀 더 빠르고, 대신 롤백이 안된다고 알고 있습니다

2024-05-05 09:54 UTC, hyxrxn commented on src/main/java/roomescape/controller/ReservationTimeApiController.java
> +    @ResponseStatus(HttpStatus.CREATED)
혹시 location 헤더에 대해 말씀하신게 맞나요??
저희도 `ResponseEntity.created()`를 사용하면 URI를 꼭 담아야 하는 것을 보고 그 부분에 대해 생각을 해봤습니다.

저희의 생각의 흐름은 다음과 같습니다.

1. 현재 URI를 함께 줄 이유가 없다. 그런데 굳이 줘야하나?
2. 주는 것이 규칙이라면 주자.
3. [찾은 규칙](https://http.dev/201)
>The HTTP response will optionally contain the [Location](https://http.dev/location) HTTP header field to indicate where the resource was created.  
4. 선택적이라면 필요 없는 정보는 주지 않는 것으로 하자.

그런데 이 질문을 받고 다른 사이트들 [여기](https://developer.mozilla.org/ko/docs/Web/HTTP/Status/201), [저기](https://www.webfx.com/web-development/glossary/http-status-codes/what-is-a-201-status-code/)를 보니 주는 것이 규칙인 것 같기도 하네요.....??
일단 담도록 하겠습니다.
혹시 다른 부분에 대해 말씀해주신 거라면 다시 알려주시면 감사하겠습니다!

2024-05-05 11:55 UTC, hyxrxn commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +        return findReservationById(savedId);
설명을 의도에 맞게 바꾸었습니다.

그런데 페어와 이야기해보니 현재의 서비스 관련 테스트가 정말 의미가 있는지 고민해보아야 하겠다는 결론이 났습니다...
이렇게 테스트해볼 수 있다는 것을 알게 되긴 했는데요...!
`실제 db가 작동을 하지 않아도 ServiceTest가 통과하는 것이 맞을지? 의미있는 새 로직이 존재하는지?`
일단 아직은 저는 repository가 어떤 대답을 줬을 때 원하는대로 실행이 되고, 어떤 대답을 줬을 때 예외를 터뜨리는지를 확인하는 것도 의미있다고 생각하기는 합니다.

이 부분도 좀 더 고민해보겠습니닷,,,, 🫠

2024-05-05 12:17 UTC, hyxrxn commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +    @DisplayName("모든 예약 정보 조회 및 의존 객체 상호작용 테스트")
테스트 의도에 맞는 이름으로 변경했습니다!

그런데 페어와 이야기를 하다가, 현재의 서비스 테스트가 의미가 있는지 고민해봐야겠다는... 결론을 냈어요.
`db가 제대로 작동하지 않아도 ServiceTest가 성공하는 게 맞는지? 테스트를 할만큼 의미있는 로직이 있는지?`
물론 이 테스트들로 이런 방식으로도 테스트를 할 수 있다는 것을 알게 되었습니다!
그리고 아직 저는 repository가 어떤 대답을 줬을 때 원하는 실행을 하는지, 어떤 대답을 줬을 때 예외를 터뜨리는지 확인하는 것도 필요하다고 생각하기는 합니다!

이 부분도 좀 더 고민해보아야겠어요,,, 🫠

2024-05-05 14:28 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationTimeApiController.java
> +    @ResponseStatus(HttpStatus.CREATED)
알아보신 내용이 맞습니다. 201을 받으면 Location header를 찾는 경우가 많아요.

알아보신 것처럼 사실에 대한 설명이 갈리는 경우 원본을 보면 좋긴 합니다.

어떤 사실에 대한 평가나 의견은 여러가지 있는것이 당연하지만, 스펙과 같이 정해져 있는 것은 official한걸 찾아보는것도 좋은것 같아요~

(그냥 구경하고 넘어가세요) ietf라는게 있습니다. [201에 관한 ietf](https://datatracker.ietf.org/doc/html/rfc7231#section-6.3.2)

ietf는 지금은 읽기 힘든 문서가 많으니 이런게 있다~ 정도만 알고 넘어가면 좋겠네요.

2024-05-05 14:29 UTC, andole98 commented on src/main/java/roomescape/domain/Reservation.java
> +        return Objects.equals(id, that.id);
> id가 같고 나머지가 다른 객체는 같은객체로 봐도 될까요?

이것에 대한 아토의 의견이 궁금해요

2024-05-05 14:31 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +        return findReservationById(savedId);
완전한 Reservation을 만들기 위해 한번더 조회를 하는거군요.

2024-05-05 14:33 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +                .addValue("timeId", timeId);
sqlParameter였군요 음주리뷰 이슈인것 같네요... 😓 
대부분 해당영역에 맞는 notation을 활용하긴 하지만 (db는 snake)  이렇게요
```java
String sql = "... :time_id";
.addValue("time_id", timeId);
```
그렇지만 충분히 용인할수 있는 표현인것 같아요.

2024-05-05 14:37 UTC, andole98 commented on src/test/java/roomescape/service/ReservationServiceTest.java
> +    @DisplayName("모든 예약 정보 조회 및 의존 객체 상호작용 테스트")
[위에 코멘트](https://github.com/woowacourse/spring-roomescape-member/pull/83#discussion_r1589291073)
에 이어서 이것은 지금의 학습주제를 좀 벗어난것 같아요. 페어의 마수에 빠지신것 같은데 굳이 지금 알아야 할 필요는 없어보입니다. 

코드가 있어서 질문을 한거고 지금당장 어렵게 고민해야 할 필요는 없을것 같아요~

2024-05-05 14:37 UTC, andole98 commented on src/test/java/roomescape/MissionStepTest.java
> +@Sql("/truncate.sql")
더해서 truncate하면 pk의 increment도 초기화됩니다~

2024-05-05 14:56 UTC, andole98 approved these changes
잘 구현해 주셨네요~ 학습목표인 사용자 기능 구현을 충분히 잘 구현해 주셨어요.

몇몇 질문들에 답글도 달아두었어요. 필요하다면 슬랙 or pr 스레드에서 이어서 진행해보아요~

2024-05-05 14:56 UTC, andole98 commented on src/main/java/roomescape/controller/ReservationApiController.java
> +        return ResponseEntity.created(URI.create("/reservations/" + reservation.getId())).body(reservation);
ResponseEntity의 conveninet method들을 잘 알아보신것 같네요~

2024-05-05 14:56 UTC, andole98 commented on src/main/java/roomescape/service/dto/AvailabilityOfTimeResponse.java
> +public class AvailabilityOfTimeResponse {
response를 잘 분리해주셨네요~ :+1:

2024-05-05 14:56 UTC, andole98 commented on src/main/java/roomescape/repository/JdbcReservationRepository.java
> +    }
:+1: 

repository에서 바로 예외를 던지는 방법도 있지만, 서비스 레이어에서 없는 경우 무슨 에러를 던질지 선택할 여지를 주는 방법도 있을것 같아요.

예컨대

```java
class SomeRepository {

    public 있는지없는지몰라요<Reservation> findById(long id) {
        ...
    }
}

class SomeService {
  
    public Reservation find() {
      있는지없는지몰라요<Reservation> found = someRepository.findById(..);
        if (없으면) {
           throw 내가_정한_에러(...);
        }
        return found.있어요();
    }
}
```

2024-05-05 14:56 UTC, merged