[4 - 6단계 - 방탈출 사용자 예약] 초코칩(권기호) 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #89
Opened 2024-05-10 04:24 UTC by Chocochip101

안녕하세요, 비밥! 백엔드 크루 초코칩입니다 🍪

step 1-3에 이어, step 4-6도 리뷰 잘 부탁드립니다. 😆 아래에는 이전 리뷰에서 답변하지 못했던 내용들을 남겨놨습니다!

> cascade를 활용

> exception 타입만 검사하는 것으로는 안정적인 테스트가 힘들 수 있습니다. 거짓 양성, 거짓 음성에 대해 알아보시면 좋을것 같습니다.

> 도메인 모델과 데이터 영속성 모델을 1:1로 대응하여 바라보는 것을 경계해보시면 좋을것 같습니다.

감사합니다 :)

2024-05-10 15:24 UTC, pci2676 commented
> exception 타입으로 어떤 exception에 해당되서 예외가 발생했는지, 확인하는게 어려울 것 같아서 에러 메시지까지 검증했습니다.
> 언급해주신 거짓 양성, 거짓 음성에 대해 알아봤는데 Exception과 어떤 연관성이 있는지 제가 이해를 못했습니다. 🥲

exception만 검사했을때 검증하는 대상이 발생시키는 exception이 여러개인 경우 그리고 여러개의 exception중 중복되는 exception이 있는 경우 정확히 검증하고자 하는 부분이 검증되었는지 확인이 어렵습니다.

2024-05-10 16:20 UTC, pci2676 requested changes
질문에 대한 답변과 조금 더 고민해보면 좋을 부분에 리뷰를 남겨두었으니 확인바랍니다.

2024-05-10 16:20 UTC, pci2676 commented on src/main/java/roomescape/auth/interceptor/CheckAdminInterceptor.java
> +        return true;
AuthInfo를 저장하고 가져오는 Cookie도 하나의 구현세부사항으로 볼 수 있지 않을까요?

2024-05-10 16:20 UTC, pci2676 commented on src/main/java/roomescape/auth/interceptor/CheckMemberInterceptor.java
> +    }
`CheckAdminInterceptor`의 코드와 유사한 부분이 존재하는 것 같습니다.

2024-05-10 16:20 UTC, pci2676 commented on src/main/java/roomescape/global/config/WebMvcConfiguration.java
> +                .addPathPatterns("/admin/**")
admin 경로도 `checkMemberInterceptor`가 필요한가요?

2024-05-11 04:56 UTC, Chocochip101 commented on src/main/java/roomescape/auth/service/TokenProvider.java
> +    boolean validateToken(String token);
반환값이 boolean이기에 `isToken`으로 변경했습니다.

2024-05-12 07:43 UTC, Chocochip101 commented on src/main/java/roomescape/member/domain/Member.java
> +    private Role role;
final을 통해 재할당을 막았습니다.

2024-05-12 07:48 UTC, Chocochip101 commented on src/main/java/roomescape/auth/interceptor/CheckAdminInterceptor.java
> +        return true;
구현 세부사항으로 볼 수 있어 RequestHandler, ResponseHandler 인터페이스를 정의하고 CookieRequestHandler, CookieResponseHandler에서 구현하게 했습니다.

2024-05-12 07:48 UTC, Chocochip101 commented on src/main/java/roomescape/auth/interceptor/CheckMemberInterceptor.java
> +    }
상속으로 AuthInterceptor를 구현했습니다.

2024-05-12 07:53 UTC, Chocochip101 commented on src/test/java/roomescape/auth/controller/AuthControllerTest.java
> +    }
DynamicTest에 대해 공부해보고 적용했습니다.

2024-05-12 07:56 UTC, Chocochip101 commented
안녕하세요, 비밥! 주말 잘 지내셨나요?!

남겨주신 피드백 읽어보고 반영했습니다! 질문과 고민 사항이 있어 여기에 남깁니다!

# 질문
> payload를 가져오기 위해서 validate 하는 과정이 반드시 필요하다고 생각하시는것 같습니다.

2024-05-12 13:05 UTC, pci2676 commented
> > 제네릭 인터페이스에 대한 고민
> 
> payload를 제넥릭으로 사용하다보니, `TokenProvider`에서 `TokenProvider<T>`로 변경했습니다. 이때 구현 클래스가 `TokenProvider<String>`타입인 `JwtTokenProvider`이다 보니, 클라이언트(`TokenProvider`를 사용하는 쪽)에서는 `TokenProvider<String>`를 참고하게 됩니다.
> 
> ```java
> @Service
> public class AuthService {
>     private final TokenProvider<String> tokenProvider;
> }
> ```
> 
> 제네릭의 타입을 명시하다보니, DIP에 위배되는 느낌을 받았습니다. 이러한 구현 방법이 최선인지 여쭤보고 싶습니다.

아 이 부분은 제가 코멘트로 즉석에서 코드를 작성하면서 제네릭으로 작성해서 제네릭 설계를 하신것 같은데  
도메인이 주도권을 가져가는것이 맞기 때문에 굳이 제네릭으로 할 필요는 없습니다.

2024-05-12 13:18 UTC, pci2676 commented
> > payload를 가져오기 위해서 validate 하는 과정이 반드시 필요하다고 생각하시는것 같습니다.
> 
> jwt 구조에서 payload는 BASE64로 인코딩 되어 누구나 볼 수 있는 것으로 알고 있습니다. 클라이언트 측에서 토큰을 수정하거나 위조할 수 있기에, 페이로드의 내용을 검증함으로써 토큰이 변조되지 않았는지 확인할 수 있습니다.
> 
> 해당 방식이 일반적인지 여쭤보고 싶습니다.

일반적인지에 대한 답변은 조금 어려운것 같습니다.  
팀마다 어떤 전략을 취하느냐에 따라 달라질 수 있는 부분으로 보이고  
애플리케이션을 운영하고 있는 시스템의 규모에 따라서도 달라질 수 있을것 같습니다.

아시다시피 Base64는 인코딩 기법이기 때문에 보안에 큰 이점은 없습니다. 따라서 payload를 서버에서 검증하는 것 또한 좋은 방법입니다.  

아쉽게도 제가 몸담고 있는 팀은 위와 같은 사용자 보안과 맞닿아있지 않은 팀이라 좋은 인사이트를 드리기는 힘들 것 같습니다.  😓   
저라면 특정 암호화 기법을 이용해 payload에 대한 암호화와 payload의 hash 값을 함께 검증하는 방식을 취할 것 같습니다. (제가 속한 팀은 이러한 방식으로 통신하는 경우가 많습니다.)

jwt와 관련하여 아래 아티클이 도움이 될 것 같으니 시간 여유가 되실때 한번 읽어보시면 좋을것 같습니다.

https://curity.io/resources/learn/jwt-best-practices/

2024-05-12 13:43 UTC, pci2676 requested changes
질문에 대한 답변과 고민해볼만한 부분에 조금 리뷰를 남겨두었으니 확인해주세요.

2024-05-12 13:43 UTC, pci2676 commented on src/main/java/roomescape/auth/service/jwt/JwtTokenProvider.java
> +    public boolean isToken(String token) {
👍

2024-05-12 13:43 UTC, pci2676 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        }
검색조건이 늘어나면 service와 repository에 관련된 로직이 추가로 늘어나게될 것 같습니다.

동적으로 쿼리를 제공할 수 있도록 개선하는 것을 고민해보시면 좋을것 같습니다.

2024-05-12 13:43 UTC, pci2676 commented on src/main/java/roomescape/reservation/service/ReservationService.java
> +        }
이 과정은 Reservation이 생성될 때 항상 같이 수반되어야 하는 중요한 로직으로 보이는데 어떻게 생각하시나요?

2024-05-12 15:06 UTC, Chocochip101 commented
> 비즈니스를 담당하는 domain의 영역에 spring 특화된 코드가 들어가있는것 같은데 이는 의도하신 부분일까요?


> 이 과정은 Reservation이 생성될 때 항상 같이 수반되어야 하는 중요한 로직으로 보이는데 어떻게 생각하시나요?

Reservation이 생성될 때 항상 같이 수반되어야 하는 로직이라고 **생각하지 않습니다.** 과거의 예약을 불러오게 되면, 현재 날짜보다 이전 날짜인지에 대한 검증이 필요없기 때문입니다.

하지만 새로운 예약 생성 시, 이를 검증하는 것은 도메인의 책임이라고 생각하기 때문에 Reservation 클래스의 정적 팩터리 메서드를 이용해 날짜 검증 로직을 옮겼습니다.

2024-05-13 02:20 UTC, pci2676 commented
> > 비즈니스를 담당하는 domain의 영역에 spring 특화된 코드가 들어가있는것 같은데 이는 의도하신 부분일까요?
> 
> 특정 프레임워크에 얽매이지 않게 하기 위해 domain 계층에 프레임워크(spring) 특화된 코드를 지양하는 것으로 알고 있습니다. 하지만 해당 부분을 위해 추가로 코드를 작성하는 것이 더 비효율적이라 생각했습니다.

지금은 웹 요청과 응답이 오고가는 코드를 작성하시고 있지만 비동기 메세지 처리, 배치성 데이터 처리등의 영역으로 넘어가면 exception에 http status가 필요없는 경우가 발생합니다. 지금 당장 다 알아야하는 정보는 아닐것 같으니 그런 경우가 있다 정도로 참고해주세요.



> > 이 과정은 Reservation이 생성될 때 항상 같이 수반되어야 하는 중요한 로직으로 보이는데 어떻게 생각하시나요?
> 
> Reservation이 생성될 때 항상 같이 수반되어야 하는 로직이라고 **생각하지 않습니다.** 과거의 예약을 불러오게 되면, 현재 날짜보다 이전 날짜인지에 대한 검증이 필요없기 때문입니다.
> 
> 하지만 새로운 예약 생성 시, 이를 검증하는 것은 도메인의 책임이라고 생각하기 때문에 Reservation 클래스의 정적 팩터리 메서드를 이용해 날짜 검증 로직을 옮겼습니다.

Reservation을 생성할 수 있는 창구인 생성자가 해당 로직을 검증하지 않고 있는 경우  
현재 시점에서 잘못된 Reservation이 생성하여 사용할 수 있음을 말씀드리고자 하였습니다. 

이를 방어할 수 있는 방법을 고민해보시기를 유도해보고자 했던 것인데 전달 방법이 좋지 못했는지 잘 되지 않았네요 😄 

facotry 메서드를 이용하는것도 좋은 방법이지만 여전히 생성자가 열려있다는 부분이 방어적이지 못할 수 있습니다. 그래서 객체생성시점을 함께 멤버변수로 들고 있는 것이 하나의 방법이 될 수 있습니다. (물론 DB에도 함께 저장이 되어야 합니다.)

2024-05-13 02:21 UTC, pci2676 approved these changes
리뷰드린 내용에 대해 잘 개선해주신것 같습니다.

질문에 대한 답변과 추가 리뷰를 남겨두었는데 참고만 해주셔도 될 것 같습니다.

고생하셨습니다. 머지하겠습니다. 🚀

2024-05-13 02:21 UTC, pci2676 commented on src/main/java/roomescape/auth/interceptor/AdminInterceptor.java
> +public class AdminInterceptor extends AuthInterceptor {
interceptor들의 단일 테스트는 존재하지 않는것 같습니다.

지금 단계에서는 조금 어려울 수 있어 반드시 반영을 바라는 것은 아니지만 여유가 되신다면 테스트 추가를 권장드립니다.

2024-05-13 02:22 UTC, merged