[4 - 6단계 방탈출 사용자 예약] 명오 미션 제출합니다.
woowacourse/spring-roomescape-member pull request #94
Opened 2024-05-10 07:54 UTC by HyungHoKim00

안녕하세요 썬~ 드디어 돌아왔습니다.

이번 미션은 시간을 구현 반 구현해서 터진 코드 고치기 반  쓴 느낌이네요...

보통 구현을 빨리 하고 리뷰를 빠르게 받는 것을 선호하는 편인데, 이번에는 생각보다 쉽지 않았습니다.

이번에 많이 고민한 부분에 대한 질문 하나만 남기겠습니다. 이번 리뷰도 잘 부탁드립니다!!

사용자 정보 조회 방식, 어떤 방식을 선택해야 하지?
---
아래는 제 생각을 간단하게 정리했습니다.
저는 1번 방식을 사용했습니다. 2번의 첫번째 단점 해결 방법을 찾지 못해서 그리하였습니다.

1. 토큰의 subject에서 id를 받아온 후, 사용자 정보를 DB에서 가져온다.
장점: 맞는 책임을 가지고 있는 것으로 느껴진다.
단점: 굉장히 많은 상황에서 일어나는 작업인데, DB에 지속적으로 접근해야 하는 것이 비용이 크다.

2. 토큰의 claim들에 사용자 정보를 저장해서, 토큰에서 바로 사용자 정보를 가져온다.
장점: 빠르고 간편하다.
단점: 사용자 정보가 변경되면? 이름이나 email이 바뀌는 상황에 대응할 수 없다.

썬은 위에 대해 어떻게 생각하시나요?

2024-05-11 10:42 UTC, syoun602 requested changes
안녕하세요 명오!

인증/인가, 토큰 부분을 잘 고려해서 작성해주신 것 같네요 👍
몇가지 코멘트 남겨봤으니 확인 부탁드려요~!

2024-05-11 10:42 UTC, syoun602 commented on src/main/java/roomescape/controller/MemberController.java
> +public class MemberController {
LoginController와 MemberController는 클래스를 어떤 기준으로 나누신건지 궁금합니다~!

2024-05-11 10:42 UTC, syoun602 commented on src/main/java/roomescape/util/JwtTokenProvider.java
> +public class JwtTokenProvider {
> 사용자 정보 조회 방식, 어떤 방식을 선택해야 하지?

좋은 고민을 해보셨네요 👍 저도 말씀하신 것처럼 정보 비대칭을 고려해 1번 방식을 선택할 것 같아요.
2번을 선택하게 된다면, jwt 토큰 만료를 따로 관리해야 할텐데 이러면 stateless한 속성이 깨지게 되기도 하구요.

2024-05-12 04:23 UTC, syoun602 requested changes
안녕하세요 리비!

2단계 구현하느라 고생 많으셨습니다! 잘해주셨네요 👍
몇가지 코멘트 남겨봤는데, 확인후 재요청 주세요!

2024-05-13 02:22 UTC, HyungHoKim00 commented on src/main/java/roomescape/config/CheckLoginInterceptor.java
> +public class CheckLoginInterceptor implements HandlerInterceptor {
맞는 말씀이네요.. 수정했습니다!

2024-05-13 02:24 UTC, HyungHoKim00 commented on src/main/java/roomescape/config/CheckLoginInterceptor.java
> +        return authService.isAdmin(cookies);
아앗.. 너무 기초적인 실수를 했네요. 꼼꼼하게 확인하겠습니다!

2024-05-13 02:31 UTC, HyungHoKim00 commented on src/main/java/roomescape/service/AuthService.java
> +        }
레벨1때 열심히 학습한 점을 또다시 활용하지 못했네요 ㅜㅜ. 수정해보았습니다 ㅎㅎ

2024-05-13 02:39 UTC, HyungHoKim00 commented on src/main/java/roomescape/dao/MemberDao.java
> +        List<Member> members = jdbcTemplate.query(
이 부분은 커스텀 예외를 생성하여 잡는 과정에서 바뀐 부분이였습니다.
하나만 가져오는 경우 자체적으로 IncorrectResultSizeDataAccessException이 발생할 가능성이 있기 때문입니다.
하지만 썬이 저번에 말씀해 주신 것 처럼, 스프링 프레임워크에 대한 예외까지 이렇게 처리할 이유는 없어 보입니다. (충분히 어떤 상황에서 발생할 지 인지할 수 있기 때문이라고 생각합니다.)
다시 수정했습니다!

2024-05-13 03:39 UTC, HyungHoKim00 commented on src/main/java/roomescape/dao/MemberDao.java
> +    private final RowMapper<Member> rowMapper = (rs, rowNum) -> new Member(
맞습니다!! 수정했습니다~

2024-05-13 03:44 UTC, HyungHoKim00 commented on src/main/java/roomescape/service/AuthService.java
> +        throw new InvalidInputException("토큰이 만료되었습니다. 다시 로그인 해주세요.");
예전에 웹사이트에서 장시간 방치하면, 세션이 만료되었다는 메시지를 받았던 기억이 나 작성했었습니다.
생각해보니, 그것을 사용자에게 전달할 필요가 없겠네요. 저 역시도 그 메시지를 받았을 때 이해하지 못했으니까요!!

2024-05-13 03:46 UTC, HyungHoKim00 commented on src/main/java/roomescape/controller/MemberController.java
> +public class MemberController {
기본적으로는 URI에 따라 나눴지만, 추가적으로는 역할에 따라 나눴습니다.
LoginController는 인증 관련 부분을 다루고,
MemberController는 멤버의 정보를 관리하는 부분을 다루고 있습니다.

2024-05-13 04:54 UTC, HyungHoKim00 commented on src/main/java/roomescape/config/MemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
Object를 Member로 바꾸어도 잘 동작하는 것을 확인할 수 있었습니다.
이에 대해 찾아봤는데, 두 방식이 어떤 차이가 있는지 알기 힘들었습니다.

2024-05-13 05:07 UTC, HyungHoKim00 commented on src/main/java/roomescape/config/CheckLoginInterceptor.java
> +package roomescape.config;
하나의 클래스밖에 없는 경우에 패키지를 굳이 만들고 싶지 않아 다 함께 모아놨었지만, 이상하게 느껴지긴 하네요.
패키지를 각각 분리하는 방법이 추후 resolver 혹은 interceptor가 추가될 때 추가적인 패키지 이동이 없고, 클래스가 하나더라도 패키지를 가지는 쪽이 클래스를 찾을 때 용이할 것 같아 수정했습니다!

2024-05-13 06:28 UTC, HyungHoKim00 commented on src/main/java/roomescape/controller/LoginController.java
> +    public ResponseEntity<MemberNameResponse> checkMemberProfile(Member member) {
5단계 요구사항 부분 중
- Cookie에 담긴 인증 정보를 이용해서 멤버 객체를 만드는 로직을 분리합니다.
- HandlerMethodArgumentResolver을 활용하면 회원정보를 객체를 컨트롤러 메서드에 주입할 수 있습니다.
부분을 보고 'ArgumentResolver는 도메인으로 매핑해야 한다' 라는 말로 착각했던 것 같습니다.
RequestBody 역시 일종의 ArgumentResolver이고, 컨트롤러까지는 request가 전달 되는 것이 옳은 흐름으로 느껴져 수정했습니다!

2024-05-13 06:37 UTC, HyungHoKim00 commented on src/main/java/roomescape/dto/request/MemberReservationRequest.java
> +) implements ReservationRequest {
중복된 코드를 피하기 위해서 위같은 행동을 했었는데, 논리적으로 맞지 않는다는 생각은 드네요. 로직이 없는 dto가 인터페이스를 가지는 것이 이상해 보여 수정했습니다!

2024-05-13 07:28 UTC, HyungHoKim00 commented on src/main/java/roomescape/config/MemberArgumentResolver.java
> +    private final MemberDao memberDao;
memberService에서 불필요한 메서드를 하나 생성하고 싶지 않아 dao를 주입했습니다.
하지만, 계층 구조에서 service를 사용하는 쪽이 혼용을 방지하고 논리적으로 헷갈리지 않겠다는 생각이 드네요!
현재는 memberDao가 필요없어져서 사라진 상태입니다.

2024-05-13 07:51 UTC, HyungHoKim00 commented on src/main/java/roomescape/config/MemberArgumentResolver.java
> +public class MemberArgumentResolver implements HandlerMethodArgumentResolver {
제가 느낀 바로는 다음과 같습니다.
1, ArgumentResolver
들어온 요청을 자바의 클래스로 매핑하는 역할을 가집니다.
2, Interceptor
들어온 요청이 Controller에 들어가기 전/후 및 요청이 끝난 후에 끼어들어 특정 프로세스를 수행합니다.
둘이 차이점을 비교하기에는 하는 역할이 다르다고 느꼈습니다.

2024-05-13 08:36 UTC, HyungHoKim00 commented
안녕하세요 썬!
덕분에 ArgumentResolver, Interceptor에 대해 더 공부하고 사용해 볼 수 있었습니다 ㅎㅎ.
오늘이 미션 마지막날임을 생각하면 참 시간이 빨리 간 것 같네요. 더 빠르고 많이 리뷰를 보냈어야했는데..
이번에도 잘부탁드립니다!

2024-05-13 16:17 UTC, syoun602 requested changes
안녕하세요 명오 👋

코멘트 적용해주신 것 잘 확인했습니다 💯
머지해도 될 것 같은데, 대체로 질문같은 코멘트 몇개 남겨두어서 한번만 더 RC로 두겠습니다!

2024-05-13 16:17 UTC, syoun602 commented on src/main/java/roomescape/resolver/FilteredReservationArgumentResolver.java
> +public class FilteredReservationArgumentResolver implements HandlerMethodArgumentResolver {
변경 의도가 궁금합니다 ArgumentResolver는 어떤 상황에서 사용해야되나요?
또한 해당 resolver가 재사용되는지, 개발자가 유지보수하기 편한 코드가 맞는지 고민해보면 좋을 것 같습니다

2024-05-13 16:17 UTC, syoun602 commented on src/main/java/roomescape/resolver/MemberArgumentResolver.java
> +        return new MemberRequest(memberId);
그냥 long을 반환하지 않고 이렇게 래핑하신 이유가 궁금합니다

2024-05-13 16:17 UTC, syoun602 commented on src/main/java/roomescape/config/MemberArgumentResolver.java
> +    public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
반환타입을 Object로 하게되면 사용하는 입장에서 강제 타입 캐스팅을 해주어야해서 안정성 측면에서 떨어지기도 하고, 명확하게 어떤 것을 반환하겠다는 것을 명시하는데 의미가 있을 것 같아요. 여기서는 해당 메서드를 직접 가져다가 쓰지 않기 때문에 상관없지만, 추후 이런 상속을 이용하게 된다면 위의 이유로 특정 객체로 제한해주는게 좋습니다

2024-05-13 16:17 UTC, syoun602 commented on src/main/java/roomescape/dao/MemberDao.java
> +        List<Member> members = jdbcTemplate.query(
넵 지금도 좋지만, optional을 이용한다면 지금보다 더 상세한 예외와 메시지를 남겨볼 수 있습니다 😊

2024-05-14 01:33 UTC, HyungHoKim00 commented on src/main/java/roomescape/resolver/FilteredReservationArgumentResolver.java
> +public class FilteredReservationArgumentResolver implements HandlerMethodArgumentResolver {
저도 이를 분리하면서, 해당 부분은 재사용될 일이 없다고 느껴져 굳이 resolver로 만들 필요가 없다고 생각했습니다.

2024-05-15 00:57 UTC, HyungHoKim00 commented on src/main/java/roomescape/interceptor/CheckAdminInterceptor.java
> -public class CheckLoginInterceptor implements HandlerInterceptor {
이러한 방식으로 바꾼 이유는, 계속하여 Component로 주입하면 Config의 생성자 부분이 불필요하게 길어질 것 같다고 느껴 수정했습니다! 다른 차이는 아직 잘 모르겠네요..

2024-05-15 01:07 UTC, HyungHoKim00 commented on src/main/java/roomescape/interceptor/CheckAdminInterceptor.java
>              response.sendError(HttpServletResponse.SC_FORBIDDEN, "접근 권한이 없습니다.");
예외가 발생한다는 사실을 prehandle에서 인지하고, 그 정보를 서블릿까지 전달한 이후 오류 페이지로 direct시키면서 오류를 발생시킵니다. 그래서 controllerAdvice의 오류로 잡히지 않고, 별도의 오류 페이지를 보여줍니다.

2024-05-15 01:18 UTC, HyungHoKim00 commented on src/main/java/roomescape/resolver/MemberArgumentResolver.java
> +        return new MemberRequest(memberId);
추후 member가 더 필요한 정보가 생길 가능성도 있고, 메서드에서 다른 Long 타입 매개변수들과 헷갈릴 여지가 존재할 수 있다고 생각했습니다.

2024-05-15 01:36 UTC, HyungHoKim00 commented on src/main/java/roomescape/dao/MemberDao.java
> +        List<Member> members = jdbcTemplate.query(
Optional을 이용하면, 예외 메시지를 일관성있게 Service에서 처리할 수도 있겠네요! 수정했습니다!

2024-05-15 01:41 UTC, HyungHoKim00 commented
안녕하세요 썬!!

이번 미션동안 최고의 리뷰에 정말 감사드립니다.

덕분에 많은 것을 배울 수 있었습니다!!

마지막까지 잘 부탁드립니다~

2024-05-16 14:24 UTC, syoun602 approved these changes
안녕하세요 명오!

마지막까지 잘 적용해주셨네요! 미션은 이만 머지하겠습니다 수고 많으셨어요 👏
질문에 대해서 본인의 생각을 얘기하는 것도 좋지만, 학습을 유도하는 질문도 있기 때문에
한번 더 확인해보는 습관을 들여보면 조금 더 좋은 공부가 될 것 같아요 💪

2024-05-16 14:24 UTC, syoun602 commented on src/main/java/roomescape/interceptor/CheckAdminInterceptor.java
> -public class CheckLoginInterceptor implements HandlerInterceptor {
참고로 `@Configuration` 내에도 `@Component`가 붙어있기 때문에 자동으로 스프링 빈으로 등록되고 있습니다~!

2024-05-16 14:24 UTC, syoun602 commented on src/main/java/roomescape/interceptor/CheckAdminInterceptor.java
>              response.sendError(HttpServletResponse.SC_FORBIDDEN, "접근 권한이 없습니다.");
`HandlerExceptionResolver`가 있어서 예외가 핸들링 가능합니다. 검색을 통해 조금 더 살펴보면 좋을 것 같아요. 말씀하신 건 `afterCompletion`과 관련 있겠네요.

2024-05-16 14:24 UTC, merged